Feature/auth with backend docs
ws-4020/mobile-app-crib-notes pull request #100
Opened 2021-03-22 04:58 UTC by shkozake

## 💣 BREAKING CHANGES 💣

- 破壊的な変更を箇条書きで記載してください
- 変更内容と変更理由を、わかりやすく記載してください
- なければ、このセクション（先頭行から「## ✅ What's done」の前の行まで）を削除してください

## ✅ What's done

- [ ] やったことをチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

## ⏸ What's not done

- やっていないこと（やる予定がないこと）を箇条書きで記載してください
- 解決できていない課題・障害があれば、それも記載してください

---

## Tests

- [ ] 実施した動作確認の内容をチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

何かあれば記載してください。
なければ「なし」と記載してください。

2021-03-22 09:36 UTC, tani-takanori commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +### 認証方式の変遷
認証方式の変遷は認証のアーキテクチャに持っていってよくない？

2021-03-22 09:39 UTC, tani-takanori commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +### 認証方式の変遷
もしくは概要ページに移す

2021-03-22 10:15 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +認証とは、何らかの手段によって対象の真正性を確認する行為です。
概要ページを作成しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/993e7c758dd0300fe655fb7bbed910aa5cf1d39a

2021-03-22 10:15 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +### 認証方式の変遷
概要ページを作成しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/993e7c758dd0300fe655fb7bbed910aa5cf1d39a

2021-03-23 02:25 UTC, tani-takanori requested changes

2021-03-23 02:25 UTC, tani-takanori commented on docs/reference/auth/overview.md
> +認証は、主に次のいずれかの内容で確認されます。
```suggestion
このガイドにおける認証対象は人間（本人認証）であり、本人認証は主に次のいずれかの内容で確認されます。
```

2021-03-23 02:25 UTC, tani-takanori commented on docs/reference/auth/overview.md
> +- 特徴がある：本人固有の身体情報
```suggestion
|要素|具体例|
|:---|:-----|
| 知っている|パスワードやPINなど、本人だけが知っている情報|
|所有している|メールアドレスやトークンなど、本人だけが所持しているもの|
|特徴がある|本人固有の身体情報|
```

2021-03-23 02:25 UTC, tani-takanori commented on docs/reference/auth/overview.md
> +認証基盤は各アプリケーション毎に実装され、管理されていました。
```suggestion
認証機能は各アプリケーション毎に実装され、管理されていました。
```

2021-03-23 02:40 UTC, tani-takanori requested changes

2021-03-23 02:40 UTC, tani-takanori commented on docs/reference/auth/overview.md
> +- 一要素のみの認証。認証強度が低い
```suggestion
- アプリケーション毎にログイン操作が必要なため、利便性に欠ける
- 一要素のみの認証なので認証強度が低い
```

書き方を合わせたほうがいいかな、と思いました

2021-03-23 02:40 UTC, tani-takanori commented on docs/reference/auth/overview.md
> +そこで、各アプリケーション毎に認証基盤を用意するのではなく、認証サービス（アイデンティティ・プロバイダ）を利用したシステム構成が採用され始めました。
```suggestion
そこで、各アプリケーション毎に認証機能を用意するのではなく、認証サービス（アイデンティティ・プロバイダ）を利用したシステム構成が採用され始めました。
```

2021-03-23 02:52 UTC, kz-takahashi commented on docs/reference/auth/overview.md
> +### 認証方式に関する疑問や課題
"疑問"という単語を使うのは、口語的にはともかく文章として使うには強い表現すぎて若干違和感があります。
既存の考え方に疑いを持っているわけではなく、単に理解が難しいとか正解がないとか考慮すべき点が多いとかそういった類だと思うので。

2021-03-23 02:52 UTC, kz-takahashi commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +今回紹介する認証方式は、[認証方式に関する疑問や課題](overview#認証方式に関する疑問や課題)に対する1つの解決手法です。
列挙した中のどれを解決しているのか明確にした方が良いと思います。
全部？

2021-03-23 02:52 UTC, kz-takahashi commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +[OpenID Connectにおける認証フロー](./stateless-authn.md#openid-connectにおける認証フロー)の紹介にあるとおり、[RFC 8252](https://www.rfc-editor.org/rfc/rfc8252.txt)ではネイティブアプリケーションのBCP（Best Current Practice）を定義しています。
この後BCPという省略表現を使っていないので、略さずに全表記だけで良い気がします。

2021-03-23 02:52 UTC, kz-takahashi commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +### 認証方式の優位性
具体的に何と比較したときに優位なのかわからないので、あまり"優位"という言葉は使いたくないです。
それよりは、この認証方式で何の課題が解決できるのかという方向性の見出しの方が良いかと思います。

2021-03-23 02:52 UTC, kz-takahashi commented on docs/reference/auth/overview.md
> +- 一要素のみの認証。認証強度が低い
別に構成上一要素のみの認証しかできないわけではないので、これを含めたいならもう少し説明が必要な気がします。
各アプリケーションで個別に多要素認証を管理するとユーザーが煩雑だという方向での課題？それとも別々に実装すると工数がかさむという方向での課題？

2021-03-23 03:58 UTC, shkozake commented on docs/reference/auth/overview.md
> +### 認証方式に関する疑問や課題
「認証方式に関する不明点や課題」であれば違和感はないですか？

2021-03-23 03:58 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +今回紹介する認証方式は、[認証方式に関する疑問や課題](overview#認証方式に関する疑問や課題)に対する1つの解決手法です。
全部です。

2021-03-23 04:00 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +[OpenID Connectにおける認証フロー](./stateless-authn.md#openid-connectにおける認証フロー)の紹介にあるとおり、[RFC 8252](https://www.rfc-editor.org/rfc/rfc8252.txt)ではネイティブアプリケーションのBCP（Best Current Practice）を定義しています。
こちらで修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/ddf380fc1de8034d8ffc2f3b3729fad00d51791f

2021-03-23 04:05 UTC, shkozake commented on docs/reference/auth/overview.md
> +- 一要素のみの認証。認証強度が低い
「ID/パスワードの一要素のみで認証している場合が多く、認証強度が低い」と実態の説明となるよう修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/14ee861d70eaf7c96b59d01d10c2f3bac0b46c46

2021-03-23 04:07 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +### 認証方式の優位性
「認証方式で期待される効果」とした場合、違和感ないですか？

2021-03-23 04:25 UTC, kz-takahashi commented on docs/reference/auth/overview.md
> +### 認証方式に関する疑問や課題
良くなっているのでそれでも問題ないとは思うのですが、認証方式に関する不明点なのかはまだ若干気になるので、
認証サービスを利用したシステム構成に関する不明点や課題という表現にしても問題なければそちらの方が良い気はします。

2021-03-23 04:28 UTC, kz-takahashi commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +### 認証方式の優位性
良いと思います。できれば、この認証方式とか本認証方式のように限定する文言も先頭に足しておきたいですが。

2021-03-23 04:38 UTC, shkozake commented on docs/reference/auth/overview.md
> +### 認証方式に関する疑問や課題
「認証サービスを利用したシステム構成に関する不明点や課題」と修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/bd4fccb2497c790d4bea2ee8f7bbf8cac7e35e95

2021-03-23 04:41 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +### 認証方式の優位性
「本認証方式で期待される効果」で修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/d13b77cf2112413461cdc38c826a0c7ce5fcf4d2

2021-03-23 06:08 UTC, tani-takanori commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +認証で得たIDトークンを用いて、バックエンドサービスとのセッションを確立します。
```suggestion
OIDC認証で得たIDトークンを用いて、バックエンドサービスとのセッションを確立します。
```
認証で得たIDトークンというのが違和感があるので提案です。
もしくは `^IDトークンを用いて` にしてしまう？？

2021-03-23 06:42 UTC, kz-takahashi commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +今回紹介する認証方式は、[認証方式に関する疑問や課題](overview#認証方式に関する疑問や課題)に対する1つの解決手法です。
別ページを読んで戻ってくるのは手間がかかるので、できれば再掲しておいた方が読みやすいかと思います。
あと、リンク先の見出しタイトルを変更したのでそこも合わせておきたい。

2021-03-23 06:44 UTC, tani-takanori commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +このIDトークンをHTTPSを使用してバックエンドサービスに（従来のID/パスワードの代わりに）送信し、IDトークンの妥当性を検証することでバックエンドサービスとのセッションを確立します。
HTTPSプロトコルに言及してる意図ってあるんですか？
※ローカルで開発するときとかHTTPなんですが...

2021-03-23 06:48 UTC, tani-takanori commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +そこで、保管されたリフレッシュトークンを利用する場合、端末認証による許可を求めます。
```suggestion
そこで、保管されたリフレッシュトークンを利用する前に、端末認証による許可を求めます。
```

2021-03-23 06:51 UTC, kz-takahashi commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +[OpenID Connectにおける認証フロー](./stateless-authn.md#openid-connectにおける認証フロー)の紹介にあるとおり、[RFC 8252](https://www.rfc-editor.org/rfc/rfc8252.txt)ではネイティブアプリケーションのBest Current Practiceを定義しています。
RFC8252でネイティブアプリケーションのBest Current Practiceを定義していると言うのは苦しいのでもっと範囲を限定したい。(Suggestionは既存記事の表現に合わせましたが、長すぎてlint通らないかも)

```suggestion
[OpenID Connectにおける認証フロー](./stateless-authn.md#openid-connectにおける認証フロー)の紹介にあるとおり、[RFC 8252](https://www.rfc-editor.org/rfc/rfc8252.txt)ではモバイルアプリケーションの認証にOAuth 2.0を利用するときのBest Current Practiceを定義しています。
```

2021-03-23 06:55 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +今回紹介する認証方式は、[認証方式に関する疑問や課題](overview#認証方式に関する疑問や課題)に対する1つの解決手法です。
> できれば再掲しておいた方が読みやすいかと思います。

こちらに関しては、同じ内容を二度書くことになるのでチーム内で議論とさせてください。

> あと、リンク先の見出しタイトルを変更したのでそこも合わせておきたい。

こちらで修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/43421eb546b2a8b0180e87518c721e57e2c2b68e

2021-03-23 06:57 UTC, kz-takahashi commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +認証で得たIDトークンを用いて、バックエンドサービスとのセッションを確立します。
本認証方式ではという前提を追加するのと、ここで言う認証を行う主体を明確にしたい。

```suggestion
本認証方式では、認証サービスによる認証で得たIDトークンを用いて、バックエンドサービスとのセッションを確立します。
```

2021-03-23 06:58 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +このIDトークンをHTTPSを使用してバックエンドサービスに（従来のID/パスワードの代わりに）送信し、IDトークンの妥当性を検証することでバックエンドサービスとのセッションを確立します。
IDトークンは秘匿情報のため、安全性の確保された通信上で共有する必要があるので、このように書きました。
noteにその意図書きましょうか？

2021-03-23 07:35 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +認証で得たIDトークンを用いて、バックエンドサービスとのセッションを確立します。
こちらで修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/bb307ac9019378c350d8cc1bb6f7b65daa382a34

2021-03-23 07:52 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +今回紹介する認証方式は、[認証方式に関する疑問や課題](overview#認証方式に関する疑問や課題)に対する1つの解決手法です。
>> できれば再掲しておいた方が読みやすいかと思います。

> こちらに関しては、同じ内容を二度書くことになるのでチーム内で議論とさせてください。

谷さんと話して、概要ページと双方向リンクするよう修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/b61d00331c0cf5133e3a069612704d4493847ee0

2021-03-23 08:11 UTC, tani-takanori approved these changes

2021-03-23 09:14 UTC, kz-takahashi commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +- [RFC 8252](https://www.rfc-editor.org/rfc/rfc8252.txt)に従うことで、認証方式の安全性を担保できる。また、[RFC 8252](https://www.rfc-editor.org/rfc/rfc8252.txt)を実装したSDK（[AppAuth](https://appauth.io/)）を用いることで品質と生産性向上を期待できる
認証方式の安全性を担保できる とまで言い切るのは難しいと思うので、もう少し緩い表現にしておきたいです。

2021-03-23 09:32 UTC, shkozake commented on docs/reference/auth/authn-with-backend-using-OIDC-and-device-authn.md
> +- [RFC 8252](https://www.rfc-editor.org/rfc/rfc8252.txt)に従うことで、認証方式の安全性を担保できる。また、[RFC 8252](https://www.rfc-editor.org/rfc/rfc8252.txt)を実装したSDK（[AppAuth](https://appauth.io/)）を用いることで品質と生産性向上を期待できる
中途半端な文章なので、削除しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/4f3aebf4e68dfa5298f7eba2307907f97570c59b

2021-03-23 09:34 UTC, shkozake commented
端末認証の説明を追加しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/100/commits/f347a29ac730989d6b23ce32655ff830ac21b4b4

2021-03-23 09:46 UTC, kz-takahashi approved these changes

2021-03-23 09:50 UTC, merged