商標登録のやつ書いた
ws-4020/mobile-app-crib-notes pull request #102
Opened 2021-03-23 07:47 UTC by tani-takanori

## ✅ What's done

- [ ] 記事を見ながら必要な商標を記載する

## ⏸ What's not done

- クライテリアの修正

---

## Other (messages to reviewers, concerns, etc.)

なし

2021-03-23 10:01 UTC, kz-takahashi commented on src/pages/trademark.md
> +※iOS商標は、Cisco Systems, Inc。のライセンスに基づき使用されています。
```suggestion
※iOS商標は、Cisco Systems, Inc. のライセンスに基づき使用されています。
```

2021-03-23 11:30 UTC, in-a-paddy requested changes

2021-03-23 11:30 UTC, in-a-paddy commented on src/pages/trademark.md
> +※iOS商標は、Cisco Systems, Inc。のライセンスに基づき使用されています。
iPhoneとiOSの行、Apple Inc.の下に持っていった方が自然な気がします。
（Appleが各社とライセンスを結んでいるという話だと思うので。）

2021-03-23 11:30 UTC, in-a-paddy commented on src/pages/trademark.md
> +- 「Apple」「iCloud」「Safari」「Keychain」「iOS」「iPhone」「macOS」は、米国およびその他の国で登録されたApple Inc. の商標です。
```suggestion
- 「Apple」「iCloud」「Safari」「Keychain」「iOS」「iPhone」「macOS」は、米国およびその他の国で登録された Apple Inc. の商標です。  
  ※iPhone商標は、アイホン株式会社のライセンスに基づき使用されています。  
  ※iOS商標は、 Cisco Systems, Inc. のライセンスに基づき使用されています。
```

2021-03-24 00:38 UTC, kz-takahashi approved these changes

2021-03-24 06:40 UTC, in-a-paddy approved these changes

2021-03-24 06:40 UTC, merged