✨: Add MapView
ws-4020/mobile-app-crib-notes pull request #1054
Opened 2023-03-10 04:38 UTC by nkmr21

## ✅ What's done

- [ x ] 地図表示のデモページについての説明ページの下書きの作成
- [ ] 共通部品の作成
- [ ] デモページの作成

## ⏸ What's not done

- やっていないこと（やる予定がないこと）を箇条書きで記載してください
- 解決できていない課題・障害があれば、それも記載してください

---

## Tests

- [ ] 実施した動作確認の内容をチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

以下のコマンドのいずれかをこのプルリクエストのコメントとして投稿すると、
Azure Pipeline上でSantokuAppをビルドしてDeployGateへアップロードできます。
4種全てのビルドバリアントを対象にする場合はdeploy-all、
特定のビルドバリアントだけを対象にする場合はdeploy-ビルドバリアント名のコマンドを利用してください。

- /azp run deploy-all
- /azp run deploy-devSantokuAppDebugAdvanced
- /azp run deploy-devSantokuAppReleaseInHouse
- /azp run deploy-santokuAppDebugAdvanced
- /azp run deploy-santokuAppReleaseInHouse

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

何かあれば記載してください。
なければ「なし」と記載してください。

2023-03-10 09:11 UTC, in-a-paddy requested changes

2023-03-10 09:11 UTC, in-a-paddy commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +### マーカーの位置変更
💭 マーカーは複数表示することが多いから、追加できるようにしておくといいんじゃないかな。あと、表示範囲内にあるマーカーだけが表示されるかどうか、とかも知りたいし。

2023-03-10 09:11 UTC, in-a-paddy commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +### マーカーの位置変更
❓ マーカーをタップしたときにポップアップとかボトムシートで詳細を表示、みたいなのは必要ないかな？

2023-03-13 05:27 UTC, nkmr21 commented on website/docs/react-native/santoku/development/design/map/overview.mdx
> +地図表示のためにreact-native-maps 0.30を使用します。
バージョンの表記を削除しました。

2023-03-13 05:28 UTC, nkmr21 commented on website/docs/react-native/santoku/development/design/map/overview.mdx
> +本デモページではiOSではMapKit、Androidではgoogle mapを使用した地図表示を実装しています。
修正いたしました。

2023-03-13 05:28 UTC, nkmr21 commented on website/docs/react-native/santoku/development/design/map/overview.mdx
> +Santokuアプリではuse_frameworkでライブラリを静的にリンクさせていますが、iOSでGoogleMapを使用するためのライブラリを正常にリンクさせることができませんでした。
説明を修正いたしました。

2023-03-13 05:28 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +### マーカーの位置変更
マーカーを追加する項目を追加しました。マーカー追加のときに位置指定できるようにするので、初期表示から出しているマーカーの位置変更は削除しました。

2023-03-13 05:28 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +### マーカーの位置変更
マーカーをタップしてポップアップで説明を表示できるようにしようと思っています。説明を追加しました。

2023-03-17 05:19 UTC, nkmr21 commented
/azp run deploy-devSantokuAppReleaseInHouse

2023-03-17 05:28 UTC, nkmr21 commented
/azp run deploy-all

2023-03-24 05:45 UTC, HosodaTetsuya commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +iOSでgoogle mapを使用する場合、共通部品は使用せずライブラリから直接コンポーネントをインポートしてください。
`google map` 、 `Google map`  、 `Google Map` 
↓
`Google Maps` か `Googleマップ` に統一しましょう。 `Googleマップ` かな。

2023-03-24 05:45 UTC, HosodaTetsuya commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +以下の項目の画面操作を制限できます。
```suggestion
以下の画面操作を制限できます。
```

2023-03-24 05:45 UTC, HosodaTetsuya commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +以下を参考に`app.config.js`のダミーのAPIキーを取得したキーに置き換えてください。
```suggestion
`app.config.js`のダミーのAPIキーを取得したキーに置き換えてください。
```

2023-03-24 05:45 UTC, HosodaTetsuya commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +さらに、以下を参考に設定ファイルの変更が必要になります。
```suggestion
さらに、設定ファイルの変更が必要になります。
```

2023-03-24 05:45 UTC, HosodaTetsuya commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +iOSでGoogle Mapを使用する設定でビルドしたとき依存関係にあるファイルが見つからないというエラーが発生しました。
```suggestion
iOSでGoogle Mapを使用する設定でビルドしたとき依存関係にあるファイルが見つからないというエラーが発生します。
```

2023-03-24 05:45 UTC, HosodaTetsuya commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +以下の項目に数値を入力し表示領域を変更できます。
```suggestion
表示位置と表示範囲を変更できます。
```

2023-03-24 05:45 UTC, HosodaTetsuya commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +以下の項目を設定し地図の見た目を変更できます。
```suggestion
地図の見た目を変更できます。
```

2023-03-24 05:45 UTC, HosodaTetsuya commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +Google Maps APIが必要になります。
```suggestion
Google Maps APIを使用するためのAPIキーが必要になります。
```

2023-03-27 00:33 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +iOSでgoogle mapを使用する場合、共通部品は使用せずライブラリから直接コンポーネントをインポートしてください。
修正しました。

2023-03-27 00:33 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +以下の項目の画面操作を制限できます。
修正しました。

2023-03-27 00:34 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +以下を参考に`app.config.js`のダミーのAPIキーを取得したキーに置き換えてください。
修正しました。

2023-03-27 00:34 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +さらに、以下を参考に設定ファイルの変更が必要になります。
修正しました。

2023-03-27 00:35 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +iOSでGoogle Mapを使用する設定でビルドしたとき依存関係にあるファイルが見つからないというエラーが発生しました。
修正しました。

2023-03-27 00:35 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +以下の項目に数値を入力し表示領域を変更できます。
修正しました。

2023-03-27 00:35 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +以下の項目を設定し地図の見た目を変更できます。
修正しました。

2023-03-27 00:35 UTC, nkmr21 commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +Google Maps APIが必要になります。
修正しました。

2023-03-27 07:13 UTC, creature-water-valley commented on example-app/SantokuApp/package.json
> +    "react-native-maps": "0.31.1"
sort（Alphabet順）お願いします。

2023-03-27 07:52 UTC, creature-water-valley commented on example-app/SantokuApp/src/bases/ui/map/MapView.tsx
> +// providerをデフォルト（AndroidはGoogle Map、iOSはMapKit）に固定する
Providerを固定している理由を記載してもらえるとわかりやすいと思いました。

2023-03-27 07:52 UTC, creature-water-valley commented on example-app/SantokuApp/src/bases/ui/map/MapView.tsx
> +  return <RNMMapView provider={provider} {...props} ref={ref} testID="MapView" />;
testIDはテストコード側で渡した方が良いと思います。

2023-03-27 07:52 UTC, creature-water-valley commented on example-app/SantokuApp/src/bases/ui/map/MapView.tsx
> +  return <RNMMapView provider={provider} {...props} ref={ref} testID="MapView" />;
`showsUserLocation`を`true`に設定した場合は、`Info.plist`に`NSLocationWhenInUseUsageDescription`を設定しないとエラーになるっぽいです。

https://github.com/react-native-maps/react-native-maps/blob/0.30.x/docs/mapview.md#mapview--component-api

2023-03-27 07:52 UTC, creature-water-valley commented on example-app/SantokuApp/src/bases/ui/map/MapView.test.tsx
> +  // コンポーネント実装で指定できるPropsを確認する
このテストでMapViewに指定されていないPropsは全て何らかの理由で指定できないってことでしょうか？？

2023-03-27 07:52 UTC, creature-water-valley commented on example-app/SantokuApp/src/bases/ui/map/MapView.test.tsx
> +    // 元から存在するPropsが指定できるか確認（オブジェクト）
このコメントの意味が汲み取れなかったです。
単純い、`MapView`に指定したPropsの確認ということでしょうか？

2023-03-28 00:47 UTC, nkmr21 commented on example-app/SantokuApp/src/bases/ui/map/MapView.test.tsx
> +  // コンポーネント実装で指定できるPropsを確認する
共通部品作成でOmitしなかったPropsが実装で指定することができるか確認しています。テスト対象のPropsはOmitしなかったものから型違いでいくつかピックアップしています。そのためここでテストしていなくても指定できるものはあります。
上の意図が伝わるようにコメントを以下のように修正しました。
`  // 共通部品作成でOmitしなかったPropsから型違いでいくつかピックアップし確認する`

2023-03-28 00:48 UTC, nkmr21 commented on example-app/SantokuApp/src/bases/ui/map/MapView.test.tsx
> +    // 元から存在するPropsが指定できるか確認（オブジェクト）
> MapViewに指定したPropsの確認ということでしょうか？

はい、そうです。

2023-03-28 00:54 UTC, nkmr21 commented on example-app/SantokuApp/src/bases/ui/map/MapView.tsx
> +  return <RNMMapView provider={provider} {...props} ref={ref} testID="MapView" />;
修正しました。

2023-03-28 00:55 UTC, nkmr21 commented on example-app/SantokuApp/src/bases/ui/map/MapView.tsx
> +// providerをデフォルト（AndroidはGoogle Map、iOSはMapKit）に固定する
コメントを修正しました。
`// 現状の設定ではiOSでGoogleマップを使用できないため
// providerをデフォルト（AndroidはGoogleマップ、iOSはMapKit）に固定する`

2023-03-28 00:56 UTC, nkmr21 commented on example-app/SantokuApp/package.json
> +    "react-native-maps": "0.31.1"
修正しました。

2023-03-28 01:14 UTC, nkmr21 commented on example-app/SantokuApp/src/bases/ui/map/MapView.tsx
> +  return <RNMMapView provider={provider} {...props} ref={ref} testID="MapView" />;
現状`NSLocationWhenInUseUsageDescription`は設定していないので、エラーが起きないように`showsUserLocation`は`false`固定して、PropsからはOmitするように変更しようと思います。

2023-06-05 02:39 UTC, tksugimoto commented on example-app/SantokuApp/src/apps/app/navigators/DemoStackNav.tsx
> +import {MapScreen} from '../screens/demo-map/MapScreen';
> `import {MapScreen} from '../screens/demo-map/MapScreen';`

Screen の import はもう少し上のほう(〜L39)にまとめられているようです。

あと、 `../screens` じゃなくて  `apps/app/screens` をつかっているようです。

2023-06-05 02:49 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/form/RegionForm.ts
> +      longitudeDelta: yup.number().label('経度範囲').min(0).max(360),
```
      latitude: yup.number().label('緯度'),
      longitude: yup.number().label('経度'),
      latitudeDelta: yup.number().label('緯度範囲').min(0).max(180),
      longitudeDelta: yup.number().label('経度範囲').min(0).max(360),
```

緯度・経度のほうは min, max 要らないですか？

2023-06-05 02:53 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/form/RegionForm.ts
> +    validationSchema: yup.object().shape({
```
  const form = useFormik<RegionFormValues>({
    initialValues: params.initialValues,
    validationSchema: yup.object().shape({
```
`validationSchema` は固定なので、top levelでconst定義しておくのが良さそうです

2023-06-05 08:02 UTC, tksugimoto commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +[地図表示の共通部品](https://github.com/Fintan-contents/mobile-app-crib-notes/blob/master/example-app/SantokuApp/src/bases/ui/map/MapView.tsx)ではiOSでGoogleマップの使用を制限しています。
> 地図表示の共通部品ではiOSでGoogleマップの使用を制限しています。

なぜ制限しているのでしょう？
自然に読むとAndroidもiOSも両方GoogleMapを使ったほうが共通化できて楽そうに見えるので、理由を書いたほうが良いと思います。

※ 下のほうで関連テキストがあります

> 地図表示の共通部品ではiOSでGoogleマップを使うことはできない仕様になっています。 iOSでGoogleマップを使用する場合、共通部品は使用せずライブラリからコンポーネントをインポートしてください。 さらに、設定ファイルの変更が必要になります。

2023-06-05 08:11 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +- メンテナスが継続していること
fix typo
```suggestion
- メンテナンスが継続していること
```

2023-06-05 08:12 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +- OS標準のマップSDKが使用できること
> OS標準のマップSDKが使用できること

何が `OS標準のマップSDK` かも示されていると読みやすいです（上にあるテーブルに列追加？）

2023-06-05 08:18 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/form/RegionForm.ts
> +    validateOnChange: false,
`validateOnChange` は true で良い気がします。

2023-06-05 08:20 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +                  keyboardType={keyboardType}
緯度・経度・緯度範囲・経度範囲の入力欄は配列で定義してmapで要素を作成させたいです。

2023-06-05 08:21 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +                <Text>緯度範囲（横幅）</Text>
```suggestion
                <Text>経度範囲（横幅）</Text>
```

2023-06-05 08:38 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/components/MapTypePicker.tsx
> +  }, []);
> onDismiss

`onDone` と共通化すると、同じ動作をすることがコードからわかりやすいと思います。

`acceptCurrentSelection` みたいな名前でしょうか

2023-06-05 08:51 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/components/MapTypePicker.tsx
> +  mapType: MapType;
> MapType

MapType 定義のうち3種類しか使ってないので `Extract` して新規定義したものを使うと良さそうです。

```
export declare type MapType = 'hybrid' | 'mutedStandard' | 'none' | 'satellite' | 'standard' | 'terrain';
```

----

これで、 `?? 'standard'` が多いのも解消されますかね？

2023-06-05 09:29 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  }, [animateToRegion, region]);
```suggestion
  }, [animateToRegion]);
```

マーカーの実装で `const animateToRegion` が使われなければ、 `const animateToRegion` は `useCallback` 無しで `useEffect` の中に移動で良いと思います。

2023-06-06 02:40 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +            <Spacer heightRatio={0.01} />
`View` で箱を作ってmargin/paddingを調整できないでしょうか？

現状、設定の項目がグループ化されていますが、構造ではなくスペースの管理でグループが表現されています

2023-06-06 02:58 UTC, tksugimoto commented on example-app/SantokuApp/src/bases/ui/map/MapView.test.tsx
> +    // PROVIDERがnullになっているか確認
```suggestion
    // PROVIDERがundefinedになっているか確認
```

関連
638a907666b1eb1b31ed19a2b5670537e89532b8 `[SantokuApp] PROVIDER_DEFAULTの値がnullからundefinedに変更になった対応`

2023-06-06 03:06 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  const [scrollEnable, setScrollEnable] = useState<boolean>(true);
> `scrollEnable`

ここだけ `d` が抜けている

```
scrollEnabled
```

2023-06-06 07:29 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +    height: '50%',
入力欄がちょっと狭いので、`30%`くらいにした方が良いかもしれません

2023-06-07 08:42 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/form/useMarkersForm.ts
> +export const useMarkersForm = (
マーカーは一つだけ入力させるようにしたので、複数形ではなく単数形にした方が良いです

2023-06-07 08:44 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/form/RegionForm.ts
ファイル名は`useRegionForm`の方がわかりやすそうです。
- 他の機能もFormは`useXXXForm`にしている
- メインで使用してもらうのは`useRegionForm`

2023-06-07 08:52 UTC, creature-water-valley commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +Santokuアプリではfirebaseを使用しているため、useFrameworksで静的リンクを明示的に指定しています。
SantokuAppのドキュメントは、他のPJでも使用できるように`Santokuアプリ`ではなく`このアプリ`という表現で統一しています。

```suggestion
このアプリではfirebaseを使用しているため、useFrameworksで静的リンクを明示的に指定しています。
```

2023-06-07 08:57 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/form/RegionForm.ts
> +      longitudeDelta: yup.number().label('経度範囲').min(0).max(360),
`min`、`max`は必要そうなので追加しましたー
9edfca85ba444838a86643f57b6e75b14875e584

参考：[LatLng  |  Maps SDK for Android  |  Google for Developers](https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/LatLng?hl=ja)

2023-06-07 09:00 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/form/RegionForm.ts
ファイル名を変更しましたー
e9d19c1bedb5fb1a965d707aabd733f1b6bdeca4

2023-06-07 09:01 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  const [scrollEnable, setScrollEnable] = useState<boolean>(true);
`scrollEnabled`、`setScrollEnabled`に変更しましたー
5a5cac06d53f5717c8720a339eeba97e409df909

2023-06-07 09:02 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +    height: '50%',
`30%`に変更しましたー
ac0b604ed91d99f29e2c4d97c47a739d32be5ba0

2023-06-08 00:58 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +            <Text h4>マーカーの設定</Text>
以下が、ドキュメントとデモ画面で違いがあるので、統一した方がよさそうです。

- タイトル
  - doc: マーカーの追加
  - 画面: マーカーの設定
- マーカーブロックの記載（表示）場所
  - doc: 入力欄の最後
  - 画面: 表示領域の次

2023-06-08 01:20 UTC, creature-water-valley commented on example-app/SantokuApp/src/apps/app/navigators/DemoStackNav.tsx
> +import {MapScreen} from '../screens/demo-map/MapScreen';
import文修正しましたー
14f893b692971bf8f77fecb522386521dfc5ee3f

2023-06-08 01:21 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +            <Text h4>マーカーの設定</Text>
「マーカーの追加」に統一しました
54afb996063352a9eee82f692a09a6f2af929052

また、マーカーブロックは最下部に表示するように修正しました
8261e87217b11b4e19936366c3672600b4c18750

2023-06-08 01:45 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +このアプリでは地図表示ライブラリにreact-native-map-mapsを使用します。
ライブラリ名は、`react-native-maps`に統一した方が良いと思います。

2023-06-08 02:35 UTC, creature-water-valley commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +[地図表示の共通部品](https://github.com/Fintan-contents/mobile-app-crib-notes/blob/master/example-app/SantokuApp/src/bases/ui/map/MapView.tsx)ではiOSでGoogleマップの使用を制限しています。
iOSではGoogleMapの使用に制限があることと、その理由が記載されている箇所へのリンクを追記しましたー
3b6e52cda7045b458790ffca917279de07f6aeb1

2023-06-08 02:37 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +- OS標準のマップSDKが使用できること
上のテーブルには使用できるSDKが記載されていて、「OS標準のマップが表示できるか」みたいな列を追加すると若干冗長かもしれないと思ったので、決定事項のところにOS標準のマップとして、MapkitとGoogle Mapを明示しました
1953894e6cd9c77ea94905946a6b73f677959a9f

また、マップSDK自体はOS標準ではないと思ったので、「OS標準のマップが表示できること」に表現を変更しました
98c201a0691d50700022f4369a2cd9b245b8423b

2023-06-08 02:38 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +このアプリでは地図表示ライブラリにreact-native-map-mapsを使用します。
統一しました
5634dedbf1f50bb3302d9a6d8fc9d8aa2f452e5c

2023-06-08 02:44 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/form/useRegionForm.ts
> +const regionFormValidationSchema = yup.object().shape({
表示領域は必ず設定しないといけないので、`required`をつけた方がよさそうです。

2023-06-08 05:34 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  }, [animateToRegion, region]);
`animateToRegion`内の処理を`useEffect`に移動しましたー（マーカーの実装では使用していません）
3501b87a57c76983a660c3dfc5e9a248ac0c9fef

2023-06-08 05:34 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/components/MapTypePicker.tsx
> +  }, []);
共通化しましたー
cd87c636504c12a5a4e14e44b947a7be1db5fcd8

2023-06-08 05:37 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/components/MapTypePicker.tsx
> +  const itemsKey = pickerItems.find(item => item.value.mapType === mapType)?.key ?? 'standard';
指摘いただいた内容に以下を追加してリファクタしましたー
8760ccc34cd07d3a8306458bc780cc30cbdac7fd

- `pickerItems`の`value`と`key`は同じ場合は、`value`のみ指定でよさそうなので、`key`を削除

2023-06-08 05:38 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/components/MapTypePicker.tsx
> +  mapType: MapType;
`Extract`で使用するTypeだけを定義しましたー
026f9ddf3de9b633452ad16436c2f603f9d31715

関連コミットで、↓の内容も合わせて確認してもらった方が良いかもしれません。
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1054#discussion_r1222475434

2023-06-08 07:31 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +            <Spacer heightRatio={0.01} />
グループやフィールドに使用するBoxを作成して、BoxやBox内はgap/paddingでレイアウトするように修正しましたー
ef78777c6115db4ca631650b71421f529872c016

2023-06-08 07:38 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +                  keyboardType={keyboardType}
map()でというより JSX 部分を関数化のほうが正確でした。
↓の2パターンでほぼ全ての入力をカバーできるので。

```tsx
            <FieldBox title="title" description="タイトル">
              <TextInput value={markerForm.values.title} onChangeText={markerForm.handleChange('title')} />
            </FieldBox>
```
```tsx
            <FieldBox title="draggable" description="ドラッグを許可" fieldStyles={styles.toggleConfigContainer}>
              <ToggleButton isPressed={markerForm.values.draggable} setIsPressed={setMarkerFormDraggable} />
            </FieldBox>
```

2023-06-08 09:22 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/form/useRegionForm.ts
> +const regionFormValidationSchema = yup.object().shape({
`required`をつけました
953d48d60bf737b3f96654c13e183f6c9339df00

2023-06-08 09:35 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +        <MapView
Androidで、キーボード入力を終えてキーボードが閉じる時に一瞬地図がチラつくようです。

2023-06-09 01:23 UTC, tksugimoto commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +GoogleマップAPIを使用するためのAPIキーが必要になります
句点 `。` 漏れ
```suggestion
GoogleマップAPIを使用するためのAPIキーが必要になります。
```

2023-06-09 01:41 UTC, tksugimoto commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +iOSでGoogleマップを使用する場合、共通部品は使用せずライブラリからコンポーネントをインポートしてください。
`地図表示の共通部品` ってどれのことを指しているのでしょう？

- このアプリで作った何か
- MapKit
- react-native-maps

名前による明示があるとわかりやすいです。

`ライブラリからコンポーネントをインポート` の部分も。

2023-06-09 01:52 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +        <MapView
`KeyboardAvoidingView`の`height`を指定するとチラつくようです。
単純に`View`に変更しても問題なさそうだったので、`View`に変更しました
e2c9133797c46dc05433fdd83eed350a7caa5136

2023-06-09 01:54 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/components/MapTypePicker.tsx
> +  {value: 'hybrid', label: 'hybrid', inputLabel: 'hybrid'},
pickerItems の `label` って未使用っぽいです？

2023-06-09 02:18 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  const [mapType, setMapType] = useState<MapType>('standard');
> `useState<MapType>('standard');`

現在、偶然の一致になっています。

`example-app/SantokuApp/src/features/demo-map/components/MapTypePicker.tsx` の
`const defaultItem = pickerItems[0];` から取ったほうが良さそうです。

2023-06-09 02:49 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +                  keyboardType={keyboardType}
`TextInput`/`ToogleButton`/`Button`を`FieldBox`でラップした部品を作成してみましたー
a61a73c26cfeebf114d0987e92875e7c9223f012

2023-06-09 02:50 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +    <View style={styles.search}>
`search`はちょっと意味が違いそうです。単純に`button`でもよさそうです。

2023-06-09 02:52 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +    <View style={styles.search}>
`button`に変更しましたー
91807300985b5f8fad40072b0e528f2c80b1ae8a

2023-06-09 02:52 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +            </Text>
```suggestion
            <Text>地図を表示します。オプションを変更し、表示や操作を確認できます。</Text>
```

※ 改行が消えてレイアウトが変わります。

| 変更前 | 変更後 |
|:-------:|:-------:|
|<img src="https://github.com/ws-4020/mobile-app-crib-notes/assets/13145001/5d01fcad-2c0c-4a3d-9f8c-9a67a8d2414c"> | <img src="https://github.com/ws-4020/mobile-app-crib-notes/assets/13145001/0c5f56ab-aff8-4143-ba79-a38e62f355e4"> |

2023-06-09 02:56 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +            </View>
マーカーと違ってこっちは更新ボタンが SectionBox から出てました
```suggestion
              <View style={styles.search}>
                <Button title="更新する" onPress={form.submitForm} size="middle" />
              </View>
            </SectionBox>
```

2023-06-09 03:46 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +                  keyboardType={keyboardType}
↓ のような定義をイメージしていましたが、 TS だと無理そうですかね？（Formによって分けない限り）
```ts
type FormTextInputProps = Omit<FieldBoxProps, 'fieldStyles'> &
  (
    | (Pick<ReturnType<typeof useRegionForm>, 'form'> & {formKey: RegionFormKeys})
    | (Pick<ReturnType<typeof useMarkerForm>, 'form'> & {formKey: MarkerFormKeys})
  ) &
  Pick<TextInputProps, 'keyboardType'>;
const FormTextInput: React.FC<FormTextInputProps> = ({title, description, form, formKey, keyboardType}) => {
  return (
    <FieldBox title={title} description={description}>
      <TextInput
        value={form.values[formKey]} // FIXME: type ERROR
        onChangeText={form.handleChange(formKey)}
        errorMessage={form.errors[formKey]} // FIXME: type ERROR
        keyboardType={keyboardType}
      />
    </FieldBox>
  );
};
```

```diff
@@ -113,9 +113,8 @@ export const DemoMapPage: React.FC = () => {
                   key={`region-field-${index}`}
                   title={formKey}
                   description={description}
-                  value={form.values[formKey]}
-                  onChangeText={form.handleChange(formKey)}
-                  errorMessage={form.errors[formKey]}
+                  form={form}
+                  formKey={formKey}
                   keyboardType={keyboardType}
                 />
               ))}
@@ -168,24 +167,13 @@ export const DemoMapPage: React.FC = () => {
                 key={`marker-coordinate-field-${index}`}
                 title={formKey}
                 description={description}
-                value={markerForm.values[formKey]}
-                onChangeText={markerForm.handleChange(formKey)}
-                errorMessage={markerForm.errors[formKey]}
+                form={markerForm}
+                formKey={formKey}
                 keyboardType={keyboardType}
               />
```

2023-06-09 04:26 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +                  keyboardType={keyboardType}
僕も最初は↑と同じようなイメージで作っていたんですが、型解決わからないってなってやめましたね、、、
かつ、共通部品やライブラリじゃなくページ内に小難しい型定義を記載するのもちょっと可読性に欠けるなと思い。

2023-06-09 04:46 UTC, creature-water-valley commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +iOSでGoogleマップを使用する場合、共通部品は使用せずライブラリからコンポーネントをインポートしてください。
名称を明示するように修正しました
c973df62c927b8007c7d2cf3fbd8fb7d2987b4a3

2023-06-09 04:48 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  const [mapType, setMapType] = useState<MapType>('standard');
`defaultItem.value`から取得するように変更しましたー
併せて、`defaultItem`でexportすると何のデフォルトかわかりづらかったので、`defaultMapTypeItem`に変数名を変更しました
c973df62c927b8007c7d2cf3fbd8fb7d2987b4a3

2023-06-09 04:48 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +            </View>
`SectionBox`内に移動しましたー
9974038f9de55a7a2b53835408c3982a0d98eb96

2023-06-09 04:49 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +                  keyboardType={keyboardType}
でしたか〜。

共通化の嬉しさ半減ですねぇ。

2023-06-09 04:50 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  } as const);
> const keyboardType

数字キーボードであることがわかる名前が良いですね

2023-06-09 04:55 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  } as const);
`numberKeyboard`に変更しましたー
4c2db9e8274446654cf298a242b4dddc04947e27

2023-06-09 06:02 UTC, tksugimoto commented on example-app/SantokuApp/prebuild/local/android/app/src/main/AndroidManifest.xml
> +    <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> `<uses-library android:name="org.apache.http.legacy" android:required="false"/>`

これ何で増えました？

commitはこれなんですが、関係なさそうで。

6c9095e54bf47eda6cefdd91ebf734acb11abd41 `[SantokuApp] GoogleマップのAPIKeyを、gradle.propertiesやシステムプロパティから取得するように変更`

2023-06-09 06:14 UTC, tksugimoto commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  } as const);
> `const numberKeyboard`

関数内ではなく、ファイルのtopで定数定義で良さそうです。

2023-06-09 06:17 UTC, creature-water-valley commented on example-app/SantokuApp/prebuild/local/android/app/src/main/AndroidManifest.xml
> +    <uses-library android:name="org.apache.http.legacy" android:required="false"/>
APIKey設定して、`prebuild`実行したからだと思います。（元々APIKeyは設定されていましたが、`prebuild`後のファイルをcommitしてなかった？？）

https://github.com/expo/expo/blob/66575f0b1fbe19899b58477078d9b4900823dc91/packages/%40expo/config-plugins/src/android/GoogleMapsApiKey.ts#L35

2023-06-09 06:20 UTC, tksugimoto commented on example-app/SantokuApp/prebuild/local/android/app/src/main/AndroidManifest.xml
> +    <uses-library android:name="org.apache.http.legacy" android:required="false"/>
`GoogleMapsApiKey` の config plugin が入れているものなのですね。了解です。

commitされてなかったようですね。（prebuild commit直前に実施↓）
```diff
$ git diff prebuild/local/android/
diff --git a/example-app/SantokuApp/prebuild/local/android/app/src/main/AndroidManifest.xml b/example-app/SantokuApp/prebuild/local/android/app/src/main/AndroidManifest.xml
index 07d54a400..ab4921d09 100644
--- a/example-app/SantokuApp/prebuild/local/android/app/src/main/AndroidManifest.xml
+++ b/example-app/SantokuApp/prebuild/local/android/app/src/main/AndroidManifest.xml
@@ -14,6 +14,7 @@
     </intent>
   </queries>
   <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme" android:usesCleartextTraffic="true">
+    <meta-data android:name="com.google.android.geo.API_KEY" android:value="dummyApiKey"/>
     <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>
     <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="48.0.0"/>
     <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
@@ -26,5 +27,6 @@
       </intent-filter>
     </activity>
     <activity android:name=".AppActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:exported="false"/>
+    <uses-library android:name="org.apache.http.legacy" android:required="false"/>
   </application>
 </manifest>

```

2023-06-09 06:23 UTC, creature-water-valley commented on example-app/SantokuApp/src/features/demo-map/pages/DemoMapPage.tsx
> +  } as const);
コンポーネントの外で定義するようにしましたー
9037e12a290c9a2ef3e8260cd3eb3e450a033310

2023-06-09 06:56 UTC, tksugimoto commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> ++         apiKey: '<Your API Key>',
> `app.config.js`のダミーのAPIキーを取得したキーに置き換えてください。

これ config plugin を使うようにしたので要修正です。

2023-06-09 07:09 UTC, tksugimoto commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> +このアプリではfirebaseを使用しているため、useFrameworksで静的リンクを明示的に指定しています。
Firebase 大文字化
```suggestion
このアプリではFirebaseを使用しているため、useFrameworksで静的リンクを明示的に指定しています。
```

2023-06-09 07:23 UTC, tksugimoto approved these changes

2023-06-09 08:47 UTC, creature-water-valley commented on website/docs/react-native/santoku/design/demo/map/overview.mdx
> ++         apiKey: '<Your API Key>',
対応しましたー（PRの説明文も変更しています。）
5db8a1e9060e8fcd192262db182c0827bcc27ac5

2023-06-13 08:33 UTC, in-a-paddy requested changes

2023-06-14 02:26 UTC, creature-water-valley commented on website/docs/react-native/santoku/design/demo/map/android-map.png
日本語設定でキャプチャ更新しましたー（iOS/Androidともに）
f0b4cec4953d7a7ee6bf0f20c560fa66a8437c0b

2023-06-14 02:34 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +rnmapboxは[バージョン10](https://github.com/rnmapbox/maps/tree/10.0)のリリースに向け開発が継続しています。
`rnmapbox`のメンテナンス状況を更新しましたー
5db742a18f4f5372b8d1d2cd9d3ce410f71f931c

2023-06-14 02:35 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +| ライブラリ名 | 使用できるマップSDK | ExpoSDKに含まれているか | メンテナス状況                                                                                                  |
typo
```suggestion
| ライブラリ名 | 使用できるマップSDK | ExpoSDKに含まれているか | メンテナンス状況                                                                                                  |
```

2023-06-14 02:41 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +| [rnmapbox](https://github.com/rnmapbox/maps) | [Mapbox Maps SDK for iOS](https://docs.mapbox.com/ios/maps/guides/)、[Mapbox Maps SDK for Android](https://docs.mapbox.com/android/maps/guides/)。 | × |
`react-native-maps`と`rnmapbox`で表示する地図が違うので、それらは要件によって適宜選択するべきということを記載した方がよさそうです

2023-06-14 03:02 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +rnmapboxは[バージョン10](https://github.com/rnmapbox/maps/tree/10.0)のリリースに向け開発が継続しています。
決定事項の理由からもメンテナンスの継続性に関する記述を削除するのが漏れていたので、削除してコミットしました
65481de41e220f587ea7b0db31955b3ede096d26

2023-06-14 03:04 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +比較した内容を以下の表にまとめました。メンテナンス状況は2023年3月時点のものになります。
```suggestion
比較した内容を以下の表にまとめました。メンテナンス状況は2023年5月時点のものになります。
```

2023-06-14 04:09 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +| [rnmapbox](https://github.com/rnmapbox/maps) | [Mapbox Maps SDK for iOS](https://docs.mapbox.com/ios/maps/guides/)、[Mapbox Maps SDK for Android](https://docs.mapbox.com/android/maps/guides/)。 | × |
注意書きとして、要件によって適宜選択した方が良いという旨を追記しましたー
6e479cae8edd279d85dccc878d5fef6eb84ebcee

@tksugimoto 確認お願いします

2023-06-14 04:11 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-017-map-view-library.mdx
> +比較した内容を以下の表にまとめました。メンテナンス状況は2023年3月時点のものになります。
5月で良いと思います！（5月と6月で比較結果に変わりはなさそうなので）

2023-06-14 05:08 UTC, creature-water-valley approved these changes

2023-06-14 05:13 UTC, merged