🔨: ライブラリのライセンス管理用scriptの改善
ws-4020/mobile-app-crib-notes pull request #1107
Opened 2023-04-06 07:32 UTC by tksugimoto

## ✅ What's done

- check-licenses の出力をコンパクトにする 
- ライセンス関連のscriptのwarnログに "[WARN]" を追加
- SantokuApp/.script/managed-license.js 管理のライセンスの version up追従
- gradle 側の `org.webkit:android-jsc` を exclude (npm 側で管理)
  - 関連して LGPL-2.0 を削除

## ⏸ What's not done
- nameDuplication （name 重複しているためユーザーが区別できない）対応
- suspiciousLicenseFileList （`licenseFile is README`）対応

元から規模が大きいため別PRでやる予定だった

---

## Tests

- [x] `node ./.script/check-licenses.js` 実行で `check-licenses: OK` が出力されて成功すること

## Other (messages to reviewers, concerns, etc.)
### 関連PR
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1031
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1015
  - `@graphql-typed-document-node/core` が更新された

※ `GoogleDataTransport` と `GoogleUtilities` は ignore されている部分で、 `prebuild` によって更新されると思われる

### `check-licenses の出力をコンパクトにする` の出力例
```js
  {
    type: 'cocoapods',
    libraryId: 'RNNotifee@5.7.0',
    name: 'RNNotifee',
    version: '5.7.0',
    checksum: '5155e0a5e0a97d0c839030d8192783cd63053999',
    licenseName: 'Apache-2.0',
    licenseText: 'Apache-2.0 License\n------------------\n\n...',
    id: 'cocoapods:RNNotifee@5.7.0'
  },
  {
    type: 'cocoapods',
    libraryId: 'RNReanimated@2.9.1',
    name: 'RNReanimated',
    version: '2.9.1',
    checksum: '2cf7451318bb9cc430abeec8d67693f9cf4e039c',
    licenseName: 'MIT',
    licenseText: 'The MIT License (MIT)\n' +
      '\n' +
      'Copyright (c) 2016 Software Mansion <swmansion.com>\n' +
      '...',
    id: 'cocoapods:RNReanimated@2.9.1'
  },
```
※ `util.inspect` の `maxStringLength` で制限すると file path が壊れる場合があるので文字列の行数を3行までに制限するようにした

2023-04-06 09:05 UTC, creature-water-valley approved these changes

2023-04-07 00:31 UTC, tksugimoto commented on example-app/SantokuApp/.script/check-licenses.js
> +    dependency.licenseText = dependency.licenseText.slice(0, limit) + '...';
> `dependency.licenseText = dependency.licenseText.slice(0, limit) + '...';`

- mutable な変更をしているのがよくない（現時点の呼び出し場所周辺のコードでは問題はない）
- 他の項目もsliceすべきではないか？

2023-04-07 01:39 UTC, tksugimoto commented on example-app/SantokuApp/.script/check-licenses.js
> +    dependency.licenseText = dependency.licenseText.slice(0, limit) + '...';
110f2e23d77d71ed49c89ea2a5c33cc64d2dd87c `chore: fix: check-licenses の出力のコンパクト表示改善`

出力例
```js
  {
    type: 'cocoapods',
    libraryId: 'RNNotifee@5.7.0',
    name: 'RNNotifee',
    version: '5.7.0',
    checksum: '5155e0a5e0a97d0c839030d8192783cd63053999',
    licenseName: 'Apache-2.0',
    licenseText: 'Apache-2.0 License\n------------------\n\n...',
    id: 'cocoapods:RNNotifee@5.7.0'
  },
  {
    type: 'cocoapods',
    libraryId: 'RNReanimated@2.9.1',
    name: 'RNReanimated',
    version: '2.9.1',
    checksum: '2cf7451318bb9cc430abeec8d67693f9cf4e039c',
    licenseName: 'MIT',
    licenseText: 'The MIT License (MIT)\n' +
      '\n' +
      'Copyright (c) 2016 Software Mansion <swmansion.com>\n' +
      '...',
    id: 'cocoapods:RNReanimated@2.9.1'
  },
```
※ `util.inspect` の `maxStringLength` で制限すると file path が壊れる場合があるので文字列の行数を3行までに制限するようにした

2023-04-07 01:47 UTC, in-a-paddy requested changes

2023-04-07 01:47 UTC, in-a-paddy commented on example-app/SantokuApp/.script/check-licenses.js
> +  'LGPL-2.0', // TODO: check
@tksugimoto @creature-water-valley これって、`org.webkit:android-jsc`のライセンスを指している？

WebKitのライセンスってLGPLと修正BSDのデュアルライセンスになってるんじゃないかと思ったんだけど、違うかな？
[Licensing WebKit](https://webkit.org/licensing-webkit/)

一応、わかる範囲では追ってみたんだけど、変なところあるかな、、、？
* SantokuApp（というか、React Native）で使っているJSCは、[npmのjsc-android](https://www.npmjs.com/package/jsc-android)のはず
* これは、[react-native-community/jsc-android-buildscripts](https://github.com/react-native-community/jsc-android-buildscripts)でビルドして公開されている
* このビルドスクリプトでは、https://svn.webkit.org/ からソースコードを[ダウンロードしてるっぽい](https://github.com/react-native-community/jsc-android-buildscripts/blob/main/scripts/download.sh#L9)
* ただ、svn.webkit.orgにはライセンス表記がない
* 一方で、webkit.orgには[Licensing WebKit](https://webkit.org/licensing-webkit/)があって、GitHubへのリンクもある
  * 去年、SVNからGitHubに移管したらしい: [「WebKit」プロジェクトがGitHubに移管](https://mag.osdn.jp/22/09/05/152100)
* SVNはたぶんGitHubからミラーされてるんだろうし、そうじゃなかったとしても、同じライセンスと考えていいのでは？

2023-04-07 03:03 UTC, tksugimoto commented on example-app/SantokuApp/.script/check-licenses.js
> +  'LGPL-2.0', // TODO: check
> org.webkit:android-jscのライセンスを指している？

そうです。

----

> WebKitのライセンスってLGPLと修正BSDのデュアルライセンスになってるんじゃないかと思ったんだけど、違うかな？
[Licensing WebKit](https://webkit.org/licensing-webkit/)

> licensed under the LGPL `and` BSD licenses

なので、「どちらか選べる」ではなく「どちらも満たす」デュアルライセンスではないかと思います。

参考1：[SPDX Specification 2.1 (web version) - Software Package Data Exchange (SPDX)](https://spdx.dev/spdx-specification-21-web-version/#h.jxpfx0ykyb60)

>      2)        Conjunctive “AND” Operator  
>   
> If required to simultaneously comply with two or more licenses, use the conjunctive binary “AND” operator to construct a new license expression , where both the left and right operands are a valid license expression values.  
>   
> For example, when one is required to comply with both the LGPL-2.1 or MIT licenses, a valid expression would be:  
>   
> (LGPL-2.1 AND MIT)  

※ 通常の英文表記と SPDX 記法が完全に同じではない可能性はあります

参考2: [Open Source - Internet & Web - WebKit](https://web.archive.org/web/20091005200350/https://developer.apple.com/opensource/internet/webkit.html) ※ archive (2009年)

> WebCore and JavaScriptCore are available under the Lesser GNU Public License. WebKit is available under a BSD-style license.  

最新の[Licensing WebKit](https://webkit.org/licensing-webkit/) では どの部分がどちらのライセンスかという情報が省略されているように思えます。

----

> SantokuApp（というか、React Native）で使っているJSCは、[npmのjsc-android](https://www.npmjs.com/package/jsc-android)のはず

そうでした。
gradle 側では npm package を参照していますね。

[build​.gradle](https://github.com/ws-4020/mobile-app-crib-notes/blob/71ac22db47fbbd5b1cd8ca8fe2a27533a4aaccaf/example-app/SantokuApp/prebuild/stg/android/build.gradle#L53-L56)
```
        maven {
            // Android JSC is installed from npm
            url(new File(['node', '--print', "require.resolve('jsc-android/package.json')"].execute(null, rootDir).text.trim(), '../dist'))
        }
```

npm package 側のライブラリでライセンス管理しているので、gradle側は exclude することにしました。

51b59a8b75823769499c969733408d88a85cfdf8 `chore: org.webkit:android-jsc:r250230 を managed-license.js から除外`

※ npm package [jsc-android](https://www.npmjs.com/package/jsc-android?activeTab=code) のライセンス表記を信頼します

2023-04-07 03:09 UTC, tksugimoto commented on example-app/SantokuApp/.script/check-licenses.js
> +  'LGPL-2.0', // TODO: check
削除漏れ対応
97b607448dc96acca26190535257622b54ef91cd `chore: license-text/LGPL-apple.txt を削除`

2023-04-07 04:55 UTC, in-a-paddy approved these changes

2023-04-07 04:58 UTC, merged

2023-04-07 05:21 UTC, tksugimoto commented on example-app/SantokuApp/.script/managed-license.js
>          licenseName: 'Apache-2.0', // 名称だけ SPDX 形式に変更する (元: Apache)
📝  ライセンスバージョンアップでライセンスが変更されていないことの確認

```
[WARN] License unsafe!!!! [
  {
    type: 'cocoapods',
    libraryId: 'GoogleDataTransport@9.2.2',
    name: 'GoogleDataTransport',
    version: '9.2.2',
    checksum: '8378d1fa8ac49753ea6ce70d65a7cb70ce5f66e6',
    licenseName: 'Apache',
    licenseText: '\n' +
      '                                 Apache License\n' +
      '                           Version 2.0, January 2004\n' +
      '...',
    id: 'cocoapods:GoogleDataTransport@9.2.2'
  },
  {
    type: 'cocoapods',
    libraryId: 'GoogleUtilities@9aa0ad5a7bc171f8bae016300bfcfa3fb8425749',
    name: 'GoogleUtilities',
    version: null,
    checksum: '9aa0ad5a7bc171f8bae016300bfcfa3fb8425749',
    licenseName: 'Apache',
    licenseText: '\n' +
      '                                 Apache License\n' +
      '                           Version 2.0, January 2004\n' +
      '...',
    id: 'cocoapods:GoogleUtilities@9aa0ad5a7bc171f8bae016300bfcfa3fb8425749'
  }
]
```