📝: 強制アプリアップデートに関するADRを追加
ws-4020/mobile-app-crib-notes pull request #1139
Opened 2023-05-11 08:47 UTC by creature-water-valley

## ✅ What's done

- [x] 強制アプリアップデートに関するADRを追加

---

## Other (messages to reviewers, concerns, etc.)

### 関連PR

- #800 
- #785 
- #786

2023-05-12 00:47 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象となった場合は、アップデートを促すダイアログを表示する
> アップデート対象となった場合は、アップデートを促すダイアログを表示する

これは、キャンセルできるのでしょうか？それともアップデートしないと操作できないのでしょうか？
（`可否` じゃなくて `要否` なので後者？）

明示しておくと誤解がなくて良いと思います。

2023-05-12 00:50 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象となった場合は、アップデートを促すダイアログを表示する
また、どちらの場合でも、 `## 議論` の `###` セクションを作ると良いと思います。

前2つのように、「他の選択肢など」の説明が書ける（けど今は省略されてしまっている）のだと思います。

2023-05-12 01:32 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象となった場合は、アップデートを促すダイアログを表示する
強制アップデートなので、操作不可にする以外の選択肢は検討してなかった気がする。
コンテキストとか要約で、背景をもう少し詳細に記載したほうがいいってことかな。この機能は、「アップデート通知」機能じゃなくて「強制アップデート」機能の話なんだけど、伝わりにくいのでは？

2023-05-12 01:47 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象となった場合は、アップデートを促すダイアログを表示する
タイトルがに強制っていう文言を付けているのと、コンテキストにも通知というよりは強制的にアップデートする仕組みと記載してますが、ほかにどんな情報（背景）を記載したら良いですかね？
例をもらえると助かります。

> モバイルアプリのアップデートは、ユーザが自身で行う必要があります。しかし、セキュリティ脆弱性を検知した場合や外部サービスのインターフェースが変更された場合など、アプリを強制的にアップデートしたいケースがあります。
そういったケースに対応するため、特定のバージョン以下のアプリを強制的にアップデートする仕組みを検討します。

2023-05-12 02:22 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象となった場合は、アップデートを促すダイアログを表示する
「促す」に「強制」のニュアンスが無いため「取消できるんだな」と理解していました。
タイトルに「強制」とありますが、「アプリを長時間起動しているユーザには、アップデートを促すタイミングが遅れてしまいますが、それは許容します。」のように100%強制でもなかったので。

「強制」を使うか、もう少しマイルドにしたいならば「要求」を使ったほうが「強制」に近い気がします。

また、人によって強制アップデートの定義が違うこともありそうです。
以下は `強制アプリアップデート` で検索した1件目。。

[アプリの強制アップデート機能を実装する際に気をつけるべきポイント | Pentagon Blog](https://blog.pentagon.tokyo/1891/)

> ポップアップのアクションとしては「あとで」と「アップデートする」の２択を表示した方が良いです。

2023-05-12 02:22 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象となった場合は、アップデートを促すダイアログを表示する
後は、（今回は違いますが）ストアを通さないOTAアップデートの場合、
裏でアップデート（ダウンロード？）しておいて、次回起動時に反映されるという設定もできるという話なので、
少なくとも、「ストア更新」「OTA」に関しては記述しておくと良いと思います。


[ExpoのOTA updateの仕様について](https://zenn.dev/marin_a___/articles/7eec197a8c3579#fallbacktocachetimeout)

> fallbackToCacheTimeout  

> [パターン２: 30000ミリ秒以内にダウンロードできなかったとき]
端末にキャッシュされている最新のバージョンを使用してアプリが起動。その後もバックグラウンドでダウンロードし続けて，ダウンロードが終わった時点でキャッシュに保存されます。そのため，次回起動時(※)は最新のバンドルが反映されます。

> ※[Updates.addListener](https://docs.expo.io/versions/latest/sdk/updates/#updatesaddlistenereventlistener)を使うことで，パターン２でダウンロードが終わった時点で特定の挙動をさせることができます。

2023-05-12 02:45 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象となった場合は、アップデートを促すダイアログを表示する
> 「促す」に「強制」のニュアンスが無いため「取消できるんだな」と理解していました。

なるほどです。
促すは要求に変更しました。
また、「また、アプリをアップデートするまでは、このアプリの機能を使用できないようにします。」という文言を追加して、アップデートは半強制的であることがわかるようにしました。

79e917f56913ee9d1ee105ea9dacdecdff828ac5

> 少なくとも、「ストア更新」「OTA」に関しては記述しておくと良いと思います。

議論の前提として、アプリのアップデートはストアを介するものであり、OTAアップデートは対象外であることを明記してみました

ab074cb81d1bb5157a24abc2a7e774cd80912df3

2023-05-12 03:13 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +また、アプリをアップデートするまでは、このアプリの機能を使用できないようにします。
> アプリは、レスポンスから受け取ったアップデート要否に基づいて、アップデートを要求するダイアログを表示します。
> また、アプリをアップデートするまでは、このアプリの機能を使用できないようにします。

これは「アップデート対象の確認方法」ではないので、移動したほうが良いと思います。

`## 議論` の `### アップデートの提示` として追加しようと思いましたが、他の候補は無く `議論` ではない点がしっくりきていません。

※ 2行目 (`アプリの機能を使用できないようにします` )は、コンテキストの部分に前提（仕様・要求）として書いておくことも可能だと思います。

2023-05-12 04:27 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +また、アプリをアップデートするまでは、このアプリの機能を使用できないようにします。
うーん、それならこの部分はADRから削除しますかね？（この内容はApplication Architectureには記載するので）

個人的には、指摘もらって「言われてみれば確かに」とは思いましたが、さほど気にはならないので今のままでも良いかなとは気もしますが。

2023-05-12 04:39 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +また、アプリをアップデートするまでは、このアプリの機能を使用できないようにします。
確かに、3番目のアップデート提示に関してはこのADRの範囲外ですね。
そうしましょうか。

```suggestion
```

以下の削除は別途必要です（↑とまとめてでもOKです）
```
- アップデート対象となった場合は、アップデートを要求するダイアログを表示する
```

2023-05-12 04:43 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +また、アプリをアップデートするまでは、このアプリの機能を使用できないようにします。
↓で対応しましたー
10e253fd5ade685e79e646c8d7aa26d904b11137

2023-05-12 04:44 UTC, tksugimoto approved these changes

2023-05-12 04:59 UTC, in-a-paddy requested changes

2023-05-12 04:59 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +そういったケースに対応するため、特定のバージョン以下のアプリを強制的にアップデートする仕組みを検討します。
💭 設定によっては（というかデフォルト設定では）自動アップデートもあるから、ユーザが自身で行う必要があるというのはちょっと言い過ぎかな、と。

こんな感じでどうだろうか。（Lintとか怪しいからSuggestionは使わなかった）

> モバイルアプリでは、アプリのアップデートタイミングはユーザに委ねられており、基本的には提供元がコントロールすることはできません。
> しかし、重大なゼロデイ脆弱性を検知した場合や外部サービスのインターフェースが変更された場合など、ユーザの利用しているアプリを強制的にアップデートさせたいという要求は少なからずあります。
>
> そのため、アップデートするまでユーザがアプリを利用できないようにする仕組みを検討します。

2023-05-12 04:59 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象の確認はアプリ起動時に実施する
💭 全体的になんだけど、「アップデート対象」より「アップデート要否」の方がしっくりくるかな。直前でも「アップデート要否を確認」って言ってるし。

2023-05-12 04:59 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +その反面、開発コストも増えます。即時に確認する場合は、外部サービスの導入や新しい技術スタックの追加が必要になります。
❓ タイミングに関してメリデメ比較したのって、開発コストの問題だけだっけ？他にもメリデメ検討したような。ちょっと説得力に欠けるし、情報が少なすぎて他のプロジェクトで参考にしづらい気がする。

2023-05-12 05:11 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +そういったケースに対応するため、特定のバージョン以下のアプリを強制的にアップデートする仕組みを検討します。
↓で対応しましたー
5e84fde7f2f6101991b57f8a8566c06dc555ecd8

2023-05-12 05:19 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +- アップデート対象の確認はアプリ起動時に実施する
アップデート要否に変更しましたー
d7def7adc55aa6c265d5fa1c890b88736ecf5571

2023-05-12 05:32 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +その反面、開発コストも増えます。即時に確認する場合は、外部サービスの導入や新しい技術スタックの追加が必要になります。
当時の議論結果（受け取ったメモ）には特に記載がなく、、、

別の場で、データ更新するようなAPIを複数呼び出した場合などに、途中で強制アップデートするとデータの整合性大丈夫かなという話題は挙がった気がするけど、

**結局それは強制アップデートに限った話ではなくエラー処理全般に言えること**

なので、ここの議論ではないという結論になったかと。

2023-05-15 03:00 UTC, tksugimoto commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +その反面、開発コストも増えます。即時に確認する場合は、外部サービスの導入や新しい技術スタックの追加が必要になります。
- どういう観点で検討すべきか（アプリの機能・特性ごとに優先する観点は違う）
  - 実装コスト（クライアント）
  - 実装コスト（サーバー）
  - UX(入力中のものが消える・PUSH通知から開いたけど更新を要求されて開けない etc）
  - 強制タイミング（本当に強制が必要な更新か？どういう変更なら強制が必要か？）

> データ更新するようなAPIを複数呼び出した場合などに、途中で強制アップデートするとデータの整合性大丈夫かな

通常は、1APIでまとめて送る設計とする。が、backend都合で複数に分かれているケースがある。
また、backend FQDNが異なる場合は複数に分かれることを回避できない。

2023-05-15 05:48 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +その反面、開発コストも増えます。即時に確認する場合は、外部サービスの導入や新しい技術スタックの追加が必要になります。
議論した内容を追記してみました
c2ea3f54c2ef4792ff59a430292978a1167ab825

2023-05-16 02:37 UTC, in-a-paddy approved these changes

2023-05-16 02:59 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +前提として、アプリのアップデートはApp StoreやGoogle Playを介して行うものとします。
Google Play Store -> Google Playに変更した方が良い（他のページではStoreを付けてない）
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1141#discussion_r1194539382

2023-05-16 03:00 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-016-forced-app-updates.mdx
> +前提として、アプリのアップデートはApp StoreやGoogle Playを介して行うものとします。
↓で対応
fa59588b9cad638dffed671cf7132f1333dd018f

2023-05-17 01:02 UTC, merged