📝: コーディング規約を追加
ws-4020/mobile-app-crib-notes pull request #1201
Opened 2023-07-21 08:47 UTC by creature-water-valley

## ✅ What's done

- [x] 静的解析ツールの規約を追加
- [x] 自動ではチェックできない規約を追加
- [x] NablarchのJavaScript規約に記載されているルールを一覧化し、それらのルールを以下のカテゴリに分けました。
  - 静的解析ツールでチェック可能
  - レビュー対象（今回のPRで追加した「JavaScript/TypeScriptのコーディング規約」ページに追加）
  - 対象外（このアプリでは不要と思われる規約）
- [ ] ↑のページをマージ前に削除
- [ ] ESLintのルール一覧最新化（以下のPRマージ後に最新化）
  - https://github.com/ws-4020/mobile-app-crib-notes/pull/1191
  - https://github.com/ws-4020/mobile-app-crib-notes/pull/1192
  - https://github.com/ws-4020/mobile-app-crib-notes/pull/1193
  - https://github.com/ws-4020/mobile-app-crib-notes/pull/1194
  - https://github.com/ws-4020/mobile-app-crib-notes/pull/1195

## ⏸ What's not done

- Reactに関する規約の追加

---

## Other (messages to reviewers, concerns, etc.)

### 参考

[Nablarchのサンプルプロジェクト開発ガイド](https://github.com/Fintan-contents/nablarch-system-development-guide/tree/master/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E9%96%8B%E7%99%BA%E3%82%AC%E3%82%A4%E3%83%89/PGUT%E5%B7%A5%E7%A8%8B/pg)

- 今回のPRで追加した「静的解析ツールの運用」は↓のページをベースにしています。
  - [Checkstyle運用ガイド](https://github.com/Fintan-contents/nablarch-system-development-guide/blob/master/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E9%96%8B%E7%99%BA%E3%82%AC%E3%82%A4%E3%83%89/PGUT%E5%B7%A5%E7%A8%8B/proman-style-guide/java/staticanalysis/checkstyle/docs/Ops-Rule.md)
- 今回のPRで追加した「JavaScript/TypeScriptのコーディング規約」は↓のページをベースにしています。
  - [JavaScriptコーディング規約.docx](https://github.com/Fintan-contents/nablarch-system-development-guide/blob/master/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E9%96%8B%E7%99%BA%E3%82%AC%E3%82%A4%E3%83%89/PGUT%E5%B7%A5%E7%A8%8B/proman-style-guide/js/JavaScript%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84.docx)

2023-07-28 07:32 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement.mdx
> +    to: '/react-native/santoku/development/implement/coding-rules/overview',
`/overview` のタイトルはスタイルガイドで良いと思います。


[nablarch-system-development-guide/サンプルプロジェクト/サンプルプロジェクト開発ガイド/PGUT工程/proman-style-guide/README.md at 3.5 · Fintan-contents/nablarch-system-development-guide](https://github.com/Fintan-contents/nablarch-system-development-guide/blob/3.5/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E9%96%8B%E7%99%BA%E3%82%AC%E3%82%A4%E3%83%89/PGUT%E5%B7%A5%E7%A8%8B/proman-style-guide/README.md)

> Nablarchスタイルガイド  
> 本リポジトリではJavaをはじめとする各言語のコーディング規約と、Checkstyle・SpotBugsといった静的解析ツールの導入ガイドを提供します。  
>   
> Javaスタイルガイド  
> JavaScriptスタイルガイド  
> JSPスタイルガイド  
> SQLスタイルガイド  
> シェルスクリプトスタイルガイド  


[nablarch-system-development-guide/サンプルプロジェクト/サンプルプロジェクト開発ガイド/PGUT工程/proman-style-guide/java/README.md at 3.5 · Fintan-contents/nablarch-system-development-guide](https://github.com/Fintan-contents/nablarch-system-development-guide/blob/3.5/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E9%96%8B%E7%99%BA%E3%82%AC%E3%82%A4%E3%83%89/PGUT%E5%B7%A5%E7%A8%8B/proman-style-guide/java/README.md)

> Javaスタイルガイド  
> ここではJavaをコーディングする際に役立つコーディング規約やコードフォーマッター、静的検査のガイドを提供しています。  


[nablarch-system-development-guide/サンプルプロジェクト/サンプルプロジェクト開発ガイド/PGUT工程/proman-style-guide/java/java-style-guide.md at 3.5 · Fintan-contents/nablarch-system-development-guide](https://github.com/Fintan-contents/nablarch-system-development-guide/blob/3.5/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E9%96%8B%E7%99%BA%E3%82%AC%E3%82%A4%E3%83%89/PGUT%E5%B7%A5%E7%A8%8B/proman-style-guide/java/java-style-guide.md)

> Javaコーディング規約

2023-07-28 08:02 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement.mdx
> +    title: 'コーディングルール',
「コーディング規約」に統一しましたー
085e9d5a4bdb41b5fedd7e72d600c7d1f7d2f2bd

2023-07-28 08:10 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement.mdx
> +    to: '/react-native/santoku/development/implement/coding-rules/overview',
> ⚠Nablarchのガイドだと、ディレクトリ名はstyle-guideになってるからそろえてほしい
対応しましたー
085e9d5a4bdb41b5fedd7e72d600c7d1f7d2f2bd

> /overview のタイトルはスタイルガイドで良いと思います（その場合 website/docs/sidebars.js の labelも変更）
対応しましたー
95e07d48b1696c0ddb7b276f0ea69517397754af

2023-07-28 08:15 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement.mdx
> +    to: '/react-native/santoku/development/implement/style-guide/overview',
スタイルガイドは全体に影響する大きい話なので、
```
メッセージの定義と取得 »
Firebaseの機能を利用する際の注意点 »
HTTP APIの呼び出し »
コーディング規約 »
```
の最後じゃなくて先頭にあると良いと思います。

2023-07-28 08:16 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement.mdx
> +    to: '/react-native/santoku/development/implement/style-guide/overview',
> このアプリケーションを実装する際の部品の使用方法などについて紹介します。

部分もスタイルガイドについて追記すると良いと思います。

2023-07-28 08:17 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/naming-conversion.mdx
> +`Keychain`や`UserDefaults`、`SharedPreferences`のようなローカルストレージに格納するキーは、格納する項目を端的に表す名詞にしてください。
現状の実装に合わせてこのような記載にはしたけど、本当にこれで良い？という感覚でいます。
（キー重複が発生しそうと言う意味で）

対応するなら、「機能モジュール名_項目名」とかかなと思ったのですが、
現状セキュアストレージに格納している機能モジュール名は`secure-storage`となっており、それだと何の意味もないと思ってるところです。

何か、案はないでしょうか？

2023-07-28 08:36 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/typescript.mdx
> +| [allowJs](https://www.typescriptlang.org/tsconfig#allowJs)                                           | true                |
ts config のテーブル順は`tsc --showConfig` だと思うんですが、
[tsconfig.json](https://github.com/ws-4020/mobile-app-crib-notes/tree/master/example-app/SantokuApp/tsconfig.json)にかかれている順と同じほうが読みやすい（人が多少は多い）んじゃないかと思いました。

2023-07-28 08:44 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +npm run lint:es
fix じゃないと フォーマットされませんでした。
```suggestion
npm run fix:es
```

```
$ npm run lint:es
> santoku-app@1.0.0 lint:es
> eslint --ext .jsx,.js,.tsx,.ts .


example-app/SantokuApp/src/features/demo-react-query/pages/DependentQueryDemo3Page.tsx
  8:10  warning  Replace `⏎····todoDetails,⏎····isIdle,⏎····isLoading,⏎····isRefetching,⏎····isSuccess,⏎····isError,⏎····refetch,⏎····reload,⏎··` with `todoDetails,·isIdle,·isLoading,·isRefetching,·isSuccess,·isError,·refetch,·reload`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

2023-07-28 08:55 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +Visual Studio CodeでPrettierを有効にする方法については、[Visual Studio Code - Lint、フォーマッタ](../../tools/vscode.md#lintフォーマッタ)を参照してください。
このPRの範囲外ですが、リンク先を見て
```
"editor.formatOnSave": true
```
設定を入れてみましたが、自動フォーマットされませんでした。
↓が必要でした（↑はなくてもOK）
```
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    }
```

2023-07-31 02:14 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement.mdx
> +    to: '/react-native/santoku/development/implement/style-guide/overview',
> スタイルガイドは全体に影響する大きい話なので、

↓で対応しましたー
dffc2fdbab0a41fac8831a02d5a87b700e978894

2023-07-31 02:15 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/eslint.mdx
> +npm run lint:es -- --fix
いえ、`npm script`に定義してあるのを忘れてました。
↓で修正しましたー
b0e20910f50342eec928e1da7bebd1be4de8398f

2023-07-31 02:17 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/typescript.mdx
> +| [allowJs](https://www.typescriptlang.org/tsconfig#allowJs)                                           | true                |
記載順をSantoku Appの定義順に合わせましたー
ad9db70b57e91e634e2b3836cc05bbb74a6bff96

2023-07-31 02:19 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +npm run lint:es
ここは `Prettier`の実行（fixなし）のコマンドを記載しているつもりだったので、 フォーマットされないのは想定通りなのですが、 `fix`するコマンドも記載した方が良さそうですね。

ESLintと同じコマンドになるので、ESLintの実行方法を参照するように変更しましたー
f53d632fe79e624613bc6f4adc042f7bad4cac1d

2023-07-31 02:57 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/naming-conversion.mdx
> +`Keychain`や`UserDefaults`、`SharedPreferences`のようなローカルストレージに格納するキーは、格納する項目を端的に表す名詞にしてください。
キー重複を見つけやすくするために、キー文字列定義を1ファイルにまとめるなら、モジュール名は `secure-storage` で統一になるので使わずに、サブモジュール(?)名＝methodを呼び出す機能名（現状1つしかないですが、`ACCOUNT` など）でしょうか。

- `ACCOUNT-ACTIVE_ID`
- `ACCOUNT-PASSWORD`

1ファイルにまとめると多すぎる規模なら、ディレクトリ構造を1階層深くして、サブモジュール単位でファイルを作成となると思います（こちらはファイルが分かれるのでルール遵守が必要）。


### 現状（参考）
`storedItemKeys.ts`
```ts
export const STORED_ITEM_KEYS = {
  ACTIVE_ACCOUNT_ID: 'activeAccountId',
  PASSWORD: 'password',
} as const;
```
```
$ git grep "return SecureStore"
src/features/secure-storage/services/deleteActiveAccountId.ts:  return SecureStore.deleteItemAsync(STORED_ITEM_KEYS.ACTIVE_ACCOUNT_ID);
src/features/secure-storage/services/deletePassword.ts:  return SecureStore.deleteItemAsync(`${hash}_${STORED_ITEM_KEYS.PASSWORD}`);
src/features/secure-storage/services/loadActiveAccountId.ts:  return SecureStore.getItemAsync(STORED_ITEM_KEYS.ACTIVE_ACCOUNT_ID);
src/features/secure-storage/services/loadPassword.ts:  return SecureStore.getItemAsync(`${hash}_${STORED_ITEM_KEYS.PASSWORD}`);
src/features/secure-storage/services/saveActiveAccountId.ts:  return SecureStore.setItemAsync(STORED_ITEM_KEYS.ACTIVE_ACCOUNT_ID, accountId, {
src/features/secure-storage/services/savePassword.ts:  return SecureStore.setItemAsync(`${hash}_${STORED_ITEM_KEYS.PASSWORD}`, password, {
```
（hashの結合は先頭じゃなくて末尾のほうがprefixが揃うので良さそうです）

2023-07-31 04:51 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +Visual Studio CodeでPrettierを有効にする方法については、[Visual Studio Code - Lint、フォーマッタ](../../tools/vscode.md#lintフォーマッタ)を参照してください。
VS Codeの設定をGit管理して、その設定のリンクを追加で記載しておけば良さそうですね。

@tksugimoto ↓にタスクを切っておいたので、お手隙の時に対応お願いします。
（VS Code使ってないのでわからず。）

https://dev.azure.com/ws-4020/develop-mobile-app-casually/_workitems/edit/18103

特段急ぎではないので、このPRをマージしてからでも全然問題ないかと思います。

2023-07-31 05:25 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +競合を解決するために、[eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)を導入します。`eslint-config-prettier`は、Prettierと競合するESLintのルールを無効化するためのESLintプラグインです。
`eslint-config-universe` (`universe/native`)に含まれていて、設定済みであることことを書いておくと良さそうです。

2023-07-31 05:31 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +Prettierのいくつかのルールは、EditorConfigのルールと同じものがあります。
EditorConfig へのリンク追加。
あと、サイドバーなどでPrettierよりEditorConfigが先にあると良いと思います。今はまだ未説明のものが前に出てきているので。
```suggestion
Prettierのいくつかのルールは、[EditorConfig](./editorconfig.mdx)のルールと同じものがあります。
```

2023-07-31 05:34 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/editorconfig.mdx
> +Visual Studio CodeでPrettierを有効にする方法については、[Visual Studio Code - Lint、フォーマッタ](../../tools/vscode.md#lintフォーマッタ)を参照してください。
コピペ修正漏れ
```suggestion
Visual Studio CodeでEditorConfigを有効にする方法については、[Visual Studio Code - Lint、フォーマッタ](../../tools/vscode.md#lintフォーマッタ)を参照してください。
```

2023-07-31 07:12 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +適用している全てのルールは以下のとおりです。
`.prettierrc.js`にある設定数と下のテーブルの行数が(EditorConfigを除いても)結構違います。

> ESLintのCLIで[--print-config](https://eslint.org/docs/latest/use/command-line-interface#--print-config)オプションを指定すると、適用されているルールを確認できます。

のようなCLIから実行して取得した場合、それを書いておくと良いと思います。

後、`.prettierrc.js` に書かれてないものの在り処も。TSCと違いデフォルトを表示しているんでしょうか？

2023-07-31 07:26 UTC, tksugimoto commented on website/docs/sidebars.js
> +                'react-native/santoku/development/implement/style-guide/typescript-style-guide',
`TypeScriptコーディング規約` がメインで
`コーディングに関する命名規約` がサブっぽいので、順序を逆にするのはどうでしょう？


```suggestion
                'react-native/santoku/development/implement/style-guide/typescript-style-guide',
                'react-native/santoku/development/implement/style-guide/naming-conversion',
```

2023-07-31 07:44 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +コンポーネント名は、基本的にそのコンポーネントの特徴を端的に表す名詞とし、先頭の文字は大文字で開始してください。
> 基本的には

例外についての説明がないので「基本的には」を消しても良いのではないでしょうか？

```suggestion
### クラス名は名詞としてください

クラス名は、そのクラスの特徴を端的に表す名詞とし、先頭の文字は大文字で開始してください。

### 型エイリアス名は名詞としてください

型エイリアス名は、その型エイリアスの特徴を端的に表す名詞とし、先頭の文字は大文字で開始してください。

### コンポーネント名は名詞としてください

コンポーネント名は、そのコンポーネントの特徴を端的に表す名詞とし、先頭の文字は大文字で開始してください。
```

2023-07-31 07:53 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +}
コード例修正
```suggestion
// OK
public collectNames(items: Item[]) {
  // 一時変数はローカル変数を使用して、メソッドに渡して引き回している
  const itemNames: string[] = [];
  for (const item of items) {
      this.collectName(itemNames, item);
  }
  return itemNames.join(',');
}

private collectName(itemNames: string[], item: Item) {
  itemNames.push(item.name);
}
```

2023-07-31 08:02 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +    return this.items.map(item => item.price).reduce((price1, price2) => price1 + price2);
items が `[]` の場合にエラーとなるため初期値を追加
```suggestion
    return this.items.map(item => item.price).reduce((price1, price2) => price1 + price2, 0);
```

2023-07-31 08:07 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +    service.update(readNotification);
本質的じゃない部分に差異があって混乱するので統一
```suggestion
    const alreadyReadNotification = {...notification, status: Status.ALREADY_READ};
    service.update(alreadyReadNotification);
```

```ts
//「既読状態への更新」は別メソッドとしている
function updateToAlreadyRead(notifications: Notification[]) {
  for (const notification of notifications) {
    const alreadyReadNotification = {...notification, status: Status.ALREADY_READ};
    service.update(alreadyReadNotification);
  }
}
```

2023-07-31 08:19 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +  .reduce((sum, age) => sum + age);
空配列に対応
```suggestion
  .reduce((sum, age) => sum + age, 0);
```

直後で 0除算になるが、エラーの位置を揃えておく

2023-07-31 08:26 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +多くの場合、これは1つのファイルに付き1つの`export`を持つことが良いことを意味します。
`に付き` → `につき`

```suggestion
### 1つのファイルにつき1つの export にしてください

アプリ内の各ファイルは、1つの論理的な`Module`を表すべきです。
無関係なさまざまな関数やシンボルをエクスポートするような`Module`は避けてください。

多くの場合、これは1つのファイルにつき1つの`export`を持つことが良いことを意味します。
```

既存文章に揃える。

```
$ git grep -E "に(付|つ)き"
website/docs/distribution/usecase.mdx:|デバイス台数制限|1人につき30台まで|なし|
website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx:### 1つのファイルに付き1つの export にしてください
website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx:多くの場合、これは1つのファイルに付き1つの`export`を持つことが良いことを意味します。
```

2023-07-31 08:40 UTC, creature-water-valley commented on website/docs/sidebars.js
> +                'react-native/santoku/development/implement/style-guide/typescript-style-guide',
↓で順序を逆にしてみましたー
0004ad0b7cce1c7276a3701a183239513e6e00bc

2023-07-31 08:41 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +Prettierのいくつかのルールは、EditorConfigのルールと同じものがあります。
↓でリンクを追加しましたー
c7eb7c925b9ad4f051df0701c3260ddaa374023d

また、目次でEditorConfigをPrettierより先に表示するように変更しましたー
935ef621182267bce48aa791a8a77d0b10fa41e0

2023-07-31 08:47 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/nablarch-javascript-santoku-mapping.mdx
> +| 2.2.2 |定数 ★| 定数は必ずconstを使用して定義する。変数名は全て大文字かつ単語間の区切りにアンダースコア("_")を用いる。 | 対象（Javaの規約の命名ルールと合わせて考える）                              |
定数の変数名に関する規約なかった気がします

2023-07-31 09:10 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/nablarch-java-santoku-mapping.mdx
> +| 3.4 | [データモデルの用語辞書を活用して命名してください](https://github.com/Fintan-contents/nablarch-system-development-guide/blob/master/サンプルプロジェクト/サンプルプロジェクト開発ガイド/PGUT工程/proman-style-guide/java/java-style-guide.md#no3-4
> データモデルの用語辞書を活用して命名してください
> 対象

見つけられませんでした。

2023-07-31 09:12 UTC, tksugimoto commented on website/docs/react-native/santoku/development/implement/style-guide/nablarch-javascript-santoku-mapping.mdx
> +| 2.2.4 |変数(真偽値) ★| 真偽値を格納する変数の名前は、形容詞、もしくは 節 とする。節の時制は、基本的に状態動詞の場合は現在形、動作動詞の場合は過去形とし、主語が明確である場合は省略する。| 対象（Javaの規約の命名ルールと合わせて考える）                              |
> | 2.2.4 |変数(真偽値) ★| 真偽値を格納する変数の名前は、形容詞、もしくは 節 とする。節の時制は、基本的に状態動詞の場合は現在形、動作動詞の場合は過去形とし、主語が明確である場合は省略する。| 対象（Javaの規約の命名ルールと合わせて考える）                              |

こちらもなかった気がします。

2023-08-01 06:57 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/typescript.mdx
> +TypeScriptに対応しているエディタやIDEでコーディングすると、コード補完や型チェックなどの機能が使えます。
以下の対応をしましたー

* 概要に記載していたエディタ、IDEに関する記述を削除
* 必要に応じて、エディタ、IDEの項？に移動

対象は、以下です。
* ESLint
* EditorConfig
* Prettier
* TypeScript

75e5b83276b64ccff64d34a4f1138938f2be5efe

2023-08-01 06:57 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +競合を解決するために、[eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)を導入します。`eslint-config-prettier`は、Prettierと競合するESLintのルールを無効化するためのESLintプラグインです。
`eslint-config-universe`について、追記してみましたー
2fc4f12c87ee8b609c4c2ca0cf8536c576dc55e7

2023-08-01 07:00 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/nablarch-javascript-santoku-mapping.mdx
> +| 2.2.2 |定数 ★| 定数は必ずconstを使用して定義する。変数名は全て大文字かつ単語間の区切りにアンダースコア("_")を用いる。 | 対象（Javaの規約の命名ルールと合わせて考える）                              |
定数を追加しましたー
1867368a11ee4148f1ac05492d407e522c334eb9

2023-08-01 07:00 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/nablarch-java-santoku-mapping.mdx
> +| 3.4 | [データモデルの用語辞書を活用して命名してください](https://github.com/Fintan-contents/nablarch-system-development-guide/blob/master/サンプルプロジェクト/サンプルプロジェクト開発ガイド/PGUT工程/proman-style-guide/java/java-style-guide.md#no3-4
用語辞書の活用に関するルールを追加しましたー
2c0b5556d5917bd65a30756658ba316d2660ab08

2023-08-01 07:01 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/nablarch-javascript-santoku-mapping.mdx
> +| 2.2.4 |変数(真偽値) ★| 真偽値を格納する変数の名前は、形容詞、もしくは 節 とする。節の時制は、基本的に状態動詞の場合は現在形、動作動詞の場合は過去形とし、主語が明確である場合は省略する。| 対象（Javaの規約の命名ルールと合わせて考える）                              |
変数名のルールに、真偽値に関する内容を追記しましたー
7d7afa6543fb81ceedc855b61adecafe82d44a8c

2023-08-01 07:38 UTC, tksugimoto approved these changes

2023-08-01 08:28 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/coding-rules/lint-ops.mdx
> +new Person(); // eslint-disable-line no-new -- コンストラクタの検証のみをテストするため、作成したインスタンスを使用しない
「作成したインスタンスを以降の処理で使用しないため」に変更しました。（が、あまりいい例ではない気がするので、もし良い案があれば連携ください、、、）
776dddd37e85cafb9b21a54d9c540766856f6ccf

2023-08-01 08:40 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/naming-conversion.mdx
> +`Keychain`や`UserDefaults`、`SharedPreferences`のようなローカルストレージに格納するキーは、格納する項目を端的に表す名詞にしてください。
なんか、単純に`機能モジュール名_項目名`で良い気がしてきました。
`secure-storage`の機能モジュールに置いてるから、`account`っていう機能モジュール名を付けちゃダメではないのと、それが嫌なら`account`にキーの定数を移動してしまえば良いと思い。

a9ea12cabc29a5077c2efb9880742ea594dfb8ed

2023-08-01 08:45 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/prettier.mdx
> +Prettierのいくつかのルールは、EditorConfigのルールと同じものがあります。
「静的解析ツールの運用」ページに記載しているツールの順番も、目次に合わせました
fb9de502e8bac561c694e3fd8ad1e6bc8b7efa95

2023-08-03 04:45 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +## 推奨事項
NablarchのJava規約に追加された以下は追加した方が良さそうです。
- https://github.com/Fintan-contents/coding-standards/pull/20/files#diff-6c5fd305eeaa4cc84a612bb1fe6b2632e95843d82be42ef923b98839817d4a24R73

2023-08-03 05:58 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +## 推奨事項
追加しました
eb66cf730beae1552f56bd6205089f13b6c0e9f2

2023-08-22 10:23 UTC, in-a-paddy commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +なお、`Barrel`に関してはこの規約の対象外とします。
💭 Barrelはコード表記にしなくていいんじゃないかな。

```suggestion
なお、Barrelに関してはこの規約の対象外とします。
```

2023-08-23 00:56 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
TOCがサイドにあると、ほとんどのタイトルが改行されて見づらいので、ページ先頭に表示してみてはどうでしょうか

2023-08-23 00:57 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +- コンストラクタ内で別のクラスに処理を委譲し、その結果を使用する
関数に委譲するように文言を修正しましたー
85853d6cde9d05e03bea43c69f532bd0878012f2

2023-08-23 00:58 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
TOCをページ先頭に表示するように修正してみましたー
447708e10703ed5625ae810ad799063fb73381c1

2023-08-23 04:12 UTC, in-a-paddy requested changes

2023-08-23 04:12 UTC, in-a-paddy commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +### 配列やオブジェクト全体をコピーする場合はスプレット構文を使用してください
スプレット構文 → スプレッド構文

[スプレッド構文 - JavaScript - MDN Web Docs](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

2023-08-23 04:12 UTC, in-a-paddy commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +const values Item[] = ...
```suggestion
const values: Item[] = ...
```

2023-08-23 04:12 UTC, in-a-paddy commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +const values Item[] = ...
```suggestion
const values: Item[] = ...
```

2023-08-23 04:39 UTC, creature-water-valley commented on website/docs/react-native/santoku/development/implement/style-guide/typescript-style-guide.mdx
> +### 配列やオブジェクト全体をコピーする場合はスプレット構文を使用してください
修正しましたー
1c611fb4e9be611e5181b41f589b05a0a445350e

2023-08-23 08:28 UTC, in-a-paddy approved these changes

2023-08-24 00:04 UTC, merged