📝 モバイルアプリケーション配布のドラフト版作成
ws-4020/mobile-app-crib-notes pull request #122
Opened 2021-04-06 08:55 UTC by tani-takanori

## ✅ What's done

- [ ] 配布ガイドのTopページ作成
- [ ] 配布パターン毎のページの作成
- [ ] ビルドパターンごとのビルドページの作成

## ⏸ What's not done

- 既存ページからの移植
- 全体の整合性の確認

---

## Other (messages to reviewers, concerns, etc.)

なし

2021-04-07 00:49 UTC, in-a-paddy requested changes

2021-04-07 00:49 UTC, in-a-paddy commented on docs/reference/index.md
>  ## 前提条件
この`index.md`って存在価値あるかな？

2021-04-07 00:49 UTC, in-a-paddy commented on src/pages/index.tsx
> +    summary: <>リファレンス</>,
こんな感じ？トップに配置するかどうか、少し悩ましい感じもあるけど、どうだろう。
```suggestion
    summary: <>アプリケーションの配布</>,
```

2021-04-07 00:49 UTC, in-a-paddy commented on src/pages/index.tsx
> +    title: 'Distribution Guide',
「Guide」は付けないイメージ
```suggestion
    title: 'Distribution',
```

2021-04-07 00:49 UTC, in-a-paddy commented on docs/distribution/index.md
> +本ガイドではモバイルアプリケーション開発時にアプリを確認するユースケース毎に開発者が実施する手順や利用するライセンスについてガイドします。
「本ガイド」「本ドキュメント」「本～」が統一感ない気がする。「このドキュメント」とかくらいにしたいかなぁ。

2021-04-07 00:49 UTC, in-a-paddy commented on docs/distribution/index.md
> +本ガイドではモバイルアプリケーション開発時にアプリを確認するユースケース毎に開発者が実施する手順や利用するライセンスについてガイドします。
少し柔らかくしてみたんだけど、どうだろう？
```suggestion
このドキュメントでは、デバイスにアプリをインストールするために開発者が実施する手順や利用するライセンスについて、アプリをインストールしたいシチュエーションごとに紹介します。
```

2021-04-07 00:49 UTC, in-a-paddy commented on docs/distribution/index.md
> +- iOSとAndroid向けのモバイルアプリの配布方法をガイドします
```suggestion
- iOSとAndroid向けの`配布方法を紹介します
```

2021-04-07 00:49 UTC, in-a-paddy commented on docs/distribution/index.md
> +- Continuous Deployment(CD)はガイドしていません
```suggestion
- このドキュメントで紹介しないもの
  - Google PlayやApp Storeでの公開手順
  - Continuous Delivery (CD)
  - ライセンスや、配布に必要なリソースの管理方法
```

2021-04-07 00:49 UTC, in-a-paddy commented on docs/reference/index.md
> +- モバイルアプリケーションの開発プロセス、Google Play・AppStoreへのアプリ配布方法などについては[こちら](../distribution/)を参照してください
```suggestion
- モバイルアプリケーションの開発プロセス、Google PlayやApp Storeへのアプリ配布方法などについては[こちら](../distribution/)を参照してください
```

2021-04-07 00:49 UTC, in-a-paddy commented on docs/reference/index.md
> +- モバイルアプリケーションの開発プロセス、Google Play・AppStoreへのアプリ配布方法などについては[こちら](../distribution/)を参照してください
「こちらを参照してください」 → 「モバイルアプリのリリース（Storeでの公開）は対象外です」
なかなかのコンボ

2021-04-07 02:05 UTC, tani-takanori commented on docs/reference/index.md
> +- モバイルアプリケーションの開発プロセス、Google Play・AppStoreへのアプリ配布方法などについては[こちら](../distribution/)を参照してください
referenceから飛ばすのは一旦やめた

2021-04-07 02:21 UTC, tani-takanori commented on docs/distribution/index.md
> +本ガイドではモバイルアプリケーション開発時にアプリを確認するユースケース毎に開発者が実施する手順や利用するライセンスについてガイドします。
とりこみー

2021-04-07 02:21 UTC, tani-takanori commented on docs/distribution/index.md
> +- Continuous Deployment(CD)はガイドしていません
とりこみー

2021-04-07 02:21 UTC, tani-takanori commented on src/pages/index.tsx
> +    title: 'Distribution Guide',
> 「Guide」は付けないイメージ

構成変えたのでそっちで間違えないようにする

2021-04-07 02:22 UTC, tani-takanori commented on src/pages/index.tsx
> +    summary: <>リファレンス</>,
トップへの配置はやめた

2021-04-09 05:50 UTC, tani-takanori commented on docs/distribution/index.md
> +- iOSとAndroid向けのモバイルアプリの配布方法をガイドします
該当行がなくなったのでresolveに

2021-04-09 08:11 UTC, OshitaTatsuya commented on docs/distribution/build/index.md
> +### iOS
本ページ配下の順序が、iOSアプリ→Androidアプリの順なので、
こちらの記載順序も合わせた方がよいかと思います。

2021-04-09 08:11 UTC, OshitaTatsuya commented on docs/distribution/build/ios/personal_team.md
> +- 最初Xcodeからビルドして実機でアプリを起動しようとすると以下エラーになります。
ここでの「以下エラーになります。」はどこを指しているのでしょうか？

2021-04-09 08:11 UTC, OshitaTatsuya commented on docs/distribution/build/ios/personal_team.md
> +- 以下のようになります。このあと、実機でアプリをタップすると起動できるようになっています
ここも同じく「以下～」とはどこを指していますか？

2021-04-09 08:11 UTC, OshitaTatsuya commented on docs/distribution/build/ios/adp_testflight.md
> +- 上記手順が正しく行われていれば、App Store Connectでアプリを表示して TestFlightのタブを選択すると、iOSのビルドにアプリが追加されていることが確認できる
「2. ビルドしたアプリをApp Store Connectにアップロード」章の説明と思うので、インデントが足りない気がします。

2021-04-09 08:11 UTC, OshitaTatsuya commented on docs/distribution/build/android/overview.md
> +title: Androidアプリのビルド
iOS側には本ページと同等のものがありませんでした。（必要？）

2021-04-09 08:29 UTC, tani-takanori commented on docs/distribution/build/ios/personal_team.md
> +- 最初Xcodeからビルドして実機でアプリを起動しようとすると以下エラーになります。
これまだSharePointから持ってきただけなんですが、そもそもSharePointが右に画像があるのに以下になっているので、（画像を貼り付けるかどうかの判断も劣後させた結果）そのまま持ってきてます。

2021-04-09 08:29 UTC, tani-takanori commented on docs/distribution/build/index.md
> +### iOS
すいません。ここまだページおいただけになってました。順番は変えます。

2021-04-12 01:32 UTC, tani-takanori commented on docs/distribution/index.md
> +title: アプリケーションの配布
Topページからリンクがほしい

2021-04-12 04:09 UTC, in-a-paddy requested changes
いったん

2021-04-12 04:09 UTC, in-a-paddy commented on docs/distribution/usecase/local.md
> +- [内部テスト版で配布](distribution/build/android/google_play_test)
```suggestion
- [内部テスト版で配布](../build/android/google_play_test.md)
```

2021-04-12 04:09 UTC, in-a-paddy commented on docs/distribution/usecase/local.md
> +- [APKファイルを配布](distribution/build/android/apk_dist)
```suggestion
- [APKファイルを配布](../build/android/apk_dist.md)
```

2021-04-12 04:09 UTC, in-a-paddy commented on docs/distribution/usecase/local.md
> +iOSでプッシュ通知などのAppの高度な機能を使用するアプリの場合は、ADP・ADEPライセンスの証明書、プロビジョニングプロファイル、デバイスが必要です。USB経由でデバイスにインストールするのが最も簡単ですが、デバイスをADPライセンスで登録する必要があります。ADPに登録できるiPhoneは契約毎に100台という厳しい制限があるのでできればUSB経由ではなくTestFlightまたはIn-
```suggestion
iOSでプッシュ通知などのAppの高度な機能を使用するアプリの場合は、ADP・ADEPライセンスの証明書、プロビジョニングプロファイル、デバイスが必要です。USB経由でデバイスにインストールするのが最も簡単ですが、デバイスをADP・ADEPライセンスに登録する必要があります。ADP・ADEPに登録できるiPhoneは契約毎に100台という厳しい制限があるので、できればUSB経由ではなくTestFlightまたはIn-Houseでの配布をおすすめします。
```

2021-04-12 04:09 UTC, in-a-paddy commented on docs/distribution/usecase/local.md
> +- ADP・ADEPの[AdHoc](/distribution/build/ios/adp_local)でインストールする
```suggestion
- ADPの[TestFlight](../build/ios/adp_testflight.md)の内部テスターを利用する
- ADEPの[In-House](../build/ios/adep_in_house.md)で配布
- [個人のApple ID](../build/ios/personal_team.md)を使用する
- ADP・ADEPの[AdHoc](../build/ios/adp_local.md)でインストールする
```

2021-04-12 04:09 UTC, in-a-paddy commented on docs/distribution/usecase/local.md
> +AndroidはiOSのようにAppの高度な機能を考慮する必要はありません。 USB経由でデバイスにインストールするのが最も簡単ですが、USB接続は禁止されている場合はAPKファイル配布か内部テスト版をご利用ください。APKファイルの配布は自前で配布が必要ですが、内部テストであればGoogle Play Console経由で配布できるので簡単です。
```suggestion
AndroidはiOSのようにAppの高度な機能を考慮する必要はありません。 USB経由でデバイスにインストールするのが最も簡単ですが、USB接続が禁止されている場合はAPKファイルでの配布か内部テスト版としての配布が利用できます。APKファイルでの配布は自分たちでサーバを立てるなどして配布する必要がありますが、内部テストであればGoogle Play Console経由で配布できるので簡単です。
```

2021-04-12 04:12 UTC, tani-takanori commented on docs/distribution/index.md
> +  - [配布に利用するリソース](resource)
間違えてるので修正しました

2021-04-12 04:13 UTC, tani-takanori commented on docs/distribution/index.md
> +    - [iOS](build/ios/overview)
間違えているので修正しました

2021-04-12 04:15 UTC, tani-takanori commented on docs/distribution/build/ios/personal_team.md
> +- 以下のようになります。このあと、実機でアプリをタップすると起動できるようになっています
こちらも今後修正予定

2021-04-12 04:15 UTC, tani-takanori commented on docs/distribution/build/ios/adp_testflight.md
> +- 上記手順が正しく行われていれば、App Store Connectでアプリを表示して TestFlightのタブを選択すると、iOSのビルドにアプリが追加されていることが確認できる
こちらも今後修正予定

2021-04-12 04:26 UTC, tani-takanori commented on docs/distribution/index.md
> +    - [Android](build/android/overview)
修正しました

2021-04-12 04:28 UTC, tani-takanori commented on docs/distribution/build/android/apk_dist.md
> +⚠️ ただしAPKファイルを作成するコマンドは `./gradlew bundleRelease` ではなく `.gradlew assembleRelease` を使ってください ⚠️
ブラウザのTabが3つ（このドキュメント、上から順に読むドキュメント、この補足からリンクされたドキュメント）になると読みやすいかな？？

2021-04-14 06:49 UTC, OshitaTatsuya commented on docs/distribution/build/android/apk_dist.md
> +⚠️ ただしAPKファイルを作成するコマンドは `./gradlew bundleRelease` ではなく `.gradlew assembleRelease` を使ってください ⚠️
ToDo事項をドラフト版以降で対応すること理解したので、一旦本指摘はcloseします

2021-04-14 07:25 UTC, OshitaTatsuya approved these changes

2021-04-15 02:05 UTC, in-a-paddy approved these changes

2021-04-15 02:05 UTC, merged