🐛: モックデータのイベント日付を未来日に設定
ws-4020/mobile-app-crib-notes pull request #1256
Opened 2023-10-12 08:13 UTC by sinho-lee

## ✅ What's done

- [ ] モックデータのイベント日付を固定値から動的に未来の日付に修正しました。

## Tests

- [ ] 実施した動作確認の内容をチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

以下のコマンドをこのプルリクエストのコメントとして投稿すると、
Azure Pipeline上でSantokuAppをビルドしてDeployGateへアップロードできます。

- /azp run deploy-stg
- /azp run deploy-dev
- /azp run deploy-all
  - `stg`, `dev` の両方

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

何かあれば記載してください。
なければ「なし」と記載してください。

2023-10-13 01:45 UTC, tksugimoto commented on example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
> +                                                                      "endDate": "2023-10-14",
> `"endDate": "2023-10-14",`

これ、明日の日付固定なので、明日以降にtestしたらfailしてしまうと思われます。

```ts
  const date = new Date();
  date.setDate(date.getDate() + 1);
  const formatDate = date.toISOString().split('T')[0];
```

毎回snapshotを更新するのは手間がかかるので、以下のいずれかが良いと思います。

- 月と日は固定で年だけ動的に変更する
  - 年に数回snapshotの更新が必要（6/1, 6/3, 6/10, 1/18, 2/1, 6/7, 7/17 を過ぎたらHomePageのイベント表示が変わる）
- 3個だけ、年を数年先の未来に固定する
  - 数年先に3回snapshotの更新が必要
    - 数年先の1回目にまとめて変更するようにコメントを残しておくのが良いと思います

最初は前者で考えてましたが、毎年の手間が大きいので、後者が良いと思います。

他の方法としては、
[Q&Aアプリプロジェクトの説明 | Fintan » Mobile App Development](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/qa-app/app-project-desc#msw%E3%81%AE%E8%A8%AD%E5%AE%9A)
のMSW設定部分で学習コンテンツの実施者に書き換えてもらう案もありますが、少し手間が起きいので、`example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts` だけ更新が楽だと思います。

2023-10-13 01:53 UTC, tksugimoto commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +    endDate: formatDate,
`content` 部分に日本語で `日時：2023年7月14日（金） 17:00〜19:00` が書かれておりズレが発生しています。

月と日はそのままで年だけ変更ならば、`content`から年と曜日の情報を消しておくのが良さそうです。

※ 年によって、土日祝日になるかもしれませんが、妥協します。

2023-10-13 01:57 UTC, tksugimoto requested changes

2023-10-13 01:57 UTC, tksugimoto commented on example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
> +                                                                      "endDate": "2023-10-14",
> 毎回snapshotを更新するのは手間がかかるので、対策として以下を考えました。

いつ見ても以下を満たすようにできると嬉しいです。

- 少なくとも3件は表示されるイベントがある
  - イベントリストは3パターンの表示があるため
    1. 右端だけに次カードが見えている（最初）
    2. 両端に前後のカードが見えている（↑と↓以外）
    3. 左端だけに前のカードが見えている（最後）
- 少なくとも1件は表示されないイベントがある
  - 過ぎたイベントは非表示にされることを確認できる

2023-10-13 02:52 UTC, creature-water-valley commented on example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
> +                                                                      "endDate": "2023-10-14",
これって、自動テスト時は日付を固定すればSnapshotのdiffは特に問題なさそうに思いました。

現状は、`beforeEach`で日付を固定してますが、`beforeAll`の方が先に動いてしまい、その中で実施しているMSWのデータ作成じは日付が固定されないまま実施されちゃってるとかだと思います。

- https://github.com/ws-4020/mobile-app-crib-notes/blob/master/example-app/SantokuApp/src/apps/app/App.test.tsx#L34

2023-10-13 02:55 UTC, creature-water-valley commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +  const formatDate = date.toISOString().split('T')[0];
`formatDate`だと関数に見えそうなので、`formattedDate`とかの方が良さそうに思いました。

2023-10-13 04:45 UTC, tksugimoto commented on example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
> +                                                                      "endDate": "2023-10-14",
`jest.setSystemTime(new Date(2023, 5, 1, 0, 0, 0, 0));` を `beforeEach` から `beforeAll` に移動すれば良さそうですね（別PRが理想）

2023-10-13 04:45 UTC, sinho-lee commented on example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
> +                                                                      "endDate": "2023-10-14",
4件は日付を1年後に動的に設定しました。
他は過去日を固定で設定しました。
これによって表示/非表示イベントに変化が無いようにできると思います。
年が変わったらスナップショットを更新するようにコメントを記載しました。

2023-10-13 04:46 UTC, sinho-lee commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +    endDate: formatDate,
年のみ動的に設定することで解消できました。

2023-10-13 04:47 UTC, sinho-lee commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +  const formatDate = date.toISOString().split('T')[0];
ソースコードを修正することで`formatDate`を使用しなくなりました。

2023-10-13 07:00 UTC, tksugimoto commented on example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
> +                                                                      "endDate": "2023-10-14",
https://github.com/ws-4020/mobile-app-crib-notes/pull/1256#discussion_r1357696851 のコメントを参考に、時間経過でテスト修正しなくて良いように対応お願いします。

（「対応した」コメントには commit hash も張ってもらえると見やすいです）

2023-10-13 07:16 UTC, creature-water-valley approved these changes
Discussionされている内容が完了すれば問題ないのでApproveしておきます。

2023-10-13 08:42 UTC, sinho-lee commented on example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
> +                                                                      "endDate": "2023-10-14",
https://github.com/ws-4020/mobile-app-crib-notes/pull/1256#discussion_r1357751793
今のPRがマージできてないので、コンフリクトを起こさないようにするため、別PRではなくこのPRで対応しました。

2023-10-13 08:54 UTC, tksugimoto commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +    endDate: '2023-01-01T10:00:00Z',
固定値のうち、このイベントだけ1/1にしている理由はなんですか？
元の6/7で良さそうです。

```suggestion
    endDate: '2023-06-07T10:00:00Z',
```

2023-10-13 09:30 UTC, sinho-lee commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +    endDate: '2023-01-01T10:00:00Z',
すみまさん。間違えました。
元に戻しました。

2023-10-16 06:24 UTC, tksugimoto commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +    endDate: '2023-01-01T10:00:00Z',
修正commit: 873c39dca7fa91231eabc305f7f0f8e74f767d3f

2023-10-16 07:44 UTC, tksugimoto commented on example-app/SantokuApp/src/apps/app/App.test.tsx
> +  jest.setSystemTime(new Date(2023, 5, 1, 0, 0, 0, 0));
ローカルとサーバーでtimezoneがズレてしまう問題の対策として `new Date` の方法を変更すると良いと思います。

```suggestion
  // テスト時は2023/6/1(UTC)で日付を固定する。CIとlocalで差が出ないようにISO書式で指定する
  jest.setSystemTime(new Date('2023-06-01T00:00:00+00:00'));
```

```
TZ=UTC npm test -- src/apps/app/App.test.tsx
```
で動作確認

2023-10-16 07:47 UTC, tksugimoto commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +  const formattedDate = new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString();
> `date.getTime() - date.getTimezoneOffset() * 60000`

873c39dca7fa91231eabc305f7f0f8e74f767d3f `toISOStringで日付がずれてしまう現象を解消し、不要に修正した日付を元に戻す`

CI(GitHub Actions)とlocalで差が出てしまう対策ならば、 日時固定側でやると良さそうです

- https://github.com/ws-4020/mobile-app-crib-notes/pull/1256#discussion_r1360246452

```
  // テスト時は2023/6/1(UTC)で日付を固定する。CIとlocalで差が出ないようにISO書式で指定する
  jest.setSystemTime(new Date('2023-06-01T00:00:00+00:00'));
```

上記対応だけだとローカルのテストが落ちるので、↓を入れます

```suggestion
  const formattedDate = date.toISOString();
```

2023-10-16 07:53 UTC, tksugimoto commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +  date.setFullYear(date.getFullYear() + 1);
このファイルを見た人が混乱しないように、1年後を指定する理由をコメントに残しておきましょう。

```suggestion
  // 常に募集中のイベントが用意するため、日付を1年後に設定する
  date.setFullYear(date.getFullYear() + 1);
```

2023-10-16 08:03 UTC, sinho-lee commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +  const formattedDate = new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString();
対応commit: https://github.com/ws-4020/mobile-app-crib-notes/pull/1256/commits/bfd4f97afc0164631709a424eb053ab9a9429971

2023-10-16 08:04 UTC, sinho-lee commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +  date.setFullYear(date.getFullYear() + 1);
対応commit: https://github.com/ws-4020/mobile-app-crib-notes/pull/1256/commits/8b89252303ab1d0c66ef3b78fed030e16763c2db

2023-10-16 08:07 UTC, tksugimoto commented on example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts
> +    endDate: formatDate,
ズレは残っていますが、現状、endDateが表示に使われていない＆コメントを残したのでこのディスカッションは解決とします。

8b89252303ab1d0c66ef3b78fed030e16763c2db `コメントの修正`

- https://github.com/ws-4020/mobile-app-crib-notes/pull/1256#discussion_r1360264635

2023-10-16 08:24 UTC, tksugimoto approved these changes

2023-10-16 08:24 UTC, merged