📝: サードパーティライブラリの導入に関する方式設計を追加
ws-4020/mobile-app-crib-notes pull request #1278
Opened 2023-10-27 07:08 UTC by creature-water-valley

## ✅ What's done

- [x] サードパーティライブラリの導入ページを追加
  - ライブラリの選定方針
  - ライブラリの利用を検討することが多い機能
  - このアプリで使用しているライブラリ
- [x] QAアプリのプロジェクトの説明ページに、ライブラリの選定に困ったサイトの参考として、追加したページを紹介

## Other (messages to reviewers, concerns, etc.)

「ライブラリの利用を検討することが多い機能」のアウトライン共有時に、「UIコンポーネントは別の表に記載する」方針になりましたが、UIコンポーネント名を文字で並べた一覧を作成しても、直感的にそのコンポーネントを想像しづらいと感じました。

そのため、Appleの[Human Interface Guidelines](https://developers.apple.com/design/human-interface-guidelines/components/all-components)やGoogleが提供する[Material Design](https://m3.material.io/components)のコンポーネント一覧を参照する形に変更しました。

2023-10-31 08:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +React NativeのGithubで公開されている[The React Native Ecosystem](https://github.com/facebook/react-native/blob/main/ECOSYSTEM.md)では、**Partners**として定義されており信頼性もあります。
```suggestion
React NativeのGitHubで公開されている[The React Native Ecosystem](https://github.com/facebook/react-native/blob/main/ECOSYSTEM.md)では、**Partners**として定義されており信頼性もあると考えています。
```

2023-10-31 08:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +このアプリでは、[Expo](https://docs.expo.dev/)の提供する機能を優先的に利用します。
💭 [Expo SDK](https://docs.expo.dev/versions/latest/)の方が良かったりしないかな？

```suggestion
このアプリでは、[Expo SDK](https://docs.expo.dev/versions/latest/)に含まれる機能を優先的に利用します。
```

2023-10-31 08:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| 開発母体の信頼性       | 個人による開発か組織による開発かを確認します。組織による開発の場合は、組織の規模や実績（他にリリースしているアプリやライブラリはあるか）などを確認します。<br/><br/>また、React NativeのGithubで公開されている[The React Native Ecosystem](https://github.com/facebook/react-
```suggestion
| 開発母体の信頼性       | 個人による開発か組織による開発かを確認します。組織による開発の場合は、組織の規模や実績（他にリリースしているアプリやライブラリはあるか）などを確認します。<br/><br/>また、React NativeのGitHubで公開されている[The React Native Ecosystem](https://github.com/facebook/react-native/blob/main/ECOSYSTEM.md)に紹介されているかも信頼性を判断する上で大きな要素になります。 |
```

2023-10-31 08:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| 学習コスト          | ライブラリ導入時の学習コストの高さを確認します。学習コストが高いと、ライブラリを導入しても開発工数があまり削減されない場合もあります。<br/>また、誤った利用方法によりアプリが予期せぬ動作を引き起こす場合もあります。
💭 予期せぬ動作ってより、不具合入れちゃうとかでどう？

2023-10-31 08:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +ここに記載した機能が、ライブラリの検討に必要なすべての機能ではないことにご留意ください。
```suggestion
ここに記載した機能が、ライブラリを検討する必要があるすべての機能ではないことにご留意ください。
```

タイポと思われる箇所直してみたけど、この注意書きなくてもいいと思うな。そりゃ、ここにないやつもあって当然でしょ、と思う。

2023-10-31 08:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| ネットワークアクセス   | axios
🥜 ライブラリはリンクしてあげてほしいかなぁ

2023-10-31 08:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| ロギング         | @react-native-firebase/app<br/>@react-native-firebase/crashlytics
💭 `@react-native-firebase/app`は書かなくてもいいんじゃないかな。

2023-10-31 08:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| ナビゲーション      | @react-navigation/bottom-tabs<br/>@react-navigation/core<br/>@react-navigation/drawer<br/>@react-navigation/elements<br/>@react-navigation/native<br/>@react-navigation/native-stack<b
💭 React Navigationにまとめちゃっていいんじゃないかと。

2023-11-01 01:46 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +このアプリでは、[Expo](https://docs.expo.dev/)の提供する機能を優先的に利用します。
そうだね、ここの文脈だとExpo SDKの方が良さそう。
↓で修正しましたー
f9c0d3ce281c0d154b13a42cca6b7b9f71c6ac0f

2023-11-01 01:49 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| 学習コスト          | ライブラリ導入時の学習コストの高さを確認します。学習コストが高いと、ライブラリを導入しても開発工数があまり削減されない場合もあります。<br/>また、誤った利用方法によりアプリが予期せぬ動作を引き起こす場合もあります。
不具合混入で良さそう。
↓の文章に修正しましたー
>誤った利用方法により不具合を混入してしまう場合もあります。
bf863394a455034313cfe4f5659c02d9556216c8

2023-11-01 01:49 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +ここに記載した機能が、ライブラリの検討に必要なすべての機能ではないことにご留意ください。
確かに、当然かw
削除しちゃいましたー
1b3cfe2f483a2d3a784548c6ee9dc9612fd5bfde

2023-11-01 01:52 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| ネットワークアクセス   | axios
リンク追加しましたー
- ドキュメントページがあるやつはそれをリンク先に追加
  - ただし、Async Storageみたいに、ライブラリ側とExpo SDKのドキュメント両方があるやつは、Expo SDKのドキュメントをリンク先に追加
- ドキュメントページがないやつはGItHubのリポジトリをリンク先に追加
b9f7a4bfda3ca0b6610ec3f1778633e9ac3d8421

2023-11-01 01:53 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| ロギング         | @react-native-firebase/app<br/>@react-native-firebase/crashlytics
削除しましたー
b9f7a4bfda3ca0b6610ec3f1778633e9ac3d8421

2023-11-01 01:54 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| ナビゲーション      | @react-navigation/bottom-tabs<br/>@react-navigation/core<br/>@react-navigation/drawer<br/>@react-navigation/elements<br/>@react-navigation/native<br/>@react-navigation/native-stack<b
全体的に、パッケージ名を羅列していたけど、ライブラリ名を記載するように修正しましたー
b9f7a4bfda3ca0b6610ec3f1778633e9ac3d8421

2023-11-01 09:26 UTC, tisurgm requested changes

2023-11-01 09:26 UTC, tisurgm commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +React Nativeには、[Core Components and APIs](https://reactnative.dev/docs/components-and-apis)に記載されている通り、多くのUIコンポーネントやAPIが提供されています。
めっちゃ細かいんですが「React Nativeには」から始まって「提供されています。」と繋がるのは違和感ありました。

以下のいずれかなら違和感がなさそうです。

- A)「提供されています。」ではなく「あります。」
- B)「React Nativeには」ではなく「React Nativeでは」

2023-11-01 09:26 UTC, tisurgm commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +React NativeのGitHubで公開されている[The React Native Ecosystem](https://github.com/facebook/react-native/blob/main/ECOSYSTEM.md)では、**Partners**として定義されており信頼性もあると考えています。
> 頼性もあると考えています。

「考えられています。」の方が自然だと思いました。

2023-11-01 10:03 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| 学習コスト          | ライブラリ導入時の学習コストの高さを確認します。学習コストが高いと、ライブラリを導入しても開発工数があまり削減されない場合もあります。<br/>また、誤った利用方法によりアプリが予期せぬ動作を引き起こす場合もあります。
「不具合が混入」じゃない？

2023-11-02 00:06 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +| 学習コスト          | ライブラリ導入時の学習コストの高さを確認します。学習コストが高いと、ライブラリを導入しても開発工数があまり削減されない場合もあります。<br/>また、誤った利用方法によりアプリが予期せぬ動作を引き起こす場合もあります。
そうですな。修正しましたー
137ecfbf26d6c9366f9477745dc001955f859736

2023-11-02 00:06 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/app-project-desc.md
> +サンプルアプリ（SantokuApp）では、ライブラリの選定方針を定めています。また、ライブラリの検討を利用することが多い機能や、それらの機能を実現するために採用したライブラリも公開しています。
↓の文章に修正しましたー
>ライブラリの利用を検討
3f2584cd4a2cdcc6d7ef1fc47cc3b8a3f1d0d9e1

2023-11-02 00:07 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +React Nativeには、[Core Components and APIs](https://reactnative.dev/docs/components-and-apis)に記載されている通り、多くのUIコンポーネントやAPIが提供されています。
↓のように修正しましたー
>React Nativeでは

080e5154c72c09866ceeadeb446b8e4a0fe98366

2023-11-02 00:14 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +React NativeのGitHubで公開されている[The React Native Ecosystem](https://github.com/facebook/react-native/blob/main/ECOSYSTEM.md)では、**Partners**として定義されており信頼性もあると考えています。
「考えられています。」だと、恐らく「React Native開発チームなどがExpoは信頼性があると考えていそう」っていう意味合いになるかと思うのですが、ここは、それを踏まえて「SantokuAppとしては、信頼性があると考えている」という意味で使っていました。

ここでは「SantokuAppとして信頼性があると考えている」、そのため「Expoを使っています」とした方が良さそうには思いましたがどうでしょうか？（ただ、大きなこだわりがあるわけではないので、違和感あれば修正しちゃいます！）

2023-11-02 01:07 UTC, tisurgm commented on website/docs/react-native/santoku/application-architecture/third-party-libraries/overview.mdx
> +React NativeのGitHubで公開されている[The React Native Ecosystem](https://github.com/facebook/react-native/blob/main/ECOSYSTEM.md)では、**Partners**として定義されており信頼性もあると考えています。
なるほど、私の理解誤りでした。コメント取り下げますー。

2023-11-02 01:07 UTC, tisurgm approved these changes

2023-11-06 04:47 UTC, in-a-paddy approved these changes

2023-11-06 04:47 UTC, merged