📝: Q&Aアプリの実装前に読んでもらいたいページとコンポーネント作成時の注意点を追加
ws-4020/mobile-app-crib-notes pull request #1299
Opened 2023-11-27 08:25 UTC by creature-water-valley

## ✅ What's done

- [x] 学習コンテンツ受講者から、「実装方法の選択肢が複数ある場合はどのように考えて決めていけば良いのか」という質問が来ていたので、それのサポートをできるようなページを追加
  - 「Q&Aアプリの実装前に」
    - 「概要」ページ
    - 「実装方法の検討について」ページ
- [x] 学習コンテンツ受講者から、「コンポーネントの粒度はどうしたら良いか」という質問が来ていたので、それに関するガイドを追加
  - 「Q&Aアプリの実装前に」
    - 「デザインシステムについて」ページ
      - 基本的にはデザインシステムに従うということを説明しながら、デザインシステムがない場合の部品切り出し方法についても説明
- [x] 学習コンテンツ受講者から、「コンポーネントの余白や、サイズ指定はどうするのが良いか」という質問が来ていたので、それに対するヒントを最初に実装する画面の説明ページに追加
    - コンポーネント間の余白について
    - コンポーネントのサイズについて
    - 異なる画面サイズの端末について

---

## Other (messages to reviewers, concerns, etc.)

2023-11-29 06:49 UTC, in-a-paddy commented on website/docs/react-native/learn/qa-app/about-design-system.mdx
> +title: デザインシステムについて
⚠ ここで説明したいのは、コンポーネントの粒度をどのように考えるかだと思うので、タイトルは変えたほうが良さそう。既に書いてあるようなデザインシステムについての説明も残した方がいいけど。

コンポーネントの粒度は、UIの設計プロセス？設計方法？と関係があるよ。例えば、デザインシステムってのがあってね、みたいな感じの導入にしたら何とかなりそうな気はする。

2023-11-29 06:49 UTC, in-a-paddy commented on website/docs/react-native/learn/qa-app/about-implementation-selection.mdx
> +各実装方法のメリット・デメリットを把握した後は、この中で何を優先するかを決めて、それに従って実装方法を選択します。
💭 じゃあ、今回の場合はどう判断するの？ってフィードバックが絶対くるよ～（笑

2023-11-29 06:49 UTC, in-a-paddy commented on website/docs/react-native/learn/qa-app/exercise-basic-home-components.md
> +どちらかのコンポーネントへ含めてしまうと、余白が不要な画面ではそのコンポーネントを利用できません。
❓ どちらかってのはどっちとどっちなんだ？ってなった。NG例とOK例を絵で描いてあげた方が理解しやすそうかなぁ。

2023-11-29 06:49 UTC, in-a-paddy commented on website/docs/react-native/learn/qa-app/exercise-basic-home-components.md
> +基本的には、コンポーネントを利用する側が決めた領域全体に広がるように作成することが重要です。
💭 「重要です」は強い気がするので、「扱いやすいコンポーネントになると思います」くらいかなぁ、と。どうだろうか？

2023-11-29 06:49 UTC, in-a-paddy commented on website/docs/react-native/learn/qa-app/screen-home-header.png
💭 オレンジ背景に赤枠は視認性が悪すぎてきついかなぁ。

2023-11-29 06:49 UTC, in-a-paddy commented on website/docs/react-native/learn/qa-app/app-basic-concepts.mdx
❓ ファイル名ってこれで良いのかな？

2023-11-29 09:55 UTC, tisurgm requested changes

2023-11-29 09:55 UTC, tisurgm commented on website/docs/react-native/learn/qa-app/about-design-system.mdx
> +
デザインシステムを推奨するような一文があると良いと思いました。
デザインシステムを定義する場合は初期コストはかかるけれどデザインの一貫性と開発効率の向上のためにも定義した方が良い、みたいな感じです。

2023-11-29 09:55 UTC, tisurgm commented on website/docs/react-native/learn/qa-app/about-design-system.mdx
> +- [デザインシステム](https://github.com/{@inject:organization}/mobile-app-crib-notes/blob/master/website/docs/react-native/learn/qa-app/qa-app.fig)
文脈から理解はできますが、リンクテキストを「Q&Aアプリのデザインシステム」とした方がより親切だと思いました。

2023-11-29 09:55 UTC, tisurgm commented on website/docs/react-native/learn/qa-app/about-design-system.mdx
> +この場合、以下のような手順で実施すると良いでしょう。
実装するタイミングがわからないと思ったのですが「一覧化」という言葉に実装することも含まれていますか？

私のイメージだとNo.1, 2, 3の工程を経て全体的に整理がついたあとに基本部品から順に実装するのだと思うのですが、認識ズレていますかね？

2023-11-29 09:55 UTC, tisurgm commented on website/docs/react-native/learn/qa-app/exercise-basic-home-components.md
> +コンポーネントには基本的にサイズを指定しないようにしましょう。
細かいかもしれませんが「〜基本的に自身のサイズを〜」とした方が良いと思いました。
コンポーネントの中で利用するコンポーネントのサイズは指定するので、利用する側・される側がわかりやすく表現されている方が理解しやすい気がします。

2023-11-30 08:05 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/about-design-system.mdx
> +画面の実装を1つのコンポーネント内に実装をすると、コードが肥大化してしまいます。また、他の画面で同じような表示をする場合に再利用できません。
修正しましたー
299cce407cd2f1206eaab4974ccf2fc614129c6a

2023-11-30 08:06 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/about-design-system.mdx
> +title: デザインシステムについて
タイトルを「コンポーネントの分割について」に変更して、デザインシステムの説明につながるように修正してみましたー
775a9808783d9a34ac06a15285f7965d614bc30b

2023-11-30 08:08 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/about-implementation-selection.mdx
> +各実装方法のメリット・デメリットを把握した後は、この中で何を優先するかを決めて、それに従って実装方法を選択します。
実装する人によって優先事項は変わると思ったので、ここでは記載しなかったんだよねー。
ただ、フィードバックが来るのは確かにそうだと思うので、SantokuAppではこうしているよっていうのをnoteで追記しましたー
afa10d107bca4901b004443f3bba9cf2afa94397

2023-11-30 08:08 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/exercise-basic-home-components.md
> +どちらかのコンポーネントへ含めてしまうと、余白が不要な画面ではそのコンポーネントを利用できません。
例を追加してみましたー
b8a8adca69accb5e047da8cd6548831161425af3

2023-11-30 08:09 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/exercise-basic-home-components.md
> +基本的には、コンポーネントを利用する側が決めた領域全体に広がるように作成することが重要です。
少し控えめな表現に変更してみましたー
4875b82be52fcd6dbaa9566489f3ca2c0ecdbb25

2023-11-30 08:09 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/screen-home-header.png
青枠にしてみました
2284764dedd0bb5f011e05a0db3ace2cdb748c35

2023-11-30 08:11 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/app-basic-concepts.mdx
学習コンテンツの最初の「アプリの実装前に」がこのファイル名だったので、それに合わせた方が良いかも？と思い、こうしたんだけど、やはり無理があるかね（自身でもそうは感じていた）
ので、ファイル名を修正しましたー
de523e61b0f4357e01af017a979abbe07701a484

2023-11-30 08:12 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/about-design-system.mdx
> +
推奨するような文章を最後に追加してみましたー
db2673b9359be614b802e41d315e06187a39eab5

2023-11-30 08:21 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/about-design-system.mdx
> +この場合、以下のような手順で実施すると良いでしょう。
いえ、実装のタイミングについてはあまり意識していなかったですね。

>私のイメージだとNo.1, 2, 3の工程を経て全体的に整理がついたあとに基本部品から順に実装するのだと思うのですが、認識ズレていますかね？

はい、基本的にも僕もそのイメージです。
が、No.1（基本部品の一覧化）が完了したタイミングで、それらの実装を始めても、特に問題はなさそうな気もしています。
（特に、共通系の部品を作るチームとかで分かれているプロジェクトだと、基本部品を先に作ってしまうみたいなこともある気がしています。）

ただ、Q&Aアプリでは、まず一覧を整理してその後に実装するっていう手順の方がわかりやすい気がするので、No.4に「部品の実装」を追加しましたー

d2e22984a6eb98e5362e19a8e62ed670a0778a10

2023-11-30 08:21 UTC, creature-water-valley commented on website/docs/react-native/learn/qa-app/exercise-basic-home-components.md
> +コンポーネントには基本的にサイズを指定しないようにしましょう。
そうですね、その方がわかりやすいと思うので修正しましたー
f04d0df128dbb748a8daef08531075490d8abe5f

2023-12-01 07:14 UTC, tisurgm approved these changes

2023-12-05 05:20 UTC, in-a-paddy approved these changes

2023-12-05 05:21 UTC, merged