Feature/ios lisence resource
ws-4020/mobile-app-crib-notes pull request #169
Opened 2021-04-15 02:33 UTC by tani-takanori

## ✅ What's done

- [ ] iOSアプリの配布、インストール時に必要なリソースの説明を追記

---

## Other (messages to reviewers, concerns, etc.)

なし

2021-04-15 06:31 UTC, takei0w0 requested changes

2021-04-15 06:31 UTC, takei0w0 commented on docs/distribution/build/ios/overview.md
> +リソースの作成方法は[iOSのライセンス](../../ios_lisence.md)によって違うため、確認していなければライセンスのページを確認してください。
「確認していなければライセンスのページを確認してください」は何を確認すればいいのかわかりにくいです。。

2021-04-15 06:31 UTC, takei0w0 commented on docs/distribution/build/ios/overview.md
> +※配布用証明書はライセンス毎、開発用証明書は開発者アカウント毎です。（[Appleのヘルプ > 証明書の概要](https://help.apple.com/developer-account/#/deveedc0daa0)）を参照してください。
```suggestion
利用できる証明書には[上限](https://help.apple.com/xcode/mac/current/#/dev3a05256b8)があります。配布用証明書はライセンス毎、開発用証明書は開発者アカウント毎に上限数が決まっています。詳細は（[Appleのヘルプ > 証明書の概要](https://help.apple.com/developer-account/#/deveedc0daa0)）を参照してください。
```

2021-04-15 06:31 UTC, takei0w0 commented on docs/distribution/build/ios/overview.md
> +WebApplicationのURLドメインのように一意になるIDを指定してください。
誰がいつ取得するものなのかわからないです。

2021-04-15 07:47 UTC, tani-takanori commented on docs/distribution/build/ios/overview.md
> +※配布用証明書はライセンス毎、開発用証明書は開発者アカウント毎です。（[Appleのヘルプ > 証明書の概要](https://help.apple.com/developer-account/#/deveedc0daa0)）を参照してください。
詳細は...概要を参照っていうのがちょっと引っかかったので別の修正にしました。

2021-04-15 08:31 UTC, takei0w0 requested changes

2021-04-15 08:31 UTC, takei0w0 commented on docs/distribution/build/ios/overview.md
> +プロビジョニングプロファイルは[登録ページ](https://developer.apple.com/account/resources/profiles/add)で証明書とApp IDを組み合わせて作成します。
登録端末の情報も関係してることは書かないと、この後の「AdHoc Distributionを利用する場合の考慮」に繋がらないと思います。

また、登録端末が増えたときは新しく作成する必要があることは記載した方がいいかなあと思いました。（証明書更新時は忘れないと思いますが端末追加時は忘れられそうなので）

2021-04-15 08:31 UTC, takei0w0 commented on docs/distribution/build/ios/overview.md
> +### AdHoc Distributionを利用する場合の考慮
リソースと並列に書くと、リソースの一部にみえてしまうので ## か ####のどちらかがいいのではないかと

2021-04-15 08:42 UTC, in-a-paddy requested changes

2021-04-16 00:37 UTC, takei0w0 approved these changes

2021-04-16 01:51 UTC, in-a-paddy approved these changes

2021-04-16 01:51 UTC, merged