🖋: 学習コンテンツにビルドの仕組み説明を追加
ws-4020/mobile-app-crib-notes pull request #178
Opened 2021-04-16 07:50 UTC by takei0w0

## ✅ What's done

- [x] RN学習のGettingStartedにビルドの仕組みについてかんたんに説明を記載
- [ ] 説明用の図を追加する

---

## Other (messages to reviewers, concerns, etc.)

図の作成に時間がかかりそうなのでいったん文章だけプッシュしました

2021-04-16 11:31 UTC, OshitaTatsuya approved these changes

2021-04-16 14:38 UTC, in-a-paddy requested changes
Android/iOSのロゴがちょっと気になっちゃったのと、build&install, loadのあたりが少し読み取りづらいかな、と。
あと、ロード元がブラウザっぽいアイコンになってるから、アプリっぽいのにしたいなぁ、と。

buildは端末内に、installの矢印とloadの矢印は上下を逆にしたほうがいいかな、と思った。あと、loadは Load JSとかにしたほうがいいかも
Build App → Install App → Load JS in App の順番が自然にわかるような図になっていると良いなぁ、と。

2021-04-16 14:38 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +Expo Goを使用する場合は、React Nativeのみの場合と異なりアプリのビルドが不要です。
なぜアプリのビルドが不要なのか、を少し説明してあげたほうがいい気がする

2021-04-16 14:40 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +その後、インストールされたアプリがMetro Bundlerを通してJava Scriptのソースを読み込み、実行します。
Expo Goの方では「同じネットワーク内の」と明記しているので、こっちもそう書いてあげたほうが良さそう

2021-04-20 02:31 UTC, takei0w0 commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +Expo Goを使用する場合は、React Nativeのみの場合と異なりアプリのビルドが不要です。
追記しました

2021-04-20 02:56 UTC, takei0w0 commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +その後、インストールされたアプリがMetro Bundlerを通してJava Scriptのソースを読み込み、実行します。
ここ書き方が微妙だったので直しました。QRコードを読み取ることで同一無線ネットワーク内のBundlerに簡単に接続できる点について説明したかったものでした。

接続先を変えてしまえば同じネットワークでなくてもBundlerには接続できるはずなので（やったことはないですが）同じネットワーク内のという説明は不要と考えています。

2021-04-20 03:01 UTC, in-a-paddy approved these changes

2021-04-20 03:01 UTC, merged