✨landing page を追加
ws-4020/mobile-app-crib-notes pull request #179
Opened 2021-04-16 09:18 UTC by asahi99

## ✅ What's done

- [x] LPを追加

## Other (messages to reviewers, concerns, etc.)

なし

2021-04-19 03:30 UTC, OshitaTatsuya commented on landing-page/landing-page.md
> +本ガイドでは以上のようなOSや開発のステージのユースケースに応じたアプリケーションの配布方法を解説します。
紹介する内容の概要を説明できればと思いました。
詳細な配布時の状況等については割愛してよいかと思います。
イメージは以下のような感じです。

```suggestion
モバイルアプリケーションは実機にアプリケーションをインストールして動作するものになります。
ガイドではよくあるユースケースを紹介しながらiOSとAndroidそれぞれのアプリケーション配布を解説しています。
また、それぞれのOS毎にビルド方法とテスト時の配布方法についても解説しています。
```

2021-04-20 05:00 UTC, tani-takanori commented on landing-page/landing-page.md
> +本ガイドでは以上のようなOSや開発のステージのユースケースに応じたアプリケーションの配布方法を解説します。
いまは[ws-4020](https://ws-4020.github.io/mobile-app-crib-notes/distribution/)しかないけど[Fintan-contents](https://fintan-contents.github.io/mobile-app-crib-notes/distribution/)ができるので、Fintan-contentsにリンクがほしい

2021-04-20 07:31 UTC, in-a-paddy requested changes

2021-04-20 07:31 UTC, in-a-paddy commented on landing-page/landing-page.md
> +本ガイドでは以上のようなOSや開発のステージのユースケースに応じたアプリケーションの配布方法を解説します。
ファイル名が `landing-page.md` になってるけど、他のランディングページも入れたいから名前変えてほしいな。

2021-04-20 08:41 UTC, tani-takanori commented on landing-page/landing-page.md
> +また、開発したアプリケーションをApp Store、Google Playで一般公開する場合。
```suggestion
モバイルアプリケーション開発では開発中の実際のデバイスにアプリケーションをインストールして確認します。
開発の状況により公開したい範囲が変わるため、インストールできる対象を制限したり、一般公開とは別の方法でテスターを募り、インストールしてもらうこともあります。

iOSとAndroidの配布方法のパターンではなく、ビルドしたアプリを誰にインストールして確認してもらうかという観点でシチュエーション（ユースケース）を整理したものを[こちら](https://ws-4020.github.io/mobile-app-crib-notes/distribution/)で公開しています。
```

2021-04-20 09:38 UTC, tani-takanori commented
代表的なユースケースをあげてしまってもいいかも

2021-04-21 05:32 UTC, tani-takanori commented on landing-page/app-distribution-lp.md
> +モバイルアプリケーション開発では開発中の実際のデバイスにアプリケーションをインストールして確認します。
```suggestion
モバイルアプリケーション開発では実際のデバイスに開発中のアプリケーションをインストールして確認します。
```

2021-04-21 05:42 UTC, tani-takanori commented on landing-page/app-distribution-lp.md
> +上記リンクではユースケースとして以下のシチュエーションを掲載しています。
```suggestion
[ユースケース](https://fintan-contents.github.io/mobile-app-crib-notes/distribution/usecase)としてつぎのようなシチュエーションの配布方法を公開しています。
```

2021-04-21 05:43 UTC, tani-takanori commented on landing-page/app-distribution-lp.md
> +iOSとAndroidを対象に開発してきた経験をもとに、配布方法のパターンではなく、ビルドしたアプリを誰にインストールして確認してもらうかという観点でシチュエーション（ユースケース）を整理したものを[こちら](https://fintan.github.io/mobile-app-crib-notes/distribution/)で公開しています。
```suggestion
iOSとAndroidを対象に開発してきた経験をもとに、配布方法のパターンではなく、ビルドしたアプリを誰にインストールして確認してもらうかという観点でシチュエーション（ユースケース）を整理したものを[こちら](https://fintan-contents.github.io/mobile-app-crib-notes/distribution/)で公開しています。
```

2021-04-21 06:36 UTC, OshitaTatsuya approved these changes

2021-04-21 06:48 UTC, tani-takanori commented on landing-page/app-distribution-lp.md
> +[ユースケース](https://fintan-contents.github.io/mobile-app-crib-notes/distribution/usecase)としてつぎのようなシチュエーションの配布方法を公開しています。
```suggestion
[ユースケース](https://fintan-contents.github.io/mobile-app-crib-notes/distribution/usecase)としてつぎのようなシチュエーションの配布方法を利用するライセンスや手順とあわせて公開しています。
```

2021-04-21 07:39 UTC, tani-takanori commented on landing-page/app-distribution-lp.md
> +# モバイルアプリケーション配布方法
```suggestion
# モバイルアプリケーションをテストするときのユースケース別配布方法
```

2021-04-21 08:37 UTC, tani-takanori commented on landing-page/app-distribution-lp.md
> +iOSとAndroidを対象に開発してきた経験をもとに、配布方法のパターンではなく、ビルドしたアプリを誰にインストールして確認してもらうかという観点でシチュエーション（ユースケース）を整理したものを[こちら](https://fintan-contents.github.io/mobile-app-crib-notes/distribution/)で公開しています。
```suggestion
iOSとAndroidを対象に開発してきた経験をもとに、配布方法のパターンではなく、ビルドしたアプリを誰にインストールして確認してもらうかという観点でシチュエーション（ユースケース）を整理したものを[こちら](https://ws-4020.github.io/mobile-app-crib-notes/distribution/)で公開しています。
```

2021-04-21 08:37 UTC, tani-takanori commented on landing-page/app-distribution-lp.md
> +[ユースケース](https://fintan-contents.github.io/mobile-app-crib-notes/distribution/usecase)としてつぎのようなシチュエーションの配布方法を利用するライセンスや手順とあわせて公開しています。
```suggestion
[ユースケース](https://ws-4020.github.io/mobile-app-crib-notes/distribution/usecase)としてつぎのようなシチュエーションの配布方法を利用するライセンスや手順とあわせて公開しています。
```

2021-04-21 09:19 UTC, asahi99 commented on landing-page/app-distribution-lp.md
> +# モバイルアプリケーション配布方法
こちらですが、`テストのためのモバイルアプリケーション配布`でいかがですか?

2021-04-21 10:09 UTC, asahi99 reviewed
見出しを削除

2021-04-21 10:09 UTC, asahi99 commented on landing-page/app-distribution-lp.md
> +## はじめに
```suggestion

```

2021-04-21 10:09 UTC, asahi99 commented on landing-page/app-distribution-lp.md
> +## ユースケース
```suggestion

```

2021-04-21 10:22 UTC, tani-takanori commented
lintいれた
https://github.com/ws-4020/mobile-app-crib-notes/pull/179/commits/4ead4e290275754484b59209505de485df38c380

2021-04-21 10:25 UTC, tani-takanori approved these changes
いいと思います。

2021-04-21 10:30 UTC, in-a-paddy approved these changes

2021-04-21 10:30 UTC, merged