🖋: 画面遷移実装を学習コンテンツの最初によせる
ws-4020/mobile-app-crib-notes pull request #193
Opened 2021-04-21 08:46 UTC by takei0w0

## 💣 BREAKING CHANGES 💣

- 画面遷移の実装を最初に寄せ、型定義のない実装に変更
- 後続の画面で整合性がとれなくなっているが、修正は別タスクで行う予定

## ✅ What's done

- [x] 遷移実装特化のStackナビゲーションページを追加
- [ ] Tabナビゲーションのページ修正
- [ ] Modalスクリーンのページ修正
- [ ] ナビゲーションの整理、ナビゲーションの型定義削除

---

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [x] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

2021-04-22 09:27 UTC, asahi99 approved these changes

2021-04-22 23:08 UTC, in-a-paddy requested changes

2021-04-23 00:32 UTC, takei0w0 commented on docs/react-native/learn/todo-app/stack-navigation.mdx
> +まずは、Welcome画面からToDo一覧までの画面遷移をStackナビゲーションで実装します。
画面遷移図の「トップ」「サインアップ」を「Welcome」「ユーザ登録」に修正します

2021-04-23 01:01 UTC, takei0w0 commented on docs/react-native/learn/todo-app/stack-navigation.mdx
> +まずは、Welcome画面からToDo一覧までの画面遷移をStackナビゲーションで実装します。
図の画面名をWelcomeに統一したので修正して取り込みます

2021-04-23 01:03 UTC, takei0w0 commented on docs/react-native/learn/todo-app/stack-navigation.mdx
> +    <View style={styles.container}>{/* Todo*/}</View>
ひな形は全て画面名をわかるように修正しました

2021-04-23 01:04 UTC, takei0w0 commented on docs/react-native/learn/todo-app/stack-navigation.mdx
> +![StackNavigation](app-hands-on/screen-transition-stack.png)
太く修正しました

2021-04-23 02:41 UTC, takei0w0 commented on docs/react-native/learn/todo-app/stack-navigation.mdx
> +    <View style={styles.container}>{/* Todo*/}</View>
ひな形は全て画面名をわかるように修正しました

2021-04-23 02:41 UTC, takei0w0 commented on docs/react-native/learn/todo-app/stack-navigation.mdx
> +-     <View style={styles.container}>{/* Todo*/}</View>
ひな形は全て画面名をわかるように修正しました

2021-04-23 02:42 UTC, takei0w0 commented on docs/react-native/learn/todo-app/stack-navigation.mdx
> +修正量が多いので、次のソースコードで`RootStackNav.tsx`を上書きしてください。
節を分けて、説明を詳細化しました。

2021-04-23 02:42 UTC, takei0w0 commented on docs/react-native/learn/todo-app/stack-navigation.mdx
> +
suggestionが崩れてたので手動でとりこみました

2021-04-28 04:26 UTC, tani-takanori commented on docs/react-native/learn/todo-app/modal.mdx
> +モーダルはStackナビゲータの`mode`属性を`modal`に変更（デフォルトは`card`）することで実現できます。
```suggestion
モーダルはStackナビゲータの`mode`属性（デフォルトは`card`）を`modal`に変更することで実現できます。
```
個人的にはこっちが好みなんだけど、どうでしょう？

2021-04-28 04:26 UTC, tani-takanori commented on docs/react-native/learn/todo-app/modal.mdx
> +ではモーダルを実装していきましょう。
```suggestion
では`TodoForm`がモーダルになるように実装しましょう。
```

2021-04-28 04:55 UTC, tani-takanori commented on docs/react-native/learn/todo-app/login.mdx
>  入力フォームの検証が動作しているかも併せて確認してください。
iOSでハンズオン受けた人が気にならないならOKなんだけど、ここで入力しづらくて詰まることないかな？

2021-04-28 05:29 UTC, takei0w0 commented on docs/react-native/learn/todo-app/login.mdx
>  入力フォームの検証が動作しているかも併せて確認してください。
キーボードが最初表示されないってやつですかね？注記で追記します

2021-04-28 05:31 UTC, tani-takanori commented on docs/react-native/learn/todo-app/login.mdx
>  入力フォームの検証が動作しているかも併せて確認してください。
あ、そっちがあるのか。
ソフトウェアキーボードが出てくるとログインボタン押しづらくなる（つぎのページで説明しているKeyboradAvoidingViewがないと操作しづらい）ことで「なんか間違えてる？」ってならないか気になったんだけど、そもそもキーボードが出ないっていうフィードバックのほうが多かったね...

2021-04-28 05:36 UTC, takei0w0 commented on docs/react-native/learn/todo-app/login.mdx
>  入力フォームの検証が動作しているかも併せて確認してください。
ああ～AndroidだとKeyboradAvoidingView入れなくても勝手に動いてくれるので盲点でした。

iOSだとこの時点では隠れてしまうことも注記追加します。

2021-04-28 07:44 UTC, takei0w0 commented on docs/react-native/learn/todo-app/login.mdx
>  入力フォームの検証が動作しているかも併せて確認してください。
対応しました

2021-05-10 04:14 UTC, tani-takanori commented on docs/react-native/learn/todo-app/login.mdx
> +現時点では、iOSで動かした場合入力フォームがキーボードで隠れてしまいます。
```suggestion
現時点では、iOSで動かした場合、ソフトウェアキーボードが表示されると入力フォームが隠れてしまいます。
```
表示されないケースが多いっぽいので条件にしました。

2021-05-10 04:32 UTC, tani-takanori reviewed
LGTM

2021-05-10 04:33 UTC, in-a-paddy approved these changes

2021-05-10 04:33 UTC, merged