#7478 「前提知識」を型定義使用しない説明にする
ws-4020/mobile-app-crib-notes pull request #202
Opened 2021-04-23 06:46 UTC by asahi99

## ✅ What's done

- [x] 型定義についての記述を「アプリの実装前に」の「ReactNavigationの基本」から削除

2021-04-23 09:16 UTC, takei0w0 requested changes

2021-04-23 09:16 UTC, takei0w0 commented on docs/react-native/learn/basic-concepts/react-navigation-basics/modal.mdx
>        <Text style={styles.title}>Modal 1</Text>
`{route.params.message}`でmessageは型objectに存在しません。とTypeScriptのエラーが発生。もしかしてTypeScriptでパラメーター使いたいなら型定義必須？

2021-04-23 09:16 UTC, takei0w0 commented on docs/react-native/learn/basic-concepts/react-navigation-basics/modal.mdx
> -  RouteProp,
他にも不要なimportがあるので削除お願いします

2021-04-26 01:10 UTC, takei0w0 commented on docs/react-native/learn/basic-concepts/react-navigation-basics/modal.mdx
>        <Text style={styles.title}>Modal 1</Text>
ミニマムな対応としては `const route = useRoute<RouteProp<{Modal1: {message: string}}, 'Modal1'>>();` とすれば未定義エラーは解消するが、定義をばらけさせると管理が複雑になるため推奨はできないと思う。

2021-04-26 05:29 UTC, takei0w0 commented on docs/react-native/learn/basic-concepts/react-navigation-basics/modal.mdx
> -  RouteProp,
削除済

2021-04-26 05:29 UTC, takei0w0 commented on docs/react-native/learn/basic-concepts/react-navigation-basics/modal.mdx
> -## useNavigationの型定義
削除済

2021-04-26 07:02 UTC, takei0w0 commented on docs/react-native/learn/basic-concepts/react-navigation-basics/modal.mdx
>        <Text style={styles.title}>Modal 1</Text>
型定義と切り離せないため応用編として別ページへ移動　前提知識からは削除

2021-04-26 16:24 UTC, in-a-paddy commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +title: 画面間でパラメータを渡す
「画面間」というよりは、「遷移先の画面に」かな、と。

```suggestion
title: 遷移先の画面にパラメータを渡す
```

2021-04-27 01:33 UTC, takei0w0 commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +
ありがとうございます！！！とりこみます

2021-04-27 02:05 UTC, in-a-paddy commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +React Navigationでは。型定義を積極的に利用することでより詳細な型チェックが可能です。例えば、`navigate`で遷移する先の画面のパラメータ名が間違えている時に、型チェックでエラーとすることなどが可能です。もしReact Navigationで利用する型定義の全体像について知りたい場合は、[Type checking with TypeScript  | React Navig
これで良かったりするのだろうか？

```suggestion
React Navigationでは。型定義を積極的に利用することでより詳細な型チェックが可能です。例えば、`navigate`で遷移する先の画面のパラメータ名が間違えている時に、型チェックでエラーとすることなどが可能です。もしReact Navigationで利用する型定義の全体像について知りたい場合は、[Type checking with TypeScript | React Navigation](https://reactnavigation.org/docs/typescript/)を参照してください。
```

2021-04-27 02:07 UTC, in-a-paddy commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +ただ、React Navigationで利用する型定義は、TypeScriptの型システムに精通していないと理解が難しいです。また、せっかく型定義を頑張ってもその利用方法が誤っていると、型チェックではエラーとならないが実行時にエラーが発生するという、望まない結果となってしまいます。
```suggestion
ただ、React Navigationで利用する型定義はTypeScriptの型システムに精通していないと理解が難しいです。また、せっかく型定義を頑張ってもその利用方法が誤っていると、型チェックではエラーにはなりませんが実行時にエラーが発生してしまいます。
```

2021-04-27 02:54 UTC, takei0w0 commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +ただし、TypeScriptを使用している場合は`route.params.message`で`message`が未定義のエラーが出てしまいます。
追記しました

2021-04-27 02:54 UTC, takei0w0 commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +1. 画面名をキーに、パラメータ定義を値としてもつリストを定義（`RootParamList`）
分けて記載しました

2021-04-27 02:54 UTC, takei0w0 commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +React Navigationで遷移する際、遷移元から遷移先にパラメータを渡すことができます。
軽く書いてみましたが、伝わるでしょうか・・・

2021-04-27 03:53 UTC, in-a-paddy approved these changes

2021-04-27 03:53 UTC, in-a-paddy commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +モバイルアプリケーションでどのように実装するか紹介します。
このくらいで良いかな、と。

```suggestion
検索条件やIDなどのパラメータを次の画面に渡したい場合に、React Navigationでどのように実装するか紹介します。
```

2021-04-27 03:53 UTC, in-a-paddy commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +`navigate`の引数で遷移先画面に渡すパラメータを指定できます。
文を分けているけどちょっと冗長に感じたかな。

```suggestion
React Navigationで遷移する際、遷移先の画面に渡したいパラメータを`navigate`の引数として指定できます。
```

2021-04-27 03:53 UTC, in-a-paddy commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +```typescript jsx
ハイライトしておくとわかりやすいかも

```suggestion
```typescript jsx {8-10}
```

2021-04-27 06:21 UTC, takei0w0 commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +モバイルアプリケーションでどのように実装するか紹介します。
にを2回つかっててlintエラーになるので、以下で取り込みました。

> 検索条件やIDなどのパラメータを次の画面に渡したい場合、React Navigationでどのように実装するか紹介します。

2021-04-27 08:12 UTC, in-a-paddy approved these changes

2021-04-28 05:17 UTC, tani-takanori commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +ただし、TypeScriptを使用している場合は次のエラーが発生します。
エラーが発生するんだっけ？（エラーメッセージが表示される？）

2021-04-28 05:22 UTC, tani-takanori commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +こういった理由から、このコンテンツでのReact Navigationのための型定義の紹介は、定義しないとエラーになるなどの必要最低限の場合に限っています。
```suggestion
こういった理由から、React Navigationのための型定義は、定義しないとエラーになるなどの必要最低限のものだけを紹介しています。
```

2021-04-28 05:25 UTC, tani-takanori commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +先のエラーを解消するためには、`route`を定義する際にその画面がもつパラメータの型定義を教える必要があります。
```suggestion
先のエラーを解消するためには、`route`を利用する際にその画面が受け取るパラメータの型定義を教える必要があります。
```

2021-04-28 05:34 UTC, takei0w0 commented on docs/react-native/learn/advance/react-navigation-param.mdx
> +ただし、TypeScriptを使用している場合は次のエラーが発生します。
ビルドは通って動作も問題ないのですが、エディタ上でエラーが表示されます。

2021-04-28 05:56 UTC, tani-takanori approved these changes

2021-04-28 05:56 UTC, takei0w0 approved these changes

2021-04-28 05:56 UTC, merged