VSCodeでのデバッグを追加
ws-4020/mobile-app-crib-notes pull request #207
Opened 2021-04-27 07:34 UTC by asahi99

## ✅ What's done

- [x] VSCodeでデバッグを行う設定を追加

2021-04-27 07:47 UTC, in-a-paddy requested changes

2021-04-27 07:47 UTC, in-a-paddy commented on docs/react-native/vscode-debug.md
> +VSCode上でデバッグを行うには`ReactNativeTools`を利用します
```suggestion
Visual Studio Codeで、React NativeのTypeScriptコードをデバッグできるように、[React Native Tools](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native)をセットアップします。
```

2021-04-27 07:47 UTC, in-a-paddy commented on docs/react-native/vscode-debug.md
> +title: VSCode 上でデバッグを行う
```suggestion
title: 'Visual Studio Codeでのデバッグ
```

2021-04-27 07:47 UTC, in-a-paddy commented on docs/react-native/vscode-debug.md
> +## ReactNativeTools のセットアップ
```suggestion
## React Native Toolsのセットアップ
```

2021-04-27 07:47 UTC, in-a-paddy commented on docs/react-native/vscode-debug.md
> +VSCodeの「拡張機能」で`ReactNative Tools`検索してインストール
実は、プラグインサイトの「Install」ボタンからインストールできます
[React Native Tools](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native)

2021-04-27 07:47 UTC, in-a-paddy commented on docs/react-native/vscode-debug.md
> +プロジェクトルート配下の`/.vscode/launch.json`を変更する。(無い場合は新規に作成する)
これ、どのディレクトリをワークスペースとしてVS Codeで開く想定にしているんだろう？`.vscode`ディレクトリをコミットしておいた方が良いのではないかという気がする。

2021-04-27 07:47 UTC, in-a-paddy commented on docs/react-native/vscode-debug.md
> +プロジェクトルート配下の`/.vscode/launch.json`を変更する。(無い場合は新規に作成する)
コミットしたうえで、「～するために、～で次のような設定をしてあります」という説明を書いておくのが良さそう。

2021-04-27 07:47 UTC, in-a-paddy commented on docs/react-native/vscode-debug.md
> +通常の起動と同様に`npx expo start`するとデバッガが立ち上がる
デバッガの使い方にリンクしてあげたら親切かな？メンテナンスめんどくさそうだからやめといた方が良いかな？

2021-04-27 09:29 UTC, takei0w0 requested changes
手順に沿って動かせるかは確認できてないですが気になったところ先にコメントします

2021-04-27 09:29 UTC, takei0w0 commented on docs/react-native/vscode-debug.md
> +```json title="/launch.json"
```suggestion
```json title="/.vscode/launch.json"
```

2021-04-27 09:29 UTC, takei0w0 commented on docs/react-native/vscode-debug.md
> +## デバッグの設定としてexpoのポートにアタッチする
複数あるうちのExpoを使用する場合の設定方法を紹介することを述べたほうがいかと

AndroidやiOSの設定方法もできれば紹介したいけど、ReactNative Toolsのページで詳しく紹介されてるからそちらに誘導すればいいかな？

2021-04-27 09:44 UTC, in-a-paddy requested changes

2021-04-28 02:56 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +VSCodeの「拡張機能」で`ReactNative Tools`検索してインストール
プラグインサイトからのインストールも併記する形にしました

2021-04-28 04:45 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +## デバッグの設定としてexpoのポートにアタッチする
>  複数あるうちのExpoを使用する場合の設定方法を紹介することを述べたほうがいかと
こちら対応しました

> AndroidやiOSの設定方法もできれば紹介したいけど、ReactNative Toolsのページで詳しく紹介されてるからそちらに誘導すればいいかな？
ページへのリンクを記載しました

2021-04-28 05:16 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +## デバッグの設定としてexpoのポートにアタッチする
こちら対応しました

2021-04-28 05:17 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +## デバッグの設定としてexpoのポートにアタッチする
> AndroidやiOSの設定方法もできれば紹介したいけど、ReactNative Toolsのページで詳しく紹介されてるからそちらに誘導すればいいかな？

リンクを記載して対応しました

2021-05-10 01:14 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +title: VSCode 上でデバッグを行う
設定にデバッグツールの紹介という形で対応しました
おすすめプラグインの中身を追加しています

2021-05-10 07:27 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +通常の起動と同様に`npx expo start`するとデバッガが立ち上がる。
環境が混ざっていて勘違いがあったようです…。
デバッグの手順はこちらです

デバッグの実行

実機の場合

`npx expo start` で起動した後に端末をシェイクし、開発者メニューを表示
`Debug Remote JS` を選択した後、VS Codeの「実行とデバッグ」から`Attach to packager`をクリックして実行

※ `Debug Remote JS` を選択した後、ブラウザでdebugger-uiが立ち上がった場合、そのタブを閉じてから`Attach to packager`を実行。

シミュレータの場合

iOS シミュレータ
`npx expo start` で起動した後に`Ctrl+cmd+z`を押下し、開発者メニューを表示
`Debug Remote JS` を選択した後、VS Codeの「実行とデバッグ」から`Attach to packager`をクリックして実行

Android シミュレータ
`npx expo start` で起動した後にWindowsかんきょうの場合、`Ctrl+m`、 Macの場合`cmd+m`を押下し、開発者メニューを表示
`Debug Remote JS` を選択した後、VS Codeの「実行とデバッグ」から`Attach to packager`をクリックして実行

2021-05-10 07:37 UTC, takei0w0 commented on docs/react-native/vscode-debug.md
> +通常の起動と同様に`npx expo start`するとデバッガが立ち上がる。
できましたー！ありがとうございます。
expoのデフォルトポートは19000だからConfigrationは修正が必要でした。

すでに起動しているメトロバンドラーにAttachするんですね。これならexpo関係なく、react nativeオンリーの場合でもできそうですね。

2021-05-10 07:55 UTC, takei0w0 commented on docs/react-native/vscode-debug.md
> +通常の起動と同様に`npx expo start`するとデバッガが立ち上がる。
Tetra環境のAndroidエミュレーターでも以下手順で確認できました。

1. `npm run android -- --port=任意のポート`
2. launch.jsonのportは1で指定したポートに修正
3. `Ctrl+M` 開発者メニューからDebugを選択
4. 自動で立ち上がるdebugger-uiを閉じる
5. VS Codeの「実行とデバッグ」からAttach to packagerをクリック
6. エミュレーター内アプリをReload

expoの方もattachしてからアプリリロードしないと、接続が確立しなかったので手順に加えてほしいです。

expoに限らず任意のポートを指定してあげれば使える設定なので、手順の`npx expo start` のところは任意の起動方法としてよいと思います！

2021-05-10 09:35 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +通常の起動と同様に`npx expo start`するとデバッガが立ち上がる。
主にexpo でのデバッグ方法で補足としてAndoridシミュレータのデバッグ方法を追加しました！

2021-05-11 01:26 UTC, takei0w0 requested changes

2021-05-11 01:26 UTC, takei0w0 commented on docs/react-native/vscode-debug.md
> +:::
Androidに限らないので、より汎用的にしましょう。

```suggestion
:::info
portにはMetro Bundlerのポート番号を指定してください。デフォルトはExpoの場合19000、Expoを使用しない場合は8081です。

ポート番号をデフォルトから変更している場合はその番号を指定してください。
:::
```

2021-05-11 01:26 UTC, takei0w0 commented on docs/react-native/vscode-debug.md
> +:::
ここは不要になりますね
```suggestion
```

2021-05-11 01:26 UTC, takei0w0 commented on docs/react-native/vscode-debug.md
> +4. 開発者メニューからアプリをリロード。
共通化できるところは共通化したほうが見やすいかなと思いました　どうでしょうか

```suggestion
### デバッグ

以下の手順でデバッガーを起動します。

1. デバッグ対象のアプリで開発者メニューを表示する
1. `Debug Remote JS`を選択する
1. ブラウザで`debugger-ui`が立ち上がるのでそのタブを閉じる
1. VS Codeの「実行とデバッグ」から`Attach to packager`をクリックして実行する
1. 開発者メニューからアプリをリロードする

:::info
開発者メニューの表示方法は端末によって異なります。

- 実機: 端末をシェイクする
- iPhoneシミュレータ: Windowsの場合`Ctrl+Z`、 Macの場合`cmd+Z`
- Androidエミュレータ: Windowsの場合`Ctrl+M`、 Macの場合`cmd+M`
:::
```

2021-05-11 01:48 UTC, in-a-paddy requested changes

2021-05-11 01:48 UTC, in-a-paddy commented on docs/react-native/vscode-debug.md
> +1. 任意の起動方法にてアプリ起動した後に`Ctrl+cmd+z`を押下し、開発者メニューを表示。
Ctrlがパスカルなら、cmdもパスカルにした方が良いと思うな

```suggestion
1. 任意の起動方法にてアプリ起動した後に`Ctrl+Cmd+z`を押下し、開発者メニューを表示。
```

2021-05-11 01:48 UTC, in-a-paddy commented on docs/sidebars.js
> +            'react-native/vscode-debug',
ファイル名は `vscode-debug` じゃなくて`settings-vscode`で良さそうじゃない？

2021-05-13 02:50 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +1. 任意の起動方法にてアプリ起動した後にWindows環境の場合`Ctrl+m`、 Mac環境の場合`cmd+m`を押下し、開発者メニューを表示。
小文字表記に統一しました

2021-05-13 04:38 UTC, asahi99 commented on docs/sidebars.js
> +            'react-native/vscode-debug',
たしかにそうですね。変更しました

2021-05-13 04:38 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +1. 任意の起動方法にてアプリ起動した後にWindows環境の場合`Ctrl+m`、 Mac環境の場合`cmd+m`を押下し、開発者メニューを表示。
パスカルに統一しました

2021-05-13 04:39 UTC, asahi99 commented on docs/react-native/vscode-debug.md
> +1. 任意の起動方法にてアプリ起動した後に`Ctrl+cmd+z`を押下し、開発者メニューを表示。
パスカルに統一しました

2021-05-13 06:12 UTC, takei0w0 approved these changes

2021-05-13 09:27 UTC, in-a-paddy approved these changes

2021-05-13 09:27 UTC, merged