✨: PullRequestでon workflowを利用してリポジトリへの書き込む
ws-4020/mobile-app-crib-notes pull request #208
Opened 2021-04-27 08:53 UTC by tani-takanori

## 💣 BREAKING CHANGES 💣

- AppのActionでレポートする箇所を削除し、on workflowでレポートするように修正

## ✅ What's done

- [ ] AppのActionでレポートする箇所を削除し、on workflowでレポートするように修正

## ⏸ What's not done

- reviewdogの置き換えはしていない（エラーになるケースがすくないので）

---

## Other (messages to reviewers, concerns, etc.)

なし

2021-04-27 08:54 UTC, tani-takanori commented
[自分のmasterで検証したPR](https://github.com/tani-takanori/mobile-app-crib-notes/pull/4)

2021-04-27 10:37 UTC, in-a-paddy commented
まとめて入れたいので、reviewdogの対応もお願いします。Jestの結果も含めて、各テスト結果・Lint結果のファイルがあったらレポートするようにしてほしいです。

2021-04-28 00:32 UTC, in-a-paddy requested changes

2021-04-28 01:01 UTC, tani-takanori commented on .github/workflows/report.yaml
> +          path: 'junit.xml'
artifactにarchiveする前にrenameするイメージかな？

2021-04-28 01:01 UTC, tani-takanori commented on .github/workflows/report.yaml
> +          path: 'junit.xml'
```
          npm run -s test --prefix SantokuApp -- --ci --reporters=default --reporters=jest-junit --coverage
          mv SantokuApp/junit.xml SantokuApp/jest-junit.xml
```

2021-04-28 01:04 UTC, in-a-paddy commented on .github/workflows/report.yaml
> +          path: 'junit.xml'
`package.json`の`jest-junit`のところで`outputName`として設定するのがいいんじゃないかな。
https://github.com/jest-community/jest-junit#configuration

2021-04-28 01:08 UTC, tani-takanori commented on .github/workflows/report.yaml
> +          path: 'junit.xml'
rn-spoilerまでは反映せんでいいんかな？

2021-04-28 01:09 UTC, in-a-paddy commented on .github/workflows/report.yaml
> +          path: 'junit.xml'
うん、いいと思います。

2021-05-07 19:15 UTC, in-a-paddy approved these changes

2021-05-10 05:05 UTC, OshitaTatsuya approved these changes

2021-05-10 05:05 UTC, merged