追加 各ページの学習内容把握するための対応
ws-4020/mobile-app-crib-notes pull request #236
Opened 2021-05-21 04:00 UTC by OshitaTatsuya

## ✅ What's done

- [x] サンプルアプリのdiffを参考に各学習コンテンツの作成する内容が分かるものを作成

## ⏸ What's not done

- この内容をもとに各学習コンテンツを作成するスケジュールを作成する

## Tests

- [x] ローカルブラウザでの表示確認

## Other (messages to reviewers, concerns, etc.)

なし

2021-05-21 04:53 UTC, tani-takanori reviewed
気になった点を書きました。
※漏れてたり、ズレてないか気になる点を上げているので、構成自体までは踏み込んでません。

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +ここでは、それぞれの動作確認前の準備を説明します。学習環境にあわせて適した内容を確認してください。
```suggestion
バックエンドの呼び出しでは、モバイルアプリケーション以外と接続するための準備をします。
  - バックエンドとのインタフェース（OpenAPI）を利用したコードの生成
  - バックエンドの確認
    - Open APIを利用したmock
    - ローカル
    - Web上、LAN上（開発端末外）にあるAPI
  - バックエンドとの疎通確認
```
それぞれが何をさすのかとかわからないのですが、呼び出しの確認までするはず？

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +ここでは、それぞれの動作確認前の準備を説明します。学習環境にあわせて適した内容を確認してください。
呼び出し確認までで、正常応答の表示はここでしない？
正常応答の表示をしないとすると目次の順番がおかしいと思う。

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +修正内容と制御方法を説明する。（コードを紹介して、制御方法の説明）
制御ってなんだろう。
＋今回の使用を説明する必要があるかな

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +ここでは、それぞれの動作確認前の準備を説明します。学習環境にあわせて適した内容を確認してください。
対象とするAPIはここで説明する？

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +クライアント作成とモックの利用。
OpenAPIの利用の説明ってそもそも今回のバックエンドのAPIの説明も含めてる？

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +づづいて、バックエンドの実行中および、結果のハンドリング方法を説明します。
```suggestion
結果のハンドリング方法を説明します。
エラーの表示方法は [Alert](https://reactnative.dev/docs/alert) を利用します
```

エラーハンドリングの仕様も決めたものを提示した上で、実際はプロジェクトで決めた制御方針に合わせて実装してくださいっていう話が入るはず

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +確認対象は、OpenAPIドキュメントのスペックを対象。
確認対象はPUTの404, GET、POST、PUT、DELETEの500系, NetworkErrorかな？

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +確認対象は、OpenAPIドキュメントのスペックを対象。
POSTの400も出せそうだったけど、まだここは追わなくていいかな

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +これは、ローカル環境のみで確認する（バックエンドサービスの停止）
バックエンドサービスの停止しなくてもconfig.ts書き換えて向き先適当にすればできるけど...

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +づづいて、バックエンドの実行中および、結果のハンドリング方法を説明します。
あと、OpenAPIのインタフェース不一致みたいなバグのグローバルエラーハンドリングは対象外

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +configのローカルIPアドレス設定。
補足だけどIPアドレスじゃなくて接続先のURL（basePath）です。
Mockのときは9080じゃなくて4000とかだったはず

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +title: バックエンドの実行結果
`api-err-control.mdx` だけど、"実行結果"？
 エラーハンドリングのページじゃない？？

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +動作確認方法を説明し、期待値と一致していることを確認するよう説明する。
期待値（正常応答の仕様）と一致しているのもここで書くでOKですよね？

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +- クライアントエラー（400系）
エラーを出すための手順も必要ですね

2021-05-21 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +待機処理（非同期処理中）を確認するための方法も説明する。
確認するための方法にはバックエンドの応答を遅らせる方法も提示するイメージでいいですか？

2021-05-21 05:18 UTC, in-a-paddy requested changes

2021-05-21 05:18 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +## 処理結果の制御方法
「制御」だと漠然としすぎだから、もっと具体的にした方がいいかな。ここでやりたいのは、エラーの場合はポップアップを出すってことなのかな？

2021-05-21 05:18 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +## 処理中の制御方法
ここももっと具体的に

2021-05-21 05:18 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +## 処理中の制御方法
関心事が違うから、別ページにした方がいいと思う

2021-05-21 05:18 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +title: バックエンドの呼び出し
準備をするなら、ページを分けた方がいい

2021-05-21 05:18 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +づづいて、非同期処理を実行している際の制御を説明していきます。
制御、ってわかりにくいと思う。何をするのか伝えて欲しい

2021-05-21 08:16 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +ここでは、それぞれの動作確認前の準備を説明します。学習環境にあわせて適した内容を確認してください。
ここでは、実行と正常応答の確認まで行いたいと考えています。
実行と正常応答の確認をすることを記載。(確認は、想定との一致)
また、ハンズオンで利用するAPIは準備の前に説明しようかと思います。(I/Oと機能概要を説明しようかと思います。)

2021-05-21 08:20 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +修正内容と制御方法を説明する。（コードを紹介して、制御方法の説明）
ここでの説明で考えているのは、処理中（ローディング）を利用者に分かるようにする方法(実装)を
説明しようかと考えています。

2021-05-21 08:23 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +クライアント作成とモックの利用。
説明内容としては、OpenAPIドキュメントを元にクライアントコードの生成と、
モックの利用方法を考えていました。
他の指摘と重複してしまいますが、このハンズオンで利用するバックエンドAPIは別途説明しようかと考えています。

2021-05-21 08:26 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +づづいて、バックエンドの実行中および、結果のハンドリング方法を説明します。
ハンズオンで作成するエラーハンドリングの仕様を説明することを明記して、
実際はプロジェクト側で決めた仕様（設計）に従ってもらうことを記載しました。（学習コンテンツ作成時に漏れないように）

2021-05-21 08:28 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +確認対象は、OpenAPIドキュメントのスペックを対象。
確認対象は、その認識でいます。
確認対象がOpenAPIドキュメントが対象は誤ってました。
(NetworkErrorはOpenAPIドキュメントに定義していないので)

2021-05-21 08:32 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +configのローカルIPアドレス設定。
誤認してました。
実際に学習コンテンツを作成する際に誤りがないように明記しました。
Mockも同様

2021-05-21 08:32 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +title: バックエンドの実行結果
タイトルが誤っているので、修正

2021-05-21 08:33 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +修正内容と制御方法を説明する。（コードを紹介して、制御方法の説明）
利用者って学習コンテンツの利用者？それともアプリの利用者（ユーザー）？

2021-05-21 08:34 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +動作確認方法を説明し、期待値と一致していることを確認するよう説明する。
動作確認として実行結果と期待値が一致することを確認する想定です。なので、期待値もここに記載します。

2021-05-21 08:35 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +- クライアントエラー（400系）
再現方法も必要なので、漏れないよう追記しました。

2021-05-21 08:35 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +待機処理（非同期処理中）を確認するための方法も説明する。
バックエンド応答を遅らせることを想定しています。

2021-05-21 08:38 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +## 処理結果の制御方法
それぞれの具体的内容、メッセージ（ポップアップ表示）や画面表示する旨を明記

2021-05-21 08:39 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +## 処理中の制御方法
他と同様で、具体的に学習コンテンツとして記載すべき内容を明記

2021-05-21 08:43 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +## 処理中の制御方法
他と同様で、具体的に学習コンテンツとして記載すべき内容を明記

2021-05-21 08:43 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +づづいて、非同期処理を実行している際の制御を説明していきます。
他と同様で、具体的に学習コンテンツとして記載すべき内容を明記

2021-05-21 08:44 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +title: バックエンドの呼び出し
新規ページを作成し、準備の内容はそっちに記載します。（一緒にすると１ページのボリュームが大きすぎるので）

2021-05-21 08:51 UTC, in-a-paddy requested changes

2021-05-21 08:51 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +## バックエンド連携の準備
ドキュメントを上から順番にやるわけではなくて、途中で他のページに飛ばして戻ってくる形にする？

2021-05-24 01:15 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +## バックエンド連携の準備
APIの内容を確認したいタイミングは他でもありそうなので、外だしにして作成するようにします。

2021-05-24 02:35 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +待機処理（非同期処理中）を確認するための方法も説明する。
遅らせるための学習コンテンツ利用者の手順とモバイル施策チームの準備作業のイメージありますか？？

2021-05-24 02:39 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +## バックエンド連携の準備
外に出しても結局このページからしかリンクしないならStepごとにページ分割したらいいんじゃないの？

（後続で）他にタイミングがあるなら、そのときにAPIのインタフェースのリンクを貼ればいいんだし

2021-05-24 02:40 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-env-build.md
> +疎通確認では、[localhost:9080/api/todos(Todo取得API)](http://localhost:9080/api/todos)を実行して確認する。
ブラウザから？curl？
URLを実行するってどういうことかわからないけど...

2021-05-24 02:42 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-design.md
> +## バックエンドAPI一覧
OpenAPIのyamlはいつ提示するんだろ？

2021-05-24 02:43 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +それぞれの再現方法（エラーの発生）も説明する。
ここはイメージありますか？？

2021-05-24 02:47 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +このハンズオンで利用するAPIを[バックエンドの説明](api-design.md)で説明。
図が欲しくなるかも

- Backendのパターン
- OpenAPI仕様のyaml（の利用）
  - Backend APIの仕様理解
  - 自動生成
  - Mockサーバ
- 呼び出し (Service以下を書き換えることがわかる）

2021-05-24 02:50 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +そもそも、開発時のバグであり、ハンドリング対象ではないため
開発時のバグっていうより、グローバルエラーハンドリングの範疇だからってイメージだった。
（APIのI/F不一致は本番でもAPI側の互換性が維持されていなければ発生するし）

2021-05-24 04:33 UTC, in-a-paddy requested changes

2021-05-24 04:33 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +## バックエンド連携の準備
> APIの内容を確認したいタイミングは他でもありそうなので、外だしにして作成するようにします。

ごめん、たぶん意図が伝わらなかったかな。別に「正規化した方が良い」という指摘ではないです。

ハンズオンコンテンツって、この部分までは基本的にページ右下の次へを押しながら進んでくる流れで作られてるはず。それがここだけ途中で急に別ページに一回行かなきゃいけなくて、しかもそのあと戻ってこないといけないとなると、流れを見失ってしまうと思う。

2021-05-24 04:33 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +ハンズオンで作成するアプリのエラーハンドリング仕様を説明する。
なんでこういう仕様が必要なのかは、書いてあげてほしい（このPRじゃなくていいです）

2021-05-24 04:53 UTC, tani-takanori requested changes
typoがあるので、削除してみました

2021-05-24 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +づづいて、非同期処理を実行している際の待機情報を表す方法を説明していきます。
```suggestion
非同期処理を実行している際の待機情報を表す方法を説明していきます。
```

2021-05-24 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +づづいて、バックエンドと連携するため、呼び出し方法を説明していきます。
```suggestion
バックエンドと連携するため、呼び出し方法を説明していきます。
```

2021-05-24 04:55 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +実際はプロジェクトにて設計を行いハンドリング仕様を決定するので、
```suggestion
実際はプロジェクトごとにエラーハンドリングを設計します。
```
〜を行いを利用しないようにしましょう。

2021-05-24 06:59 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +## バックエンド連携の準備
ハンズオン連携の仕様 → バックエンド呼び出し → 非同期処理中（待機） → エラーハンドリング
の順序で遷移するよう修正（他の遷移と合わせることと、学習者がいったりきたりしないように）

2021-05-24 06:59 UTC, tani-takanori commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +title: 非同期処理中の表す振る舞い
非同期処理中にUIでユーザーの操作を制限することをどこかで説明したほうがいいと思う。
SampleだとReadのときはIndicatorを使っているけど、PUTやDELETEはOK前提で処理してしまってからエラーが来たら戻すっていう方法をとっているので、一律「非同期処理中を表す」ことが必須じゃないし。

2021-05-24 07:01 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +このハンズオンで利用するAPIを[バックエンドの説明](api-design.md)で説明。
ハンズオン連携の仕様を説明するページを作成し、その中でフロントエンドとバックエンドを含めた構成図を作成します。（見積もりに入れておきます）

2021-05-24 07:13 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +待機処理（非同期処理中）を確認するための方法も説明する。
もらった内容と自身がイメージしていたものが相違しているので、検討が必要です。
見積もり（スケジュール）に検討からのタスク分を入れておきます。

2021-05-24 07:14 UTC, tani-takanori commented on docs/sidebars.js
> +        'react-native/learn/todo-app/todo-backend/api-env-build.mdx',
```suggestion
        'react-native/learn/todo-app/todo-backend/api-backend-spec',
        'react-native/learn/todo-app/todo-backend/api-env-build',
```

ここでエラーになって起動できない

2021-05-24 07:20 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +title: バックエンドの呼び出し
内容の理解誤りでした。以下に修正。
バックエンド連携の仕様 → バックエンド連携の準備 → バックエンドの呼び出し …
の順番で遷移するよう修正

2021-05-24 07:22 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-env-build.md
> +疎通確認では、[localhost:9080/api/todos(Todo取得API)](http://localhost:9080/api/todos)を実行して確認する。
ブラウザからアクセスして確認する想定です。なので内容を修正

2021-05-24 07:29 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-design.md
> +## バックエンドAPI一覧
バックエンド連携の仕様（api-backend-spec.mdx）部分へ提示する考えです

2021-05-24 07:36 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +それぞれの再現方法（エラーの発生）も説明する。
それぞれの確認方法を学習コンテンツ作成時に漏れないよう追記

2021-05-24 08:58 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +そもそも、開発時のバグであり、ハンドリング対象ではないため
記載内容の見直しを行い、修正

2021-05-24 09:18 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +ハンズオンで作成するアプリのエラーハンドリング仕様を説明する。
エラーハンドリングの必要性（利用者へアプリの結果を知らせる）を追記する

2021-05-24 09:20 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +づづいて、非同期処理を実行している際の待機情報を表す方法を説明していきます。
誤字の修正

2021-05-24 09:20 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-request.mdx
> +づづいて、バックエンドと連携するため、呼び出し方法を説明していきます。
誤字の修正

2021-05-24 09:21 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/api-err-control.mdx
> +実際はプロジェクトにて設計を行いハンドリング仕様を決定するので、
誤字の修正

2021-05-24 09:22 UTC, OshitaTatsuya commented on docs/sidebars.js
> +        'react-native/learn/todo-app/todo-backend/api-env-build.mdx',
記載ミス箇所の修正

2021-05-24 09:38 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/todo-backend/async-api-control.mdx
> +title: 非同期処理中の表す振る舞い
限定した内容であった為、ここで学習出来ること（利用者へ処理中と一部操作が出来ないこと）を修正

2021-05-25 07:55 UTC, tani-takanori commented
バックエンド連携で考えてた構成
![backend-structure](https://user-images.githubusercontent.com/74525873/119460789-ff7ce600-bd79-11eb-8389-cdf35d7b0e2e.png)

2021-05-26 01:55 UTC, tani-takanori approved these changes
いいと思います

2021-05-26 02:52 UTC, in-a-paddy approved these changes

2021-05-26 02:52 UTC, merged