✨ : トラブルシュートではなくハマりがちな罠に変更
ws-4020/mobile-app-crib-notes pull request #237
Opened 2021-05-21 07:22 UTC by tani-takanori

## 💣 BREAKING CHANGES 💣

- トラブルシュートというページをハマりがちな罠に変更

## ✅ What's done

- [ ] トラブルシュートをハマりがちな罠に変更
- [ ] troubleshooting -> common-trap に変更
- [ ] ドキュメントのビルドとリンク切れチェック

---

## Other (messages to reviewers, concerns, etc.)

`santoku-app`からリンクがあったので修正済み

2021-05-21 09:05 UTC, in-a-paddy requested changes

2021-05-21 09:05 UTC, in-a-paddy commented on docs/react-native/common-trap.md
> +title: ハマりがちな罠
「罠」というと意図的に仕掛けている感じがするから、「落とし穴」くらいの意味にしたいな。
英語もtrapではなくてpitfallとかtroubleとかの方が良い気がする。

2021-05-21 09:05 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +issueがCloseされていない場合、[XCodeでビルドが失敗する](../../common-trap/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
Xcodeでビルドが失敗するケース多すぎてタイトルどうしようねw
```suggestion
issueがCloseされていない場合、[Xcodeでビルドが失敗する](../../common-trap/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
```

2021-05-24 05:20 UTC, tani-takanori commented on docs/react-native/common-trap.md
> +title: ハマりがちな罠
落とし穴 , pitfallにした
（語感がpitfallのほうが可愛かった）

2021-05-24 05:29 UTC, tani-takanori commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +issueがCloseされていない場合、[XCodeでビルドが失敗する](../../common-trap/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
個人的にはHeaderファイルがない系のエラーが出るとFlipperが絡んでる印象があるなぁ…

2021-05-24 07:20 UTC, in-a-paddy requested changes

2021-05-24 07:20 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +うまく起動できない場合は、[落とし穴](../../pitfall.md)を参照してください。
```suggestion
うまく起動できない場合は、[ハマりがちな落とし穴](../../common-pitfalls.md)を参照してください。
```

2021-05-24 07:20 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +  詳細については、[react-native-cliについて](../../pitfall/react-native-cli-uninstall.md)を参照してください。
```suggestion
  詳細については、[react-native-cliについて](../../common-pitfalls/react-native-cli-uninstall.md)を参照してください。
```

2021-05-24 07:46 UTC, creature-water-valley commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +issueがCloseされていない場合、[XCodeでビルドが失敗する](../../pitfall/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
```suggestion
issueがCloseされていない場合、[Xcodeでビルドが失敗する](../../pitfall/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
```

2021-05-24 07:46 UTC, creature-water-valley commented on docs/sidebars.js
> +  trap: {
`pitfall` or `commonPitfall`?

2021-05-24 07:47 UTC, tani-takanori commented on docs/sidebars.js
> +  trap: {
！！！

2021-05-24 07:48 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +issueがCloseされていない場合、[XCodeでビルドが失敗する](../../common-trap/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
いったん、ぶち当たった事例をまとめておく感じにしようか、、、

2021-05-24 08:00 UTC, tani-takanori commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +issueがCloseされていない場合、[XCodeでビルドが失敗する](../../common-trap/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
ちょっと追記できる感じに修正しておきますね

2021-05-24 09:12 UTC, in-a-paddy requested changes

2021-05-24 09:12 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +issueがCloseされていない場合、[XCodeでビルドが失敗する](../../common-pitfalls/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
```suggestion
issueがCloseされていない場合、[Xcodeでビルドが失敗する](../../common-pitfalls/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
```

2021-05-24 09:12 UTC, in-a-paddy commented on src/pages/index.tsx
> +    title: 'CommonPitfalls',
```suggestion
    title: 'Common Pitfalls',
```

2021-05-25 00:31 UTC, tani-takanori commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +issueがCloseされていない場合、[XCodeでビルドが失敗する](../../pitfall/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
https://github.com/ws-4020/mobile-app-crib-notes/pull/237#discussion_r637802750

2021-05-25 00:31 UTC, tani-takanori commented on docs/react-native/learn/getting-started/setting-up-development-environment.mdx
> +issueがCloseされていない場合、[XCodeでビルドが失敗する](../../common-trap/cant-build-in-xcode.md)を参照して対応するか、`AwesomeProject`のiOSシミュレータの確認をSkipしてください。
https://github.com/ws-4020/mobile-app-crib-notes/pull/237#discussion_r637802750

2021-05-25 01:10 UTC, in-a-paddy approved these changes

2021-05-25 01:22 UTC, creature-water-valley approved these changes

2021-05-25 01:22 UTC, merged