✨: API Clientの自動生成のガイドと説明を追加
ws-4020/mobile-app-crib-notes pull request #241
Opened 2021-05-26 05:13 UTC by tani-takanori

## ✅ What's done

- [x] クライアントの自動生成方法の記載
- [ ] クライアントの説明
- [ ] configの作成とexportするためのindex.tsの修正のガイド

## ⏸ What's not done

- Open API SpecのYAMLの参照をbackendのtagにすること

---

## Tests

- [x] プロジェクトの作成にあるコマンドで生成したプロジェクトでnpm install -D したあとに npxとnpm scriptで自動生成できること 

## Other (messages to reviewers, concerns, etc.)

なし

2021-05-26 08:14 UTC, in-a-paddy requested changes

2021-05-26 08:14 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +export const config = new Configuration({basePath: 'http://localhost:9080/api'});
`localhost`じゃなくて、前に確認している自分の端末のIPアドレスを設定してもらうことになると思う。（まだそっちのドキュメントないけど）

2021-05-26 08:14 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +APIクライアントは`src/components/backend` に作成されています。
`src/components/backend`ってなんかおかしくない？？`src/backend`じゃないっけ？？

2021-05-26 08:14 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +自動生成したファイルに修正を入れてしまうと自動生成し直したときに修正漏れが発生するため、自動生成したファイルは修正せず、`backend`ディレクトリに接続先の設定をするためのコンポーネントを追加します。
設定オブジェクトのことを「コンポーネント」って呼んでいいかな、、、？

```suggestion
デフォルトでは接続先が`localhost`となっているため、このままではAPIサーバを起動しているマシン以外のデバイスやAndroidエミュレータなどからアクセスできません。

接続先を変更するために、`backend`ディレクトリに接続先を設定するためのモジュールを追加します。再生成したときに修正漏れが発生しないように、自動生成したファイルは修正しないでください。
```

2021-05-26 08:14 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +APIクライアントは、APIと通信し、レスポンスのJSONとJavaScriptのクラスとの型変換や共通的なエラー処理を担当します。
これ、レスポンスに限定されなかったね。リクエストの時もJSONにシリアライズしてるもんな

2021-05-26 08:14 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +`npx`か、package.jsonに`npm script`を追加してAPIクライアントを自動生成してください。
npxで実行する場合って、`npm i -D ～`は必要ない気がする。

2021-05-26 08:46 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +APIクライアントは、APIと通信し、レスポンスのJSONとJavaScriptのクラスとの型変換や共通的なエラー処理を担当します。
たしかに

2021-05-26 08:57 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +APIクライアントは`src/components/backend` に作成されています。
おかしいの修正しました

2021-05-27 00:33 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +自動生成で利用するOpenAPIは[mobile-app-hands-on-backend](https://github.com/ws-4020/mobile-app-hands-on-backend/tree/main/rest-api-specification)で公開されているものを利用します。
他との文言統一を目的に"OpenAPIドキュメント"であわせてもよいかと思いました。

```suggestion
自動生成で利用するOpenAPIドキュメントは[mobile-app-hands-on-backend](https://github.com/ws-4020/mobile-app-hands-on-backend/tree/main/rest-api-specification)で公開されているものを利用します。
```

2021-05-27 05:18 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +また、作成したコンポーネントを`TodoService`から利用しやすいように`index.ts`も作成します。
コンポーネントなのか？

2021-05-27 05:21 UTC, in-a-paddy requested changes

2021-05-27 05:21 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +APIクライアントは、APIと通信し、JSONとJavaScriptのクラスとの型変換や共通的なエラー処理を担当します。
クラスじゃない気がする。もうちょっと適切な表現がありそう。
JSONとOpen APIドキュメントで定義しているモデルとの型変換とか？

2021-05-27 06:14 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +APIクライアントは、APIと通信し、JSONとJavaScriptのクラスとの型変換や共通的なエラー処理を担当します。
モバイルアプリ側からすると提供してもらう感じがしたので「JSONとOpen APIドキュメントで定義されているモデルとの型変換」にしました。

2021-05-27 06:15 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +また、作成したコンポーネントを`TodoService`から利用しやすいように`index.ts`も作成します。
具体的に列挙するようにしました。
「自動生成したAPIクライアントと設定モジュールを」

2021-05-27 09:44 UTC, in-a-paddy approved these changes

2021-05-28 00:20 UTC, creature-water-valley approved these changes

2021-05-28 01:31 UTC, merged