✨ : サービスからTodosAPIを呼び出して確認するページを追加
ws-4020/mobile-app-crib-notes pull request #242
Opened 2021-05-27 01:28 UTC by tani-takanori

## ✅ What's done

- [ ] ServiceからAPIクライアントを呼び出す手順を追加
- [ ] 動作確認手順を追加
- [ ] APIサーバの再起動時の挙動を追加

## ⏸ What's not done

- 処理中の挙動を検証できるようにMiddlewareを修正する対応をガイドするのはアクティビティインジケータのときにやる

---

## Tests

- [ ] 手順通りに実施して動作確認できることを確認する

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-05-27 01:34 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +`TodoService`の3つのメソッドを以下のように修正してください。
インスタンス作成時に`config`を渡して、接続先URLをデフォルトから変えてるよ、というのを伝えておいた方が前とのつながりがスムーズになりそう。

2021-05-27 03:09 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +  return await todosApi.putTodo({todoId: id, toDoStatus: {completed}});
Open APIドキュメントがそうなってるからだと思いますが、`toDoStatus`→`todoStatus`が良いかと思います。

2021-05-27 04:25 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +  return await todosApi.putTodo({todoId: id, toDoStatus: {completed}});
https://github.com/ws-4020/mobile-app-hands-on-backend/pull/6
こちらと合わせて修正しました。

2021-05-27 06:53 UTC, tani-takanori commented
手順確認しているときに `type Todo` がなくなっていることに気づいたので修正しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/242/commits/71ea50d44757f16f8fce787cec874e3490de3f4d

2021-05-27 09:21 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +`TodoService`の3つのメソッドを以下のように修正してください。
https://github.com/ws-4020/mobile-app-crib-notes/pull/242/commits/e8167c90040066168af5c2843eb66092478c157d
対応しました

2021-05-27 10:31 UTC, in-a-paddy requested changes

2021-05-27 10:31 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +1. ToDoFormからToDoを登録
ToDoFormって呼び方はしてない気がするから、ToDo登録画面とか？

2021-05-27 10:31 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +curl http://localhost:9080/api/todos -X POST -d '{"text": "アプリ外からの登録"}' -H "Content-type: application/json"
```suggestion
curl http://localhost:9080/api/todos -X POST -d '{"text": "アプリ外からの登録"}' -H "Content-Type: application/json"
```

2021-05-28 00:11 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +1. ToDo一覧の「全て」タブで全量を確認
現状だと `./mvnw jetty:run` で動かすと2件データあるんよね...
Dockerだと0件

2021-05-28 00:20 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +これでToDoアプリから登録したToDoが保存され、アプリを再起動しても、前に登録したToDoが参照できるようになりました。
画面の実装 - タスク登録画面では、ToDoではなくタスクを登録っていう表現にしてるっぽいです。

2021-05-28 00:20 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/api-request.mdx
>  これで、REST APIを呼び出せるようになりました。しかし、このままではAPIを呼び出している間も画面が操作可能のままになってしまいますし、ユーザにアプリが処理中であることを伝えられません。
```suggestion
これで、REST APIを呼びだせるようになりました。しかし、このままではAPIを呼び出している間も画面が操作可能のままになってしまいますし、ユーザにアプリが処理中であることを伝えられません。
```

2021-05-28 00:27 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +これでToDoアプリから登録したToDoが保存され、アプリを再起動しても、前に登録したToDoが参照できるようになりました。
なるほど

https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/todo-app/screens/use-focus-effect
> それがToDo一覧画面にタスクが表示されない理由です。

ToDo一覧ですらタスクって呼んでるのでタスクにしてみましょうか...

2021-05-28 02:14 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +1. ToDo一覧の「全て」タブで全量を確認
それは合わせたほうが良さそうな。（ここに書くかどうかは別として。）

2021-05-28 02:47 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +```
deleteメソッドを実装している場合、ガイドが漏れてないか？

2021-05-28 02:47 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +
ここもdeleteメソッドの補足が欲しいと思う

2021-05-28 04:49 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +
https://github.com/ws-4020/mobile-app-crib-notes/pull/242/commits/208ded7184d431d04fa422050ce752cddc0b4ff0
追加

2021-05-28 05:12 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +これでToDoアプリから登録したToDoが保存され、アプリを再起動しても、前に登録したToDoが参照できるようになりました。
AB#8073

2021-05-28 05:14 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +1. ToDo一覧の「全て」タブで全量を確認
backend側を修正する
AB#8077

2021-05-28 05:16 UTC, in-a-paddy approved these changes

2021-05-28 05:22 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +画面の実装の演習問題で[タスクの削除](../screens/exercise.mdx#タスクの削除)を実装している場合は削除メソッドもAPIクライアントを呼びだすように修正してください。
ここの表現`タスク`は、別途`Todo`に修正されるでしょうか？

2021-05-28 05:23 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/api-request.mdx
> +画面の実装の演習問題で[タスクの削除](../screens/exercise.mdx#タスクの削除)を実装している場合は削除メソッドもAPIクライアントを呼びだすように修正してください。
はい。このページに限らず学習コンテンツ全体での見直しなので修正されます。

2021-05-28 05:53 UTC, creature-water-valley approved these changes

2021-05-28 05:53 UTC, merged