REST API`no
ws-4020/mobile-app-crib-notes pull request #243
Opened 2021-05-27 06:42 UTC by OshitaTatsuya

## ✅ What's done

- [x] 今後作成してい構成の図と説明を追加
- [ ] APIサーバの起動の説明を追加
- [ ] APIサーバへの接続確認の説明を追加

## Tests

- [x] ローカルで起動して、ブラウザにて今回の追加内容を確認

## Other (messages to reviewers, concerns, etc.)
なし

2021-05-28 00:42 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +![Image](react-native-api-env.png)
地球の画像だと、Wanに思えてしまうんですがそんな事ないですかね？
地球 + PCだからLan？

2021-05-28 00:42 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +これまでの構成との違いを理解してもらいたいので、[アプリの実行](../../getting-started/launch-created-app.mdx#アプリ実行の仕組み)を参照してここまでで作成した構成を確認してください。
前の画像と比較するよりも、一つの画像の中でここが追加されたよっていう枠があった方が見やすいかなと思いましたがどうでしょうか

2021-05-28 00:42 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +これまでの構成との違いを理解してもらいたいので、[アプリの実行](../../getting-started/launch-created-app.mdx#アプリ実行の仕組み)を参照してここまでで作成した構成を確認してください。
後、今回追加部分が全体的に明度・彩度が低くて前に作成した部分が目立っちゃってるので、そう意味でも追加した部分が目立つような作りにしたほうがいいかなと思いました

2021-05-28 02:12 UTC, in-a-paddy requested changes

2021-05-28 02:12 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +    {label: 'Expo + React Native', value: 'expo-build'},
`Expo + React Native`は、全部そうだと思う。構成の違いは起動方法（エミュレータ/シミュレータなのか実機なのか）の違いなんじゃないかな。

2021-05-28 02:12 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +![Image](react-native-api-env.png)
APIって、Metro Bundlerと同じ端末で実行されている想定にした方が分かりやすそう。
Metro Bundlerと違う場所にアクセスしてるから、なおさらWANに見えるな。

2021-05-28 07:03 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +URLには確認時に使用する端末のIPアドレスが必要となります。それぞれの環境で以下のコマンドを実行してIPアドレスを確認してください。
portが80じゃないのと、`http://${ip}:9080/` だとAPIっぽいレスポンス返ってこないので接続するURL体系と期待値を記載したほうがいいと思います。

2021-05-28 07:03 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +URLには確認時に使用する端末のIPアドレスが必要となります。それぞれの環境で以下のコマンドを実行してIPアドレスを確認してください。
[SampleAction](https://github.com/ws-4020/mobile-app-hands-on-backend/commit/fc92225e656b01e36ec36fe497edac6bd503cee2#diff-5fe995eada76c5f5c36cb296453a5ee2e45c45ef8a31e5eaa224ab597d4c99f3)復活させて
`http://${IP}:9080/api/test` にアクセスしてもらう？

2021-05-28 07:09 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +URLには確認時に使用する端末のIPアドレスが必要となります。それぞれの環境で以下のコマンドを実行してIPアドレスを確認してください。
`http://${IP}:9080/api/todos`でいいんじゃないの？

2021-05-28 07:23 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +URLには確認時に使用する端末のIPアドレスが必要となります。それぞれの環境で以下のコマンドを実行してIPアドレスを確認してください。
配列（データを入れてなければ空の配列）が返ってくることを期待値にすれば良さそうですね

2021-05-28 08:23 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +![Image](react-native-api-env.png)
構成図の見直しと、iOSとAndroidを分けて説明する必要性はないので図を纏める修正

2021-05-28 08:27 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +これまでの構成との違いを理解してもらいたいので、[アプリの実行](../../getting-started/launch-created-app.mdx#アプリ実行の仕組み)を参照してここまでで作成した構成を確認してください。
比較のために色々参照するのも理解しずらいので、構成図の中で明度・彩度を利用して変更点を説明する方が学習者にとって理解しやすいと思うので修正

2021-05-28 08:32 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +    {label: 'Expo + React Native', value: 'expo-build'},
構成の違いの観点が誤っていた為、修正

2021-05-28 08:33 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +[バックエンド サンプルアプリ](https://github.com/ws-4020/mobile-app-hands-on-backend#readme)にそれぞれの起動と確認方法が記載されているので確認して実行してください。
`ハンズオン用バックエンドサンプルアプリ`へ修正

2021-05-28 08:33 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +URLには確認時に使用する端末のIPアドレスが必要となります。それぞれの環境で以下のコマンドを実行してIPアドレスを確認してください。
確認方法(ブラウザを利用して)とURLと期待を追記

2021-05-31 05:06 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +![Image](react-native-api-env.png)
僕はよいと思いました。

2021-05-31 05:09 UTC, creature-water-valley commented
> Expo Goやテスト用のデバイスからAPIサーバにアクセスしようとしても、ファイアウォールなどに制限されてアクセスできない場合があります。

「テスト用のデバイス」っていうのが初めて出てきたような気がして、少し「？」となりました。

2021-05-31 05:19 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +`${IP}`部分を確認したIPアドレスへ変更してアクセスしてください。
APIサーバと同じ端末のエミュレータからの場合は、`10.0.2.2`だと思うので、そこらへんの記述もあった方が親切かなと思いました。
https://developer.android.com/studio/run/emulator-networking.html

2021-05-31 05:19 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +データを登録していない場合、空配列のJSONがレスポンスとなります。
データを登録する説明がないのに、「データを登録していない場合」という記載があってちょっと？？になりそうな気がしたので、初めてAPIサーバを起動した場合は～とかの方がわかりやすいかなと思いました。

2021-05-31 05:25 UTC, creature-water-valley commented
> デバイスやシミュレータでブラウザを起動し、APIサーバのURLにアクセスできることを確認してください。

この文言があるので、アクセス確認をしようと思いますが、ホストはいいにしても動作確認用のパスがなんだろう？？ってなりそう気がしました。（少し、進めばそれも記載されているのですが、ちょっとわかりづらい気がしました）

2021-05-31 05:47 UTC, tani-takanori requested changes
diffがなかったのでコメントで

> Expo Goやテスト用のデバイスからAPIサーバにアクセスしようとしても

最初の「Expo Goや」が不要だと思います。

2021-05-31 05:47 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +<Tabs
アプリのインストールがあるかないか？の違いの図に見えます。
（実機をUSBでつないだ場合は実機だけどInstall Appはある）

Expo GO経由でインストールしたか、React Nativeでインストールしたかはあまり重要ではなくて、
MetroBundlerからLoadしたJSが実行されて（ここまでが「画面の実装」）、モバイルアプリから開発端末のREST APIサーバと接続するようになることがポイントかなと思います

2021-05-31 05:47 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +では、React Nativeを開発している端末にAPIサーバを起動します。APIサーバはDockerを利用して起動する方法と、Mavenを利用して起動する方法があります。いずれかお好みの方法で起動してください。
```suggestion
では、Todoアプリを開発している端末でAPIサーバを起動します。APIサーバはDockerを利用して起動する方法と、Mavenを利用して起動する方法があります。いずれかお好みの方法で起動してください。
```

2021-05-31 05:47 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +{}
```suggestion
[]
```

2021-05-31 08:24 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +`${IP}`部分を確認したIPアドレスへ変更してアクセスしてください。
これって`10.0.2.2` じゃないと繋がらないって意味じゃなくて、Android Emulatorは`10.0.2.2` で設定すればいいから確認しなくていいよってことですかね？

2021-05-31 08:26 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +![Image](react-native-api-env.png)
青がめちゃくちゃ強い気がする。Stackナビゲーションのところとかと同じような表現でいいんじゃないかな。

2021-05-31 09:28 UTC, tani-takanori commented
> > デバイスやシミュレータでブラウザを起動し、APIサーバのURLにアクセスできることを確認してください。
> 
> この文言があるので、アクセス確認をしようと思いますが、ホストはいいにしても動作確認用のパスがなんだろう？？ってなりそう気がしました。（少し、進めばそれも記載されているのですが、ちょっとわかりづらい気がしました）

REST APIのToDo一覧取得のURLであることがわかるように記載しました

2021-05-31 09:29 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +データを登録していない場合、空配列のJSONがレスポンスとなります。
下記のように修正

```
ブラウザにレスポンスのToDo一覧のJSONが表示されます。
APIサーバを起動しただけであれば、ToDoの一覧は空配列のJSONがレスポンスとなります。
```

2021-05-31 09:30 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +`${IP}`部分を確認したIPアドレスへ変更してアクセスしてください。
アドレス確認のTabにAndroidエミュレータを追加しました

2021-05-31 09:52 UTC, creature-water-valley approved these changes

2021-05-31 09:54 UTC, in-a-paddy requested changes

2021-05-31 09:54 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +いままでの構成とこれから準備する構成の違いがわかるよう色分けしています。
```suggestion
ToDoアプリをAPIサーバと接続する場合、下の図にあるようなネットワーク構成で開発することになります。いままでの構成とこれから準備する構成の違いがわかるよう色分けしています。
```

2021-05-31 09:54 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +- グレー部分は画面の実装のときに用意し、確認していた部分です。アプリケーションを開発環境で動かすために必要な構成です。
```suggestion
- グレー部分は画面の実装のときに用意し、確認していた部分です。Metro BundlerのURLは、React NativeやExpoが自動的に設定しています。
```

2021-05-31 09:54 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +  ここはアプリケーションが利用するので、アプリケーションに接続先を設定する必要がある箇所です。
```suggestion
- 背景色または、実線が青色になっている部分はこれから準備する部分を表しています。REST APIのURLは、React NativeやExpoでは接続先を設定しないため、ToDoアプリで設定する必要があります。
```

2021-05-31 09:54 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +次の学習でクライアントからREST APIへRequestを送信し、Responseをクライアントが受け取り、結果を画面出力する等を学習していきます。
```suggestion
ここからは、ToDoアプリからREST APIにリクエストを送信し、レスポンスとして受け取った結果を画面出力する方法などを学習していきます。
```

2021-05-31 09:54 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +URLには確認時に使用する端末のIPアドレスが必要となります。それぞれの環境で以下のコマンドを実行してIPアドレスを確認してください。
```suggestion
アクセス確認には、APIサーバを起動している端末のIPアドレスが必要となります。それぞれの環境で以下のコマンドを実行してIPアドレスを確認してください。
```

2021-05-31 09:54 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +アクセス先端末のIPアドレスが確認出来たので、ブラウザを利用して実際にアクセスしてみましょう。
どのブラウザのことか書いたほうがいい気がする。
```suggestion
アクセス先端末のIPアドレスが確認出来たので、Expo Goをインストールしているデバイスやエミュレータ内のブラウザから、実際にアクセスしてみましょう。
```

2021-05-31 09:54 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +アクセス先のURLとレスポンスの期待値は以下となります。
「以下となります」の次の行に見出しが来るのは違和感があるかな。

2021-05-31 09:55 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +アクセス先端末のIPアドレスが確認出来たので、ブラウザを利用して実際にアクセスしてみましょう。
`ToDoアプリを起動する` でいいかな？

2021-05-31 09:59 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +URLには確認時に使用する端末のIPアドレスが必要となります。それぞれの環境で以下のコマンドを実行してIPアドレスを確認してください。
conflictしちゃった

2021-05-31 10:02 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +アクセス先端末のIPアドレスが確認出来たので、ブラウザを利用して実際にアクセスしてみましょう。
あぁ、それがいいかも

2021-05-31 10:02 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +アクセス先端末のIPアドレスが確認出来たので、ブラウザを利用して実際にアクセスしてみましょう。
「Expo Goをインストールしているデバイスやエミュレータから、ブラウザなどを使って実際にアクセスしてみましょう。」とか？

2021-05-31 10:25 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +アクセス先端末のIPアドレスが確認出来たので、ブラウザを利用して実際にアクセスしてみましょう。
https://github.com/ws-4020/mobile-app-crib-notes/pull/243/commits/4dda00c5460bd62b8a7c8469a1ef8564daf430fd

2021-05-31 11:09 UTC, in-a-paddy requested changes

2021-05-31 11:09 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +- 背景色または、実線が青色になっている部分はこれから準備する部分を表しています。REST APIのURLは、React NativeやExpoでは設定されないので、ToDoアプリで設定する必要があります。
```suggestion
- 青色部分はこれから準備する部分を表しています。REST APIのURLは、React NativeやExpoでは設定されないので、ToDoアプリで設定する必要があります。
```

2021-05-31 11:09 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +アクセス先端末のIPアドレスが確認出来たので、ToDoアプリを起動するデバイスやエミュレータ内のブラウザから、実際にアクセスしてみましょう。
```suggestion
アクセス先端末のIPアドレスが確認出来たら、ToDoアプリを起動するデバイスやエミュレータ内のブラウザから、実際にアクセスしてみましょう。
```

2021-05-31 11:09 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +### レスポンス結果の期待値
サジェストしても使えない気はするけど、、、
```suggestion
### レスポンスの期待値
```

2021-06-01 00:33 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx
> +### レスポンス結果の期待値
https://github.com/ws-4020/mobile-app-crib-notes/pull/243/commits/ffaed0d80f516ea0cecd78ea790e3bd7d9077b7e

もう少し大きめに修正した

2021-06-01 01:42 UTC, tani-takanori commented
開発環境端末でLinuxがあるけど削除して欲しい。

2021-06-01 02:15 UTC, in-a-paddy approved these changes

2021-06-01 02:27 UTC, tani-takanori approved these changes

2021-06-01 02:27 UTC, merged