🖋: 前提知識の書き方を少し変えてみる
ws-4020/mobile-app-crib-notes pull request #251
Opened 2021-06-04 08:08 UTC by tani-takanori

## 💣 BREAKING CHANGES 💣

- 必須だぞっていうメッセージ性を削除

## ✅ What's done

- [x] 参照して欲しいサイトとして、わからなければ確認してもらうように修正

## Other (messages to reviewers, concerns, etc.)

なし

2021-06-04 08:34 UTC, in-a-paddy requested changes

2021-06-04 08:34 UTC, in-a-paddy commented on docs/react-native/learn/basic-concepts/pre-requisites.md
> +技術習得にあたり有効なサイトを紹介させて頂きますので、用語やコード例など、わからないことがあるときは参照してください。
```suggestion
用語やコード例など、わからないことがあったときに参考にしてもらいたいサイトを紹介します。
```

2021-06-04 08:34 UTC, in-a-paddy commented on docs/react-native/learn/basic-concepts/pre-requisites.md
> +まずは[Reactのチュートリアル](https://ja.reactjs.org/tutorial/tutorial.html)の内容がわかるようになってからReact Nativeの学習に進んでください。
この文がここにあると、「わかんなかったら見てね」からの「まず見てね」になっている気がして❓❓ってなるかなぁ。
こういう書き方にするなら、「必ず学んでおいてほしいこと」と「参考情報」で節を分けるとかした方が良い気もする。

TypeScriptの文法、Promiseの使い方、React.jsのチュートリアルとコンセプトあたりは抑えておいてほしいよねって話もあった気がする？

2021-06-04 08:34 UTC, in-a-paddy commented on docs/react-native/learn/basic-concepts/pre-requisites.md
> +まずは[Reactのチュートリアル](https://ja.reactjs.org/tutorial/tutorial.html)の内容がわかるようになってからReact Nativeの学習に進んでください。
* JavaScript Primer: 「第一部: 基本文法」の見出しを見て、内容を推測できる程度の知識があれば大丈夫。
* サバイバルTypeScript: Javaなど文法が似た言語の経験があって、細かいことを気にしないのであれば、読まなくて大丈夫「これだけはおさえておきたいTypeScriptの機能」の見出しを見て、内容を想像できる程度の知識があれば安心。
* React公式サイト: 書いてあるところは全部抑えておいてほしいなぁ、、、けど、現実的には「チュートリアル」くらいがいいところかな？

2021-06-08 00:48 UTC, tani-takanori commented on docs/react-native/learn/basic-concepts/pre-requisites.md
> +まずは[Reactのチュートリアル](https://ja.reactjs.org/tutorial/tutorial.html)の内容がわかるようになってからReact Nativeの学習に進んでください。
https://github.com/ws-4020/mobile-app-crib-notes/discussions/128#discussioncomment-833837

2021-06-08 01:31 UTC, creature-water-valley approved these changes

2021-06-08 01:46 UTC, in-a-paddy approved these changes

2021-06-08 01:46 UTC, merged