Fix/set todo and go back issue
ws-4020/mobile-app-crib-notes pull request #256
Opened 2021-06-09 02:08 UTC by tani-takanori

## ✅ What's done

- [x] `git grep` で `goBack` と `setTodos` の問題になる箇所を洗い出し
- [x] 実装の修正
- [x] 実装の意図をnoteで追記
- [ ] コード例の修正後にアプリが動作することを確認

## ⏸ What's not done

- REST API側の実装はマージされてないので未取り込み

---

## Tests

- [ ] 修正したコードでハンズオンを実施して問題がないことを確認

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-06-09 08:26 UTC, in-a-paddy requested changes
rn-spoilerへの反映を忘れずにお願いしたい

2021-06-09 08:26 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/todo-board.mdx
> +これは「画面の実装」を学習中には発生しづらい不具合ですが、「REST APIとの接続」で実装を追加するとToDoのステータス更新処理で時間がかかるようになるため不具合が発生します。
顕在化、だと硬すぎるかな？
```suggestion
これは「画面の実装」を学習中には発生しづらい不具合ですが、「REST APIとの接続」で実装を追加するとToDoのステータス更新処理で時間がかかるようになるため不具合が顕在化します。
```

2021-06-09 08:26 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/todo-board.mdx
> +そのため、最後に更新したToDo以外のToDoの状態が戻ってしまうことがあります。
めっちゃむずいので、わかるようにしたい。ダメな例と合わせて説明しないと意味がわからない気がしてきた、、、絵とかで示さないと、理解できない気がする

2021-06-09 08:26 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/todo-form.mdx
> +これは`postTodo`の処理中にユーザが右上の閉じるボタン（Xボタン）で画面を閉じてしまったユーザが意図しない画面遷移を防ぐためです。
これはこれでむずいな。どういう不具合なのか、と`navigation.isFocused()`でなぜ防げるのか、が伝わるようにしたいなぁ。こっちも、絵とかで示さないと、理解できない気がする

2021-06-09 08:58 UTC, nagano-ryo commented on docs/react-native/learn/todo-app/screens/todo-form.mdx
> +これは`postTodo`の処理中にユーザが右上の閉じるボタン（Xボタン）で画面を閉じてしまったユーザが意図しない画面遷移を防ぐためです。
以下の説明あればより分かりやすいと思いました。
- `navigation.isFocused()`によりToDo登録画面が表示されているときだけ`navigation.goBack()`するようにしている。

2021-06-09 09:03 UTC, nagano-ryo commented on docs/react-native/learn/todo-app/screens/todo-board.mdx
> +そのため、最後に更新したToDo以外のToDoの状態が戻ってしまうことがあります。
関数型の更新を何回も読んでいたら理解できました。

> `setTodos()`にtodoという値でなく、関数を渡すことで、前回のtodoを受け取って処理してくれる。

なんでこれで問題が解消されるかは「こういうものだから」までしか理解できませんでした。

2021-06-09 10:19 UTC, tani-takanori commented
これくらいやってやっと再現したぜ
```
const putTodo = async (id: number, completed: boolean) => {
  const target = todos.find((todo) => todo.id === id);
  if (!target) {
    return Promise.reject(new Error('not found'));
  }
  target.completed = completed;
  return new Promise((resolve) => setTimeout(() => resolve({...target}), 2000 + id * 100));
};
```

2021-06-10 12:05 UTC, in-a-paddy reviewed
読む人にどう受け取られるかわからないところではあるけど、いい感じだと思った。
不具合を修正しているPRで演習課題として追加しているのが特に秀逸w

2021-06-10 12:05 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +この実装ではレンダリング用の値を参照して更新しています。
こっちのほうがいいかな、と。
```suggestion
この実装ではレンダリング時の値を参照して更新しています。
```

2021-06-10 12:05 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +ここではScreenの状態を判定しないと「登録処理待ちのときに登録画面を閉じる」ときに発生する不具合を紹介します。
何の状態かは伝えてあげてもいいかも。
```suggestion
ここではScreenの表示状態を判定しないと「登録処理待ちのときに登録画面を閉じる」ときに発生する不具合を紹介します。
```

2021-06-10 12:05 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +`TodoForm.tsx`と`TodoService.ts`を修正したらアプリを起動して、画面したのTabでHome、設定、Homeと遷移してください。
```suggestion
`TodoForm.tsx`と`TodoService.ts`を修正したらアプリを起動して、画面下のTabでHome、設定、Homeと遷移してください。
```

2021-06-11 00:02 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +ヒント：不具合が発生するのはレンダリング用の`todos`をベースに更新していることが関係しています。
```suggestion
ヒント：不具合が発生するのはレンダリング時の`todos`をベースに更新していることが関係しています。
```

2021-06-11 04:15 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +上記の処理はREST APIとの接続をすると不具合が顕在化する実装をしてしまうケースがあります。
```suggestion
上記の処理はREST APIに接続をすると不具合が顕在化する実装をしてしまうケースがあります。
```

2021-06-11 04:26 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +  const target = todos.find((todo) => todo.id === id);
ここの`todos`ってどこに定義されてます？？

2021-06-11 04:28 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +  const target = todos.find((todo) => todo.id === id);
演習問題時点ではREST APIと接続してないので
```
const todos: Todo[] = [
  {
    id: 0,
    text: '洗濯物をたたむ',
    completed: false,
  },
 // 後略

```
という定義が`TodoServices.ts`にあります。

2021-06-11 04:38 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +  const onAdd = useCallback<(values: {task: string}) => void>(
`task`→`todo`ですかね。
ToDo登録画面とかもそうなってるっぽいです。

2021-06-11 04:39 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +`TodoForm.tsx`と`TodoService.ts`を修正したらアプリを起動して、画面下のTabでHome、設定、Homeと遷移してください。
```suggestion
`TodoForm.tsx`と`TodoService.ts`を修正したらアプリを起動して、画面下のタブでHome、設定、Homeと遷移してください。
```

2021-06-11 04:52 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +### 関数型のState更新
上のリストと合わせていいんじゃないかな。

```suggestion
### ToDo一覧画面のステータスの更新処理
```

2021-06-11 04:52 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +ここでは関数型の更新を利用しない場合に「複数のToDoを連続してステータス更新する」と発生する不具合を紹介します。
複数である必要ってあるんだっけ？？

```suggestion
ここでは、ToDoのステータスを連続して更新したときに発生する不具合を紹介します。
```

2021-06-11 04:52 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +まず不具合が発生するように（間違えやすい）実装に修正します。
```suggestion
まず不具合が発生するように（間違えやすい）実装に変更します。
```

2021-06-11 04:52 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +REST APIに接続すれば不具合は再現できます。準備に時間がかかるため、ここではREST APIに接続した場合と同じ状況を再現します。
```suggestion
REST APIに接続すれば不具合は再現できますが、準備に時間がかかるため、ここではREST APIに接続した場合と同じ状況を再現します。
```

2021-06-11 04:52 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +  return new Promise((resolve) => setTimeout(() => resolve({...target}), 2000 + id * 100));
`id * 100` で若干ずらす必要ってある？？

2021-06-11 04:52 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +### 処理完了後の画面遷移
こっちもリストと合わせておいた方が良いかな、と
```suggestion
### ToDo登録画面の登録後に自動でModal画面を閉じる処理
```

2021-06-11 04:52 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +正しくは`navigation.isFocused()`が`true`の場合のみ`navigation.goBack()`を呼びますが、
これだとヒント出すぎてるかな？
```suggestion
正しくは画面が表示されている場合（`navigation.isFocused()`が`true`の場合）のみ`navigation.goBack()`を呼ぶべきですが、
```

2021-06-11 05:29 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +REST APIに接続すれば不具合は再現できます。準備に時間がかかるため、ここではREST APIに接続した場合と同じ状況を再現します。
一か八か取り込んでみる

2021-06-11 05:33 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +  return new Promise((resolve) => setTimeout(() => resolve({...target}), 2000 + id * 100));
いらなかった！

`{...target}` をしないと出来ないだけだった

2021-06-11 05:37 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +  return new Promise((resolve) => setTimeout(() => resolve({...target}), 2000 + id * 100));
3秒待つようにする
fc239ae4f19cc62e5da384973f61c3f53ce0a7ba

2021-06-11 05:38 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +  const onAdd = useCallback<(values: {task: string}) => void>(
task撲滅委員会

6063ceba00625e3967398dc28213593e41834ccc

2021-06-11 05:46 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +  return new Promise((resolve) => setTimeout(() => resolve({...target}), 2000 + id * 100));
だよね

2021-06-11 05:48 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +このように実装することで`Promise`を返す（`resolve`する）までに2秒程度待つことになり、返されるToDoも`TodoService`が参照しているオブジェクトとは別のインスタンスになります。
```suggestion
このように実装することで`Promise`を返す（`resolve`する）までに3秒程度待つことになり、返されるToDoも`TodoService`が参照しているオブジェクトとは別のインスタンスになります。
```

2021-06-11 05:49 UTC, in-a-paddy approved these changes

2021-06-11 08:13 UTC, creature-water-valley approved these changes

2021-06-11 08:13 UTC, merged

2021-06-11 08:34 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/todo-board.mdx
> +そのため、最後に更新したToDo以外のToDoの状態が戻ってしまうことがあります。
演習課題として追加されているので良さそう！

2021-06-11 08:35 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/todo-form.mdx
> +これは`postTodo`の処理中にユーザが右上の閉じるボタン（Xボタン）で画面を閉じてしまったユーザが意図しない画面遷移を防ぐためです。
こっちも演習課題として追加されているので良さそう！