Feature/status ope act
ws-4020/mobile-app-crib-notes pull request #265
Opened 2021-06-09 08:37 UTC by OshitaTatsuya

## ✅ What's done

- [x] REST API呼び出し前に変更内容を即時更新する方法を説明
- [x] 即時更新するよう修正した結果の動作確認方法を説明
- [ ] 紹介コードを利用しての動作確認

## Devices

- [ ] iOS
  - [ ] シミュレータ (iPhone 11/iOS 14.5)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)
なし

2021-06-09 08:42 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +        )
https://github.com/ws-4020/mobile-app-crib-notes/pull/256/files#diff-9f6507c1b4039f8a2773047597c33236cc1220809764aea960cd2aff3c381384R319-R324

修正前が違うきがするのと関数型の更新を利用して欲しいです。

2021-06-09 08:51 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +次のようにREST APIを呼びだす前にタップして更新したステータスを`updateTodo`で受け取ります。
`then`で受け取っていた `returnedTodo` で `todos`を更新していたため、REST APIの処理を待つ実装だったけど、モバイルアプリ側でTodoを更新するように修正するんじゃない？

2021-06-09 08:58 UTC, in-a-paddy requested changes

2021-06-09 08:58 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +ToDo一覧の最新化と同じように処理が終わるまで操作をブロックしても良いですが、複数のToDoのステータスを変更することがストレスになります。
```suggestion
ToDo一覧の最新化と同じように処理が終わるまで操作をブロックしても良いですが、複数のToDoのステータスを変更するときに、かなりのストレスになります。
```

2021-06-09 08:58 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +ここではToDoのステータスがタップされたタイミングでUIを変更するようにしましょう。
```suggestion
ここではToDoのステータスがタップされたタイミングで、サーバーの応答を待たずにUIに反映するようにしましょう。
```

2021-06-09 08:58 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +catchブロックで「ユーザにエラーを伝え」、「ToDo一覧」を操作前、もしくは最新化するという方法を考えてみてください。
```suggestion
REST APIで正常に処理出来なかった場合、実際にはステータスの更新に失敗しているのにToDo一覧上は更新されているという状態になってしまいます。このような不整合を防ぐためにはエラーが起きたときにもToDo一覧を更新する必要があります。
たとえば、エラーが起きたときは「ユーザにエラーを伝え」「ToDo一覧を最新化する」という方法が考えられます。ここでは具体的な実装は紹介しないので、どのように実装できるかぜひ考えてみてください。
```

2021-06-09 08:58 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +現状、ToDoのステータスをタップしてもすぐに変更されず、応答が返ってくるまでユーザは待つ必要があります。
「ToDoのステータス」より「ToDoのチェックボックス」かなと思ったけど、他のページでの表現とあっていれば大丈夫です。

2021-06-09 08:58 UTC, in-a-paddy commented on docs/sidebars.js
> +            'react-native/learn/todo-app/networking/status-ope-ux-act',
ファイル名は `improve-usability`とかでどうでしょう？

2021-06-10 00:24 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +現状、ToDoのステータスをタップしてもすぐに変更されず、応答が返ってくるまでユーザは待つ必要があります。
> チェックボックスをクリックしてToDoの完了状態が更新できる

https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/todo-app/screens/todo-board

クリック...だけどチェックボックスって表現ですね

2021-06-10 01:39 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +現状、ToDoのステータスをタップしてもすぐに変更されず、応答が返ってくるまでユーザは待つ必要があります。
クリック、ではないからついでに直しちゃいたいね

2021-06-10 02:13 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +                return prevTodos.map((todo) => (todo.id === id ? returnedTodo : todo));
ここでもステートを更新すると、同じToDoを完了にして、APIのレスポンスが返ってくる前に未完了にした場合、完了と未完了をいったりきたりしてしまうような？

2021-06-10 04:03 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +現状、ToDoのステータスをタップしてもすぐに変更されず、応答が返ってくるまでユーザは待つ必要があります。
`ToDoのステータス`を`ToDoのチェックボックス`にして、`クリック`を`タップ`に修正 8f4d8effbe350ded01bd457bb0f84be42433332a

2021-06-10 04:07 UTC, OshitaTatsuya commented on docs/sidebars.js
> +            'react-native/learn/todo-app/networking/status-ope-ux-act',
e2aaaf1e0be2e7af335be9ca8b1cd9b8482710ca

2021-06-10 04:32 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +        )
e1100d891f80e36377b2f82ea796e4e7a1cc8e79

2021-06-10 04:32 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +次のようにREST APIを呼びだす前にタップして更新したステータスを`updateTodo`で受け取ります。
e1100d891f80e36377b2f82ea796e4e7a1cc8e79

2021-06-10 04:32 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +                return prevTodos.map((todo) => (todo.id === id ? returnedTodo : todo));
e1100d891f80e36377b2f82ea796e4e7a1cc8e79

2021-06-10 04:59 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> ++        setTodos(prevTodos.map((todo) => (todo.id === id ? updateTodo : todo)));
```suggestion
+        setTodos((prevTodos) => prevTodos.map((todo) => (todo.id === id ? updateTodo : todo))));
```

2021-06-10 05:02 UTC, creature-water-valley submitted a review, later dismissed

2021-06-10 05:09 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> ++        setTodos(prevTodos.map((todo) => (todo.id === id ? updateTodo : todo)));
c8f80b6a278a99f034ac9fb6a0d8192e7bb133ae

2021-06-10 05:21 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +次のようにREST APIを呼びだす前にタップして更新したステータスを`updateTodo`で受け取ります。
指摘内容とcommitの内容が紐付かない...

2021-06-10 05:32 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +その後、`setTodos`へ更新した完了状態を反映するように修正します。
```suggestion
次のように更新対象のToDoの状態を変更して`setTodos`でstateを更新した後にREST APIを呼びだすように修正します。

すでにUIは更新しているため、`todos`を更新する必要はないので`then`での処理も削除します。
```

あとは`then`で処理書いたらいけない理由も必要ですね。

2021-06-10 05:51 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +```diff typescript title="screens/todo/TodoBoard.tsx"
```suggestion
```diff typescript title="/src/screens/todo/TodoBoard.tsx"
```

ほかは`/src` から書いてそう

2021-06-10 05:53 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +その後、`setTodos`へ更新した完了状態を反映するように修正します。
修正の説明を修正したのと、`then`をここで利用してはいけない理由を追記 4f8c0b5dd25c9fd1c4230636ae93ed377b282198

2021-06-10 06:06 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`を削除する理由は、REST API呼び出し後にまたUIへ反映してしまい、完了状態が意図しない状態となってしまうためです。
これだとイメージできないので水谷さんに指摘されたようなケースを具体的に出したほうがいいです。

2021-06-10 06:32 UTC, in-a-paddy requested changes

2021-06-10 06:32 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +         }
なんとなくインデントがおかしい気がする

2021-06-10 06:36 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`を削除する理由は、REST API呼び出し後にまたUIへ反映してしまい、完了状態が意図しない状態となってしまうためです。
API呼びだし後に更新するんじゃなくて、呼びだし前に更新するんだから`then`から消すのは当たり前だと思った。具体的なケースまで出さなくても、「移動するよ」ということが伝わる文章になっていれば問題ないんじゃないかな。

2021-06-10 06:49 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +         }
他の対応とあわせてインデントを修正 4f8c0b5dd25c9fd1c4230636ae93ed377b282198

2021-06-10 06:49 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`を削除する理由は、REST API呼び出し後にまたUIへ反映してしまい、完了状態が意図しない状態となってしまうためです。
4f8c0b5dd25c9fd1c4230636ae93ed377b282198

2021-06-10 06:49 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +```diff typescript title="screens/todo/TodoBoard.tsx"
4f8c0b5dd25c9fd1c4230636ae93ed377b282198

2021-06-10 06:50 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +次のようにREST APIを呼びだす前にタップして更新したステータスを`updateTodo`で受け取ります。
4f8c0b5dd25c9fd1c4230636ae93ed377b282198

2021-06-10 07:34 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +```diff typescript title="screens/todo/TodoBoard.tsx"
490cb3c122043e4d24d74452e829a801da43dd76

2021-06-10 07:34 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`を削除する理由は、REST API呼び出し後にまたUIへ反映してしまい、完了状態が意図しない状態となってしまうためです。
490cb3c122043e4d24d74452e829a801da43dd76

2021-06-10 07:52 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`を削除する理由は、REST API呼び出し後にまたUIへ反映してしまい、完了状態が意図しない状態となってしまうためです。
9247df3ac55d4c94840f72fc61be78fe335cfa4f

2021-06-10 07:52 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +次のようにREST APIを呼びだす前にタップして更新したステータスを`updateTodo`で受け取ります。
9247df3ac55d4c94840f72fc61be78fe335cfa4f

2021-06-10 08:11 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`の部分を残しておくとREST API呼び出し前にUI反映しているのに、同じToDoの完了状態が余計に反映されてしまうので、削除します。
```suggestion
次のように`then`の処理（UIに反映するための`setTodos`）をREST API呼びだし前に移動します。
```

2021-06-10 08:22 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`の部分を残しておくとREST API呼び出し前にUI反映しているのに、同じToDoの完了状態が余計に反映されてしまうので、削除します。
e779c0bc8f15bdd05e14a0f58e338d74ce186af1

2021-06-10 08:22 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`を削除する理由は、REST API呼び出し後にまたUIへ反映してしまい、完了状態が意図しない状態となってしまうためです。
e779c0bc8f15bdd05e14a0f58e338d74ce186af1

2021-06-10 08:22 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/status-ope-ux-act.mdx
> +次のようにREST APIを呼びだす前にタップして更新したステータスを`updateTodo`で受け取ります。
e779c0bc8f15bdd05e14a0f58e338d74ce186af1

2021-06-10 08:52 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +`then`の処理（UIに反映するための`setTodos`）はREST APIの呼びだし前に移動します。
差分の内容を説明しているので、個人的にはこっちの方がしっくりくるんだけどどうだろう？

```suggestion
`then`の処理（UIに反映するための`setTodos`）を、REST APIの呼びだし前に移動しています。
```

2021-06-10 09:09 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/improve-usability.mdx
> +ToDo一覧が表示されたらToDoのチェックボックスをタップして完了状態が更新されるまでの応答速度を改善してみましょう。
```suggestion
次はToDoのチェックボックスをタップしてから、完了状態がUIに反映されるまでの応答速度を改善してみましょう。
```

2021-06-10 09:15 UTC, in-a-paddy approved these changes

2021-06-10 09:16 UTC, tani-takanori approved these changes

2021-06-10 09:16 UTC, merged