Add stack navigator description
ws-4020/mobile-app-crib-notes pull request #267
Opened 2021-06-10 05:44 UTC by nagano-ryo

## ✅ What's done

- [X] 「React Navigationの基本」ページに初期表示画面の説明を追加

## Tests
- [x] npm run lint:text
- [x] npm run lint:md

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-06-10 10:12 UTC, creature-water-valley commented on docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
> +`Navigator`で最初に定義した画面コンポーネントが初期表示される画面です。
`Navigator`⇨`Root.Navigator`のほうが正確で良い気がします。
公式のドキュメントは、同じような記載で書かれているので。
https://reactnavigation.org/docs/stack-navigator/#props

2021-06-10 10:16 UTC, creature-water-valley commented on docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
> +:::note
なんとなく、Noteの位置がソースコードの上ではなく、下に配置したほうがしっくりくるような気がしましたがどうでしょう？
他のページもそうなってたような気がしました。

2021-06-10 11:56 UTC, in-a-paddy commented on docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
> +`Navigator`で最初に定義した画面コンポーネントが初期表示される画面です。
書き方としてはそっちのほうが良さそう。Noteが上にあると、Navigatorって書いてもRoot.Navigatorって書いても唐突感があるから、下のほうがいいね。

2021-06-10 11:57 UTC, in-a-paddy commented on docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
> +:::note
疑問を持つタイミングは、実装してみて動かしてみてからだと思うから、コードの下のほうがいいってのに同意かな

2021-06-11 02:12 UTC, nagano-ryo commented on docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
> +`Navigator`で最初に定義した画面コンポーネントが初期表示される画面です。
NavigatorからRoot.Navigatorへ変更  54208f7fb9e9c8bc5a3ac2f7f8d0b22967549f3b

※別の指摘も含めてコミットしています。「コミットは指摘事項毎に」というお話しを聞く前に修正してしまっていました。以後コミットは指摘事項ごとにします。

2021-06-11 02:14 UTC, nagano-ryo commented on docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
> +:::note
NOTEの位置をソースコードの後に変更 54208f7fb9e9c8bc5a3ac2f7f8d0b22967549f3b

2021-06-11 04:44 UTC, creature-water-valley commented on docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
> +初期表示画面を指定する場合は、`Navigator`の`initialRouteName`属性に画面コンポーネントを指定します。
```suggestion
初期表示画面を指定する場合は、`Root.Navigator`の`initialRouteName`属性に画面コンポーネントを指定します。
```

2021-06-11 08:07 UTC, creature-water-valley approved these changes

2021-06-11 08:46 UTC, in-a-paddy requested changes

2021-06-11 08:46 UTC, in-a-paddy commented on docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
> +初期表示画面を指定する場合は、`Root.Navigator`の`initialRouteName`属性に画面コンポーネントを指定します。
`initialRouteName`は`name`属性の値を設定するはずでは？文章も少し見直してみたけど、どうだろうか。あまりしっくり来ていないかも、、、

```suggestion
`Root.Navigator`の`initialRouteName`属性に画面名（`Root.Screen`の`name`属性の値）を指定すると、対応する画面が初期表示画面になります。指定しない場合は、最初の`Root.Screen`が初期表示に利用されます。
例えば上のソースコードでは、最初の`Root.Screen`である`Screen1`が初めに表示されます。
```

2021-06-15 09:19 UTC, in-a-paddy approved these changes

2021-06-15 09:19 UTC, merged