📝: モバイルアプリケーション開発 学習コンテンツのLP
ws-4020/mobile-app-crib-notes pull request #269
Opened 2021-06-10 14:32 UTC by OshitaTatsuya

## ✅ What's done

- [x] 素案を考え、作成
- [ ] 他のLPを参考に内容のブラッシュアップ

## ⏸ What's not done

- 本当にざっくりした内容の為、共有レベル（レビューできる内容ではない）です。
途中で意見をもらうのと、もう少し考えて内容をブラッシュアップ

---

## Tests

- [x] npm run lint -s

## Other (messages to reviewers, concerns, etc.)
なし

2021-06-11 00:54 UTC, tani-takanori commented
`learn-react-native-landing-page` とかじゃだめかしら？
すくなくともモバイルアプリっていう範囲はリファレンス側だと思うのでReact Nativeでアプリ開発をするんだけど、React Nativeの経験がない人向けだと思う。

ハンズオンにフォーカスしたLPより、React Nativeよくわからん人向けにしたほうがいいのかな？
 - React Nativeを採用している理由（学習コンテンツを利用する意味）
 - React Native開発のための環境構築
 - （Expoにここで触れるか微妙だけど）Project作成のテンプレートをつかって実装しながら学習できる

2021-06-14 05:08 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +アプリの実装自体の学習コストは低いものの、アプリ開発のスタートするには学習しないといけないことがあります。
```suggestion
アプリの実装はReactに近いため学習コストは低いものの、アプリを開発するときにチームメンバーである開発者全員が理解しないといけないこと（Reactの開発と大きく異なるポイント）があります。
```

2021-06-14 05:08 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +- React Nativeでの開発環境を構築方法は何を参照するか
```suggestion
- React Nativeでの開発環境はどうやって構築すればよいか
```

2021-06-14 05:08 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +- アプリの動作確認はどうやるのか
```suggestion
- 開発中のアプリをどうやって動作確認するのか
```

2021-06-14 05:08 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +簡易アプリを作成しながら学習できる内容となっています。
```suggestion
実際に「ToDoアプリ」というシンプルなアプリを手を動かしながら作成し、React Nativeについて学習できます。
```

ハンズオンって手を動かしてる感あるっけ？

2021-06-14 08:23 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +モバイルアプリケーションを開発しようするとき、Reactの経験が多い組織、チームであればReact Nativeを採用して学習コストを抑えてすぐに開発できることが期待できます。
結構唐突な感じがするけどどうですかね？

2021-06-14 08:23 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +公開するコンテンツでは、事前に学習しておいてもらいたい内容を紹介しています。
```suggestion
公開しているコンテンツでは、事前に学習しておいてもらいたい内容を紹介しています。
```

2021-06-14 08:28 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +学習を進める前の前提知識の紹介となるので、コンテンツの理解がより進むと考えている為、一度目を通してみてください。
```suggestion
公開しているコンテンツでは、React Nativeの学習の前に理解しておいたほうがよい内容(JavaScriptやReactなど)も紹介しています。
学習を進めるための[前提知識](link)なので、React Nativeの学習をする前に確認してもらい、自信がなければ紹介しているサイトを参照して事前知識を理解してみてください。
```

2021-06-14 08:29 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +以降では実際に「ToDoアプリ」というシンプルなアプリを手を動かしながら作成し、学習できます。
react native のコンポーネントとか、React Navigationがあったはず…

2021-06-15 02:03 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +以降では実際に「ToDoアプリ」というシンプルなアプリを手を動かしながら作成し、学習できます。
不足している点を踏まえて、学習コンテンツの流れにあわせて説明内容を修正 a8ebb891b11b5b7f79bcb8e59c0665dff8d61be3

2021-06-15 09:17 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +モバイルアプリケーションを開発しようするとき、Reactの経験が多い組織、チームであればReact Nativeを採用して学習コストを抑えてすぐに開発できることが期待できます。
どういったコンテンツかを紹介する一文を追加 2efa1cbd7208803b102914ca3a0c959bceb7bf9c

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +モバイルアプリケーションを開発しようするとき、Reactの経験が多い組織、チームであればReact Nativeを採用して学習コストを抑えてすぐに開発できることが期待できます。
```suggestion
モバイルアプリケーションを開発しようするとき、Reactの経験が多い組織やチームであれば、React Nativeを採用して学習コストを抑えてすぐに開発できることが期待できます。
```

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +アプリの実装はReactに近いため学習コストは低いものの、アプリを開発するときにチームメンバーである開発者全員が理解しないといけないこと（Reactの開発と大きく異なるポイント）があります。
```suggestion
アプリの実装はReactに近いので学習コストは低くなりますが、ReactでのWebアプリの開発とは異なるポイントがあります。
```

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +- React Nativeでの開発環境はどうやって構築すればよいか
```suggestion
- React Nativeでのアプリ開発環境はどうやって構築すればよいか
```

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +- プロジェクトの初期セットアップはどうするか（Reactであれば`create-react-app`のようなことはできないのか）
ここは落としたいかなぁ（レベル2とは言えないかな）

```suggestion
```

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +- Reactでアプリケーションを実装する場合と比べて大きな違いはあるか
```suggestion
- ReactでWebアプリを実装する場合と比べて大きな違いはあるか
```

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +Reactの公式サイトにあるチュートリアルのようなガイドがなく、環境構築でつまづくことも多いです。そのためReact Nativeを利用したことがない開発者の方でもアプリを作成して学習できるコンテンツを公開しています。
```suggestion
そのため、React Nativeを利用したことがない方向けに、実際にアプリを作成して学習できるコンテンツを公開しています。
```

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +以降では、実際に「ToDoアプリ」というシンプルなアプリを手を動かしながら作成して学習できます。
順番違う感じがする。「環境構築」→「React Native/React Navigation」→「ToDoアプリ」

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +- React Navigationのテクニカルな画面遷移（ネストした遷移等）の学習が難しい為、それぞれのパターン毎に説明する
「テクニカルな」がちょっとわからないな

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +- React Navigationのテクニカルな画面遷移（ネストした遷移等）の学習が難しい為、それぞれのパターン毎に説明する
「学習できる内容となっています」なので、それぞれの項目が「説明する」ってなってるのははちょっと変かなと思った

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +このコンテンツの学習に必要な期間はReact Nativeを利用した開発経験の有無で変わってきます。
ReactでのWebアプリ開発の知識がある程度ということは伝えたほうが良いかも。初めての人は、[SPA + REST API構成のサービス開発リファレンス](https://fintan.jp/?p=5952)の「ハンズオンコンテンツ」に誘導してもいいのかな、と。

2021-06-15 09:45 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +[モバイルアプリケーション開発学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
```suggestion
[React Native学習用コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
```

2021-06-16 03:02 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +以降では、実際に「ToDoアプリ」というシンプルなアプリを手を動かしながら作成して学習できます。
内容を見直し、説明の順序を修正 9bb3043d5a0f925b978b85902453f9a2deeb0131

2021-06-16 04:37 UTC, creature-water-valley commented on landing-page/learn-react-native-lp.md
> +モバイルアプリケーションを開発しようするとき、Reactの経験が多い組織やチームであれば、React Nativeを採用して学習コストを抑えてすぐに開発できることが期待できます。
```suggestion
モバイルアプリケーションを開発しようとするとき、Reactの経験が多い組織やチームであれば、React Nativeを採用して学習コストを抑えてすぐに開発できることが期待できます。
```

2021-06-16 04:46 UTC, creature-water-valley commented on landing-page/learn-react-native-lp.md
> +- フックを利用したStateの管理方法が難しい為、それぞれのフック毎のState管理方法
> それぞれのフック毎のState管理方法

それぞれのフックって何を指してるいるのかちょっとわかりませんでした

2021-06-16 04:51 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +- React Navigationのテクニカルな画面遷移（ネストした遷移等）の学習が難しい為、それぞれのパターン毎に説明する
曖昧な表現（テクニカルな）の修正 243a49db2ba6649d68949c8a31f406579c7a34f2

2021-06-16 05:49 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +[モバイルアプリケーション開発学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
もらった案から少しだけ変えて修正 b3e29929c52d4cbbcaa8040e3baf921493baeed5

2021-06-16 05:51 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +このコンテンツの学習に必要な期間はReact Nativeを利用した開発経験の有無で変わってきます。
前提の知識、SPAの紹介と想定期間はSPAの学習期間を含んでいないことを追加 b3e29929c52d4cbbcaa8040e3baf921493baeed5

2021-06-16 05:53 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +- フックを利用したStateの管理方法が難しい為、それぞれのフック毎のState管理方法
曖昧な表現部分を修正 b3e29929c52d4cbbcaa8040e3baf921493baeed5

2021-06-16 06:28 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +- プロジェクトの初期セットアップはどうするか（Reactであれば`create-react-app`のようなことはできないのか）
記載不備箇所の修正 24290a42b45f479c20ba9d11494df568a45819ef

2021-06-16 06:28 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +モバイルアプリケーションを開発しようするとき、Reactの経験が多い組織やチームであれば、React Nativeを採用して学習コストを抑えてすぐに開発できることが期待できます。
記述不備 24290a42b45f479c20ba9d11494df568a45819ef

2021-06-16 09:25 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +React Nativeでの開発を学習する中で、特に経験の浅い方が理解するのに難しかったと感じたReact Native ComponentsとNavigationの部分をより深堀して説明しています。
見出しがないと何を（前提知識についての）説明か分かりづらいと思います

2021-06-16 09:25 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +学習内容の他に実際にこのコンテンツを利用して学習した際に挙がったFAQ（[ハマりがちな落とし穴](https://ws-4020.github.io/mobile-app-crib-notes/react-native/common-pitfalls)）を紹介しています。
このコンテンツは学習コンテンツのことですが、ハマりがちな落とし穴自体は学習コンテンツとは関係なくUpdateされるはずなので、実際にReact Nativeを利用して開発したときにでいいと思います。

2021-06-17 02:25 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +本コンテンツはReact Nativeを利用した開発方法をハンズオン形式で学習できる内容を紹介します。
曖昧かつ間違った紹介を修正 391e459cbadc803f4f6119af9c0c56f53fc13a3f

2021-06-17 02:50 UTC, nagano-ryo commented on landing-page/learn-react-native-lp.md
> +ハンズオン形式のアプリケーション実装の学習前に前提知識として理解しておいたほうがよい内容（JavaScriptやReactなど）を紹介しています。
冒頭で「はじめに、React Nativeを～」と「はじめに」があるので、
「学習前に前提知識として」の前に「次に」などコンテンツの流れがわかる文言があっても良いと思ました。

2021-06-17 02:53 UTC, nagano-ryo commented on landing-page/learn-react-native-lp.md
> +
「実際の開発経験で理解が難しかったと感じた～」は「React Nativeの経験の浅い人」でしょうか？
それとも「学習コンテンツ完了後のある程度経験の人」でしょうか？

2021-06-17 03:01 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +React Nativeでの開発を学習する中で、特に経験の浅い方が理解するのに難しかったと感じたReact Native ComponentsとNavigationの部分をより深堀して説明しています。
紹介内容を明確にする為、見出しを付けるのと内容の修正 c1bcc86dd9b3b750ef2f438e8afb038921dbcb57

2021-06-17 05:23 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +学習内容の他に実際にこのコンテンツを利用して学習した際に挙がったFAQ（[ハマりがちな落とし穴](https://ws-4020.github.io/mobile-app-crib-notes/react-native/common-pitfalls)）を紹介しています。
FAQの紹介内容を修正 3d15abc2606e6d0f025f3be960c2b800d934a9d8

2021-06-17 05:40 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +## はじめに
「はじめに」の導入はもう少し前提から入ったほうがいいと思います。
（セキュリティのやつみたいに）

2021-06-17 05:42 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +ハンズオン形式のアプリケーション実装の学習前に前提知識として理解しておいたほうがよい内容（JavaScriptやReactなど）を紹介しています。
章構成を含めて、該当箇所の文章を修正 3d15abc2606e6d0f025f3be960c2b800d934a9d8

2021-06-17 05:43 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +
理解が難しかったのは、`React Nativeの経験の浅い人`なので、明確になるよう修正 3d15abc2606e6d0f025f3be960c2b800d934a9d8

2021-06-17 05:51 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +React Nativeを利用したモバイルアプリケーション開発が学習できるコンテンツを公開します。
「はじめに」の導入はもう少し前提から入ったほうがいいと思います。
（セキュリティのやつみたいに）

2021-06-17 05:51 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +
ハンズオン形式でアプリケーション開発がない？

2021-06-17 05:51 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +
開発環境の構築方法もないのか

2021-06-17 05:51 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +はじめに、React Nativeを利用した開発環境の構築から進めていきます。
学習できる内容が省かれているからか、親の見出しと合わない感じがしないですか？

2021-06-17 05:51 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +## コンテンツで学習できる内容
## コンテンツで学習できる内容

### React Nativeで作成したアプリの動作確認方法

GettingStarted なので環境構築とかふくむかな？

### React Nativeの前提知識

${### 前提知識に書かれている内容}

### サンプルアプリ作成をテーマとした学習

${###サンプルアプリ作成をテーマとした学習に書かれている内容}

### 学習の進め方

いるかな？

2021-06-17 05:51 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +## React Native学習コンテンツ
見出しと内容があってないと思います。

2021-06-17 08:26 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +React Nativeを利用したモバイルアプリケーション開発が学習できるコンテンツを公開します。
モバイルアプリ学習コンテンツの前提を追加 6a2aa4ff84ed6b92c6b6e1e11d1389daed461d11

2021-06-17 08:27 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +
概要レベルで把握できるものを追加 6a2aa4ff84ed6b92c6b6e1e11d1389daed461d11

2021-06-17 08:28 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +はじめに、React Nativeを利用した開発環境の構築から進めていきます。
タイトル構成の見直しをして修正 6a2aa4ff84ed6b92c6b6e1e11d1389daed461d11

2021-06-17 08:29 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +## コンテンツで学習できる内容
タイトル構成の見直しと修正（学習の進め方は削除） 6a2aa4ff84ed6b92c6b6e1e11d1389daed461d11

2021-06-17 08:29 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +## React Native学習コンテンツ
内容を見直し修正 6a2aa4ff84ed6b92c6b6e1e11d1389daed461d11

2021-06-17 09:35 UTC, in-a-paddy requested changes

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +
「サンプルアプリとバックエンドの連携方法」は「ハンズオン形式でのサンプルアプリの作成」に含まれそうな

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +
「ReactとReact Nativeの違い」をピックアップして説明しているところってあったっけ？

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +理由としては、ReactとReact Nativeの違いを理解してもらいたい内容を含めているからです。
この行いる？

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +自信のない方は、まず[SPA + REST API構成のサービス開発リファレンス](https://fintan.jp/?p=5952)から学習を進めてみてください。
```suggestion
Reactでの開発経験がない方は、まず[SPA + REST API構成のサービス開発リファレンス](https://fintan.jp/?p=5952)からに含まれるハンズオンコンテンツから学習を始めてみてください。
```

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +[React Native学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
このリンクって、ここではない気がする

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +このコンテンツを学習するのに必要な期間はReact Nativeを利用した開発経験の有無で変わってきます。
コンテンツの対象がReact Nativeの経験が浅い方ならば、経験者の場合の期間は必要ないのでは？？

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +## コンテンツで学習できる内容
個人的には、各章の説明はLPに書くんじゃなくてコンテンツ側に書いてほしい

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +
それぞれの項目と、コンテンツが対応していないように感じるので、対応させたほうが良いのでは？

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +学習を進めるための[前提知識](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/basic-concepts/pre-requisites)なので、React Nativeの学習をする前に確認してもらい、自信がなければ紹介しているサイトを参照して事前知識を理解してみてください。
ここだけはリンクがあるのは変な感じ

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +上記の学習期間に、[SPA + REST API構成のサービス開発リファレンス](https://fintan.jp/?p=5952)の学習期間は含んでいません。
そりゃ含まないだろ、って思うので書かなくてもいいんじゃないかなぁ。

2021-06-17 09:35 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +React Nativeを利用して開発を進める中で挙がったFAQ（[ハマりがちな落とし穴](https://ws-4020.github.io/mobile-app-crib-notes/react-native/common-pitfalls)）を紹介しています。
URLは全体的に後でfintan-contentsに向けると思うので忘れないようにお願いします。

2021-06-17 11:36 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +## コンテンツで学習できる内容
LP側では章と簡単な見出しの説明へ修正 3083ee35296b847237685a854647d0d99baf77ee

2021-06-17 11:37 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +理由としては、ReactとReact Nativeの違いを理解してもらいたい内容を含めているからです。
内容を見直して不要な説明を削除 3083ee35296b847237685a854647d0d99baf77ee

2021-06-17 11:37 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +自信のない方は、まず[SPA + REST API構成のサービス開発リファレンス](https://fintan.jp/?p=5952)から学習を進めてみてください。
3083ee35296b847237685a854647d0d99baf77ee

2021-06-17 11:39 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +学習を進めるための[前提知識](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/basic-concepts/pre-requisites)なので、React Nativeの学習をする前に確認してもらい、自信がなければ紹介しているサイトを参照して事前知識を理解してみてください。
コンテンツ側の一部説明の修正。LP側はポイントを紹介するレベルへ修正 3083ee35296b847237685a854647d0d99baf77ee

2021-06-17 11:42 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +React Nativeを利用して開発を進める中で挙がったFAQ（[ハマりがちな落とし穴](https://ws-4020.github.io/mobile-app-crib-notes/react-native/common-pitfalls)）を紹介しています。
忘れないよう、What's doneへ追加

2021-06-17 11:42 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +上記の学習期間に、[SPA + REST API構成のサービス開発リファレンス](https://fintan.jp/?p=5952)の学習期間は含んでいません。
過剰な説明を削除 3083ee35296b847237685a854647d0d99baf77ee

2021-06-17 12:30 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +[React Native学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
学習コンテンツ紹介場所の修正 3acc053dcd1afbfe6f3c2b7ffa8c016022c8df95

2021-06-18 00:47 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +React Nativeを利用して開発を進める中で挙がったFAQ（[ハマりがちな落とし穴](https://ws-4020.github.io/mobile-app-crib-notes/react-native/common-pitfalls)）を紹介しています。
タスクに詰んでるよ。

2021-06-18 00:56 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +そこで、React Nativeを利用したモバイルアプリケーション開発が学習できるコンテンツを公開します。
```suggestion
Reactを利用したWebアプリを開発してきた開発者がガイドにそってReact Nativeを利用したモバイルアプリケーション開発が学習できるコンテンツを公開しています。
```

「はじめに」って前置きしようとして書くことがないところを無理やりだすなら省略してしまっていいんじゃないですか？

2021-06-18 02:21 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +
コンテンツ内容の紹介を整理（コンテンツのどの部分を指しているかを明確にする）して修正 3083ee35296b847237685a854647d0d99baf77ee

2021-06-18 02:22 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +React Nativeを利用して開発を進める中で挙がったFAQ（[ハマりがちな落とし穴](https://ws-4020.github.io/mobile-app-crib-notes/react-native/common-pitfalls)）を紹介しています。
ありがとうございます。What's doneから消しました

2021-06-18 02:44 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +上記の学習期間に、[SPA + REST API構成のサービス開発リファレンス](https://fintan.jp/?p=5952)の学習期間は含んでいません。
不要な記載を削除し、説明を修正 29ae530e570f2ecfb4067d788d17609e4d4ed145

2021-06-18 02:46 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +そこで、React Nativeを利用したモバイルアプリケーション開発が学習できるコンテンツを公開します。
はじめにと余計な前置き説明を削除 29ae530e570f2ecfb4067d788d17609e4d4ed145

2021-06-18 02:47 UTC, in-a-paddy commented on docs/react-native/learn/todo-app.md
> +経験の浅い方で理解が難しいと感じた以下の点をより詳しく説明しています。
「経験の浅い方で」というより「私たちが」とかにしたらどうだろう？実際、自分たちが難しいと思ったし。

2021-06-18 02:47 UTC, in-a-paddy commented on docs/react-native/learn/todo-app.md
> +経験の浅い方で理解が難しいと感じた以下の点をより詳しく説明しています。
「Webベースのハンズオンを参照し」の後に書いてあるからか、Webベースのハンズオンの方で学習できる内容に見えたりしている。
箇条書きにするんじゃなくて、PageListの中で説明したらどうかな？

2021-06-18 02:47 UTC, in-a-paddy commented on docs/react-native/learn/basic-concepts.mdx
> +学習を進めるための前提知識なので、React Nativeの学習をする前に確認してもらい、自信がなければ以下を参照して事前知識を深めてください。
「React Nativeの学習をする前に確認してもらい、自信がなければ以下を参照して事前知識を深めてください。」
ちょっとアクションのイメージがわきにくいかな、と。

2021-06-18 02:47 UTC, in-a-paddy commented on landing-page/learn-react-native-lp.md
> +このコンテンツを学習するのに必要な期間はReact Nativeを利用した開発経験の有無で変わってきます。未経験者（経験の浅い方含む）の方でおおよそ5日程度必要となります。
```suggestion
このコンテンツを学習するのに必要な期間はReact Nativeを利用した開発経験の有無で変わってきます。未経験の方でおおよそ5日程度必要となります。
```

2021-06-18 06:30 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app.md
> +経験の浅い方で理解が難しいと感じた以下の点をより詳しく説明しています。
説明ポイントが前段の説明を踏まえて混乱する為、ポイントと内容を修正 1a8402258f6a196e8559c67cf006b722750133af

2021-06-18 06:56 UTC, OshitaTatsuya commented on docs/react-native/learn/basic-concepts.mdx
> +学習を進めるための前提知識なので、React Nativeの学習をする前に確認してもらい、自信がなければ以下を参照して事前知識を深めてください。
事前知識の説明が前提知識のページでもしているので、内容を修正（元に戻す） 1281dd381edf9f07e09e81bc4e2bd70ee3fad313

2021-06-18 06:56 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +このコンテンツを学習するのに必要な期間はReact Nativeを利用した開発経験の有無で変わってきます。未経験者（経験の浅い方含む）の方でおおよそ5日程度必要となります。
必要期間の説明を修正 1281dd381edf9f07e09e81bc4e2bd70ee3fad313

2021-06-18 08:15 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +[React Native学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
このリンクを一番上の文章に入れられないかな？

`Reactを利用したWebアプリの開発経験者がReact Nativeを利用したモバイルアプリケーション開発を学習するための[モバイルアプリケーション開発の学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)を公開しています。`

2021-06-18 08:28 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +[React Native学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
最初の部分でコンテンツを紹介するよう修正（周辺の不備箇所も併せて修正） a53c6303ff856b2ac5b453fcf1db3aa0684d9964

2021-06-18 09:48 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +- [アプリの実装前](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/basic-concepts)
誤りなので取り込みました

2021-06-18 10:06 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +[React Native学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
リンクとh1ヘッダは合わせて欲しいです

2021-06-18 10:09 UTC, tani-takanori commented on landing-page/learn-react-native-lp.md
> +公開するコンテンツでは、次のことが学習できます。
```suggestion
公開しているコンテンツでは、次のことが学習できます。
```

2021-06-18 10:09 UTC, OshitaTatsuya commented on landing-page/learn-react-native-lp.md
> +[React Native学習コンテンツ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn)
ヘッダとリンクの修正 881ee58f0b42868d73474db3927d89af521969d3

2021-06-18 10:11 UTC, in-a-paddy approved these changes

2021-06-18 10:12 UTC, tani-takanori approved these changes

2021-06-18 10:20 UTC, merged