🖋: アプリの実行と仕組みを同じような分け方で記載する
ws-4020/mobile-app-crib-notes pull request #297
Opened 2021-06-15 09:08 UTC by tani-takanori

## 💣 BREAKING CHANGES 💣

- 破壊的な変更を箇条書きで記載してください
- 変更内容と変更理由を、わかりやすく記載してください
- なければ、このセクション（先頭行から「## ✅ What's done」の前の行まで）を削除してください

## ✅ What's done

- [x] アプリの実行の仕組みをアプリの実行に合わせる形で修正
- [x] 画像も分けておく

---

## Other (messages to reviewers, concerns, etc.)

https://github.com/ws-4020/mobile-app-crib-notes/issues/281

2021-06-15 09:27 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +    {label: 'Expo Go', value: 'expo-build'},
これ、valueを上と合わせたらどう？

2021-06-16 00:20 UTC, tani-takanori commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +    {label: 'Expo Go', value: 'expo-build'},
value合わせると初期表示がおかしくなると思ってたけど、初期値変えてないのが原因だったので対応しました。

d301009b38d552f24f5edb7c75b1a2564a52bbfb

2021-06-16 02:48 UTC, in-a-paddy requested changes

2021-06-16 02:48 UTC, in-a-paddy commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +Expo Goを利用する場合、ストア公開されているExpo Goアプリを端末にインストールして使用するため、アプリのビルドが不要です。
```suggestion
Expo Goを利用する場合、ストア公開されているExpo Goアプリを端末にインストールして使用するため、アプリのビルドは不要です。
```

2021-06-16 04:27 UTC, creature-water-valley commented
> アプリ実行の仕組みについて、アプリ実行コマンドの前に説明があると嬉しいと感じました
これが、対応されてないような？

2021-06-16 05:39 UTC, tani-takanori commented
> > アプリ実行の仕組みについて、アプリ実行コマンドの前に説明があると嬉しいと感じました
> 
> これが、対応されてないような？

対応しました

2021-06-16 07:06 UTC, creature-water-valley commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +iOSアプリがビルドされ、シミュレータにインストールされます。
前の行でアプリが起動しますと言っているので、既にシミュレータにはインストールされているのでは？

2021-06-16 07:09 UTC, creature-water-valley commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +Androidアプリがビルドされ、エミュレータにインストールされます。
iPhoneシミュレータの場合と微妙に書きっぷりが違うような。
シミュレータとエミュレータの違いしかないかと思われるので、それ以外は同じにしたほうが良いかなと思いました

2021-06-16 07:22 UTC, tani-takanori commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +Androidアプリがビルドされ、エミュレータにインストールされます。
書きっぷり合わせる
https://github.com/ws-4020/mobile-app-crib-notes/pull/297/commits/c13e3ff0e35d5a141102a022602fc6f99d4c1c35

2021-06-16 07:23 UTC, tani-takanori commented on docs/react-native/learn/getting-started/launch-created-app.mdx
> +iOSアプリがビルドされ、シミュレータにインストールされます。
順番がおかしい箇所を修正して、書きっぷりをあわせる

https://github.com/ws-4020/mobile-app-crib-notes/pull/297/commits/c13e3ff0e35d5a141102a022602fc6f99d4c1c35

2021-06-16 07:32 UTC, creature-water-valley approved these changes

2021-06-17 04:20 UTC, in-a-paddy approved these changes

2021-06-17 04:20 UTC, merged