✨: ToDo毎にブロックするように修正する
ws-4020/mobile-app-crib-notes pull request #308
Opened 2021-06-17 05:17 UTC by tani-takanori

## ✅ What's done

- [x] ToDoごとに操作をブロックする実装を追加
- [x] ガイドを修正

---

## Tests

- [ ] ガイド通りに実装できるかの検証

## Devices

- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

https://github.com/ws-4020/mobile-app-crib-notes/issues/290

2021-06-17 06:46 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +ここではチェックボックスをタップされたToDoだけを処理中のUIに変更し、操作をブロックしてみましょう。
```suggestion
ここではチェックボックスがタップされたToDoだけを処理中のUIに変更し、操作をブロックしてみましょう。
```

2021-06-17 06:46 UTC, OshitaTatsuya commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +タップしたToDoの完了状態がすぐに反映されることが確認できます。
```suggestion
タップしたToDoがブロックされていて、完了状態がすぐに反映されることが確認できます。
```

2021-06-17 07:05 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +タップしたToDoの完了状態がすぐに反映されることが確認できます。
`タップしたToDoがブロックされ処理が完了するまで操作できないことが確認できます。` でいいですか？

2021-06-17 07:09 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> ++  removeTodo,
`Props`に定義されてない`removeTodo`が突如出現

2021-06-17 07:14 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +`TodoList.tsx`でも`TodoItem`にprocessingを渡すようにします。
`TodoList.tsx`を修正するような誘導に見えますが、コード例は`TodoItem.tsx`の修正になっていて少しわかりづらい気がします。

2021-06-17 07:18 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +まずは`TodoBoard.tsx`から`TodoList.tsx`に処理中のToDoのIDのリスト（`processingTodos`）を渡します。
`TodoBoard.tsx`を修正するように見えますが、コード例は`TodoList.tsx`の修正になっていて少しわかりづらい気がします。

2021-06-17 07:42 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +まずは`TodoBoard.tsx`から`TodoList.tsx`に処理中のToDoのIDのリスト（`processingTodos`）を渡します。
8361ad8a8b627a08f166974a831318c2e430e4dd

2021-06-17 07:42 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +`TodoList.tsx`でも`TodoItem`にprocessingを渡すようにします。
8361ad8a8b627a08f166974a831318c2e430e4dd

2021-06-17 08:53 UTC, creature-water-valley commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +処理中のToDoのIDを管理できたので、処理中の状態を判断できるように`TodoList.tsx`、`TodoItem`を修正します。
```suggestion
処理中のToDoのIDを管理できたので、処理中の状態を判断できるように`TodoList.tsx`、`TodoItem.tsx`を修正します。
```

2021-06-17 09:12 UTC, in-a-paddy requested changes

2021-06-17 09:12 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +title: ブロックする範囲を限定する
タイトルに違和感あるかな。もともとブロックしていた範囲を狭くするわけではないので。
「REST API呼びだし中の表示」の方もタイトル変えて、「ToDo一覧取得中の表示」と「ToDo更新中の表示」とかでどうだろうか

2021-06-17 09:12 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +次はToDoのチェックボックスをタップしてから、完了状態がUIに反映されるまでインジケータを表示し、ブロックしてみましょう。
「完了状態がUIに反映されるまで」ってちょっとわかりにくいかな、と。
更新APIを呼び出している間は表示する、ってことだと思う。

2021-06-17 09:12 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +受け取るパラメータ（`Props`）に`processing`を追加してインジケータと、ToDoの操作ブロックするViewを表示できるようにしましょう。
表示できるようにする、ってのとはちょっと違うかなと思った

```suggestion
受け取るパラメータ（`Props`）に`processing`を追加して、`ToDoItem`で表示しているToDoが処理中かどうかを判断できるようにしましょう。
```

2021-06-17 09:12 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +アクティビティインジケータと操作ブロック用のViewを表示できるよう、次のように修正してください。
```suggestion
次のように修正して、ToDoが処理中の場合だけアクティビティインジケータと操作ブロック用のViewを表示しましょう。
```
他と温度感変わっちゃうかな？

2021-06-17 09:34 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +次はToDoのチェックボックスをタップしてから、完了状態がUIに反映されるまでインジケータを表示し、ブロックしてみましょう。
fd072fabea5cc4769cf561efe60fea634bcd3dde

2021-06-17 09:34 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +title: ブロックする範囲を限定する
fd072fabea5cc4769cf561efe60fea634bcd3dde

2021-06-17 09:39 UTC, in-a-paddy requested changes

2021-06-17 09:39 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> +次はToDoのチェックボックスがタップされたら、更新APIを呼び題している間はインジケータを表示し、ブロックしてみましょう。
```suggestion
次はToDoのチェックボックスがタップされたら、更新APIを呼びだしている間はインジケータを表示し、ブロックしてみましょう。
```

2021-06-18 00:03 UTC, creature-water-valley approved these changes

2021-06-18 02:12 UTC, in-a-paddy approved these changes

2021-06-18 02:12 UTC, merged