Push通知用の設定の追加
ws-4020/mobile-app-crib-notes pull request #32
Opened 2021-02-08 07:17 UTC by tani-takanori

## ✅ What's done

- [x] 依存関係の追加 
- [x] .gitignoreに設定用のファイルを追加

## ⏸ What's not done

- [ ] 実際の手順の簡素化

---

## Tests

- [ ] Firebaseの設定を追加後のAndroid、iOSでの起動確認
- [ ] expoでの動作確認

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

何かあれば記載してください。
なければ「なし」と記載してください。

2021-02-09 01:47 UTC, in-a-paddy requested changes

2021-02-09 01:47 UTC, in-a-paddy commented on santoku-app/android/app/build.gradle
> +// apply plugin: 'com.google.gms.google-services'
単純にコメントアウトされてるだけだと気になっちゃうので、何かしら補足コメント欲しい

2021-02-09 01:47 UTC, in-a-paddy commented on santoku-app/android/build.gradle
> +//      classpath('com.google.gms:google-services:4.3.3')
単純にコメントアウトされてるだけだと気になっちゃうので、何かしら補足コメント欲しい

2021-02-09 01:47 UTC, in-a-paddy commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
`project.pbxproj`の変更がPRに含まれてない気がするけど、大丈夫？

2021-02-09 01:51 UTC, kz-takahashi approved these changes

2021-02-09 01:55 UTC, tani-takanori commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
READMEの手順（iOSの場合にFirebaseConsoleから取得したGoogleService-Info.plistをAdd Fileする)で変更が入るので大丈夫です。
（と思ったけど、`clone` じゃなくてDownloadで作成した場合に戻せないな...）

2021-02-09 01:57 UTC, in-a-paddy commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
`project.pbxproj`の変更をそのままにしておけば、ダウンロードしたファイル（`GoogleService-Info.plist`, `google-service.json`）を配置するだけで動くようにできないかな？Gradle側にももしかしたらある程度修正いるかもだけど。

2021-02-09 02:06 UTC, tani-takanori commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
そうすると `GoogleService-Info.plist` がないとSantokuAppが起動できないんじゃないかな？と思って入れてないんですよね。
SantokuAppはFCMでアプリ作成することを前提にします？？

2021-02-09 02:06 UTC, tani-takanori commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
エラーハンドリング追加したらイケるのかな？？
ちょっとやってみます。

2021-02-09 02:07 UTC, in-a-paddy commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
そうかそうか、、、
`PersonalAccount.xcconfig.template`/`PersonalAccount.xcconfig`と同じ扱いをしないといけないってことね、、、

2021-02-09 02:08 UTC, in-a-paddy commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
あったら読み込む、みたいなことができればいいんだけど、、、

2021-02-09 02:15 UTC, tani-takanori commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
`Podfile.lock` もcommitしちゃえば、依存するファイルはあるから、`AppDelegate.m` で `Firebase.h` はimportして
configure(ここで`Info.plist`見にいくはず)でコケた場合にハンドリングするロジック入れちゃえばいいのかな？？

2021-02-09 05:08 UTC, tani-takanori commented on santoku-app/android/app/build.gradle
> +// apply plugin: 'com.google.gms.google-services'
そもそもplugin自体は有効にしてOKなのでコメントアウトを外す

2021-02-09 05:08 UTC, tani-takanori commented on santoku-app/android/build.gradle
> +//      classpath('com.google.gms:google-services:4.3.3')
依存はあっていいのでコメントアウトを外す

2021-02-09 05:09 UTC, tani-takanori commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
ダミーの`GoogleService-Info.plist` を配置するように修正

2021-02-09 05:21 UTC, in-a-paddy commented on santoku-app/README.md
> +漏れている場合は一度 `project.pbxproj` ファイルの変更を戻してから`GoogleService-Info.plist` を再度追加してください。
> ローカルに未コミットの修正が残る状態で開発はしたくないなぁ、と。

こいつはやっぱり嫌なので、`GoogleService-Info.plist`自体はコミットしない方針で。

こんな感じにすれば何とかまとまる気がする。

1. ダミーの`GoogleService-Info.plist`は`GoogleService-Info.dummy.plist`みたいな感じでコミットしておく
2. [READMEの環境構築手順](https://github.com/ws-4020/mobile-app-crib-notes/tree/master/santoku-app#apple-id%E3%81%AE%E8%A8%AD%E5%AE%9A)にダミーをコピーする手順を追加
3. 「Push通知の設定」は、現状では、READMEにリンクはなしにしておく。
    - 「サーバ環境を用意する」みたいな手順にして、最終的にcrib-notesにリンク張る感じになるといいかな、と。
    - そこにCognitoの設定やAzure Funtionsの準備に関しても書いておけば、ちゃんと収まる気がする。

2021-02-10 00:47 UTC, in-a-paddy requested changes

2021-02-10 10:19 UTC, in-a-paddy approved these changes

2021-02-10 10:19 UTC, merged