🌱: code-blockでも置き換えられるように実装してみる
ws-4020/mobile-app-crib-notes pull request #323
Opened 2021-06-22 06:52 UTC by tani-takanori

## ✅ What's done

- [x] `{@inject: ${key}}` で置き換えられるようにプラグインを作成
- [ ] buildしてみて`master` 差分を確認する

---

- [ ] 壊れてないか確認

## Other (messages to reviewers, concerns, etc.)

なし

2021-06-22 08:47 UTC, in-a-paddy requested changes

2021-06-22 08:47 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +import {RepositoryLink} from '../../../../../src/components';
`RepositoryLink`もまだ使い続ける？

2021-06-22 08:47 UTC, in-a-paddy commented on docusaurus.config.js
> +    let replaced = value;
わかんないけど`reduce`できそう

2021-06-22 09:54 UTC, tani-takanori commented on docusaurus.config.js
> +    let replaced = value;
function replace(value) {
    return keys.reduce((replaced, key) => {
      return replaced.replace(key, options[key]);
    }, value);
  }

2021-06-22 09:54 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/generate-api-client.mdx
> +import {RepositoryLink} from '../../../../../src/components';
使い続けます...

2021-06-23 00:02 UTC, creature-water-valley approved these changes

2021-06-23 00:45 UTC, creature-water-valley commented
あれ、これって`npm start`で起動した場合APIクライアントの作成のページに`{@inject: ws-4020}`で表示されているのはあってるんですか？

2021-06-23 00:49 UTC, in-a-paddy requested changes

2021-06-23 00:49 UTC, in-a-paddy commented on docusaurus.config.js
> +      return replaced.replace(key, options[key]);
`{@inject`とかが残るんじゃね？

2021-06-23 02:16 UTC, creature-water-valley submitted a review, later dismissed

2021-06-23 04:34 UTC, tani-takanori commented
href書き換えやってみたら何故かすんなり行ったのでReopsitoryLinkにも対応

2021-06-23 04:46 UTC, in-a-paddy requested changes

2021-06-23 04:46 UTC, in-a-paddy commented on docusaurus.config.js
> +        tree.properties.href = hasPlaceHolder(href) ? replace(href) : href;
`decodeURI`した後`encodeURI`しなくて大丈夫？

2021-06-23 04:46 UTC, in-a-paddy commented on src/components/RepositoryLink.tsx
> +    projectName ? projectName : siteConfig.projectName
直後が`path ?? ''`だから、`projectName ?? siteConfig.projectName`の方がしっくりくるかな

2021-06-23 04:46 UTC, in-a-paddy commented on src/components/index.ts
> +export * from './RepositoryLink';
使わないのでは？

2021-06-23 04:46 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/welcome.mdx
> +`App.tsx` ファイルを編集している場合は、[プロジェクト作成時のApp.tsx](https://github.com/ws-4020/rn-spoiler/blob/{@inject:rnSpoilerTag}/template/src/App.tsx)の内容に上書きしてからToDoアプリの実装をはじめてください。
ここも`organization`をinjectしてあげてくれw

2021-06-23 04:46 UTC, in-a-paddy commented on docusaurus.config.js
> +  const placeHolders = keys.map((key) => new RegExp('{@inject: ?' + key + '}'));
スペースの数はこだわらなくていいんじゃないかな、って。
```suggestion
  const placeHolders = keys.map((key) => new RegExp('{@inject: *' + key + '}'));
```

2021-06-23 04:46 UTC, in-a-paddy commented on docusaurus.config.js
> +      tree.children = tree.children.map((c) => inject(c));
ただの好みなのかもしれないけど、、、
```suggestion
      tree.children = tree.children.map(inject);
```

2021-06-23 04:46 UTC, in-a-paddy commented on docusaurus.config.js
> +        const href = decodeURI(tree.properties?.href);
ここって`?`つけてあげないとエラーになるかな？`if`でチェックしてるから`undefined`になることはないと思うんだけど。

```suggestion
        const href = decodeURI(tree.properties.href);
```

2021-06-23 04:46 UTC, in-a-paddy commented on docusaurus.config.js
> +    return value.includes('{@inject:');
一応ガードしておきたい気持ち
```suggestion
    return value && value.includes('{@inject:');
```

2021-06-23 04:46 UTC, in-a-paddy commented on src/components/RepositoryLink.tsx
> +    projectName ? projectName : siteConfig.projectName
あ、消すのか。

2021-06-23 04:53 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/welcome.mdx
> +`App.tsx` ファイルを編集している場合は、[プロジェクト作成時のApp.tsx](https://github.com/ws-4020/rn-spoiler/blob/{@inject:rnSpoilerTag}/template/src/App.tsx)の内容に上書きしてからToDoアプリの実装をはじめてください。
あれ？rn-spoilerもfintan持ってっくっけ？

2021-06-23 04:53 UTC, tani-takanori commented on docusaurus.config.js
> +        const href = decodeURI(tree.properties?.href);
encode漏れてたから一緒に直した！

2021-06-23 04:54 UTC, tani-takanori commented on docusaurus.config.js
> +        tree.properties.href = hasPlaceHolder(href) ? replace(href) : href;
だめ！

2021-06-23 04:54 UTC, tani-takanori commented on src/components/index.ts
> +export * from './RepositoryLink';
そうね

2021-06-23 04:58 UTC, in-a-paddy commented on docs/react-native/learn/todo-app/screens/welcome.mdx
> +`App.tsx` ファイルを編集している場合は、[プロジェクト作成時のApp.tsx](https://github.com/ws-4020/rn-spoiler/blob/{@inject:rnSpoilerTag}/template/src/App.tsx)の内容に上書きしてからToDoアプリの実装をはじめてください。
持ってかないw間違えたw

2021-06-23 05:00 UTC, tani-takanori commented on docusaurus.config.js
> +  const placeHolders = keys.map((key) => new RegExp('{@inject: ?' + key + '}'));
1e7b664fb9a5d85044e4620262ca0b30ca9d4c97
出来た...

2021-06-23 05:00 UTC, in-a-paddy commented on docusaurus.config.js
> +        tree.properties.href = encodeURI(hasPlaceHolder(href) ? replace(href) : href);
個人的には、こっちかなぁ、、、変更しない場合にわざわざdecode→encodeするのはちょっと怖い。

```suggestion
if (hasPlaceHolder(href)) {
  tree.properties.href = encodeURI(replace(href))
}
```

2021-06-23 05:00 UTC, tani-takanori commented on docusaurus.config.js
> +        const href = decodeURI(tree.properties?.href);
b78a32a40454af87b9b4197202f04e263eac6d8e

2021-06-23 05:21 UTC, tani-takanori commented on src/components/index.ts
> +export * from './RepositoryLink';
a69c673367c0ea0c2b909d8590968deb1f0952fa

2021-06-23 05:21 UTC, tani-takanori commented on src/components/RepositoryLink.tsx
> +    projectName ? projectName : siteConfig.projectName
a69c673367c0ea0c2b909d8590968deb1f0952fa

2021-06-23 05:53 UTC, in-a-paddy commented on docusaurus.config.js
> +if (hasPlaceHolder(href)) {
インデントが、、、

2021-06-23 05:58 UTC, creature-water-valley approved these changes

2021-06-23 06:13 UTC, tani-takanori commented on docusaurus.config.js
> +if (hasPlaceHolder(href)) {
おれsuggestをcommitしただけだよ...

2021-06-23 06:15 UTC, tani-takanori commented on docusaurus.config.js
> +if (hasPlaceHolder(href)) {
7e61560e839cace097d00a94b6bbbb1986b29b3a

2021-06-23 06:30 UTC, in-a-paddy commented on docusaurus.config.js
> +if (hasPlaceHolder(href)) {
suggestは取り下げたんだけど、修正前だったか。

2021-06-23 06:31 UTC, in-a-paddy approved these changes

2021-06-23 06:31 UTC, merged