🖋: 演習課題をREST APIとの接続の後ろに移動
ws-4020/mobile-app-crib-notes pull request #336
Opened 2021-06-28 06:50 UTC by nagano-ryo

## ✅ What's done

- [x] 「演習課題」を「画面の実装まで」の後ろから「REST APIとの接続」の後ろに移動
- [x] 影響のあるソースコードブロックの修正（演習課題にて実装する内容が含まれていたので削除）

---

## Tests

- [x] npm run lint

## Other (messages to reviewers, concerns, etc.)

なし

2021-06-29 00:39 UTC, tani-takanori requested changes
「演習課題」でgit grepして欲しい

2021-06-29 00:39 UTC, tani-takanori commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> -   onRemove: (id: number) => void;
これ消しちゃだめじゃない？

2021-06-29 06:49 UTC, nagano-ryo commented on docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
> -   onRemove: (id: number) => void;
ご指摘の/src/components/parts/todo/TodoItem.tsxを確認しましたが、ハンズオン実施中に「onRemove: (id: number) => void;」の記述はありませんでした。
REST APIとの接続 - ToDo更新中の表示セクションのソースコードブロックではじめて「onRemove: (id: number) => void;」が登場しています。
そのため削除して問題ない認識です。
（「onRemove: (id: number) => void;」を削除しても動作することを確認済み）

2021-06-29 06:53 UTC, tani-takanori commented
> 「演習課題」でgit grepして欲しい

あれ？これやってる？？

2021-06-29 06:55 UTC, tani-takanori commented
演習課題じゃなくて演習問題じゃん…

2021-06-30 00:34 UTC, tani-takanori reviewed
https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/todo-app/networking/api-request#todoservice%E3%81%AE%E4%BF%AE%E6%AD%A3

2021-06-30 00:46 UTC, nagano-ryo commented
修正内容の認識誤りがありました。
「演習課題」を「ToDoアプリの実装」の末尾に移動（「画面の実装」、「REST APIとの接続」と並ぶように移動）しました。
f9b077871964990f4c7bd3c8532b468d27c61efb

2021-06-30 08:28 UTC, tani-takanori reviewed
演習課題側に「削除API」があることを:note:で伝えたほうがいいかな

2021-06-30 08:55 UTC, tani-takanori requested changes

2021-06-30 08:55 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +削除APIは[APIクライアントの作成](../networking/generate-api-client.mdx)で生成されています。削除APIを`/src/services/TodoService.ts`で呼びだすように修正します。
```suggestion
ToDoの削除API（`TodosApi.deleteTodo `）は[APIクライアントの作成](../networking/generate-api-client.mdx)で生成されています。
```

ヒントとして使うAPIがわかればいいと思います。（他もここで実装しなさいってガイドはしてないと思う）

2021-06-30 09:00 UTC, tani-takanori commented on docs/react-native/learn/todo-app/screens/exercise.mdx
> +ToDoの削除API（`TodosApi.deleteTodo `）は[APIクライアントの作成](../networking/generate-api-client.mdx)で生成されています。
```suggestion
ToDoの削除API（`TodosApi.deleteTodo`）は[APIクライアントの作成](../networking/generate-api-client.mdx)で生成されています。
```

2021-06-30 09:03 UTC, OshitaTatsuya approved these changes

2021-06-30 09:04 UTC, tani-takanori approved these changes

2021-06-30 09:04 UTC, merged