♻: Docusaurus関連のフォルダ構成の変更
ws-4020/mobile-app-crib-notes pull request #348
Opened 2021-07-07 08:54 UTC by nagano-ryo

## ✅ What's done

- [x] Docusaurus関連のフォルダ構成の変更
  - [x] docsフォルダをwebsiteに移動
  - [x] その他設定ファイルなどの移動
 

## ⏸ What's not done

- github actionの確認
- 「Tests」に記載したコマンド以外のコマンドの実行確認

---

## Tests

- [ ] websiteフォルダで以下のココマンドが実行できること
  - [x] npm ci
  - [x] npm start
  - [x] npm run build

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-07-07 09:10 UTC, in-a-paddy commented
* `.gitignore`はルートディレクトリと`website`で分割しないといけなかった。
  * `website/build`とかは無視されるべき
* `.prettierrc.js`, `.stylelintrc.js`, `.textlintrc.js`, `babel.config.js`, `tsconfig.json`も移動してほしい

2021-07-07 09:15 UTC, tani-takanori reviewed
~`<root>/package.json` は他のディレクトリのlintも入ってるので動かしちゃうと影響大きいと思う。~
~lintを分割するならrcファイルも一緒に。~

~rootに残すなら、docusaurusのコマンド郡だけwebsiteに持ってきて、README分割するとかしないといけないかな~

websiteにlanding-pageも持ってきたほうがいいかな

2021-07-07 09:24 UTC, tani-takanori commented
rootのREADMEもwebsiteにほしいと思う

2021-07-07 09:29 UTC, in-a-paddy commented
たしかにその方がいいね。で、rootのREADMEは、各ディレクトリの説明を載せてほしい。

2021-07-08 04:29 UTC, nagano-ryo commented
> * `.gitignore`はルートディレクトリと`website`で分割しないといけなかった。
>   
>   * `website/build`とかは無視されるべき
> * `.prettierrc.js`, `.stylelintrc.js`, `.textlintrc.js`, `babel.config.js`, `tsconfig.json`も移動してほしい

各ファイル、フォルダをwebsiteに移動
482b6cd69af1c479f3f18d76c4bfd2ef84278c92

`.gitignore`をルートディレクトリと`website`で分割
47f3b18df63146e592e374a2e24069715bedecba

2021-07-08 04:31 UTC, nagano-ryo commented
> たしかにその方がいいね。で、rootのREADMEは、各ディレクトリの説明を載せてほしい。

トップのREADME.mdをwebsiteに移動し、トップのREADME.mdとして各フォルダの説明を記載
604cdbbb35b525881f9757e20d0141ddab7c72e4

2021-07-08 04:32 UTC, nagano-ryo commented
> ~`<root>/package.json` は他のディレクトリのlintも入ってるので動かしちゃうと影響大きいと思う。~
> ~lintを分割するならrcファイルも一緒に。~
> 
> ~rootに残すなら、docusaurusのコマンド郡だけwebsiteに持ってきて、README分割するとかしないといけないかな~
> 
> websiteにlanding-pageも持ってきたほうがいいかな

各ファイル、フォルダをwebsiteに移動　この修正でlanding-pageも移動しています
482b6cd69af1c479f3f18d76c4bfd2ef84278c92

2021-07-08 05:29 UTC, in-a-paddy requested changes

2021-07-08 05:29 UTC, in-a-paddy commented on README.md
> +# 各フォルダの説明
これはh1ではないと思うのと、ライセンスは残す必要があると思う。

```suggestion
# mobile-app-crib-notes

これまでWebアプリケーションを開発していたエンジニアが、モバイルアプリケーションの開発を始めるために調査した内容などをまとめています。そのため、Webとは考え方やアーキテクチャが異なるポイントを重視した内容となっています。

> ここでは、まだモバイルアプリケーションの開発におけるごく一部の側面しか紹介できていません。また、すでに紹介している内容についても、内容を追記する可能性もありますし、プラットフォームの変化などで変更されていく可能性もあります。

## Project Layout

* `website`: GitHub Pagesで公開しているページのソースコード（Docusaurus）
* `example-app`: サンプルアプリケーションのソースコード（React Native）
* `react-native-samples`: GitHub Pagesで「リファレンス」として紹介しているコンテンツのソースコード例（React Native）

## ライセンス

ドキュメントは、<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">クリエイティブ・コモンズ 表示 - 継承 4.0 国際 ライセンス</a>の下に提供されており、コードサンプルは<a rel="license" href="https://www.apache.org/licenses/LICENSE-2.0">Apache 2.0 License</a>の下に提供されています。

修正などをPull Requestで出していただけると大変ありがたいです。また、改変の制約はありませんのでフォークしていただくことも可能ですし、商用利用の制限もありません。

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  <img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /> </a>```

2021-07-08 05:29 UTC, in-a-paddy commented on website/.gitignore
> +.env.production.local
ここは消しちゃって大丈夫です。`santoku-app`の`.gitignore`にもっていかないといけないかな。

2021-07-08 05:29 UTC, in-a-paddy commented on .gitignore
>  public
これは過去の遺産なので、ついでに消してもらいたいかな。

2021-07-08 05:29 UTC, in-a-paddy commented on .gitignore
一行目から移動してほしい

2021-07-08 05:41 UTC, in-a-paddy requested changes

2021-07-08 05:41 UTC, in-a-paddy commented on .github/workflows/gh-pages.yaml
> +      - website/docs/**
`website`配下を全部入れて、いらないがあれば除外したほうが良さそう。

2021-07-08 06:19 UTC, nagano-ryo commented on website/.gitignore
> +.env.production.local
`santoku-app`の`.gitignore`に移動
934e64bce0c9da8886e34c0aaf0c1b2b3d9262ed

2021-07-08 06:20 UTC, nagano-ryo commented on .gitignore
>  public
Hugoの記述を削除
f6726e4d034b99a6df6a99e6060bf31c792251b0

2021-07-08 06:20 UTC, nagano-ryo commented on .gitignore
トップの記述を削除
f6726e4d034b99a6df6a99e6060bf31c792251b0

2021-07-08 06:21 UTC, nagano-ryo commented on .github/workflows/gh-pages.yaml
> +      - website/docs/**
`website`配下を全部入れて、除外対象を指定するように修正
1aafa9996107851a6a29ba71559a4645ec85cb33

2021-07-08 07:48 UTC, tani-takanori requested changes
renovate.jsonの67,68くらいも変えないとだめな気が
```
      // SantokuAppのReactなどのパッケージとまとめられないように、ルートディレクトリのpackage.jsonだけを対象にしています
      matchFiles: ['package.json'],
```

2021-07-08 07:48 UTC, tani-takanori commented on .gitignore
> -.DS_Store
これって消しちゃっていいのか？
node関係なさそうだけど

2021-07-08 08:07 UTC, nagano-ryo commented on .gitignore
> -.DS_Store
トップの.gitignoreの.DS_Storeの削除を元に戻す
4e6152dd1536fe6c7823c89e3d26a74589e815ab

2021-07-08 08:13 UTC, in-a-paddy requested changes

2021-07-08 08:13 UTC, in-a-paddy commented on .github/workflows/gh-pages.yaml
> +      - '!website/build/**'
`.gitignore` で外されてるやつはどうせリポジトリに入らないので、わざわざ書かなくていいのでは？

2021-07-08 08:13 UTC, in-a-paddy commented on .github/workflows/gh-pages.yaml
>            key: 1-${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
この表記のままだと、他の `node_modules` とキャッシュがかぶりませんか？

2021-07-08 08:13 UTC, in-a-paddy commented on .github/workflows/gh-pages.yaml
> +          cd website && npm clean-install 2>&1 | tee /dev/stderr | test $(grep --count -E '(Error:|gyp ERR!)') -le 0
他のワークフローではnpmの`-p`オプションを使ってたはず

2021-07-08 08:13 UTC, in-a-paddy commented on README.md
> +モバイルアプリケーション開発チームで利用する各フォルダの説明です。
さすがにこれ以降は不要になっているのでは、、、

2021-07-08 08:14 UTC, tani-takanori commented on README.md
> +  <img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /> </a>```
```suggestion
  <img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /> </a>
```

不要な"`"がある

2021-07-08 08:19 UTC, nagano-ryo commented
> renovate.jsonの67,68くらいも変えないとだめな気が
> 
> ```
>       // SantokuAppのReactなどのパッケージとまとめられないように、ルートディレクトリのpackage.jsonだけを対象にしています
>       matchFiles: ['package.json'],
> ```

対象を`website/package.json`に修正
b2fbb1b1e88fe0f72e78909b8886bc374211494f

2021-07-08 08:24 UTC, nagano-ryo commented on .github/workflows/gh-pages.yaml
> +      - '!website/build/**'
git管理していないファイル、フォルダの記述を削除
f10b31e372f9c4341cbd2644ada29cb15d9a6aa4

2021-07-08 08:31 UTC, nagano-ryo commented on README.md
> +モバイルアプリケーション開発チームで利用する各フォルダの説明です。
不要な文言を削除
085d8e4477e56312be0668cbd8c9e28d1bf78096

2021-07-08 09:16 UTC, nagano-ryo commented on .github/workflows/gh-pages.yaml
> +          cd website && npm clean-install 2>&1 | tee /dev/stderr | test $(grep --count -E '(Error:|gyp ERR!)') -le 0
カレントディレクトリの変更手段をcdでなく--prefixで指定するように修正（reviewdog以外）
7e130c4a6c87610b0042770f7d116e73494d65d6

2021-07-08 09:26 UTC, nagano-ryo commented on .github/workflows/gh-pages.yaml
>            key: 1-${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
npmとnode_modulesのキャッシュのキーにディレクトリ名（website）を追加
1f842af165b0f1dc5a5b5105fa9247647787c3af

2021-07-08 09:40 UTC, tani-takanori approved these changes
Conflict解消してもらったらOKです。

2021-07-08 10:08 UTC, in-a-paddy commented on .github/workflows/gh-pages.yaml
> +          cd website && npm clean-install 2>&1 | tee /dev/stderr | test $(grep --count -E '(Error:|gyp ERR!)') -le 0
使い分けているので、理由を書いてあげてほしいです。

2021-07-08 11:34 UTC, in-a-paddy commented on .github/workflows/gh-pages.yaml
> +      - website/docs/**
labeler.yamlも、、、

2021-07-09 00:57 UTC, nagano-ryo commented on .github/workflows/gh-pages.yaml
> +      - website/docs/**
docのラベルの設定を`website`配下を全部入れて、除外対象を指定するように修正
0f7a72c0db75645fc7eb4f9779f9eab7ed7b11b2

2021-07-09 02:22 UTC, nagano-ryo commented on .github/workflows/gh-pages.yaml
> +          cd website && npm clean-install 2>&1 | tee /dev/stderr | test $(grep --count -E '(Error:|gyp ERR!)') -le 0
reviewdogを実行している箇所は--prefixではなくcdを利用している理由を追記
e6983ae5931ab9b0061ed8b975eb6fd27dbc2151

2021-07-09 05:58 UTC, in-a-paddy requested changes

2021-07-09 05:58 UTC, in-a-paddy commented on .github/labeler.yaml
> +  - '!website/tsconfig.json'
これって、意図通りに動く？[公式のサンプル](https://github.com/actions/labeler#common-examples)はこんな感じっぽいけど。

```
# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['src/**/*', '!src/docs/*']
```

2021-07-09 05:58 UTC, in-a-paddy commented on README.md
> +
ごめん、著作権がどうなるのか整理できてないから、いったん消しとこう

```suggestion
```

2021-07-09 05:58 UTC, in-a-paddy commented on website/package.json
>      "fix:text": "textlint --fix \"*.md\" \"*.mdx\" \"!(node_modules|build|santoku-app|SantokuApp)/**/*.md\" \"!(node_modules|build|santoku-app|SantokuApp)/**/*.mdx\" \"SantokuApp/*.md\" \"SantokuApp/
これもっと単純化できると思う。santoku-appとかの考慮いらないよね。
`node_modules`と`build`だけ除外しておけばいいのでは？

markdownlintも同じ

2021-07-09 06:31 UTC, nagano-ryo commented on .github/labeler.yaml
> +  - '!website/tsconfig.json'
公式の指定方法に修正　※テスト未実施　完了次第Testsにチェック付けます
ab0478cd3b9b695489bfc31b68f47a6a710e5692

2021-07-09 06:38 UTC, nagano-ryo commented on website/package.json
>      "fix:text": "textlint --fix \"*.md\" \"*.mdx\" \"!(node_modules|build|santoku-app|SantokuApp)/**/*.md\" \"!(node_modules|build|santoku-app|SantokuApp)/**/*.mdx\" \"SantokuApp/*.md\" \"SantokuApp/
scriptsから不要な除外設定を削除
bc3fe90e6e17a54d69c8017610b36734e6b3ade9
b5c735c929e338fe41180ba722cab9f7317e7648

2021-07-09 07:29 UTC, nagano-ryo commented on website/package.json
>      "fix:text": "textlint --fix \"*.md\" \"*.mdx\" \"!(node_modules|build|santoku-app|SantokuApp)/**/*.md\" \"!(node_modules|build|santoku-app|SantokuApp)/**/*.mdx\" \"SantokuApp/*.md\" \"SantokuApp/
md lintの除外設定を見直し
806e0420bc2157f1b3539c1618b85f3f6927c78c

2021-07-09 08:27 UTC, in-a-paddy approved these changes

2021-07-09 08:27 UTC, merged