♻: モバイルアプリの基本的な知識（ソースコード）のフォルダ構成の変更
ws-4020/mobile-app-crib-notes pull request #353
Opened 2021-07-12 04:51 UTC by nagano-ryo

## ✅ What's done

- [x] トップにreact-native-samplesフォルダを作成
- [x] react-native-samplesにsantoku-appを移動
- [x] react-native-samples/authentication/backendにnablarch-example-webをコピー（<https://gitlab.com/ws-4020/mobile-cross-platform/nablarch-example-web>）
- [x] react-native-samples/push-notification/backendにsantoku-app-backendを移動
- [x] santoku-app-backendのモジュール名をsantoku-app-push-notification-backendに変更
- [ ] nablarch-example-webの.travis.ymlの修正

## ⏸ What's not done

- 以下のsantoku-appへのリンクの修正
  - [website/landing-page/mobile-security-and-authentication-lp.md](https://github.com/ws-4020/mobile-app-crib-notes/blob/master/website/landing-page/mobile-security-and-authentication-lp.md)
`    また、以下のガイドで示したアーキテクチャと設計を実際のソースコードに落としたサンプルアプリケーションも[ソースコード](https://github.com/Fintan-contents/mobile-app-crib-notes/tree/master/santoku-app)を公開しています。`

---
## Tests

- [ ] santoku-appの動作確認
- [ ] santoku-app-backendの動作確認
- [ ] nablarch-example-webの動作確認

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-07-12 06:07 UTC, in-a-paddy commented on website/docs/reference/notification/client.md
> +サンプルアプリとして公開している[santoku-app](https://github.com/ws-4020/mobile-app-crib-notes/tree/master/react-native-samples/santoku-app)ではReact Nativeを利用しています。
リポジトリによってリンク先を変えたいので、↓に書いてある方法で設定してほしいです。

https://github.com/ws-4020/mobile-app-crib-notes/blob/master/website/docs/docusaurus/plugins.md#%E3%82%B0%E3%83%AD%E3%83%BC%E3%83%90%E3%83%AB%E5%A4%89%E6%95%B0%E3%81%AE%E5%88%A9%E7%94%A8

2021-07-12 06:08 UTC, in-a-paddy commented on .idea/encodings.xml
> +    <file url="file://$PROJECT_DIR$/santoku-app-push-notification-backend/src/main/java" charset="UTF-8" />
これ、ディレクトリ名は変わってるけど配置先が変わってないですね

2021-07-12 09:02 UTC, nagano-ryo commented on website/docs/reference/notification/client.md
> +サンプルアプリとして公開している[santoku-app](https://github.com/ws-4020/mobile-app-crib-notes/tree/master/react-native-samples/santoku-app)ではReact Nativeを利用しています。
organizationグローバル変数を利用するように修正
55c0bb69a385c581099f4d81dffe150b08e4a50e

2021-07-12 09:16 UTC, nagano-ryo commented on .idea/encodings.xml
> +    <file url="file://$PROJECT_DIR$/santoku-app-push-notification-backend/src/main/java" charset="UTF-8" />
構成変更後のフォルダパスに修正
d15622d095d34595664c993f0cccefe9f7f9eb22

2021-07-13 00:44 UTC, tani-takanori commented
`<root>/react-native-samples`に簡単なREADMEがあると嬉しいかな。

2021-07-13 01:47 UTC, tani-takanori commented
`react-native-samples`のディレクトリにREADMEがあってもいいかなっておもいます。

2021-07-13 01:53 UTC, tani-takanori commented
`santoku-app`っていう名前残すの？SantokuAppと混乱しそうだし、消していいんじゃないのかな？

2021-07-13 02:11 UTC, tani-takanori commented
santoku-appをそれぞれの機能に分割するのってWhat's not doneですよね？

2021-07-13 02:29 UTC, nagano-ryo commented
> santoku-appをそれぞれの機能に分割するのってWhat's not doneですよね？

What's not doneに機能分割しない旨を追記しました。

2021-07-13 08:05 UTC, nagano-ryo commented
> `santoku-app`っていう名前残すの？SantokuAppと混乱しそうだし、消していいんじゃないのかな？

プッシュ通知のバックエンドの名称から`santoku-app`を削除
712729331d8d44af9e9a77793f7f9964295b05ed

2021-07-13 08:35 UTC, nagano-ryo commented
> `react-native-samples`のディレクトリにREADMEがあってもいいかなっておもいます。

react-native-samplesフォルダにREADME.mdを追加し、各フォルダの説明を記載
b71fe7b59f2c4ad891e0bb9b5bcc75872e07de14

2021-07-13 09:15 UTC, nagano-ryo commented
> 最終形でいいんじゃないの？っていうのと
> 「認証」とか「プッシュ通知」っていうレベルだけでいいと思う。
> 
> （詳細なディレクトリ内の内容は`authentication`とか`push-notification`に書けばいいので。）



> いや、リファレンスの中では「認証」とか「プッシュ通知」とかになってるから「機能」を取り除けばいいのか。

最終的なフォルダ構成に修正し、リファレンスにあわせ「機能」を削除
9487f7f41470fe751789b3338abc88ba7a6bb49f

2021-07-13 09:27 UTC, in-a-paddy requested changes

2021-07-13 09:27 UTC, in-a-paddy commented on react-native-samples/README.md
> +本フォルダはGitHub Pagesで「リファレンス」として紹介しているコンテンツのソースコード例を格納しています。
「🚧🚧🚧 コンテンツの構成変更中なので、記載とズレている箇所があります 🚧🚧 🚧」みたいな注意は入れといた方が良い気がするな。

```suggestion
> 🚧 🚧 🚧 🚧 🚧
> コンテンツの構成変更中なので、今は記載内容と異なっています。
> 認証とプッシュ通知のサンプルは、現時点では`santoku-app`に含まれています。
> 🚧 🚧 🚧 🚧 🚧

GitHub Pagesで「リファレンス」として紹介しているコンテンツのソースコード例を格納しています。
```

2021-07-15 02:13 UTC, tani-takanori approved these changes

2021-07-15 02:41 UTC, in-a-paddy approved these changes

2021-07-15 02:41 UTC, merged