⬆: Upgrade Expo SDK to 42
ws-4020/mobile-app-crib-notes pull request #365
Opened 2021-07-26 00:26 UTC by OshitaTatsuya

## ✅ What's done

- [x] `npm i -gexpo-cli`でExpo CLIのバージョンを更新
- [x] `expo upgrade`で関連ライブラリを更新
- [x] 今回のUpgradeで削除されたパッケージがあるので、一部ソースの修正
- [x] Flipperを無効にするように設定を変更
- [x] 除外されたシミュレータアーキテクチャからarm64を削除
- [x] iOSテンプレートのメタデータ改善
- [x] ハードコードされたツールチェーンパスの削除
- [x] gradle.propertiesの更新 
- [x] Androidスタイルの設定を変更 
- [x] Androidテーマを手動でリセットするコードを追加 

---

## Tests

- [x] npm run ios
- [x] npm run Android

## Devices

- [x] iOS
  - [x] シミュレータ (iPhone 11/iOS 14.5)
- [x] Android
  - [x] エミュレータ (Pixel 2/Android 10)

## Other (messages to reviewers, concerns, etc.)

- 参考にしたもの
  - [Expo SDK 42](https://blog.expo.io/expo-sdk-42-579aee2348b6)
  - [Expo SDK 42 コミット ログ](https://github.com/expo/expo/commits/sdk-42/templates)

2021-07-26 04:05 UTC, in-a-paddy requested changes

2021-07-29 10:42 UTC, OshitaTatsuya commented on example-app/SantokuApp/ios/SantokuApp/Info.plist
> -	<key>CFBundleDisplayName</key>
6ccd62e492fda21a296ed086e1b863208c8b46e3

iOSアプリ名の設定部分の修正を取り下げ

2021-07-29 10:43 UTC, OshitaTatsuya commented on example-app/SantokuApp/android/app/src/main/AndroidManifest.xml
> +    android:usesCleartextTraffic="true"
d0db2da799d33f95ae9dbb3a6b015d9a35a91ac3

誤った修正のため、取り下げ

2021-07-30 01:59 UTC, in-a-paddy requested changes

2021-07-30 01:59 UTC, in-a-paddy commented on example-app/SantokuApp/ios/Podfile
> +  # end
ごめん、SantokuAppでは、「Flipper動かなくなった！」ってのを検知したいからコメントアウトしないでおきたいな

2021-07-30 02:01 UTC, in-a-paddy commented on example-app/SantokuApp/ios/SantokuApp/Info.plist
> -	<key>CFBundleDisplayName</key>
修正入っちゃってるんだよなぁ、、、
https://github.com/ws-4020/mobile-app-crib-notes/pull/365/files#diff-2c7f18c414be2f15ba510e57c8674460ac91b241367a07faae12baca16a4e917R8

2021-07-30 05:27 UTC, OshitaTatsuya commented on example-app/SantokuApp/ios/SantokuApp/Info.plist
> -	<key>CFBundleDisplayName</key>
4b4415938ab547f05e47cd6171b5fefaca1e2a00

アプリ名定義が固定になっているので修正

2021-07-30 05:28 UTC, OshitaTatsuya commented on example-app/SantokuApp/ios/Podfile
> +  # end
0ef3b31b9eb21e234e5f5f2d309f0768508a72b6

Flipperを有効化する修正

2021-08-02 09:04 UTC, in-a-paddy commented on example-app/SantokuApp/package.json
> +    "expo-updates": "~0.8.2",
`expo-updates`と`expo-constants`のバージョンが上がってるから、`npm ci`したときに`patch-package`が警告吐いてるね。

`npm ci`直後に`npx patch-package <package>`して、パッチファイルの作り直しお願いします。たぶん、ほとんどdiffは出ないけど。

2021-08-02 10:14 UTC, OshitaTatsuya commented on example-app/SantokuApp/package.json
> +    "expo-updates": "~0.8.2",
aa49f91f862b4fad59ec48e5dd656f8790b083f6

一部パッチの不整合を修正

2021-08-03 01:11 UTC, in-a-paddy approved these changes

2021-08-03 07:04 UTC, in-a-paddy requested changes

2021-08-03 07:04 UTC, in-a-paddy commented on example-app/SantokuApp/ios/SantokuApp.xcodeproj/project.pbxproj
> -		DC1CA795768B49C212EF845E /* [CP] Embed Pods Frameworks */ = {
`npm run pod-install`を実行したら、この部分って出てこないかな？？

2021-08-03 08:53 UTC, OshitaTatsuya commented on example-app/SantokuApp/ios/SantokuApp.xcodeproj/project.pbxproj
> -		DC1CA795768B49C212EF845E /* [CP] Embed Pods Frameworks */ = {
48ec84966107bbd530034aed17bd3544150c0364

コミット漏れです。プッシュしました

2021-08-04 09:03 UTC, in-a-paddy approved these changes

2021-08-06 08:01 UTC, creature-water-valley approved these changes

2021-08-10 06:18 UTC, merged