🌱: エラーハンドリングの方式設計を追加
ws-4020/mobile-app-crib-notes pull request #371
Opened 2021-07-30 02:22 UTC by creature-water-valley

## ✅ What's done

- [ ] エラーハンドリングの方式設計
  - [ ] 概要
  - [ ] 全体像
  - [ ] エラーの発生箇所毎のエラー処理方法

## ⏸ What's not done

- HTTP API通信時に発生したエラーのハンドリング方式（ドラフト版のドキュメントをpushしていますが、レビュー対象外としてください）
- WebViewのページ表示で発生したエラーのハンドリング方式（ドラフト版のドキュメントをpushしていますが、レビュー対象外としてください）

---

## Other (messages to reviewers, concerns, etc.)

なし

2021-08-02 08:11 UTC, in-a-paddy requested changes

2021-08-02 08:11 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +
JSXで発生したエラーをError Boundaryで拾うってことになると思うけど、ほとんど発生しないと思うのでそのことも書いてあげてほしい。
あと、「Reactコンポーネントのエラー処理」だとuseEffectとかもReactコンポーネントの処理じゃんってなって曖昧だから「JSXのエラー処理」にしたほうがはっきりすると思う。

2021-08-02 08:11 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +- Native Modules
順番を入れ替えたほうが良さそう

```suggestion
- ロジック[^1]
  - 非同期処理
  - 同期処理
- イベントハンドラ
  - 非同期処理
  - 同期処理
- JSX
- Native Modules
```

2021-08-02 08:11 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +## 未処理のエラーを処理する方法
これ、「個別にエラーを処理する方法」の上でいいと思う

2021-08-02 11:06 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +## 未処理のエラーを処理する方法
変更しましたー
dee8c08363ad29603434c28b9b792dcb2a6d8647

2021-08-02 11:06 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +
対応しましたー
661cbe35b194f46de80dd4f802d9a3a996374968

2021-08-03 01:53 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/overview.mdx
> +![エラーハンドリングアーキテクチャ](error-handling-architecture.drawio.png)
対応しましたー
f8c6beed31f0fdd8617ac8739499c7fc9fe22bf4

> JavaScriptの「処理結果の受信」ってどういうやつ？

Native Moduleで捕捉したエラーを、JavaScript Moduleに連携して、JavaScript側でエラー表示するようなケースを指してます。。。
分かりづらかったと思うので、図の下に説明を追加しました。

> JavaScriptで発生した未処理のエラーを、直接Firebase Crashlytics SDKに渡していいかな？実際はBridge？を経由して例外が変換されているのでは？と思っている。

そうだね、[ここら辺のBridge](https://github.com/facebook/react-native/blob/main/Libraries/BatchedBridge/BatchedBridge.js)を経由して、ExceptionManagerでスタックトレースの変換が行われてるっぽい。
https://github.com/facebook/react-native/blob/8efbb2e71e761fde9146ac6a6a9eb670776cf8b8/ReactAndroid/src/main/java/com/facebook/react/modules/core/ExceptionsManagerModule.java#L83
https://github.com/facebook/react-native/blob/8efbb2e71e761fde9146ac6a6a9eb670776cf8b8/ReactAndroid/src/main/java/com/facebook/react/util/JSStackTrace.java#L25

ので、Bridgeを経由するように図を修正しました。

> Bridgeは真ん中に円を置くんじゃなくて、JS/Nativeの境界を全部Bridgeって帯にしてしまったらどうだろ？

全部帯にしましたー

> Native Modulesの「エラーを捕捉」でSDKに直接行く矢印とBridgeを経由する矢印の差がわかんない気がする。

差がわかるように、図の修正と説明を追記してみました。

> 「Bridge」→「処理結果の受信」の矢印のところに微妙に小さい謎の四角形がある。

消しました。。。

2021-08-03 07:04 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/overview.mdx
> +![エラーハンドリングアーキテクチャ](error-handling-architecture.drawio.png)
Native Moduleで捕捉したエラー（パターン③）などを、少し修正しました。
d76f05582976c7fc20ee11eba3b6c0f2316286ad

2021-08-03 07:37 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/error-handling/overview.mdx
> +![エラーハンドリングアーキテクチャ](error-handling-architecture.drawio.png)
- 「処理結果を受信」→ 「React Native Firebase Crashlytics」の矢印があるとわかりにくいかも。
   「Native Modulesで捕捉」→「JavaScriptにエラーを返却」→「処理結果の受信」（UI表示＋エラー送信）よりは、スタックトレースのわかりやすさ的に「Native Modulesで捕捉」→「エラー送信」＋「JavaScriptにエラーを返却」→「UI表示」のほうがいい気がする
- 矢印はBridgeにつけないで、箱から箱に直接つないじゃっていい気がする。正確ではなくなるけど、ソッチのほうが処理の流れはわかりやすいんじゃないかなぁ

2021-08-03 09:13 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +ただし、ロジックやイベントハンドラの非同期処理で発生したエラーに関しては、Firebase Crashlytics SDKで捕捉できないため、必ず個別にエラー処理を実施してください。
非同期処理にはセーフガード（グローバルエラーハンドリング）がないから開発プロセスでケア（チェック）するっていうことですよね？

2021-08-03 09:20 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/error-handling/api-error-handling.mdx
> +HTTPステータスコードが4xxの場合は、モバイルアプリケーションの操作によって解決が可能なエラーになります。HTTPステータスコードが5xxの場合は、モバイルアプリケーションの操作では解決できないエラーとなります。
今回って排他はないんでしたっけ？

2021-08-04 00:14 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +ただし、ロジックやイベントハンドラの非同期処理で発生したエラーに関しては、Firebase Crashlytics SDKで捕捉できないため、必ず個別にエラー処理を実施してください。
> 非同期処理にはセーフガード（グローバルエラーハンドリング）がない

正確に言えば、手段はありそうなんですけど、未検証なのとProductionで使うのはちょっと怖そうということで採用してない感じです。
https://github.com/ws-4020/mobile-app-crib-notes/blame/master/website/docs/react-native/santoku/decisions/adr-001-error-handling.mdx#L51

> 開発プロセスでケア（チェック）するっていうことですよね？

ですね。

2021-08-04 00:16 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/api-error-handling.mdx
> +HTTPステータスコードが4xxの場合は、モバイルアプリケーションの操作によって解決が可能なエラーになります。HTTPステータスコードが5xxの場合は、モバイルアプリケーションの操作では解決できないエラーとなります。
排他ってなんの排他ですかね？

2021-08-04 00:34 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/error-handling/api-error-handling.mdx
> +HTTPステータスコードが4xxの場合は、モバイルアプリケーションの操作によって解決が可能なエラーになります。HTTPステータスコードが5xxの場合は、モバイルアプリケーションの操作では解決できないエラーとなります。
排他制御で発生する[conflict](https://developer.mozilla.org/ja/docs/Web/HTTP/Status/409)です。

2021-08-04 00:38 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/api-error-handling.mdx
> +HTTPステータスコードが4xxの場合は、モバイルアプリケーションの操作によって解決が可能なエラーになります。HTTPステータスコードが5xxの場合は、モバイルアプリケーションの操作では解決できないエラーとなります。
今のところは想定してないですね。
これはあれか、ここちゃなくて下の表に409いらないの？っていう確認ってことですかね。

2021-08-04 00:40 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/error-handling/api-error-handling.mdx
> +HTTPステータスコードが4xxの場合は、モバイルアプリケーションの操作によって解決が可能なエラーになります。HTTPステータスコードが5xxの場合は、モバイルアプリケーションの操作では解決できないエラーとなります。
そうです。
（すいません。コメントする場所がおかしかったです）

2021-08-04 07:16 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +ただし、ロジックやイベントハンドラの非同期処理で発生したエラーに関しては、Firebase Crashlytics SDKで捕捉できないため、必ず個別にエラー処理を実施してください。
> 開発プロセスでケア（チェック）する

これって、どうやってやる？

2021-08-04 07:24 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +ただし、ロジックやイベントハンドラの非同期処理で発生したエラーに関しては、Firebase Crashlytics SDKで捕捉できないため、必ず個別にエラー処理を実施してください。
開発ガイドとレビューかな？

2021-08-04 07:32 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +ただし、ロジックやイベントハンドラの非同期処理で発生したエラーに関しては、Firebase Crashlytics SDKで捕捉できないため、必ず個別にエラー処理を実施してください。
見落とす自信がある 👍

2021-08-04 07:34 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +ただし、ロジックやイベントハンドラの非同期処理で発生したエラーに関しては、Firebase Crashlytics SDKで捕捉できないため、必ず個別にエラー処理を実施してください。
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md

2021-08-04 07:48 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +ただし、ロジックやイベントハンドラの非同期処理で発生したエラーに関しては、Firebase Crashlytics SDKで捕捉できないため、必ず個別にエラー処理を実施してください。
awaitの時は、対応できなさそうだね。

2021-08-04 08:07 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx
> +ただし、ロジックやイベントハンドラの非同期処理で発生したエラーに関しては、Firebase Crashlytics SDKで捕捉できないため、必ず個別にエラー処理を実施してください。
ふむ。そもそも設計で考えなきゃいけないことだし、現時点で結論出すのは難しいか。。。。
最悪、頑張ってレビューするって感じだな。

2021-08-04 08:34 UTC, in-a-paddy approved these changes

2021-08-04 08:34 UTC, tani-takanori approved these changes

2021-08-04 08:34 UTC, merged