🌱: ディープリンクのADRを追加
ws-4020/mobile-app-crib-notes pull request #372
Opened 2021-07-30 08:31 UTC by tani-takanori

## ✅ What's done

- [ ] ADRの作成
  - [ ] 要約
  - [ ] コンテキスト
  - [ ] 議論
  - [ ] 決定

---

## Other (messages to reviewers, concerns, etc.)

なし

2021-08-02 09:48 UTC, in-a-paddy requested changes

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +招待コードや一時的なTokenをユーザ間で共有してもらう場合、次のいずれかの方法が考えられます。
カタカナのがよさそう
```suggestion
招待コードや一時的なトークンをユーザ間で共有してもらう場合、次のいずれかの方法が考えられます。
```

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +後者のほうが入力の間違いもなくユーザの操作が少ないため、アプリのユーザ体験を向上することが期待できます。
```suggestion
後者のほうが入力の間違いもなくユーザの操作も少ないため、ユーザ体験が向上することが期待できます。
```

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +共有されたURLからアプリケーションに情報を渡す方法として3つの方法があります。
```suggestion
ユーザに共有されたURLからアプリケーションが情報を受け取る方法として、3つの方法を検討しました。
```

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +まずカスタムURLスキームは招待コードやTokenを渡す用途では回避できないセキュリティのリスク（※1）があるため採用できません。
```suggestion
まず、カスタムURLスキームには回避できないセキュリティのリスク（※1）があるため、採用は見送りました。
```

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +
いきなり設定作業の比較から入るより、比較から入ったほうがわかりやすいと思う。機能比較の上で、設定作業も対した差はないです、的なことを書いてあればわかりやすいんじゃないかと。

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +まずカスタムURLスキームは招待コードやTokenを渡す用途では回避できないセキュリティのリスク（※1）があるため採用できません。
この「※1」って脚注にできないのかな？

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +|設定ファイル|△|○|
「設定ファイル」だとナンノコッチャわかんないから「設定作業の容易さ」とか？

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +OSの機能を利用する場合、インストールされていないアプリケーションに関連付けられたURLはWebサイトとしてブラウザでアクセスしてしまいます。
```suggestion
OSの機能をそのまま利用すると、URLに関連付けられたアプリケーションがインストールされていない場合は、Webサイトと判断されてブラウザでアクセスしてしまいます。
そのため、アプリケーションをインストールしていないユーザ向けに、導線としてのWebサイトも用意する必要があります。
```

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +本プロジェクトでもWebサイトのUIを構築しないため、この機能は有効です。
```suggestion
一方、[Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)では、未インストールのユーザに対する導線が簡単に用意できるので、Webサイトを持たないサービスでも簡単にディープリンクを導入できます。

このアプリケーションでもWebサイトは構築しないので、この機能は有効です。
```

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +iOS14以降ではアプリを起動時にOS通知としてアプリケーションがクリップボードで共有したことが通知されます。
これって、起動時に毎回クリップボードにアクセスするの？

```suggestion
Firebase Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。アプリケーションはこの機能のために、起動時にクリップボードにコピーされている値を読み込んでいます。

iOS14以降ではクリップボードを読み取るとOSが通知を表示する仕様となっています。そのため、アプリケーションの起動時に「<アプリ名>にSafariからペースト」のような通知が表示されます。
```

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +OSの機能を利用したディープリンクだけであれば、本番のドメインと開発用のドメインを分ける必要はありません。
これ、書き途中？Dynamic Linksは△でOS機能は○になってるんだけど、差がわからんw

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +カスタムURLスキームとは異なり、アプリケーションとURLの正当性を検証しているため、情報を他のアプリにわたすことはありません。
```suggestion
カスタムURLスキームとは異なり、アプリケーションとURL（ドメイン）の関連付けが正当であることをOSが検証しているため、ユーザの操作ミスなどで、他のアプリに情報が意図せず渡ることはありません。
```

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +ただし、情報はURLに付与されているため、ユーザ間で共有できる情報に限定します。
ここって何が主張したいんだろ？機密情報を共有するために使っちゃダメ、みたいなこと？

2021-08-02 09:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +認証、認可が必要な場合は取得するAPIのキー情報や一時的なTokenのみを共有し、情報はAPIから取得します。
APIキーは渡していいのか？？

```suggestion
認証、認可が必要な場合は取得するAPIのキー情報や一時的なトークンのみを共有し、情報はAPIから取得します。
```

2021-08-02 10:33 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +iOS14以降ではアプリを起動時にOS通知としてアプリケーションがクリップボードで共有したことが通知されます。
アプリインストールの初回起動だけですね。

2021-08-02 10:35 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +認証、認可が必要な場合は取得するAPIのキー情報や一時的なTokenのみを共有し、情報はAPIから取得します。
キー情報って書いちゃうとそう読めちゃうか。

アクセスするためのパラメータのつもりでした。

2021-08-02 11:02 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +ただし、情報はURLに付与されているため、ユーザ間で共有できる情報に限定します。
機密情報を共有するとしても機密情報を直接URLに載せちゃだめっていうことです。

2021-08-03 05:58 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Firebase Dynamic Linksには[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)があり、`unique`でない場合はユーザが意図しないURLをアプリが受け取っている可能性があります。
工事中マークが付いているのでまだ修正途中かもしれませんが、matchTypeはAndroidにはない（`unique`が返ってこない）と思うので、iOS限定の話として書いた方がいいかなと思いました。

2021-08-03 06:01 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Firebase Dynamic Linksには[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)があり、`unique`でない場合はユーザが意図しないURLをアプリが受け取っている可能性があります。
本文でもiOSではっていう話を書きます。（＋Androidは問題ないよってことも追記します）

2021-08-03 06:01 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksを利用する場合のみGoogleServiceの設定ファイルが必要です。この設定ファイルを開発者毎にするとなると管理が煩雑になります。（とくにiOSでの開発は個人開発者アカウントを利用してもらいためBundleIdが変わっていまいます）
GoogleServiceとBundleIdの話が出てきて、なんの関連性があるかちょっと分かりにくいなと思いました。

2021-08-03 07:23 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Firebse Dynamic LinksとOSの機能を直接利用する場合の違いは以下のとおりです。
```suggestion
Firebase Dynamic LinksとOSの機能を直接利用する場合の違いは以下のとおりです。
```

2021-08-20 09:57 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksを利用する場合のみGoogleServiceの設定ファイルが必要です。この設定ファイルを開発者毎にするとなると管理が煩雑になります。（とくにiOSでの開発は個人開発者アカウントを利用してもらいためBundleIdが変わっていまいます）
方式とはあまり関係ないと思ったので削除しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/95520b5a9b84d3908d14956c1848237f16eaee69

2021-08-20 09:57 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Firebase Dynamic Linksには[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)があり、`unique`でない場合はユーザが意図しないURLをアプリが受け取っている可能性があります。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/95520b5a9b84d3908d14956c1848237f16eaee69

2021-08-20 09:57 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +認証、認可が必要な場合は取得するAPIのキー情報や一時的なTokenのみを共有し、情報はAPIから取得します。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/95520b5a9b84d3908d14956c1848237f16eaee69

2021-08-20 09:58 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +ただし、情報はURLに付与されているため、ユーザ間で共有できる情報に限定します。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/95520b5a9b84d3908d14956c1848237f16eaee69

2021-08-23 07:35 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> + - Firebaseの[Dynamic Links](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)を利用する
「オペレーティング システムを統合する」ページに遷移しますが、これは意図通りではないですよね？？

2021-08-23 07:36 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> + - OSの機能（Universal Links、Android App Links）を直接利用する
Dynamic Linksにリンクを貼っているので、Universal LinksとAndroid App Linksも貼ってあげたほうが親切かなって思いました

2021-08-23 07:45 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +iOSの場合[^3]、Dynamic Linksには[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)があり、`unique`でない場合はユーザが意図しないURLをアプリが受け取っている可能性があります。
noteとかでいいと思うので、React Native Firebase Dynamic Linksが、matchTypeをサポートしてないことは触れておいて欲しいかなって思いました。

2021-08-23 07:47 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。アプリケーションはこの機能のため、起動時にクリップボードへコピーされている値を読み込んでいます。
これって、iOS14未満の場合は、どういう挙動になるんですか？

2021-08-23 07:55 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +|アプリへの誘導|◎|☓|
Webサイトを構築すれば、アプリへの誘導はできる気がするので、◎と×ほどの差はないように感じたのですがどうでしょう？

2021-08-23 07:56 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +## 決定
比較した結果、なんでDynamic Linksを選択したかっていう理由が欲しいと感じました。

比較の表とかを見ると、セキュリティとか△だし、OSの機能にしようってならないかな？と思いました

2021-08-23 08:00 UTC, in-a-paddy requested changes

2021-08-23 08:01 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +OSの機能を利用したディープリンクだけであれば、本番のドメインと開発用のドメインを分ける必要はありません。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/95520b5a9b84d3908d14956c1848237f16eaee69

凡例とか書きました

2021-08-23 08:13 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +iOSの場合[^3]、Dynamic Linksには[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)があり、`unique`でない場合はユーザが意図しないURLをアプリが受け取っている可能性があります。
ついでに、ここに別の箇所に記載する形にはなると思いますが、FirebaseのgetInitialLinkだと取得できない場合があるやつも記載しておいて欲しいです。

2021-08-23 08:15 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions.mdx
> +    to: '/react-native/santoku/decisions/adr-002-deep-link-adr',
002の奪い合い

2021-08-23 08:18 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +iOSの場合[^3]、Dynamic Linksには[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)があり、`unique`でない場合はユーザが意図しないURLをアプリが受け取っている可能性があります。
Android -> Linking.getInitialURLが（Emulatorで？）だめー
iOS -> firebase.getInitialLinkがだめー
なのでちょっと別にまとめて記載しようと思います。

2021-08-23 08:19 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。アプリケーションはこの機能のため、起動時にクリップボードへコピーされている値を読み込んでいます。
あ、iOS9以降ならクリップボード読み込みで、iOS14以降だとメッセージが出るのでちょっと書き方変えます

2021-08-23 08:19 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +|アプリへの誘導|◎|☓|
インストールまではできるんですが、クリップボードから読み込みとかまでだと作り込み必要なのでちょっと書き方変えます

2021-08-23 08:32 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions.mdx
> +    to: '/react-native/santoku/decisions/adr-002-deep-link-adr',
ギャー

2021-08-23 08:33 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksではアプリを配信するサイトを切り分けるため本番用と開発用に切り分けます。
アプリを配信するサービス（本番はStore、開発はDeployGate）くらいにしておきます
検証はTestFlight使ったけど、SantokuはiOSもDeployGateでいくので

2021-08-23 08:34 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +必要になるものは環境毎（たとえば、開発、外部テスターなどのステージング、本番）設定ファイルを想定しています。
ディープリンクを利用する（高度な機能をもつ）アプリ配信のときです。

2021-08-23 08:35 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +- iOSで意図しないURLが共有されるリスクについてもアプリケーションで対応する。
そっか
`ついても` じゃなくて `は` にします

2021-08-23 09:55 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions.mdx
> +    to: '/react-native/santoku/decisions/adr-002-deep-link-adr',
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/bc6d5cadb882d8ede78a8b19fa8a3c25d2a9388b

2021-08-23 09:56 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +|アプリへの誘導|◎|☓|
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/4ed1f3842b6548d9d6be25b84ad4ec71813305c4

2021-08-24 00:17 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +- iOSで意図しないURLが共有されるリスクについてもアプリケーションで対応する。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/bc6d5cadb882d8ede78a8b19fa8a3c25d2a9388b

2021-08-24 00:23 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Status: Proposed
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/4ed1f3842b6548d9d6be25b84ad4ec71813305c4

2021-08-24 00:37 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。アプリケーションはこの機能のため、起動時にクリップボードへコピーされている値を読み込んでいます。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/e4a53615274f87a42a7d26aaf2b7775a613f6654

2021-08-24 00:48 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +本プロジェクトでもWebサイトのUIを構築しないため、この機能は有効です。
b27ac17e44787b09f35934e36b36ccaa79f72028

2021-08-24 00:49 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +OSの機能を利用する場合、インストールされていないアプリケーションに関連付けられたURLはWebサイトとしてブラウザでアクセスしてしまいます。
https://github.com/ws-4020/mobile-app-crib-notes/commit/bc6d5cadb882d8ede78a8b19fa8a3c25d2a9388b

2021-08-24 00:58 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +本プロジェクトでもWebサイトのUIを構築しないため、この機能は有効です。
d409d624db75f96679bb51d9e33b26b9fd8c0ba9

2021-08-24 00:59 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +|設定ファイル|△|○|
https://github.com/ws-4020/mobile-app-crib-notes/commit/95520b5a9b84d3908d14956c1848237f16eaee69

2021-08-24 04:05 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> + - Firebaseの[Dynamic Links](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)を利用する
間違えてます...
https://github.com/ws-4020/mobile-app-crib-notes/commit/1c0ef7b569013061f620abd193edb3b67e53b2d6

2021-08-24 04:17 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> + - OSの機能（Universal Links、Android App Links）を直接利用する
c0c4f6d1343c32e02cfe65114b583e23ba7e446c

2021-08-24 05:13 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +iOSの場合[^3]、Dynamic Linksには[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)があり、`unique`でない場合はユーザが意図しないURLをアプリが受け取っている可能性があります。
290b053293bcfe581fafedd1e1c1a303c017c739

2021-08-24 05:13 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +## 決定
https://github.com/ws-4020/mobile-app-crib-notes/commit/0771b43f62720ac9bccbdfc93f3cb7097283ff74

2021-08-24 05:15 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +- アプリケーションをインストールするフローもサポートしている[Dynamic Links](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)を採用する。
https://github.com/ws-4020/mobile-app-crib-notes/commit/bc6d5cadb882d8ede78a8b19fa8a3c25d2a9388b

2021-08-24 05:30 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic LinksはOSの機能と比較すると、アプリへの誘導をサポートしている分、セキュリティや環境の切り分けで対応が必要になります。
https://github.com/ws-4020/mobile-app-crib-notes/commit/4ed1f3842b6548d9d6be25b84ad4ec71813305c4

2021-08-25 00:49 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +
対応しました

2021-08-25 00:51 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +|○|問題なし|
ee8f3e0c2d0331bf2fa817aea39e5619627b367a

2021-08-25 04:21 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksではこうしたユースケースをサポートしているため、Webサイトを持たないサービスに適しています。
> 結局Webサイトは必要

そうです

a2447c531a9fdddaa1162390cdf2cac14f56b339

2021-08-25 04:36 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +ただし、情報はURLに付与されているため、ユーザ間で共有できる情報に限定します。
セキュリティの項目の書き方変えてみました

5df3465d0ebd6cf195dd45e2cb9db9925398e447

2021-08-25 04:48 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +この対応でユーザが意図しないデータを受け取らないように保護します。
ec992a9966d41b0ef9f020934644a9e60419eb6b

2021-08-25 04:51 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。アプリケーションはこの機能のため、起動時にクリップボードへコピーされている値を読み込んでいます。
c9e1a3e35c4584369eb7f694f7c5b4fc1665d758

2021-08-25 09:07 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +iOSの場合[^3]、Dynamic Linksには[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)があり、`unique`でない場合はユーザが意図しないURLをアプリが受け取っている可能性があります。
セキュリティの課題は、それを記載した箇所がこのページ内にあると思うので、そこへのリンクがあるとどんな課題なのかがわかるので親切かなって思いました。

iOSのissueは、何か一言でもどんな内容のissueなのかがわかるような文言にすると、親切かなって思いました。

2021-08-25 09:22 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +## 決定
セキュリティリスクへの対応が、フィジビリティ検証でできているのと、React Native FIrebase DynamicLinksのアップデートへのパッチ追従をチームメンバーができるような状態になっていれば、SantokuAppではDynamicLinksを採用でもいいんじゃないかなって個人的には思います。

> チーム参加をサポートする点

これが、議論の中のどれに当たるのかがちょっと分かりづらいかなって思いました。

> セキュリティなどは対応する。

これも、議論の中のどれに当たるのかがちょっと分かりづらいかなって思いました。

2021-08-25 09:24 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions.mdx
> +    to: '/react-native/santoku/decisions/adr-002-deep-link-adr',
004でもいいような？

2021-08-25 10:39 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +## 決定
> チーム参加

アプリの誘導でした

> セキュリティ

iOSか
対応します

2021-08-25 10:43 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions.mdx
> +    to: '/react-native/santoku/decisions/adr-002-deep-link-adr',
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/8f292a8761383d0c711d9bba8f03b941464e2cc8

2021-08-30 02:12 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Webサイトを用意していない場合、共有されたURLでアプリケーションをインストールするように促すことでユーザをアプリへ誘導できます。
Webサイトを用意していない場合はアプリへ誘導できるっていうのはどういうことでしょう？
Webサイトがあっても、誘導はできるような？？

2021-08-30 02:13 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +本プロジェクトではWebサイトで機能を提供しないため、Firebaseが用意しているWebサイトを利用できるDynamic Linksのこの機能は有効です。
Webサイトで機能を提供しないっていうのがちょっとわからなかったです。
単純に↓ってことですかね？
```suggestion
本プロジェクトではWebサイトを提供しないため、Firebaseが用意しているWebサイトを利用できるDynamic Linksのこの機能は有効です。
```

2021-08-30 02:19 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。この機能のため、アプリケーションは初回起動時のみクリップボードの値を読み込みます。
いつクリップボードにコピーしたのかがちょっとわからないなって思いました。

後、以下の場合もクリップボードを利用するんでしたっけ？
1. アプリ未インストール
2. ディープリンク押下
3. Webサイトで「OPEN」ボタン押下
4. アプリインストール
5. ディープリンク押下

2021-08-30 02:25 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +認証、認可が必要な場合、情報自体はURLに含めず、取得するためのパラメータや一時的なトークンのみをURLに含め、保護したい情報はAPIから取得します。
なんとなく言おうとしているのはわかるようなわからないような。

アプリ内で認証済み出ないとアクセスしてはいけないような情報はURLパラメータに設定してはいけないよってことですかね？

2021-08-30 02:31 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +`some-app.com`ドメインとアプリを関連付ける場合、`https://some-app.com/apple-app-site-association`に関連付けを定義したファイルが必要です。
これはiOSの場合っていうのを明示した方がいいと思ったのと、Androidの場合の設定（`well-known`に関連づけのjsonファイルを配置でしたっけ）も記載した方がいいなと思いました。

2021-08-30 02:33 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +本プロジェクトではWebサイトで機能を提供しないため、Firebaseが用意しているWebサイトを利用できるDynamic Linksのこの機能は有効です。
Firebaseが用意しているWebサイトを利用するので提供はしています。

ただ、モバイルアプリで提供している機能（チーム参加だったり、テンプレートの追加編集）は提供していません。

Webサイトでモバイルアプリのような機能を提供せずにモバイルアプリを利用してもらうことが前提になっているということを伝えられるようにしたら、理解できますかね？

2021-08-30 02:35 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Firebaseの`page.link`ドメインを利用できるためホストを準備しなくてよい分Dynamic Linksのほうが作業は少なくなります。ただし、Firebaseを利用しなくても静的なWebサイトにドメインとアプリを関連付けるファイルを配置するだけでそこまで大きな差はありません。
Firebaseの`page.link`サブドメインを使用する場合は、WebサイトをFirebaseが構築してくれます。そのため、ホストを準備するしなくてよい分作業が少ないよ　みたいな流れの方がわかりやすいかなって思いました。

2021-08-30 02:36 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。この機能のため、アプリケーションは初回起動時のみクリップボードの値を読み込みます。
難しいんですが、「利用しない」けど「通知」されます…

2021-08-30 02:36 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +認証、認可が必要な場合、情報自体はURLに含めず、取得するためのパラメータや一時的なトークンのみをURLに含め、保護したい情報はAPIから取得します。
そうです。

2021-08-30 02:37 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +`some-app.com`ドメインとアプリを関連付ける場合、`https://some-app.com/apple-app-site-association`に関連付けを定義したファイルが必要です。
applinks.jsonも記載します

2021-08-30 02:38 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +必要になるものは環境毎（たとえば、開発、外部テスターなどのステージング、本番）設定ファイルを想定しています。
ここの設定ファイルが、何を指しているのかがちょっとわかりづらいなって思いました。
アプリの設定ファイルと、Firebaseの設定ファイル両方ですかね？

2021-08-30 02:40 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +どちらかのAPIを利用すれば実装できますが、下記の点を考慮しCold Startする場合はPlatformを判定して呼び分けます。
Cold Startだけじゃなくて、ウォームスタートもおそらく該当します。
https://developer.android.com/topic/performance/vitals/launch-time?hl=ja#warm

2021-08-30 02:42 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> + - React Native Firebaseには[iOSで起動時間が短いと読み取れないissue](https://github.com/invertase/react-native-firebase/issues/2660)があるためLinking API
```suggestion
 - React Native Firebaseには[iOSで起動時間が短いと読み取れないissue](https://github.com/invertase/react-native-firebase/issues/2660)があるためReact Native Linking API
```

2021-08-30 02:46 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksではアプリを配信するサイトを切り分けるため本番用と開発用に切り分けます。
なんでアプリを配信するサイトを切り分けなきゃだめなのかを記載した方が親切かなって思います。

2021-08-30 02:47 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +- チーム参加の招待コードを共有する方法としてディープリンクを採用し、Dynamic Linksを採用する。
そもそもの話かもしれませんが、チーム参加の招待コードを共通する方法っていうスコープに限った話なんでしたっけ？

2021-08-30 02:49 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +  - アプリインストール後の[アプリへの誘導](#アプリへの誘導)ができる点を評価し、[iOSでの意図しない共有](#iosでの意図しない共有)は対応する。
決定の最後にも、「iOSで意図しないURLが共有されるリスクについてもアプリケーションで対応する。」が記載してあって、若干文言も違うのでこれは同じことを指しているのかな？とちょっと疑問が沸きました

2021-08-30 04:25 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +本プロジェクトではWebサイトで機能を提供しないため、Firebaseが用意しているWebサイトを利用できるDynamic Linksのこの機能は有効です。
あー、機能っていうのがそういう意味なんですね。
機能のことは触れずに、↓の2点を伝える感じでどうですかね？

- 本プロジェクトでは、アプリを誘導するWebサイトを自分たちで用意しない
- Firebaseが用意してくれるWebサイトを有効に活用する

2021-08-30 04:27 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。この機能のため、アプリケーションは初回起動時のみクリップボードの値を読み込みます。
そんな微妙な動作になるんですね。。。
が、その動作まで検証できているんならば、それをどこかには残しておきたいところですね。

2021-08-30 04:44 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。この機能のため、アプリケーションは初回起動時のみクリップボードの値を読み込みます。
ほかにも微妙な挙動するやつあるので残しておきます。（多分クリップボードのドメインが一致すると読み取るけどShortだったりするとonLinkで読み取らないとかがあります…）

[ここのNo10への言及](https://github.com/ws-4020/react-native-sandbox/blob/feature/add-deep-links/DeepLink/README.md)（フィジビリティの方）と同じように残したほうがいいですかね？

2021-08-30 04:48 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +- チーム参加の招待コードを共有する方法としてディープリンクを採用し、Dynamic Linksを採用する。
Push通知（本日の時間割開始イベント）とディープリンク（チームへの招待）がどちらも情報の共有になってしまいそうで明示して記載したんですが、招待コードのを共有するためっていうスコープに限った話ではないですね

2021-08-30 05:04 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> + - React Native Linkingには[AndroidはLikingで読み取れないissue](https://github.com/facebook/react-native/issues/25675)があるためReact Native Firebase API
これがあるなら、FIrebase Dynamic Linksを使おうってなるかもしれないので、比較の表とかに追記してもらいたいです。

2021-08-30 06:00 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Firebaseの`page.link`ドメインを利用できるためホストを準備しなくてよい分Dynamic Linksのほうが作業は少なくなります。ただし、Firebaseを利用しなくても静的なWebサイトにドメインとアプリを関連付けるファイルを配置するだけでそこまで大きな差はありません。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/88088ba39d7c0598e4af531d26d796ccb736fb0f

2021-08-30 06:00 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +`some-app.com`ドメインとアプリを関連付ける場合、`https://some-app.com/apple-app-site-association`に関連付けを定義したファイルが必要です。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/88088ba39d7c0598e4af531d26d796ccb736fb0f

2021-08-30 06:00 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +本プロジェクトではWebサイトで機能を提供しないため、Firebaseが用意しているWebサイトを利用できるDynamic Linksのこの機能は有効です。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/88088ba39d7c0598e4af531d26d796ccb736fb0f

2021-08-30 06:00 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Webサイトを用意していない場合、共有されたURLでアプリケーションをインストールするように促すことでユーザをアプリへ誘導できます。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/88088ba39d7c0598e4af531d26d796ccb736fb0f

2021-08-30 06:40 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +認証、認可が必要な場合、情報自体はURLに含めず、取得するためのパラメータや一時的なトークンのみをURLに含め、保護したい情報はAPIから取得します。
8c8e1cf27208e4876ca99e4a70aaf4fc6320e9aa

2021-08-30 06:42 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +必要になるものは環境毎（たとえば、開発、外部テスターなどのステージング、本番）設定ファイルを想定しています。
88088ba39d7c0598e4af531d26d796ccb736fb0f

2021-08-30 06:52 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +どちらかのAPIを利用すれば実装できますが、下記の点を考慮しCold Startする場合はPlatformを判定して呼び分けます。
29d2a6fd615fe582820d98a2b6364c4791570151

2021-08-30 06:53 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksではアプリを配信するサイトを切り分けるため本番用と開発用に切り分けます。
88088ba39d7c0598e4af531d26d796ccb736fb0f

2021-08-30 07:00 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> + - React Native Linkingには[AndroidはLikingで読み取れないissue](https://github.com/facebook/react-native/issues/25675)があるためReact Native Firebase API
69febccdba6e815de3f7444f7981233b92cb1618

2021-08-30 07:10 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +  - アプリインストール後の[アプリへの誘導](#アプリへの誘導)ができる点を評価し、[iOSでの意図しない共有](#iosでの意図しない共有)は対応する。
4b3c2dfe26a74937e47da500ca275c2dbb57b787

2021-08-30 07:13 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +- チーム参加の招待コードを共有する方法としてディープリンクを採用し、Dynamic Linksを採用する。
b0890297b60c89785f8b06e908b44cc07d6cff28

2021-08-30 08:02 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> + - React Native Linkingには[AndroidはLikingで読み取れないissue](https://github.com/facebook/react-native/issues/25675)があるためReact Native Firebase API
なんか、「実装の容易さ」が変なとこにあるような？

2021-08-30 08:07 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。この機能のため、アプリケーションは初回起動時のみクリップボードの値を読み込みます。
うーん、どうだろ。
方式設計の方に残した方がいいのかな。SantokuAppでこういう仕様になるよってことなので。
これに関する議論はなさそう？であれば、ADRなしで方式設計に記載でいいかなぁって僕は思います。

2021-08-30 08:09 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Webサイトを用意していない場合、共有されたURLでアプリケーションをインストールするように促すことでユーザをアプリへ誘導できます。
ちょっと僕が読み取れてない気もしますが。

> Webサイトでモバイルアプリと同等の機能を用意しなくても、共有されたURLでアプリケーションをインストールするように促すことでユーザをモバイルアプリへ誘導できます。

この記載っていりますかね？
なんか、ないと割としっくりくる気がするんですが。

2021-08-30 08:12 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。この機能のため、アプリケーションは初回起動時のみクリップボードの値を読み込みます。
Copy機能を利用するかどうかの議論もあんまりできてないですね..

2021-08-30 08:54 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。この機能のため、アプリケーションは初回起動時のみクリップボードの値を読み込みます。
クリップボードの通知に関しては
クリップボードを利用しなくするっていう方法も取れるが、インストール後にURLを受け取る（オペレーティング・システムの統合）リンクがweek(not unique)になってセキュアな対応を入れるとiOSで受け取れなくなるのでクリップボードを利用する。

利用したときにここに記載してしまう事象が発生してしまうけど、制約とする。

っていう話ならかけそうです。

2021-08-30 08:56 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> + - React Native Linkingには[AndroidはLikingで読み取れないissue](https://github.com/facebook/react-native/issues/25675)があるためReact Native Firebase API
ごめんなさい！消します！！

2021-08-30 08:57 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> + - React Native Linkingには[AndroidはLikingで読み取れないissue](https://github.com/facebook/react-native/issues/25675)があるためReact Native Firebase API
efba91166b50690a6a277dc442ad214b3e43a436

2021-08-30 09:36 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Webサイトを用意していない場合、共有されたURLでアプリケーションをインストールするように促すことでユーザをアプリへ誘導できます。
843f25d73d8e75b8f670a5deb0367f4c6b6ce35b

2021-08-31 00:16 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、インストール直後のアプリケーションとURLを共有するためにクリップボードを利用しています。この機能のため、アプリケーションは初回起動時のみクリップボードの値を読み込みます。
[クリップボードを無効にする](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)こともできますが、後述する[iOSでの意図しない共有](#iosでの意図しない共有)に対応するためインストール後もURLを読み取る機能が利用できなくなります。

2021-09-01 06:29 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +本プロジェクトではアプリを誘導するためのWebサイトを独自に作成せずに、Firebaseで用意しできるWebサイトを利用します。
```suggestion
本プロジェクトではアプリを誘導するためのWebサイトを独自に作成せずに、Firebaseで用意できるWebサイトを利用します。
```

2021-09-01 07:02 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +#### iOS14以降でのクリップボード利用の通知
ここの説明って、このADRの決定事項には必要のない要素になってしまいましたかね？

2021-09-01 07:05 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksの「インストール後もURLを読み取る機能」を利用するためにはリスナーに[React Native FirebaseのonLink](https://rnfirebase.io/dynamic-links/usage#foreground-events)を利用します。
「インストール後もURLを読み取る機能」が何を指しているのかがちょっとわかりづらかったです。

2021-09-01 07:18 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +  - URLのドメインはFirebaseの`page.link`ドメインを利用し、Webサイトは独自で準備しない。
これって決定にいりますかね？

2021-09-01 07:21 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|`page.link`サブドメイン|アプリ用のWebサイトが無いときにFirebaseがWebサイトを提供するためのドメイン|[Firebaseガイド](https://firebase.google.com/docs/dynamic-links?hl=ja#custom-link-domains)|
決定事項から、`page.link`を消したら、ここも不要にになりますかね。

2021-09-01 08:34 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksの「インストール後もURLを読み取る機能」を利用するためにはリスナーに[React Native FirebaseのonLink](https://rnfirebase.io/dynamic-links/usage#foreground-events)を利用します。
そうか、他の注釈になっちゃってるので修正します。

2021-09-01 09:27 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +#### iOS14以降でのクリップボード利用の通知
はい

2021-09-01 09:27 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +  - URLのドメインはFirebaseの`page.link`ドメインを利用し、Webサイトは独自で準備しない。
いらないです！

2021-09-01 09:27 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +- React Native Firebase Dynamic Linksを採用する。
削除しました

2021-09-01 09:28 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|`page.link`サブドメイン|アプリ用のWebサイトが無いときにFirebaseがWebサイトを提供するためのドメイン|[Firebaseガイド](https://firebase.google.com/docs/dynamic-links?hl=ja#custom-link-domains)|
用語から削除して用語自体もコンテキストに上げました

2021-09-01 09:28 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +そのため、アプリケーションをインストールしていないユーザ向けに、導線としてのWebサイトも用意する必要があります。
```suggestion
そのため、アプリケーションをインストールしていないユーザ向けに、導線するWebサイトも用意する必要があります。
```

2021-09-01 09:28 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|アプリケーションの実装|△|x|
```suggestion
|アプリケーションの実装|△|☓|
```

2021-09-01 09:28 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|アプリケーションの実装|△|x[^3]|
```suggestion
|アプリケーションの実装|△|☓[^3]|
```

2021-09-01 09:28 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksの「インストール後もURLを読み取る機能」を利用するためにはリスナーに[React Native FirebaseのonLink](https://rnfirebase.io/dynamic-links/usage#foreground-events)を利用します。
議論の中では不要なので削除しました

2021-09-01 09:30 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|アプリケーションの実装|△|x|
これ間違いなので、取り下げます（古いやつ）

2021-09-01 09:32 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +そのため、アプリケーションをインストールしていないユーザ向けに、導線としてのWebサイトも用意する必要があります。
導線する？

2021-09-01 09:35 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +iOSの場合[^3]、Dynamic Linksには信頼性を表す[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)という項目があります。
```suggestion
iOSの場合[^3]、Dynamic Linksには受け取ったURLの信頼性を表す[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)という項目があります。
```

2021-09-01 09:36 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +このように対応することで別のユーザがデータを受け取りません。
```suggestion
そのため、matchTypeの値が`unique`であるか判定してからURLを処理します。このように対応することで別のユーザがデータを受け取りません。
```

2021-09-01 09:41 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +ディープリンクの実現方式として、Dynamic Linksを利用する。
```suggestion
ディープリンクの実現方式として、Dynamic Linksを利用します。
```

2021-09-01 09:44 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +そのため、アプリケーションをインストールしていないユーザ向けに、導線としてのWebサイトも用意する必要があります。
`導線となる`がいいですかね？

2021-09-01 09:51 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +#### iOS14以降でのクリップボード利用の通知
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/3ed8b04c096230be34f3c3d834aae602e5d26cb6

2021-09-01 09:53 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +パッチを適用する対象はiOSのみで、FirebaseのSDKではディープリンクのmatchTypeを返しているため、パッチ適用の難易度自体は高くないと判断し、パッチを適用して回避することにしました。
こんな感じはどうですかね？
```suggestion
:::note
パッチを適用する対象はiOSのみです。React Native Firebaseに含まれるNative Moduleは、FirebaseのSDKからmatchTypeを受け取っているため、そのmatchTypeをJavaScript Moduleに渡す機能を追加する必要があります。
:::

```

2021-09-01 10:05 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|アプリへの誘導[^2]|○|☓|
```suggestion
|アプリへの誘導|○|☓[^2]|
```

2021-09-01 10:15 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +パッチを適用する対象はiOSのみで、FirebaseのSDKではディープリンクのmatchTypeを返しているため、パッチ適用の難易度自体は高くないと判断し、パッチを適用して回避することにしました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/d6bbecf1785a6c1f81552fdd4c4ba229151b78c4

2021-09-01 10:21 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +iOSの場合[^3]、Dynamic Linksには受け取ったURLの信頼性を表す[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)という項目があります。
これって、注釈いらないであってますかね？
```suggestion
iOSの場合、Dynamic Linksには受け取ったURLの信頼性を表す[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)という項目があります。
```

2021-09-01 10:31 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +iOSの場合[^3]、Dynamic Linksには受け取ったURLの信頼性を表す[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)という項目があります。
iOSの場合って明示してますし、いらないですね。
番号ズレるので修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/fcda954804ed3ffe8d0c3c2849c12053518bd7ff

2021-09-01 10:36 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +[^3]: [iOSで受信する ＞ 6.オプションの警告](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)にあるように、matchTypeの値が`unique`にならないケースがあります。これはクリップボード機能を有効にしていても
あれ、これは4では？3が競合してる気がしますw

2021-09-01 11:03 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +[^3]: [iOSで受信する ＞ 6.オプションの警告](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)にあるように、matchTypeの値が`unique`にならないケースがあります。これはクリップボード機能を有効にしていても
なおしますーーー

2021-09-01 11:04 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +[^3]: [iOSで受信する ＞ 6.オプションの警告](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)にあるように、matchTypeの値が`unique`にならないケースがあります。これはクリップボード機能を有効にしていても
3f1047d82a604e0d636281a49b792c70e43fc96a

2021-09-01 11:28 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +そのため、アプリケーションをインストールしていないユーザ向けに、導線としてのWebサイトも用意する必要があります。
ごめんなさい。`導線となる`がいいです。

2021-09-01 23:46 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +そのため、アプリケーションをインストールしていないユーザ向けに、導線としてのWebサイトも用意する必要があります。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/eb9cee3e2ae8feadc33fcd4578359fee8ede9c6e

2021-09-07 09:26 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|Dynamic Links|App Links、Universal Linksを拡張したFirebaseの機能|カスタムURLは対象外|
```suggestion
|Dynamic Links|App Links、Universal Linksを拡張したFirebaseの機能|カスタムURLスキームは対象外|
```

2021-09-07 09:26 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> + - React Native Linkingには[AndroidはLikingで読み取れないissue](https://github.com/facebook/react-native/issues/25675)があるためReact Native Firebaseを利用してコンテンツリンクURLを取得します。
```suggestion
 - React Native Linkingには[AndroidでディーリンクのURLを読み取れないというissue](https://github.com/facebook/react-native/issues/25675)があるためReact Native Firebaseを利用してコンテンツリンクURLを取得します。
```

2021-09-07 09:26 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +アプリケーションで利用しているReact Native FirebaseではアプリケーションにmatchTypeが渡されないため、ライブラリに[パッチ](https://www.npmjs.com/package/patch-package)を適用する必要があります。
```suggestion
アプリケーションで利用しているReact Native FirebaseではアプリケーションにmatchTypeが渡されないため、ライブラリにパッチを適用する必要があります。
```

2021-09-07 09:26 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +[^4]: [iOSで受信する ＞ 6.オプションの警告](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)にあるように、matchTypeの値が`unique`にならないケースがあります。これはクリップボード機能を有効にしていても
```suggestion
[^4]: [iOSで受信する ＞ 6.オプションの警告](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)にあるように、matchTypeの値が`unique`にならないケースがあります。
```

2021-09-07 10:22 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +OSの機能を利用する場合、インストールされていないアプリケーションと関連付けられたURLのWebサイトにブラウザでアクセスしてしまいます。
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/files#diff-dc57f14ab9d9bbdab653fe6bbfc048c3db0e8bfc36d7a6b67cad020b66d6f60cR63-R68

この内容でどうでしょうか？

2021-09-07 10:23 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +必要になるものは環境毎（たとえば、開発、外部テスターなどのステージング、本番）設定ファイルを想定しています。
該当の記載は不要だったため削除してます。

2021-09-07 10:24 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-002-deep-link-adr.mdx
> +Dynamic Linksではアプリを配信するサイトを切り分けるため本番用と開発用に切り分けます。
ADRからは不要だったので削除しています。

2021-09-07 11:15 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|○|問題なし|
`問題なし`とはとくに対応が不要という意味ですか？

2021-09-07 11:15 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、未インストールのユーザに対する導線が簡単に用意できるので、ウェブサイトを持たないサービスでも簡単にディープリンクを導入できます。
```suggestion
OSの機能をそのまま利用すると、URLに関連付けられたアプリケーションがインストールされていない場合は、ウェブサイトと判断されてブラウザでアクセスしてしまいます。
そのため、アプリケーションをインストールしていないユーザ向けに、導線となるウェブサイトを用意する必要があります。

Dynamic Linksでは、未インストールのユーザに対する導線が用意できるので、ウェブサイトを持たないサービスでも簡単にディープリンクを導入できます。
```

2021-09-07 11:15 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +用語は以下のとおりです。
用語は、`コンテキスト`から外だしでいいのではと思います。（`コンテキスト`以外にもここで説明している用語が使われているので）

2021-09-07 11:15 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +## 決定
冒頭で、同様の結論が出ているのでここはなくてもいいのでは？と思いました。（ここでの説明は結論から始まってその理由があとで説明されている流れだと感じたため）

2021-09-07 11:28 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +ディープリンクを実現する方式は、次の3つの方式から選択します。
3つ以外には存在しないということは無いと思います。（Dynamic Linksのようなサービスが存在しないことを調査したわけではないので）

カスタムURLスキームとApp Links，Universal LinksはOSがサポートしている機能です。
Firebase Dynamic Linksは信頼度の高いと判断して選んでいます。

2021-09-07 11:32 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、未インストールのユーザに対する導線が簡単に用意できるので、ウェブサイトを持たないサービスでも簡単にディープリンクを導入できます。
「簡単に」を削除しているのは「他の方法で用意できる」ことがわからない（イメージできない）っていうことですかね？

ディープリンクURLでアクセスするサイトで導線を作り込んで用意することは可能です。

2021-09-07 11:35 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +## 決定
記載方法のテンプレートに沿った形で記載しています。

https://github.com/ws-4020/mobile-app-crib-notes/blob/master/website/docs/react-native/santoku/decisions/decision-record-template.mdx

2021-09-07 11:37 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +用語は以下のとおりです。
議論の中に入れたほうがよいということでしょうか？

記載方法のテンプレートに沿った形で記載しています。

https://github.com/ws-4020/mobile-app-crib-notes/blob/master/website/docs/react-native/santoku/decisions/decision-record-template.mdx

2021-09-07 11:37 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|○|問題なし|
はい。対応不要のほうがわかりやすいですか？

2021-09-07 11:41 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +|○|問題なし|
ab7cadd10a2a17a3db769703131c0be1fdeaa603

2021-09-07 11:59 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、未インストールのユーザに対する導線が簡単に用意できるので、ウェブサイトを持たないサービスでも簡単にディープリンクを導入できます。
`簡単`が続いていたので、冗長だと感じたので、挙げました

2021-09-07 12:00 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +Dynamic Linksでは、未インストールのユーザに対する導線が簡単に用意できるので、ウェブサイトを持たないサービスでも簡単にディープリンクを導入できます。
なるほど！

2021-09-07 12:00 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +用語は以下のとおりです。
テンプレ分かってなかったです。すいません。このままで問題ないです。

2021-09-07 12:03 UTC, in-a-paddy approved these changes

2021-09-07 12:20 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +## 決定
`容易に導入することが可能な` -> `導入するメリットが大きい` でどうでしょうか？

2021-09-07 12:23 UTC, tani-takanori commented on website/docs/react-native/santoku/decisions/adr-004-deep-link.mdx
> +## 決定
https://github.com/ws-4020/mobile-app-crib-notes/pull/372/commits/6d244cacdc251e2aa4e23eb63d4c7a9c75b426d2

2021-09-07 12:24 UTC, OshitaTatsuya approved these changes

2021-09-07 12:26 UTC, merged