🔗: ディープリンクの方式設計を追加
ws-4020/mobile-app-crib-notes pull request #388
Opened 2021-08-27 04:44 UTC by tani-takanori

## ✅ What's done

  - [x] アウトラインの作成（項目と流れ）
  - [x] 全体構成の図の作成
  - [x] 利用するライブラリやサービスの話
  - [x] ディープリンクを受け取って処理する
  - [x] ディープリンクを作成する方法
  - [x] 用語の整理

---

## Other (messages to reviewers, concerns, etc.)

なし

2021-08-30 04:47 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +### ディープリンクの作成
ディープリンクの作成とURLの構成は、「ディープリンクの作成」っていう別ページでもいいかなって思ったんですがどうですかね？

2021-08-30 04:51 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/recieve-deep-link.mdx
> +URLを取得するためのAPIは[コールドスタート](https://rnfirebase.io/dynamic-links/usage#backgroundquit-events)と[バックグラウンド](https://rnfirebase.io/dynamic-links/usage#foreground-events)があります。
なんかリンク先を見ると、アプリがフォアグラウンドの場合は`onLink`、アプリがバックグラウンドか停止中？の場合は`getInitialLink`って記載されているように見えるんですけど、こういう動作なんでしたっけ？

2021-08-30 04:58 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/recieve-deep-link.mdx
> +URLを取得するためのAPIは[コールドスタート](https://rnfirebase.io/dynamic-links/usage#backgroundquit-events)と[バックグラウンド](https://rnfirebase.io/dynamic-links/usage#foreground-events)があります。
混乱させる原因になりそうなのでここで説明するようにします

2021-08-30 04:59 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +### ディープリンクの作成
URLの構成が受信側からも参照いらなそうなら構成変えてみます。

2021-09-02 04:48 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +アプリケーションとURLが相互に関連を持っていることが検証できると対象のアプリケーションにURLを渡します。
Universal LinkとApp Linksの話だけど、Firebase Dynamic Linksの話に見える。

2021-09-02 10:14 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +アプリケーションとURLが相互に関連を持っていることが検証できると対象のアプリケーションにURLを渡します。
Dynamic LinksってUniversal LinkとApp Linksの機能を利用したものだからあえて分ける必要ないと思うんだけど、そういう話ではない？

2021-09-03 02:08 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|コンテンツリンク|ディープリンクURLに含まれるコンテンツを指定するためのURL形式のリンクです。Dynamic LinksではSDKを利用してディープリンクURLから取得します。|
SDKってFirebase SDKのことです？？

2021-09-03 02:10 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|コンテンツリンク|ディープリンクURLに含まれるコンテンツを指定するためのURL形式のリンクです。Dynamic LinksではSDKを利用してディープリンクURLから取得します。|
そうです。Firebase SDKと記載します

2021-09-03 02:13 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|[プレビューページ](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)|iOSでディープリンクURLに対応するアプリケーションがインストールされていない場合に表示されるページです。|
これって、Androidの場合はフォールバックURLに遷移するって感じなんですか？

2021-09-03 02:15 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|[プレビューページ](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)|iOSでディープリンクURLに対応するアプリケーションがインストールされていない場合に表示されるページです。|
この下の図を見ればそんな感じってことがわかったので、クローズします。

2021-09-03 02:39 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|[プレビューページ](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)|iOSでディープリンクURLに対応するアプリケーションがインストールされていない場合に表示されるページです。|
そうです。
[オペレーティング・システムの統合](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)のiOSにある`auto-generated...`がプレビューページです。AndroidはそのStepがないです。

2021-09-03 02:40 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +Dynamic Linksを利用しない場合、ディープリンクは[Android App Links](https://developer.android.com/training/app-links#app-links-vs-deep-links)でも説明されているようにWebサイトとモバイルアプリで同等の機能を提供することが必要です。
> Webサイトとモバイルアプリで同等の機能を提供することが必要です。

これが、Android App Linksのドキュメントのどの説明に該当するのかちょっとわからなかったです。

2021-09-03 02:50 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +本プロジェクトでは[Dynamic Linksの仕組み](https://firebase.google.com/docs/dynamic-links#how-does-it-work)を利用しWebサイトではコンテンツリンクに対応するをコンテンツを提供しません。
Dynamic Linksの仕組みに記載されている内容を利用すると、コンテンツリンクに対応するコンテンツを提供しなくて良いとなったところがちょっとよくわかりませんでした。

2021-09-03 02:54 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではテストにはDeployGate、本番環境は公式のStoreで配信します。
公式のStoreで配信するんですかね。。。

2021-09-03 02:56 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +![テストと本番の設定](./test-setting.drawio.png)
画像の中にある誤字。
「Androiアプリ」→「Androidアプリ」

2021-09-03 04:06 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +- ディープリンクによりアプリがアクティブになった場合は[getInitialLink](https://rnfirebase.io/reference/dynamic-links#getInitialLink)でディープリンクURLを取得します。
バックグラウンドからフォアグラウンドに（background→active）の時って、`onLink`じゃないんでしたっけ？

2021-09-03 04:08 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +- ディープリンクによりアプリがアクティブになった場合は[getInitialLink](https://rnfirebase.io/reference/dynamic-links#getInitialLink)でディープリンクURLを取得します。
あと、iOSの場合はLinking APIを使うのでは？

2021-09-03 04:16 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +[Universal Linksの警告](https://developer.apple.com/documentation/xcode/supporting-universal-links-in-your-app)にもあるようにディーリンクのパラメータは外部入力として構成に合致するか検査し、ユーザに情報を表示するなど安全なアクションにとどめてください。
> 外部入力として構成に合致するか検査し

この文章がちょっとわからなかったです。

2021-09-03 04:29 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +リンクパラメータをアプリケーションステートで保持してしまうと、クリアするタイミングなどの設計が難しくステートの管理が煩雑になります。
アプリ起動の初期化処理では、ステートはなくコンテクストって記載してます。

2021-09-03 04:38 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +設定により[クリップボードを無効にする](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)こともできますが、インストール後にディープリンクURLを読み取る機能が利用できません。[^1]
> インストール後にディープリンクURLを読み取る機能が利用できません

インストール後に、再度ディープリンクから起動した場合は、クリップボードを無効にしても取得できないんでしたっけ？

2021-09-03 04:40 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではテストにはDeployGate、本番環境は公式のStoreで配信します。
配信する予定はない、って別のところで書いちゃってる気がするw
ので、ここは落とそう。

あとテストと本番の設定の図の中で各ストアのケースもDeployGateのケースも全く同じように見えるので、「DeployGate」の方だけ残せばいいと思う。フォールバックURLで変えるよって話を出したいなら、「DeployGate」の箱の中にApp Storeとかを入れちゃえば同じ説明ができると思う

2021-09-03 04:43 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture.mdx
>    }
ディープリンクはエラーハンドリングの上でいいんじゃないかな。

2021-09-03 04:43 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|コンテンツリンク|ディープリンクURLに含まれるコンテンツを指定するためのURL形式のリンクです。Dynamic LinksではSDKを利用してディープリンクURLから取得します。|
ディープリンクURL vs コンテンツリンク なので、どっちかに統一したいな。コンテンツリンクURLでも良いのでは？くどいか、、、？

2021-09-03 04:44 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|コンテンツリンク|link|screenで画面、keyとvalueでパラメータを指定|`https://jp.fintan.mobile.santokuapp/`|
備考っていうカラムに記載されているものが、何を指してるのかちょっとわかりづらい気がします。

例えば、コンテンツリンクは、screenとkey/valueのことが、備考のURLにはないのでわかりづらかったり、
iOSのフォールバックURLや、パッケージ名のところは本番環境やテスト環境を見越した内容を記載しているのに、バンドルIDやパッケージ名は本番のものしかなかったり。

2021-09-03 04:49 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/react-native-firebase.mdx
> +Androidアプリでは[React Native Linkgにissue](https://github.com/facebook/react-native/issues/25675)があるため、iOSのみReact Native Linkingを利用します。
```suggestion
Androidアプリでは[React Native Linkingにissue](https://github.com/facebook/react-native/issues/25675)があるため、iOSのみReact Native Linkingを利用します。
```

2021-09-03 05:09 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +リンクパラメータをアプリケーションステートで保持してしまうと、クリアするタイミングなどの設計が難しくステートの管理が煩雑になります。
3ae41c94a74b408d1acc5e1ae9625a9ffa8d4757

2021-09-03 05:41 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|コンテンツリンク|ディープリンクURLに含まれるコンテンツを指定するためのURL形式のリンクです。Dynamic LinksではSDKを利用してディープリンクURLから取得します。|
コンテンツリンクURLにします（他でURL形式ってわざわざ記載してたりするので）

2021-09-03 05:44 UTC, in-a-paddy requested changes

2021-09-03 05:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|ディープリンクURL|ユーザが開くURLで、OSがドメインとの関連を検証するときに利用するURLです。OSの検証が成功するとアプリケーションに渡されます。|
パラメータにコンテンツリンクが含まれてるとかは、あとの文章にあんま関係ない？

```suggestion
|ディープリンクURL|ユーザが開くURLで、OSがドメインとの関連を検証するときに利用するURLです。OSの検証が成功するとアプリケーションに渡されます。パラメータ部分にコンテンツリンクなどを保持します。|
```

2021-09-03 05:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|コンテンツリンク|ディープリンクURLに含まれるコンテンツを指定するためのURL形式のリンクです。Dynamic LinksではSDKを利用してディープリンクURLから取得します。|
「ディープリンクURLに含まれるコンテンツを指定する」だと、結局よくわからない、、、これは何なの？ってなると思う。こんな感じじゃだめかな？

```suggestion
|コンテンツリンク|アプリで表示したいコンテンツをあらわすURLです。アプリと関連付けていないドメインのURLも渡すことができます。|
```

2021-09-03 05:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +React Native Linkingを利用してディープリンクURLを受け取ることはできますが、ディープリンクURLからコンテンツリンクを取得する機能がありません。また、未インストール時のフローに対応できません。
「未インストール時のフロー」が何を指しているかわからん気がする。図だけだと、インストールして起動しかしてないので。

2021-09-03 05:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +
この記載範囲であれば、Universal LinksとApp Linksでやることと変わらないと思う。ので、その情報を書いたほうが良い気がする。で、Firebase Dynamic Linksはそれに追加でいろいろとやってくれる部分があるという話なんじゃないかと、、、

2021-09-03 05:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +またディーリンクURLで利用するドメインは独自の[カスタムドメイン](https://firebase.google.com/docs/dynamic-links/custom-domains)ではなく`page.link`サブドメインを利用します。
ドメインの話はどっか別に持ってったほうが適切じゃないかな。ここは、Webサイトの話だし。

```suggestion
アプリケーションがインストールされていない場合、ディープリンクのURLを開くとブラウザでURLが開かれます。このとき、ディープリンクのURLに対応するWebサイトが存在していないと、ユーザはコンテンツへの導線を失ってしまいます。インストールしていないユーザの導線を確保するために、ディープリンクを利用する場合はWebサイトも準備することが望ましいです。

本プロジェクトでは、WebサイトとしてDynamic Linksがデフォルトで提供する[アプリのプレビューページ](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)を利用します。プレビューページではURLに対応するコンテンツ自体を表示することはできませんが、ストアなどに誘導することができるため、ユーザが導線を失うことにはなりません。
```

2021-09-03 05:44 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|フォールバックURL|アプリがインストールされていない場合にユーザがアクセスするURLです。アプリのインストール用のURLなどを設定します。|
「ユーザがアクセスするURL」ってのはちょっとよくわからん感じになると思う。iOSだと、ディープリンクURLを開いたときにアクセスするのはプレビューページなんだよね？

あと、ストア以外のURL（たとえば、DeployGateの配布ページ）を設定した場合にも自動的に遷移するの？

```suggestion
|フォールバックURL|アプリがインストールされていない場合に表示されるプレビューページから、ユーザを誘導する先のURLです。Androidでは、プレビューページからフォールバックURLに自動的にリダイレクトします。アプリのインストール用のURLなどを設定します。|
```

2021-09-03 05:47 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではテストにはDeployGate、本番環境は公式のStoreで配信します。
本番環境がないともともとの全体像と変わらないのでフォールバックURLの話をディープリンクURL作成のところに移動します。
あと、もともと本番とテストで分けるために記載していた＋「Fireabaseアプリを分けるけどFireabseのプロジェクトを分けない場合」はディープリンクURLのドメインを分けなくていいよっていうことを記載しようとしていたんですが
どっちも当てはまらないので項目ごと消します

2021-09-03 06:06 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではテストにはDeployGate、本番環境は公式のStoreで配信します。
78c4a573cbb4f8fe198038869b32ec55e156ad24

2021-09-03 06:06 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +![テストと本番の設定](./test-setting.drawio.png)
78c4a573cbb4f8fe198038869b32ec55e156ad24

2021-09-03 06:10 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +![テストと本番の設定](./test-setting.drawio.png)
78c4a573cbb4f8fe198038869b32ec55e156ad24

2021-09-03 06:10 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではテストにはDeployGate、本番環境は公式のStoreで配信します。
Firebaseのプロジェクトは環境によって変える想定だけど、その場合ってどうなるの？

2021-09-03 06:13 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではテストにはDeployGate、本番環境は公式のStoreで配信します。
環境って本番とテストじゃなくて、テストと開発（デバッグ）みたいな話だよね？

2021-09-03 06:23 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではテストにはDeployGate、本番環境は公式のStoreで配信します。
どちらかというと、テスト（DevSantokuApp）と本番（SantokuApp）の話かな

2021-09-03 06:49 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|フォールバックURL|アプリがインストールされていない場合にユーザがアクセスするURLです。アプリのインストール用のURLなどを設定します。|
ストア以外でも自動で遷移します

2021-09-03 06:51 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +アプリケーションとURLが相互に関連を持っていることが検証できると対象のアプリケーションにURLを渡します。
何が標準機能で実現できて、何がDynamic Linksで実現できるようになるのか、がわかるように書いておかないと、もろもろ理解が難しくなっていくな、と。。

2021-09-03 06:54 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +アプリケーションとURLが相互に関連を持っていることが検証できると対象のアプリケーションにURLを渡します。
なるほど

2021-09-03 06:58 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|フォールバックURL|アプリがインストールされていない場合にユーザがアクセスするURLです。アプリのインストール用のURLなどを設定します。|
Androidだとプレビューページ自体が存在しないので`アプリがインストールしていない場合にユーザを誘導するURLです。iOSではプレビューページを表示し、Androidでは自動でこのURLに遷移します。アプリのインストール用のURLを設定します。`
とかでどうですか？

2021-09-03 07:54 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではテストにはDeployGate、本番環境は公式のStoreで配信します。
ディープリンクだと証明書とかの話も関連するのでFirebaseProject周りとビルド周りについて記載しました。

5eebfb216f906e9db9f138c1b447dfc02a8fa98e

2021-09-03 08:36 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +![テストと本番の設定](./test-setting.drawio.png)
修正しました

2021-09-03 08:49 UTC, tani-takanori commented
コンテンツリンク -> コンテンツリンクURLに修正
cafa0b64205ee354cd989d8db425133e09cae80c

2021-09-06 00:40 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|フォールバックURL|アプリがインストールされていない場合にユーザがアクセスするURLです。アプリのインストール用のURLなどを設定します。|
https://github.com/ws-4020/mobile-app-crib-notes/pull/388/commits/afda58b577dba40de819786513b85681e7ecf1ad

2021-09-06 00:41 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +
修正しました

ca120895259ea4c4042f79c6c614bb0c333af718

2021-09-06 00:52 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +設定により[クリップボードを無効にする](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)こともできますが、インストール後にディープリンクURLを読み取る機能が利用できません。[^1]
d9899de5ccee7e8173a6ea22d566d5e2bd08d3c3

2021-09-06 01:39 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture.mdx
>    }
4fd7d5f90bfce196032b8f51cf9546838b6b04af

2021-09-06 01:44 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +Dynamic Linksを利用しない場合、ディープリンクは[Android App Links](https://developer.android.com/training/app-links#app-links-vs-deep-links)でも説明されているようにWebサイトとモバイルアプリで同等の機能を提供することが必要です。
https://github.com/ws-4020/mobile-app-crib-notes/commit/ca120895259ea4c4042f79c6c614bb0c333af718

2021-09-06 01:46 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +### ディープリンクURLに対応するWebサイト
```suggestion
### ディープリンクURLに対応するウェブサイト
```

2021-09-06 01:47 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +アプリケーションがインストールされていない場合、ディープリンクのURLを開くとブラウザでURLが開かれます。このとき、ディープリンクのURLに対応するWebサイトが存在していないと、ユーザはコンテンツへの導線を失ってしまいます。インストールしていないユーザの導線を確保するために、ディープリンクを利用する場合はWebサイトも準備することが望ましいです。
```suggestion
アプリケーションがインストールされていない場合、ディープリンクのURLを開くとブラウザでURLが開かれます。このとき、ディープリンクのURLに対応するウェブサイトが存在していないと、ユーザはコンテンツへの導線を失ってしまいます。インストールしていないユーザの導線を確保するために、ディープリンクを利用する場合はウェブサイトも準備することが望ましいです。
```

2021-09-06 01:47 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +本プロジェクトでは、WebサイトとしてDynamic Linksがデフォルトで提供するウェブサイトと[アプリのプレビューページ](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)を利用します。ウェブサイトやプレビューページではURLに対応するコンテンツ自体は表示できませんが、ストアなどに
```suggestion
本プロジェクトでは、ウェブサイトとしてDynamic Linksがデフォルトで提供するウェブサイトと[アプリのプレビューページ](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)を利用します。ウェブサイトやプレビューページではURLに対応するコンテンツ自体は表示できませんが、ストアなどに誘導できるため、ユーザが導線を失うことにはなりません。
```

2021-09-06 01:50 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +そのため、リンクパラメータを引き継ぐ範囲を決めてナビゲーションのパラメータとして次の画面へわたすよう設計してください。
```suggestion
そのため、リンクパラメータを引き継ぐ範囲を決めてナビゲーションのパラメータとして次の画面へ渡すように設計してください。
```

2021-09-06 01:50 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +本プロジェクトでは[Dynamic Linksの仕組み](https://firebase.google.com/docs/dynamic-links#how-does-it-work)を利用しWebサイトではコンテンツリンクに対応するをコンテンツを提供しません。
https://github.com/ws-4020/mobile-app-crib-notes/commit/ca120895259ea4c4042f79c6c614bb0c333af718

2021-09-06 01:53 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +設定により[クリップボードを無効にする](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)こともできますが、Dynamic Linksをするため[^1]、インストール後にそのまま起動してディープリンクURLを読み取る機能が利用できま
> Dynamic Linksをするため

ここが、なんか日本語変なような？

2021-09-06 02:12 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +設定により[クリップボードを無効にする](https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja#set-up-firebase-and-the-dynamic-links-sdk)こともできますが、Dynamic Linksをするため[^1]、インストール後にそのまま起動してディープリンクURLを読み取る機能が利用できま
da8bbb0c17d09be5688ee115c7917b7ad6653bcb

2021-09-06 02:24 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +- ディープリンクによりアプリがアクティブになった場合は[getInitialLink](https://rnfirebase.io/reference/dynamic-links#getInitialLink)でディープリンクURLを取得します。
ライフサイクルに合わせました
https://github.com/ws-4020/mobile-app-crib-notes/pull/388/commits/da8bbb0c17d09be5688ee115c7917b7ad6653bcb

2021-09-06 02:29 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +[Universal Linksの警告](https://developer.apple.com/documentation/xcode/supporting-universal-links-in-your-app)にもあるようにディーリンクのパラメータは外部入力として構成に合致するか検査し、ユーザに情報を表示するなど安全なアクションにとどめてください。
書き方を変えました
ed6ba14a36feb2f9e7ea182dfc225c85c9948ce0

2021-09-06 03:00 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +アプリケーションとURLが相互に関連を持っていることが検証できると対象のアプリケーションにURLを渡します。
ca120895259ea4c4042f79c6c614bb0c333af718

2021-09-06 04:12 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|コンテンツリンク|link|screenで画面、keyとvalueでパラメータを指定|`https://jp.fintan.mobile.santokuapp/`|
6b76242083af09b52fe5fe90b41e72ebab335891

2021-09-06 04:29 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|ディープリンクURL|ユーザが開くURLで、OSがドメインとの関連を検証するときに利用するURLです。OSの検証が成功するとアプリケーションに渡されます。|
e0063fc7a61cbb3b38e67ef23869af8dcbb3eda3

2021-09-06 04:29 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +React Native Linkingを利用してディープリンクURLを受け取ることはできますが、ディープリンクURLからコンテンツリンクを取得する機能がありません。また、未インストール時のフローに対応できません。
https://github.com/ws-4020/mobile-app-crib-notes/pull/388/commits/0ddd6dae71971d4f8211e7c0417eab7ed91eeb03

2021-09-06 06:51 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|コンテンツリンクURL|link|`screen`で画面、`key`と`value`でパラメータを指定|`https://jp.fintan.mobile.santokuapp/${screen}?{key}=${value}`|
OSの検証用のファイルパスがdomainに紐づくので、まず`page.link`サブドメインを取得して、Firebaseアプリを登録するので`page.link`を使うのはできないです。

ドメインじゃなくてURIのプレフィックスなので修正します。

2021-09-06 06:54 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +React Native Linkingを利用してディープリンクURLを受け取ることはできますが、ディープリンクURLからコンテンツリンクURLを取得する機能がありません。また、全体の構成にて破線で示しているDynamic Linksの拡張機能に対応できません。
ちょっと書いてみます

2021-09-06 08:30 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|コンテンツリンクURL|link|`screen`で画面、`key`と`value`でパラメータを指定|`https://jp.fintan.mobile.santokuapp/${screen}?{key}=${value}`|
`jp.fintan.mobile.santokuapp`の代わりに`santokuapp.page.link`を使えない理由としてよく分からないです、、、
Firebaseアプリの登録タイミングとコンテンツリンクURLの作成タイミングだったら、後者のほうが後だろうから使おうと思えば使えるんじゃ、、、？

あと、PCからアクセスしたときにはこのURLに実際にアクセスするから、それについてはどこかで触れておいたほうが良いのでは。

2021-09-06 09:03 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|コンテンツリンクURL|link|`screen`で画面、`key`と`value`でパラメータを指定|`https://jp.fintan.mobile.santokuapp/${screen}?{key}=${value}`|
> `jp.fintan.mobile.santokuapp`の代わりに`santokuapp.page.link`を使えない理由

あ、そういう意味か

2021-09-06 09:22 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|コンテンツリンクURL|link|`screen`で画面、`key`と`value`でパラメータを指定|`https://jp.fintan.mobile.santokuapp/${screen}?{key}=${value}`|
> `page.link`のドメインをそのまま使うってのはできないんだっけ？

@in-a-paddy 
`page.link`のドメインをコンテンツURLに使うことはできます。

2021-09-06 10:31 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +テスト（DevSantokuApp）は本番（SantokuApp）と異なるビルド設定でアプリをビルドします。
https://developer.android.com/training/app-links/verify-site-associations?hl=ja#request-verify

2021-09-06 12:07 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +テスト（DevSantokuApp）は本番（SantokuApp）と異なるビルド設定でアプリをビルドします。
やっべ、リンクの作成のほうが厳しいじゃん

2021-09-07 02:09 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +テスト（DevSantokuApp）は本番（SantokuApp）と異なるビルド設定でアプリをビルドします。
d8a4259e4700d25c4b38e96ccc0ae427cf558ff8
47d8c0cdbb29bde8b5d1dcc561b94357a6a5902b

2021-09-07 05:18 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +Firebase Dynamic Linksを利用すると、破線で示している未インストールのユーザが[インストールしたあとに、そのままディープリンクURL](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)を利用できます。
982b40ef59db3eebb0b117371108099eab8c2b2c

2021-09-07 05:42 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +React Native Linkingを利用してディープリンクURLを受け取ることはできますが、ディープリンクURLからコンテンツリンクURLを取得する機能がありません。また、全体の構成にて破線で示しているDynamic Linksの拡張機能に対応できません。
1f3a059dbd2277ac9b2444fd746a658b9edc74b3

2021-09-07 05:43 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|コンテンツリンクURL|link|`screen`で画面、`key`と`value`でパラメータを指定|`https://jp.fintan.mobile.santokuapp/${screen}?{key}=${value}`|
72972112ed0dc955f1f965f81aff5532466a13bd

2021-09-07 06:56 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +インストールされているアプリケーションとドメインが相互に関連を持っていることが検証できると対象のアプリケーションにディープリンクURLを渡します。
```suggestion
インストールされているアプリケーションとドメインが相互に関連を持っていることが検証できると、対象のアプリケーションを起動してディープリンクURLを渡します。
```

2021-09-07 06:56 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +Firebase Dynamic Linksの拡張機能では、未インストールのユーザがディープリンクURLを開くとアプリのインストールを促せます。
```suggestion
Firebase Dynamic Linksの拡張機能では、未インストールのユーザがディープリンクURLを開くとアプリのインストールページ（フォールバックURL）に誘導します。この際、Androidでは自動的にフォールバックURLが表示され、iOSではフォールバックURLへのリンクのあるプレビューページが表示されます。
```

2021-09-07 06:56 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +本プロジェクトでは、ウェブサイトとしてDynamic Linksがデフォルトで提供するウェブサイトと[アプリのプレビューページ](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)を利用します。ウェブサイトやプレビューページではURLに対応するコンテンツ自体は表示できませんが、ストアなどに
```suggestion
このアプリでは、ウェブサイトとしてDynamic Linksがデフォルトで提供するウェブサイトと[アプリのプレビューページ](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages)を利用します。ウェブサイトやプレビューページではURLに対応するコンテンツ自体は表示できませんが、ストアなどに誘導できるため、ユーザが導線を失うことにはなりません。
```

2021-09-07 06:56 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +React Native Linkingを利用してディープリンクURLを受け取ることはできますが、ディープリンクURLからコンテンツリンクURLを取得する機能がありません。また、全体の構成にて破線で示しているDynamic Linksの拡張機能に対応できません。
ん〜、この文の必要性があまりわからん。比較したいなら比較したいで書いたほうが良い気がする。結論の後に書かれてもはてな？ってなるんじゃないかなぁ。noteとかで書いておく？

```suggestion
:::note
React NativeにはOS機能の範囲のディープリンクを扱うLinkingという機能が含まれていますが、ディープリンクURLからコンテンツリンクURLを取得する機能はありません。また、全体の構成にて破線で示しているDynamic Linksの拡張機能にも対応していません。
:::
```

2021-09-07 07:16 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +SantokuAppではディープリンクURLを作成して共有するため`react-native-config`と`__DEV__`変数で切り替えられるものに限定します。たとえば、ビルドタイプのReleaseとinhouseは切り替えません。
```suggestion
SantokuAppではディープリンクURLを作成して共有するため`react-native-config`と`__DEV__`変数で切り替えられるものに限定します。たとえば、ビルドタイプのReleaseとReleaseInHouseは切り替えません。
```

2021-09-07 07:16 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +React Native Linkingを利用してディープリンクURLを受け取ることはできますが、ディープリンクURLからコンテンツリンクURLを取得する機能がありません。また、全体の構成にて破線で示しているDynamic Linksの拡張機能に対応できません。
ディープリンクの処理の中で一応触れることにはなるのでnoteで残します。

2021-09-07 07:20 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|プロダクトフレーバー|ビルドタイプ|ディープリンクURLサフィックス|
これってプロダクトフレーバーなんでしたっけ？
ビルドバリアントのページによると、`flavorSuffix`？
https://ws-4020.github.io/mobile-app-crib-notes/react-native/santoku/development/build-configuration/build-variants#%E3%83%97%E3%83%AD%E3%83%80%E3%82%AF%E3%83%88%E3%83%95%E3%83%AC%E3%83%BC%E3%83%90%E3%83%BC

2021-09-07 07:22 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|プロダクトフレーバー|ビルドタイプ|ディープリンクURLサフィックス|
`DevSantokuApp`と`SantokuApp`に修正します！

2021-09-07 07:23 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|プロダクトフレーバー|ビルドタイプ|ディープリンクURLサフィックス|
ビルドタイプも併せて修正します

2021-09-07 07:23 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|プロダクトフレーバー|ビルドタイプ|ディープリンクURLサフィックス|
`ディープリンクURLサフィックス`ってサフィックスなんですかね？なんか記載している値を見る限り何のサフィックス？？ってなりまして。

2021-09-07 07:26 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|プロダクトフレーバー|ビルドタイプ|ディープリンクURLサフィックス|
すいません、プレフィックスです...

2021-09-07 07:27 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +[ビルドバリアント](../../development/build-configuration.mdx)を設定しているためアプリケーションのID（AndroidはアプリケーションID、iOSはBundle Identifier）が切り替わります。
やっぱり、なんでこういうことを考えなきゃいけないのかとかが伝わってこない、、、
出だしはこんな感じでどうだろうか。。。

```suggestion
開発やテストは本番環境とは切り離された環境で実施するので、ディープリンクに関しても同じように「テスト用のアプリを起動するディープリンクURL」と「本番アプリを起動するディープリンクURL」を分ける必要があります。

これまで説明してきたとおり、ディープリンクではディープリンクURLに対してアプリIDと証明書の組み合わせを確認して、起動するアプリケーションが決定されます。このとき利用されるのはドメイン名だけではなく、URLのパス部分も含めて確認されます。

これらを利用して、ディープリンクURLのパス部分に応じて対象とするアプリが変わるように設定します。
```

2021-09-07 07:39 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +[ビルドバリアント](../../development/build-configuration.mdx)を設定しているためアプリケーションのID（AndroidはアプリケーションID、iOSはBundle Identifier）が切り替わります。
ef8fd7e9c03c3206e685e4ad475a1099da9c8a92

2021-09-07 07:43 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +[ビルドバリアント](../../development/build-configuration.mdx)を設定しているためアプリケーションのID（AndroidはアプリケーションID、iOSはBundle Identifier）が切り替わります。
これらを利用して、ディープリンクURLのドメイン部分とパス部分の組み合わせ応じて、対象とするアプリが変わるように設定します。

2021-09-07 07:43 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +|プロダクトフレーバー|ビルドタイプ|ディープリンクURLサフィックス|
削除しました。

https://github.com/ws-4020/mobile-app-crib-notes/commit/ef8fd7e9c03c3206e685e4ad475a1099da9c8a92

2021-09-07 08:02 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|iOSのフォールバックURL|ios.fallback|iOSアプリをインストールするときのURL|App StoreのアプリのURL|
ここら辺のAPIのパラメータの値はどこに記載されてますかね？
↓とか見ても、ちょっとパラメータ名が違うような。
https://firebase.google.com/docs/dynamic-links/rest

検証で使用しているパラメータとも違うような。
https://github.com/ws-4020/react-native-sandbox/pull/1/files#diff-43d2b31ff73eff688c8ef339068e7fd08ca1f1ca267027db038aaaa6e53c7c54R111

2021-09-07 08:14 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|iOSのフォールバックURL|ios.fallback|iOSアプリをインストールするときのURL|App StoreのアプリのURL|
検証で使用しているパラメータを書こうと思って間違えてます。

ただ、このページ自体いらない気がしてきました。

利用するAPIはOverviewで説明している。
コンテンツURLを検証する必要があることは記載している。
コンテンツリンクURLの形式は一覧形式にしてマッピングするほうが検証やナビゲーションの実装が楽なのでここでルール化する必要がなさそう。

2021-09-07 08:15 UTC, creature-water-valley commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +リンクパラメータをアプリケーションが取得したとき、（認証が必要など）すぐに処理するページに遷移できないケースがあります。
この文章と、次の文章の繋がりがちょっとわかりにくと思いました。

2021-09-07 08:37 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +リンクパラメータをアプリケーションが取得したとき、（認証が必要など）すぐに処理するページに遷移できないケースがあります。
https://github.com/ws-4020/mobile-app-crib-notes/pull/388/commits/ac16080529b2d45837e1a81886b7596178d349b6

2021-09-07 08:53 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/create-deep-link.mdx
> +|iOSのフォールバックURL|ios.fallback|iOSアプリをインストールするときのURL|App StoreのアプリのURL|
https://github.com/ws-4020/mobile-app-crib-notes/pull/388/commits/cdcda0dd6c8f99c11aee10676d90fa2ddd599196

2021-09-07 09:19 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/react-native-firebase.mdx
> +title: React Native Firebaseの対応
```suggestion
title: React Native Firebaseの課題対応
```

2021-09-07 09:19 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/react-native-firebase.mdx
> + - iOSアプリで他のユーザが開いたディープリンクURLを読み取っていないか検証できない
なんかわかりやすくなってない気がするから、matchTypeを検証できない、で良さそう。

```suggestion
 - iOSで、[Firebase Dynamic LinksのmatchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)を検証できない
```

2021-09-07 09:19 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/react-native-firebase.mdx
> + - iOSアプリでアプリ起動の時間が短いとディープリンクURLを取得できない
```suggestion
 - iOSで、アプリ起動の時間が短いとディープリンクURLを取得できない
```

2021-09-07 09:19 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/react-native-firebase.mdx
> +iOSではアプリが受け取ったディープリンクURLをユーザが開いたものかどうかを判定するために[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)という項目があります。
```suggestion
Firebase Dynamic Linksは、iOSで初回起動時にコンテンツURLを取得するためにクリップボードを利用しますが、実際はクリップボードの値だけでなく、デバイス情報なども利用しています。

このため、例えばクリップボードが空だったとしてもコンテンツURLを取得できる場合があります。こういった場合は、ユーザ自身が実際に開こうとしたわけではないコンテンツURLが取得されている可能性があります。

コンテンツURLをユーザが開いたものかどうかを判定するために[matchType](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Enums/DLMatchType.html)という項目があります。
```

2021-09-07 09:19 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/react-native-firebase.mdx
> +React Native LinkingはコンテンツリンクURLではなくディープリンクURLが取得されるため、[resolveLink](https://rnfirebase.io/reference/dynamic-links#resolveLink)を利用してコンテンツリンクURLを取得します。
```suggestion
React Native LinkingではコンテンツリンクURLではなくディープリンクURLが取得されるため、[resolveLink](https://rnfirebase.io/reference/dynamic-links#resolveLink)を利用してコンテンツリンクURLを取得します。
```

2021-09-07 09:25 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +初回起動時のクリップボードの読み取りは、ドメインが一致するディープリンクURLであれば読み取ります。
初回起動時に「OSの機能として渡されたディープリンクURL」と「クリップボードにあるディープリンクURL」を読み取るケースがあり、クリップボードにあるディープリンクURLは利用されないので通知だけが出てしまうということです。

2021-09-07 10:13 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +初回起動時のクリップボードの読み取りは、ドメインが一致するディープリンクURLであれば読み取ります。
https://github.com/ws-4020/mobile-app-crib-notes/pull/388/commits/99602bfe820c4ebcfc9c5e5ce0e11677c7846950

2021-09-07 11:10 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/overview.mdx
> +これらを利用して、ディープリンクURLのドメイン部分とパス部分の組み合わせ応じて、対象とするアプリが変わるように設定します。
```suggestion
これらを利用して、ディープリンクURLのドメイン部分とパス部分の組み合わせに応じて、起動するアプリが変わるように設定します。
```

2021-09-07 11:10 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +iOSのみですが、Firebase Dynamic Linksは、アプリがまだインストールされていないときに開いたディープリンクURLをアプリから取得するために、次のようにクリップボードを利用します。
```suggestion
iOSのみですが、Firebase Dynamic Linksは、アプリがまだインストールされていないときに開いたディープリンクURLを利用するために、次のようにクリップボードを利用します。
```

2021-09-07 11:10 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +そのため、このユーザへの通知は制限事項としています。
これって制限事項なのかな？ここの文はなくてもいい気がする。

2021-09-07 11:10 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +初回起動時にクリップボードの値がURL形式であればクリップボードを読み取ります。
```suggestion
初回起動時にディープリンクから開かれたとしても、クリップボードの値がURL形式であればクリップボードを読み取ります。
```

2021-09-07 11:15 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
> +そのため、このユーザへの通知は制限事項としています。
https://github.com/ws-4020/mobile-app-crib-notes/pull/388/commits/c2cce10d9795c47120e8f9254f6c49a58d2008e2

2021-09-07 12:03 UTC, in-a-paddy commented on website/docs/react-native/santoku/application-architecture/deep-link/react-native-firebase.mdx
> +Firebase Dynamic Linksは、iOSで初回起動時にコンテンツURLを取得するためにクリップボードを利用しますが、実際はクリップボードの値だけでなく、デバイス情報なども利用しています。
```suggestion
Firebase Dynamic Linksは、iOSで初回起動時にコンテンツURLを取得するために[クリップボードを利用するとドキュメントに記載されています](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)が、実際はクリップボードの値だけでなく、デバイス情報なども利用しています。
```

2021-09-07 12:13 UTC, tani-takanori commented on website/docs/react-native/santoku/application-architecture/deep-link/react-native-firebase.mdx
> +Firebase Dynamic Linksは、iOSで初回起動時にコンテンツURLを取得するためにクリップボードを利用しますが、実際はクリップボードの値だけでなく、デバイス情報なども利用しています。
https://github.com/ws-4020/mobile-app-crib-notes/pull/388/commits/dc398865e01ab4e6ef9994ca8ca62ad5b08a0cb8

2021-09-07 12:18 UTC, in-a-paddy approved these changes

2021-09-07 12:18 UTC, creature-water-valley approved these changes

2021-09-07 12:18 UTC, merged