🌱: モバイルアプリから利用するメッセージの取得先に関するADRを追加
ws-4020/mobile-app-crib-notes pull request #412
Opened 2021-09-08 08:19 UTC by creature-water-valley

## ✅ What's done

- [x] モバイルアプリから利用するメッセージの取得先に関するADRを追加

---

## Other (messages to reviewers, concerns, etc.)

なし

2021-09-09 00:55 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +[^1]: クラウドサービスに格納されているメッセージを更新しても、モバイルアプリ内にバンドルされているメッセージは更新されないため、それら2つのメッセージが常に同期されているわけではありません。モバイルアプリ内にバンドルされているメッセージを最新化するには、モバイルアプリをApp StoreやGoogle Playにリリースする必要があります。
うん、それはちょっと思った。
単純にファイルか、ローカルDBか、はたまたReact Queryのオフライン対応かなど、何かしらの方法でキャッシュするのは検討したほうがいいよね。
（今後、そこら辺検討して新たにADR作るって感じかね。）

2021-09-09 00:57 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +- モバイルアプリ外（クラウドサービス）に格納されたメッセージ
以下の3パターン存在するわ。。。

- モバイルアプリケーション
- モバイルアプリ
- アプリ

2021-09-09 02:39 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +[^1]: クラウドサービスに格納されているメッセージを更新しても、モバイルアプリ内にバンドルされているメッセージは更新されないため、それら2つのメッセージが常に同期されているわけではありません。モバイルアプリ内にバンドルされているメッセージを最新化するには、モバイルアプリをApp StoreやGoogle Playにリリースする必要があります。
おっけ〜、ResponseのJSONをファイルとして保存しておくのが、簡単かつ安全なのかなと感じている。

2021-09-09 02:47 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +[^1]: クラウドサービスに格納されているメッセージを更新しても、モバイルアプリ内にバンドルされているメッセージは更新されないため、それら2つのメッセージが常に同期されているわけではありません。モバイルアプリ内にバンドルされているメッセージを最新化するには、モバイルアプリをApp StoreやGoogle Playにリリースする必要があります。
全体的に、モバイルアプリ→アプリに変更しました
（コンテキストの最初だけは、文脈的にモバイルアプリの方がわかりやすいと思ったので、そのままにしてます）

db9f018e6d612d9bedcdb0610821162b0495bc13

2021-09-09 04:38 UTC, in-a-paddy requested changes

2021-09-09 04:38 UTC, in-a-paddy commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +ただし、モバイル端末のネットワークがOFFなどの理由によりクラウドサービスからメッセージを取得できない場合は、アプリ内にバンドルされているメッセージを利用します。
見落としてた。「クラウドサービス」って表現がSaaSを連想してしまうので、もうちょっと抽象化したいな、と。てか、ここではもうちょっと具体的に、APIで取得するとかでも良いのでは？別の方法も候補としてあるかな？

2021-09-09 04:46 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +ただし、モバイル端末のネットワークがOFFなどの理由によりクラウドサービスからメッセージを取得できない場合は、アプリ内にバンドルされているメッセージを利用します。
HTTP APIかクラウドのストレージに入れるかもしれないなって思って「クラウドサービス」っていう表現にしてたんだけど、クラウドのストレージもHTTP通信でアクセスするだろうから、それらを併せてAPIで取得っていう表現でいいか。

2021-09-09 04:59 UTC, creature-water-valley commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +ただし、モバイル端末のネットワークがOFFなどの理由によりクラウドサービスからメッセージを取得できない場合は、アプリ内にバンドルされているメッセージを利用します。
86e256711d3acd3429b6cf9a889137de148af7e4

2021-09-09 05:02 UTC, in-a-paddy approved these changes

2021-09-10 04:52 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +モバイルアプリでは、様々な場面でダイアログやスナックバーを通してユーザにメッセージを伝えます。ユーザがアプリを操作中にエラーが発生した場合は、そのエラー内容や復旧手順をスナックバーに表示します。
```suggestion
モバイルアプリでは、様々な場面でダイアログやスナックバーを通してユーザにメッセージを伝えます。ユーザがアプリを操作しているときにエラーが発生した場合は、そのエラー内容や復旧手順をスナックバーに表示します。
```

2021-09-10 04:52 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/decisions/adr-005-message-management.mdx
> +それらのメッセージの取得先として、大きく以下の2つが候補として挙がりました。
```suggestion
それらのメッセージの取得先として、大きく以下2つが候補として挙がりました。
```

2021-09-10 05:44 UTC, OshitaTatsuya approved these changes

2021-09-13 04:22 UTC, merged