✨: Firebaseの設定がダミーかどうかを判定する機能の追加
ws-4020/mobile-app-crib-notes pull request #464
Opened 2021-10-08 07:10 UTC by creature-water-valley

## ✅ What's done

- [x] `google-services.json`、`GoogleService-Info.plist`に定義されているプロジェクトIDが`dummy`の場合は、Firebaseの設定がダミーと判定する機能の追加
- [x] Firebaseの設定がダミーの場合は、ログをコンソールに出力するように変更
- [x] Firebaseの設定がダミーの場合は、Firebase Crashlyticsの初期処理を実施しない（Firebase Crashlyticsでエラーハンドリングをしない）ように変更

---

## Tests

- [x] 自動テスト
- [x] ビルドタイプが`Release`の場合に、Firebaseの設定ファイルがダミーの場合は、Firebase Crashlyticsにログが送信されないことを打鍵で確認
- [x] ビルドタイプが`Release`の場合に、Firebaseの設定ファイルが正しい設定ファイルの場合は、Firebase Crashlyticsにログが送信されることを打鍵で確認

## Devices

- [x] iOS
  - [x] シミュレータ (iPhone 11/iOS 15)
- [x] Android
  - [x] エミュレータ (Pixel 4a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-10-08 11:42 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +const dummyProjectId = 'santoku-app-dummy';
この `santoku-app` アピールはまじで意味ないと思ったので、ダミーのProjectIdは`dummy`とかにしたほうが良いね、、、 🙇‍♂️

2021-10-08 11:42 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +  private name: string | undefined;
```suggestion
  private name?: string;
```

2021-10-08 11:44 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +    return this.options.projectId === dummyProjectId;
都度`firebase.app()`が呼ばれちゃうから、コンストラクタでプロパティに設定したほうが良さそうな気がする。
（コメントはこのままで大丈夫だと思う）

2021-10-08 11:45 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/index.ts
> +export {firebaseConfig};
```suggestion
export {firebaseConfig} from './FirebaseConfig';
```

2021-10-08 11:48 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.test.ts
> +    expect(firebaseConfig.isDummy).toEqual(false);
こっちも`firebase.app()`の返り値を明示しておいたほうが良いと思う。

2021-10-11 00:09 UTC, creature-water-valley commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +const dummyProjectId = 'santoku-app-dummy';
`dummy`に変更しましたー
2b56ad9d217cac8a687c0e760e53d37f65e8f214

2021-10-11 00:09 UTC, creature-water-valley commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +  private name: string | undefined;
0a4d26f19f8ae56ceaa3e3cb77a37a2e13d56dc5

2021-10-11 01:24 UTC, creature-water-valley commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +    return this.options.projectId === dummyProjectId;
82e209d51fd9cb8ca7b63b475c84ac0df4359a1f

`ReactNativeFirebase`が解決できないから、↓みたいに追加したんだけど、なんかやり方が違うような？
https://github.com/ws-4020/mobile-app-crib-notes/pull/464/commits/82e209d51fd9cb8ca7b63b475c84ac0df4359a1f#diff-75fa8ba2a65fdeafe1ebc37508736f7148a79c52a6ceaa72382cc8401728f3adR14-R16

2021-10-11 01:57 UTC, in-a-paddy requested changes

2021-10-11 01:57 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +import firebase, {ReactNativeFirebase} from '@react-native-firebase/app';
型だけしか使わないから、`import type`で逃げておけばモック化しやすい感じ

```suggestion
import firebase from '@react-native-firebase/app';
import type {ReactNativeFirebase} from '@react-native-firebase/app';
```

2021-10-11 01:57 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +
`import type`してる場合は、aliasは使えないので消すしかない

2021-10-11 01:57 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +  private app: FirebaseApp;
namespaceを直接参照する
```suggestion
  private app: ReactNativeFirebase.FirebaseApp;
```

2021-10-11 01:57 UTC, in-a-paddy commented on example-app/SantokuApp/jest/__mocks__/@react-native-firebase/app.ts
> +
`FirebaseConfig.ts`を`import type {ReactNativeFirebase} from '@react-native-firebase/app'`って修正すればいらなくなるはず。

```suggestion
```

2021-10-11 01:57 UTC, in-a-paddy commented on example-app/SantokuApp/jest/__mocks__/@react-native-firebase/app.ts
> +const mock = (name: string): ReturnType<typeof firebase.app> => {
これ、`app`としてそのままexportすれば良い気がする。

2021-10-11 01:57 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.test.ts
> +    expect(firebaseConfig.name).toEqual('DEFAULT');
次のケースもだけど、値の検証じゃなくて、`spyOn`使って`firebase.app`が正しい引数で呼び出されていることを検証したほうが良さそう。
このテストだと、モックの実装の検証になってる気がする。

2021-10-11 02:26 UTC, creature-water-valley commented on example-app/SantokuApp/src/framework/firebase/FirebaseConfig.ts
> +
24fe81e4a9b5ced9aaac767c28ae11388fc82e14

2021-10-11 02:26 UTC, creature-water-valley commented on example-app/SantokuApp/jest/__mocks__/@react-native-firebase/app.ts
> +const mock = (name: string): ReturnType<typeof firebase.app> => {
bbae3d2794cd807bbaf378f5313d4c8e906ce77e

2021-10-12 08:08 UTC, merged