🌱: メッセージ管理の部品を追加
ws-4020/mobile-app-crib-notes pull request #479
Opened 2021-10-14 09:15 UTC by creature-water-valley

## ✅ What's done

- [x] メッセージをロード、取得する部品の追加
- [x] 作成した部品を使用するデモ画面の追加

---

## Tests

- [x] 自動テスト
- [x] メッセージを取得するデモ画面を打鍵

## Devices

- [x] iOS
  - [x] シミュレータ (iPhone 11/iOS 15)
- [x] Android
  - [x] エミュレータ (Pixel 4a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-10-15 01:22 UTC, kozake commented on example-app/SantokuApp/src/framework/message/Message.test.ts
> +  });
メッセージはロードされているが、メッセージキーに対するメッセージがない場合のテストは必要ないでしょうか。また、その場合に `undefined` を返すのか、`Error`を返したほうがRedBoxが出るのでエラーに気づきやすいかもしれません（が、本番ではアプリが落ちることになるのでどう判断するかですが。。）。

2021-10-15 02:31 UTC, in-a-paddy commented on example-app/SantokuApp/src/framework/message/Message.test.ts
> +    // @ts-ignore
`ts-ignore` の理由を書いておいてほしいな

2021-10-15 02:42 UTC, creature-water-valley commented on example-app/SantokuApp/src/App.tsx
> +    // アプリにバンドルしているメッセージのロードは失敗しない想定
ログ出しましたー（失敗しない想定ではあるので、コメントはそのまま）

331bbe19cab8b5beb6a982826150c3516bfd963d
5231ef59e7e04303fdef17febb961f97ea710b10

2021-10-15 02:44 UTC, creature-water-valley commented on example-app/SantokuApp/src/generated/BundledMessages.ts
> +export const BundledMessages = {
そうね。
7b0a5438dae92c47493fcd384ab39d84b9939181

2021-10-18 02:01 UTC, t-shimoda requested changes

2021-10-19 00:24 UTC, creature-water-valley commented on example-app/SantokuApp/src/framework/message/Message.ts
> +    throw new Error('Messages was not cached.');
修正しましたー

b9f473c47c03c1b2d6da28e21a931cac47dd3a09

2021-10-19 01:17 UTC, t-shimoda approved these changes

2021-10-19 06:14 UTC, merged