✏️: 全体テスト計画の作成
ws-4020/mobile-app-crib-notes pull request #506
Opened 2021-10-26 09:53 UTC by OshitaTatsuya

## ✅ What's done

- [x] 全体テスト計画書のアウトラインを作成
- [x] 全体テスト計画書の作成
- [x] シミュレータ／エミュレータと実機のバリエーション整理
---

このあと進めるもの

- 単体テスト計画書の作成
- 結合テスト計画書の作成
- テスト観点の作成

## Tests

- [x] `npm run lint:md`を実行して、lintエラーにならないことを確認
- [x] `npm start`を実行して、表示内容の確認

## Devices

- [x] Windows 10
  - [x] Chrome

## Other (messages to reviewers, concerns, etc.)

なし

2021-11-01 12:14 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-policy.mdx
> +サンプルアプリケーション開発における全体のテスト方針になります。
サンプルアプリケーションではなく、アプリへ全体的に見直して修正 dcd752835cbed12e4c0fae643cbbe22e5a0c5173

2021-11-01 12:23 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/overview.mdx
> +[テスト実施環境](../../requirements/non-functional/test-outline#テスト実施環境)で定義した端末スペックに基づいて、機種とOSバージョンを選定します。
性能テストの方で選定方針を決めてるから、そっちに沿って選定するんじゃないかな？で、結果がテスト実施環境に書かれるべきかと。

2021-11-01 12:23 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +  - 機種：Galaxy Nexus、Nexus 4（※）
これって、機種×OS（この場合は4種類）でテストする？古い方の機種×古い方のOS、新しい方の機種×新しい方のOSでテストする？

どっちかわからないので、機種とOSはセットで書いたほうが良いと思う。

2021-11-01 12:23 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +#### 単体テスト実機での検証
```suggestion
#### 単体テスト 実機での検証
```

2021-11-01 12:23 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +#### 結合テストシミュレータ／エミュレータでの検証
```suggestion
#### 結合テスト シミュレータ／エミュレータでの検証
```

2021-11-01 12:23 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +#### 結合テスト実機での検証
```suggestion
#### 結合テスト 実機での検証
```

2021-11-02 09:56 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-process-scope.mdx
> +画面の手動打鍵では、AndroidとiOSそれぞれのOS毎にエミュレータ／シミュレータと実機を利用してテストを実施します。必要なテスト環境は[テスト環境](test-environment)に定義しています。
内容見直して修正しました（あとlintエラー箇所も修正） 06ca1e125c132fe0eebe754c5e2d14ac5e77aeac

2021-11-09 06:20 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +  - 機種：Galaxy Nexus、Nexus 4（※）
テストする際に必要となるセット（機種×OS）が分かるよう記載を見直して修正しました。 1018596fe63967cf938ab691f511181f563aa7ac

2021-11-09 06:22 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/overview.mdx
> +[テスト実施環境](../../requirements/non-functional/test-outline#テスト実施環境)で定義した端末スペックに基づいて、機種とOSバージョンを選定します。
選定基準は、「性能に関する事項」を参照するよう修正 1018596fe63967cf938ab691f511181f563aa7ac

2021-11-09 08:42 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +- OS：Q 10
Android Q または Android 10 と呼ぶことはあっても、Q 10 と呼ぶことはない気がします。
Android 10以降からはコードネームは廃止されてAndroid 10という形の呼称が正式になったと思うので、Android 10でよいかと。
```suggestion
- OS：Android 10
```

2021-11-09 08:42 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +  - OS：R 11
こちらもAndroid 11に。
```suggestion
  - OS：Android 11
```

2021-11-09 08:42 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +  - OS：Pie 9
こちらはAndroid Pieでも間違いではないと思いますが、他との統一を考えるとAndroid 9でよいと思います。
```suggestion
  - OS：Android 9
```

2021-11-09 08:42 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-process-scope.mdx
> +| 1 | 単体 | 画面 | 手動（打鍵） | 画面毎にテストを実施して、画面設計通りのレイアウトとイベントが動作となっていることと、最大件数のデータ読み込みをしてクラッシュしないことの検証 |
```suggestion
| 1 | 単体 | 画面 | 手動（打鍵） | 画面毎にテストを実施して、画面設計通りのレイアウトとイベント動作となっていることと、最大件数のデータ読み込みをしてクラッシュしないことの検証 |
```

2021-11-09 08:42 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +iOSシュミレータでテストをする際の機種とOSは以下となります。
```suggestion
iOSシミュレータでテストをする際の機種とOSは以下となります。
```

2021-11-09 08:42 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +テストは、エミュレータ／シュミレータと実機を使用します。それぞれのテスト環境（機種とOS）が重複しないものを列挙しています。
```suggestion
テストは、エミュレータ／シミュレータと実機を使用します。それぞれのテスト環境（機種とOS）が重複しないものを列挙しています。
```

2021-11-09 08:42 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +Androidエミューレタでテストをする際の機種とOSは以下となります。
```suggestion
Androidエミュレータでテストをする際の機種とOSは以下となります。
```

2021-11-09 08:42 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +  - OS：12
上のほうではiOS 13と書いていたので揃える形に
```suggestion
- 直近1年で発売されたミドルエンド端末とサポートする最新のOS
  - 機種（ノッチ有）：iPhone 12 Pro
  - OS：iOS 14

- 開発時から4年前に発売された端末とサポートする最古のOS
  - 機種（ノッチ無）：iPhone 8
  - OS：iOS 12
```

2021-11-09 08:53 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku.mdx
> +    summary: 'テストに関するテスト計画',
```suggestion
    summary: 'テストに関する計画',
```

2021-11-09 09:09 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +- 直近1年で発売されたミドルエンド端末とサポートする最新のOS
ミドルエンドって一般的な用語なんでしょうか？
たまに耳にしますが、ミドルエンドではなく、ミドルレンジ端末では？と個人的には思っています。
（ちゃんと調べたことはないですが・・・）

2021-11-09 09:19 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +## エミュレータ／シミュレータでの検証
タブレットは対象外ですか？
非機能要件の「テストに関する事項」では、実機での検証は対象外とありましたが、シミュレータではタブレット特有のテストは実施するとあったような。特にタブレット特有のものは無いって判断ですかね？

2021-11-09 09:21 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/test-planning/all/test-process-scope.mdx
> +実施するテスト工程とそれぞれの工程で実施する範囲とテスト内容は以下のとおりです。
```suggestion
実施するテスト工程とそれぞれの工程で実施する範囲は以下のとおりです。
```

2021-11-09 15:33 UTC, in-a-paddy requested changes

2021-11-09 15:33 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +Androidの実機でテストをする場合、ノッチ有と無の機種で実施します。
こっちも、表にしてもらったほうがわかりやすいと思う。iOSの選定基準は、ここに書いてあるのが参照先と違ってたから適当にわかりやすそうな基準に勝手に書き換えてるから、要確認。

| OS | 選定基準 | 機種 | OSバージョン |
|----|----------|-----|----|
| Android | 直近1年で発売されたミドルレンジ端末とサポートする最新のOS | Galaxy A21 （ノッチ有）| Android 11 |
| Android | 開発時から4年前に発売された端末とサポートする最古のOS | HUAWEI P10 （ノッチ無） | Android 9 |
| iOS | 動作確認対象の最新OSバージョンがサポートする機種のうち発売日基準で最新の機種  | iPhone 12 Pro | iOS 15 |
| iOS | 動作確認対象の最古OSバージョンがサポートする機種のうち発売日基準で最古の機種 | iPhone 5s | iOS 12 |

```
| OS | 選定基準 | 機種 | OSバージョン |
|----|----------|-----|----|
| Android | 直近1年で発売されたミドルレンジ端末とサポートする最新のOS | Galaxy A21 （ノッチ有）| Android 11 |
| Android | 開発時から4年前に発売された端末とサポートする最古のOS | HUAWEI P10 （ノッチ無） | Android 9 |
| iOS | 動作確認対象の最新OSバージョンがサポートする機種のうち発売日基準で最新の機種  | iPhone 12 Pro | iOS 15 |
| iOS | 動作確認対象の最古OSバージョンがサポートする機種のうち発売日基準で最古の機種 | iPhone 5s | iOS 12 |
```

2021-11-09 15:33 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +
これ、表で書いたほうがわかりやすいと思うけど、、、あと、レイアウト確認のために複数機種でテストするのでは？

| OS | 機種 | OSバージョン |
|----|----------|-----|
| Android | Google Pixel 4 | Android 10 |
| iOS | iPhone 12 Pro Max | iOS 13 |

```
| OS | 機種 | OSバージョン |
|----|----------|-----|
| Android | Google Pixel 4 | Android 10 |
| iOS | iPhone 12 Pro Max | iOS 13 |
```

2021-11-10 05:31 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +- 直近1年で発売されたミドルエンド端末とサポートする最新のOS
調べてみたところ、`ミドルレンジ`の方が一般的に使われているようなので、そちらに修正しました。 36cf0546c469486870064dbba70f7954ad37c2dc

2021-11-11 00:35 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +## エミュレータ／シミュレータでの検証
エミュレータとシミュレータでのテストは必要なので、追記しました。 1f272c777572f1598af08d69e1d64cab81e99b47

2021-11-11 00:41 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +Androidの実機でテストをする場合、ノッチ有と無の機種で実施します。
全体的にどの選定基準に該当しているかが明確になるようもらった案（表）を取り込んで修正 1f272c777572f1598af08d69e1d64cab81e99b47

2021-11-11 00:43 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +
これもどの選定基準に該当しているかが明確になるようもらった案（表）を取り込んだのと、レイアウト確認に必要な機種の見直しをして修正 1f272c777572f1598af08d69e1d64cab81e99b47

2021-11-11 02:48 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | エミュレータ | タブレット | B | 10.3 | 1920×1200 | 無 | LAVIE Tab E TE510 | Android 10 |
選定条件は全てのサポート対象OSバージョンのAndroidタブレットになってますが、
タブレットはAndroid11はサポート対象外なんでしたっけ。

2021-11-11 02:48 UTC, kz-takahashi commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | シミュレータ | タブレット | B | 9.7 | 1536×2048 | ハ | 無 | iPad（第6世代） | iOS 13 |
OSバージョンはiPadOS 13という表記の方が正確かと思います。
こちらも選定条件は全てのサポート対象OSバージョンのiPadデバイスとなっていますが、
iPadOS 14はサポート対象外なんでしたっけ。

2021-11-11 07:42 UTC, yuto-takeshita-tis approved these changes

2021-11-11 11:19 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | エミュレータ | タブレット | B | 10.3 | 1920×1200 | 無 | LAVIE Tab E TE510 | Android 10 |
そもそもサポート対象OSバージョン全てやりますか？

2021-11-11 11:20 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | シミュレータ | タブレット | B | 9.7 | 1536×2048 | ハ | 無 | iPad（第6世代） | iOS 13 |
13, 15だけ対象ってことはありえないのでは、、、？

2021-11-11 11:28 UTC, in-a-paddy requested changes

2021-11-11 11:28 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-process-scope.mdx
> +| 1 | 単体 | 画面 | 手動（打鍵） | 画面毎にテストを実施して、画面設計通りのレイアウトとイベント動作となっていることと、最大件数のデータ読み込みをしてクラッシュしないことの検証 |
ここで書かれている観点から、選定基準が導出できないといけないはずだけど、そうなってないから読んでわからないかな。

例えば、レイアウトの確認を単体でやるって言ってるのに、タブレットサイズのテストは結合でやることになってるのはおかしいと思う。

2021-11-12 11:37 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | エミュレータ | タブレット | B | 10.3 | 1920×1200 | 無 | LAVIE Tab E TE510 | Android 10 |
利用頻度の高いものつまり、[シェア80%以内](http://smatabinfo.jp/os/android/index.html)のものを対象とするでどうかと考えました。
その場合、Android11～9のものをテスト環境として揃える考えです。
具体的なOSバージョンは、テスト計画側に記載でよいかと思っています。

2021-11-12 11:41 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | シミュレータ | タブレット | B | 9.7 | 1536×2048 | ハ | 無 | iPad（第6世代） | iOS 13 |
こっちもAndroidと同様で、[シェア80%以内](http://smatabinfo.jp/os/ios/index.html)のものを対象のOSバージョンとして選定する考えです。

2021-11-12 12:08 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-process-scope.mdx
> +| 1 | 単体 | 画面 | 手動（打鍵） | 画面毎にテストを実施して、画面設計通りのレイアウトとイベント動作となっていることと、最大件数のデータ読み込みをしてクラッシュしないことの検証 |
矛盾したテスト観点の修正 6764df9f88944010d7c24bce286dd56565f61baa

2021-11-12 12:32 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | シミュレータ | タブレット | B | 9.7 | 1536×2048 | ハ | 無 | iPad（第6世代） | iOS 13 |
諸々踏まえて、このように修正してみました 2b3a0fc02b875f2cfccfd22c0d5376bc0a396d37

2021-11-12 12:54 UTC, in-a-paddy commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | エミュレータ | タブレット | B | 10.3 | 1920×1200 | 無 | LAVIE Tab E TE510 | Android 10 |
非機能側で決めてる方にはシェアの話はなかったと思ってるんだけど、そっちにもシェアの話を足すってことかな？

あっちに書いてあるのと整合してないので、まずは要件側を固めてからにしてほしい。

2021-11-15 05:51 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/test-planning/all/test-environment.mdx
> +| 5 | エミュレータ | タブレット | B | 10.3 | 1920×1200 | 無 | LAVIE Tab E TE510 | Android 10 |
テストに関する事項の選定基準を見直したのでまずは、確認お願いします。（テスト計画はそっちが決まり次第修正を始めます。行ったり来たりですいません。）

2021-12-01 01:12 UTC, OshitaTatsuya commented
全体テスト計画の内容を大きく見直して修正して、別PRを作成して進めているので、このPRをCLOSEします。

2021-12-01 01:12 UTC, closed without merging