ToDoアプリプロジェクトの説明
ws-4020/mobile-app-crib-notes pull request #51
Opened 2021-02-19 08:41 UTC by shkozake

## ✅ What's done

- [ ] ToDoアプリプロジェクトの準備
- [ ] プロジェクト構成の説明

## ⏸ What's not done

- RNスポイラで作成される各ファイルやディレクトリの説明

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

「RNスポイラで作成される各ファイルやディレクトリの説明」については、React Native固有でないものも多く冗長と感じたので説明を省きました。

2021-02-19 08:50 UTC, tani-takanori requested changes

2021-02-19 08:50 UTC, tani-takanori commented on docs/react-native/learn/todo-app/app-project-desc.md
> +最終的に出来上がるToDoアプリのプロジェクト構成は次の通りです。
プロジェクト構成だと 欠落している印象があるのでアプリのソースコードディレクトリ構成くらいでどうでしょうか？
もしくは`ios`, `android` などをetcにしてしまうか

2021-02-19 08:50 UTC, tani-takanori commented on docs/react-native/learn/todo-app/app-project-desc.md
> +- contexts: コンテクス
```suggestion
- contexts: コンテクスト
```

2021-02-19 08:50 UTC, tani-takanori commented on docs/react-native/learn/todo-app/app-project-desc.md
> +- @types: `.d.ts`ファイル
```suggestion
- @types: 型定義(`.d.ts` )ファイル
```
他は説明しているくらいのレベルにそろえてみました

2021-02-19 09:04 UTC, shkozake commented on docs/react-native/learn/todo-app/app-project-desc.md
> +最終的に出来上がるToDoアプリのプロジェクト構成は次の通りです。
`src`ディレクトリ構成の説明 

に変更しました。

2021-02-19 19:53 UTC, in-a-paddy approved these changes

2021-02-24 01:00 UTC, tani-takanori approved these changes

2021-02-24 01:02 UTC, merged