✨: テーマコンテキストのコンポーネント実装
ws-4020/mobile-app-crib-notes pull request #543
Opened 2021-11-05 10:35 UTC by kz-takahashi

## ✅ What's done

- [x] react-native-appearanceを導入
- [x] テーマコンテキストのコンポーネントを実装
  - [x] useContext(AppThemeContext)でAppThemeを取得できる
  - [x] 端末のダークモード設定に応じてAppThemeを切り替えられる (設定されている色は同一)
  - [x] React Native Elementsのテーマ機能を用いて、利用しているReact Native Elementsの部品についてAppThemeから取得した色をデフォルトのスタイルとして指定する
- [x] テーマコンテキストの型に関するコンテキスト設計のドキュメント側記載を修正
- [x] ReactNativeAppearance導入と色変更に伴い、App.test.tsx用のスナップショットを再生成

---

## Tests

- [ ] 実施した動作確認の内容をチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

以下のコマンドのいずれかをこのプルリクエストのコメントとして投稿すると、
Azure Pipeline上でSantokuAppをビルドしてDeployGateへアップロードできます。
4種全てのビルドバリアントを対象にする場合はdeploy-all、
特定のビルドバリアントだけを対象にする場合はdeploy-ビルドバリアント名のコマンドを利用してください。

- /azp run deploy-all
- /azp run deploy-devSantokuAppDebugAdvanced
- /azp run deploy-devSantokuAppReleaseInHouse
- /azp run deploy-santokuAppDebugAdvanced
- /azp run deploy-santokuAppReleaseInHouse

## Devices

- [x] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [x] Android
  - [x] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

- どなたかにMac環境でpodfileとpodfile.lockの更新をお願いしたいです。
- どなたかにiPhone Simulator (もしくは実機) での動作確認をお願いしたいです。
- コンテキスト系のコードを入れるディレクトリを一旦 src/components/contexts 以下としましたが、より適切な場所があればご意見ください。

2021-11-05 11:28 UTC, in-a-paddy requested changes

2021-11-05 11:28 UTC, in-a-paddy commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
必要ですか？リポジトリでも触れられてますが、React Nativeの[Appearance](https://reactnative.dev/docs/appearance)や[useColorScheme](https://reactnative.dev/docs/usecolorscheme)では何か機能が不足している？

https://github.com/expo/react-native-appearance
> ⚠️ Appearance in React Native core is recommended unless you have a good reason to use the library

2021-11-05 11:29 UTC, in-a-paddy commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
@kz-takahashi アーキのメンバにレビューをお願いしてもらいたいです。（部品の初回作成なので、特に）

2021-11-05 12:12 UTC, in-a-paddy commented on example-app/SantokuApp/src/components/contexts/theme/AppThemeContext.tsx
> +const AppThemeContext = createContext<AppTheme>(defaultAppTheme);
`useAppTheme`みたいなカスタムフックを用意してあげるケースが多いかな、と。

2021-11-09 06:47 UTC, kz-takahashi commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
確かにReact Native v63以降だと本体の方にAppearance増えていたのでそちらも試してみたところ、
以下の不具合に引っかかりました。
https://github.com/facebook/react-native/issues/28823
この不具合によって、現在のv0.63.4のReact NativeではuseColorSchemeでリアルタイムな値の変更を検出できず、アプリ起動中にOSのダークモード設定を切り替えても即時反映されませんでした。

このIssueの修正はChangelogを見る限りReact Nativeの0.64.3, 0.65.2, 0.66.2で段階的に取り込まれたようで、少なくとも0.66.2では直っているものと思われます。

React Nativeを0.66.2以降に上げた後はReact NativeのAppearanceやuseColorSchemeで問題ないと思うのですが、それまでの間はreact-native-appearanceを使う形でどうでしょうか。
それでよければ、ソースコードのコメントにも上記の旨を記載しておきます。

もしくは、その内バージョンアップすれば修正されるので、現時点では設定変更が即時反映されなくてもよいのであれば、React Native側のものを使うようにします。

2021-11-09 09:25 UTC, in-a-paddy commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
試してないのですが、`react-native-appearance`では治ってましたか？ちょっと気になるコメントがあったので。

> I also fixed the same bug in the react-native-appearance package. That PR was merged already expo/react-native-appearance#50 but I don't think its been published to NPM yet.

2021-11-09 09:48 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/contexts/theme/AppThemeContext.tsx
> +const AppThemeContext = createContext<AppTheme>(defaultAppTheme);
カスタムフックとして提供する形に修正しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/543/commits/13f6de90c71507577b57dd8a810e1471d428bae6
https://github.com/ws-4020/mobile-app-crib-notes/pull/543/commits/62960df9a431467e11f4b85d4cef85ede4f7f702

2021-11-09 09:51 UTC, kz-takahashi commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
一旦react-native-appearanceを使った理由がわかるようにコメントを追加しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/543/commits/e0c75bbc9e0547003d09c90984c07541306ca725
もう現時点からReact Nativeへ移行した方が良ければ修正します。

2021-11-09 09:52 UTC, kz-takahashi commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
コメントの再読み込みできてませんでした。
React Nativeの方を使う形で修正します。

2021-11-09 10:06 UTC, kz-takahashi commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
react-native-appearanceを使わない形に修正しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/543/commits/42705662c27fd3c8ea944237c9ff50860c7d9d97

2021-11-09 11:45 UTC, kozake commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
既に使わない形に修正となっていますが、react-native-appearanceを使わない形とし、Expoのバージョンアップで対応でいいかと思います。
実際のプロジェクトで即時反映できないのは問題なので、高橋さんの対応をとるかも知れませんが、今回はサンプルアプリケーションという位置づけもあり、制約事項に倒すのがいいかと思いました。

2021-11-09 14:38 UTC, in-a-paddy commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
> 実際のプロジェクトで即時反映できないのは問題なので

とも限らないかなぁ、と思ってます。まだ、ダークモードで異なるテーマにするアプリを作ったことないからかもしれないです。ライトモードとダークモードで同じテーマを使うなら問題にはならないですよね？

2021-11-09 14:48 UTC, in-a-paddy requested changes

2021-11-09 14:48 UTC, in-a-paddy commented on example-app/SantokuApp/src/components/contexts/theme/useAppTheme.ts
> +  const [appTheme, setAppTheme] = useState<AppTheme>(defaultAppTheme);
これ、アプリ画面から `useAppTheme` したらコンポーネントごとにステートを持ってしまうのでは、、、？

イメージしてたのは、こんなやつです。

```typescript
const useAppTheme = useContext(AppThemeContext)
```

あと、こうしたら `defaultAppTheme` も不要になって、より厳密になると思ったんですが、できませんでしたっけ？

```typescript
const getAppTheme = (colorSheme: string) => colorScheme === 'dark' ? darkModeAppTheme : lightModeAppTheme;

const colorScheme = useColorScheme();
const [appTheme, setAppTheme] = useState<AppTheme>(getAppTheme(colorScheme));
```

2021-11-09 14:48 UTC, in-a-paddy commented on example-app/SantokuApp/src/components/contexts/theme/AppThemeContext.tsx
> +const AppThemeContext = createContext<AppTheme>(defaultAppTheme);
https://github.com/ws-4020/mobile-app-crib-notes/pull/543#pullrequestreview-801373182

2021-11-10 00:28 UTC, creature-water-valley commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
僕も、React Native側を使用で良いのかなって思います。
ダークモード用のテーマを適用するアプリって意外と少ない印象で、まだ当たり前機能として定着してないようにも思うので、制限ありでも良いかなと思いました。
（ExpoがReact Nativeを推奨しているのなら、それに従っておこうというお気持ちもあり）

ライトとダークが異なるテーマで、どうしても即時反映したいっていう要件があった場合のフォールバック手段として、react-native-appearanceもあるよっていうのをドキュメントに残しておくのがいいですかね。
（react-native-appearanceで正しく動作するか検証する時間があればですが）

2021-11-10 02:48 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/contexts/theme/useAppTheme.ts
> +  const [appTheme, setAppTheme] = useState<AppTheme>(defaultAppTheme);
useContextを使う形に修正しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/543/commits/052173663b96eee1f662e067c5dfa0f82f6881b4

2021-11-10 10:13 UTC, in-a-paddy commented on example-app/SantokuApp/src/components/contexts/theme/AppThemeContext.tsx
> +const AppThemeProvider: React.FC = ({children}) => {
`AppThemeProvider`という名前ですが、実際には`AppThemeContext.Provider`だけでなく、RNEの`ThemeProvider` もラップしてしまっているので、`WithAppTheme`という名前とかにしたほうがわかりやすい気がしました。

それか、分けて`RNEThemeProviderAdapter`みたいなコンポーネントを作るのもありかもと思います。

2021-11-10 10:15 UTC, in-a-paddy commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
Archiveされてるパッケージをおすすめするのはちょっとなぁ、と個人的には感じるので、ドキュメントにも残しておかなくていいんじゃないかなぁ、、、

2021-11-11 00:21 UTC, creature-water-valley commented on example-app/SantokuApp/package.json
> +    "react-native-appearance": "~0.3.3",
ほんとだ、Archiveされてるんだ。あー、それはドキュメントに残してもなという感じだね。

2021-11-11 01:43 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/contexts/theme/AppThemeContext.tsx
> +const AppThemeProvider: React.FC = ({children}) => {
WithAppThemeという名前に変更しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/543/commits/4e13b69aa4b7f3660c4dd117b3eb5d2b38b982ec

2021-11-11 01:44 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/contexts/theme/AppThemeContext.tsx
> +  const reactNativeElementsTheme = getReactNativeElementsTheme(appTheme);
メモ化対応しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/543/commits/4e13b69aa4b7f3660c4dd117b3eb5d2b38b982ec

2021-11-11 05:58 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/contexts/theme/AppTheme.ts
> +export type AppTheme = {
`contexts`っていうディレクトリはなしでも良いかなって思ったのですがどうでしょう？
`theme`の中には、`contexts`に関係ないもの（結果的にContext経由で取得するようなオブジェクトやtypeなんでしょうが）もあるので、単純に`theme`だけの方が良いかもと思いまして。

2021-11-11 06:30 UTC, yuto-takeshita-tis commented
@kz-takahashi @OshitaTatsuya 
Mac環境で動作確認し、iOSシミュレータ/実機ともに問題なく動くことを確認しました。

2021-11-11 07:05 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/contexts/theme/AppTheme.ts
> +export type AppTheme = {
方式/アプリチーム交えてZoomで話した結果でも、components直下に直接機能ごとのディレクトリを置いてよいのではという結論になったので、components/theme に移動させました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/543/commits/112ce4d546efcd4c003918f228c83c05692baa09

2021-11-11 08:38 UTC, creature-water-valley approved these changes

2021-11-11 08:44 UTC, in-a-paddy approved these changes

2021-11-11 08:55 UTC, yuto-takeshita-tis approved these changes

2021-11-11 08:59 UTC, merged