✏️: テストに関する事項の内容の見直しと修正
ws-4020/mobile-app-crib-notes pull request #548
Opened 2021-11-08 05:25 UTC by OshitaTatsuya

## ✅ What's done

- [x] テスト計画側で記載すべき内容の修正
- [x] モバイルアプリケーションに関するものだけを記載していることを注意書きで追記
- [x] テスト実施環境に性能に関する事項を参照するよう

---

## Tests

- [x] lintチェックをして、文章を確認
- [x] ローカル環境で`npm start`で実行して、ブラウザで表示崩れ等がないことを確認

以下のコマンドのいずれかをこのプルリクエストのコメントとして投稿すると、
Azure Pipeline上でSantokuAppをビルドしてDeployGateへアップロードできます。
4種全てのビルドバリアントを対象にする場合はdeploy-all、
特定のビルドバリアントだけを対象にする場合はdeploy-ビルドバリアント名のコマンドを利用してください。

- /azp run deploy-all
- /azp run deploy-devSantokuAppDebugAdvanced
- /azp run deploy-devSantokuAppReleaseInHouse
- /azp run deploy-santokuAppDebugAdvanced
- /azp run deploy-santokuAppReleaseInHouse

## Devices

- [x] Windows 10
  - [x] Chrome

## Other (messages to reviewers, concerns, etc.)

なし

2021-11-09 15:12 UTC, in-a-paddy commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +エミュレータとシミュレータでの検証時には、以下の要素を網羅できるように構成を決定します。
単体テストのときのエミュレータ/シミュレータの画面サイズは指定しないで良いんだっけ？何も触れられてないので、よくわからんってなるかな、と。

2021-11-10 05:00 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +エミュレータとシミュレータでの検証時には、以下の要素を網羅できるように構成を決定します。
単体テストの機種選定の特記事項と画面サイズの選定基準を追加 090231fa9eb6c993232e7dafc130015e104f7e4c

2021-11-10 06:16 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +エミュレータとシミュレータでの検証時には、以下の要素を網羅できるように構成を決定します。
改めて読み返して内容が間違っているので修正 e7e708c3a3e34584f659f0cad12c2961bff4019f

2021-11-11 16:57 UTC, in-a-paddy requested changes

2021-11-11 16:57 UTC, in-a-paddy commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +ここでは、一般的なテストに関する事項は記載しておりません。主にモバイルアプリケーションとしてのテストに関する事項に絞り記載しています。
一般的なテストではあるよなぁ、と思ってしまったので、削っちゃって良いんじゃないかな？

```suggestion
ここでは、主にモバイルアプリケーションとしてのテストに関する事項に絞り記載しています。
```

2021-11-11 16:57 UTC, in-a-paddy commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +これらのテストは、開発チームにて実施します。それぞれのテスト内容に関する詳細は、別途作成するテスト計画の中で定義します。
体制の話が出てくるのに違和感を感じたので、削っちゃって良いんじゃないかな

```suggestion
それぞれのテスト内容に関する詳細は、別途作成するテスト計画の中で定義します。
```

2021-11-11 16:57 UTC, in-a-paddy commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +- エミュレータとシミュレータで検証する時のOSバージョンと実機で検証したOSバージョンが同一の場合、省略することがあります。
```suggestion
- エミュレータ、シミュレータと実機で、テスト対象とするOSバージョンが重複しないよう選択します。
```

2021-11-11 16:57 UTC, in-a-paddy commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +実機での検証に用いる具体的な機種はテスト計画時に選定します。上記以外のテスト実施環境に関する特記事項は以下となります。
特記事項ってちょっと大げさかな、と。

```suggestion
実機での検証に用いる具体的な機種はテスト計画時に、以下の方針に従って選定します。
```

あと、テスト計画に書いてある選定条件と整合性が取れてないんだけど、先にこっちから見たほうが良いんだよね？

2021-11-12 10:02 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +ここでは、一般的なテストに関する事項は記載しておりません。主にモバイルアプリケーションとしてのテストに関する事項に絞り記載しています。
`一般的なテスト`の意味が誤解されるので消します

2021-11-12 10:15 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +これらのテストは、開発チームにて実施します。それぞれのテスト内容に関する詳細は、別途作成するテスト計画の中で定義します。
ここ以外とも比較して、体制部分は浮いているので削除します。

2021-11-12 10:18 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +実機での検証に用いる具体的な機種はテスト計画時に選定します。上記以外のテスト実施環境に関する特記事項は以下となります。
確認の優先度は、テストに関する事項 → 全体テスト計画 → 単体テスト計画の順番でお願いします。

2021-11-16 00:57 UTC, kozake commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +
他の非機能要件と比較して、ここだけ注意事項を書いている理由はなんでしょうか。

2021-11-16 00:57 UTC, kozake commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
>  タブレット端末はこのアプリの主要なターゲットにしていないため、実機での検証の対象外とします。
```suggestion
タブレット端末はこのアプリの主要なターゲットにしていないため、実機での検証は対象外とします。
```

2021-11-16 11:48 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +テスト時のOSバージョンは、サポート対象OSバージョンの最新／最古とその間にリリースされているOSバージョンから選定します。
文言を統一する修正 ad185115b17b96cf05d5d6aea39a2b8f2203c89b

2021-11-16 12:02 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +
ここでの内容はモバイルアプリケーションに関する部分のみに限定していることを伝えたく、注意書きにしていますが、
そもそも非機能要件が、モバイルアプリケーションとして作成しているため、あえて協調する必要性がないと思ったので、削除しました。 eae19e4c51936a5110c1445eae2aeebedfe02701

2021-11-18 01:34 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +    - 特殊な形状のものを除いたテスト対象端末の中から最小サイズと最大サイズの2パターン
テスト対象の画面解像度の選定基準を見直して修正 b308de3b4da6e98b30e1defeef5bb2c9a3d50097 177cddc140d43179d36535009aef47d8696dc4aa

2021-11-18 01:36 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +エミュレータとシミュレータでの検証時には、以下の要素を網羅できるように構成を決定します。
テスト対象の画面解像度の選定基準の見直しとあわせて、再度修正しました b308de3b4da6e98b30e1defeef5bb2c9a3d50097

2021-11-18 07:13 UTC, kozake commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +- 単体テストで用意するテスト環境の機種数は、エミュレータ／シュミレータと実機それぞれでテスト対象OSが許容する1機種を用意するものとします。機種毎に相違する画面解像度、アスペクト比を含めた網羅確認は、結合テストで実施するものとします。
単体テストでこれだけのバージョンで全パターンテストするのは大変だと感じました。
エミュレータでの実施テストは、正常系の動作確認とレイアウト確認（見た目が崩れていないかどうか）に留めるのは如何でしょうか。


```suggestion
- 単体テストで用意するテスト環境の機種数は、エミュレータ／シュミレータと実機それぞれでテスト対象OSが許容する1機種を用意するものとします。機種毎に相違する画面解像度、アスペクト比を含めた網羅確認は、結合テストで実施するものとします。
- 開発コストを抑えるため、エミュレータでの実施テストは、正常系の動作確認とレイアウト確認（見た目が崩れていないかどうか）に留めます。
```

2021-11-19 08:38 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +- 単体テストで用意するテスト環境の機種数は、エミュレータ／シュミレータと実機それぞれでテスト対象OSが許容する1機種を用意するものとします。機種毎に相違する画面解像度、アスペクト比を含めた網羅確認は、結合テストで実施するものとします。
単体テストとして、OSバージョン毎にテストを実施するもので考えておりましたが、
整理と見直しをして、最多シェアまたは、最新のOSバージョン×機種でテストを実施する方向とします。
また、これまでの内容が限定的な内容であり、方法まで記載された内容であったため、
全体を見直して、修正しました。 fc1d0facc4264c24997f0dad4dffc7f063848b97

2021-11-25 07:59 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +テスト検証観点として、大きく以下のようにカテゴライズしてテストします
```suggestion
テスト検証観点として、大きく以下のようにカテゴライズしてテストします。
```

2021-11-25 08:59 UTC, a-mtn595COMPETIZIONE approved these changes

2021-11-25 08:59 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +| 手動 | エミュレータ／シミュレータと実機にて、手動テストを実施する | レイアウト崩れがないかなどの表示確認と性能を検証する |
機能確認も手動ですかね？

2021-11-25 09:00 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +ただしこのテストは外部のセキュリティ診断サービスを使用し、そのフィードバックを受けることで対応します。そのため開発時は有識者によるソースコードレビューのレベルとします。
```suggestion
ただし、このテストは外部のセキュリティ診断サービスを使用し、そのフィードバックを受けることで対応します。そのため開発時は有識者によるソースコードレビューのみとします。
```

2021-11-25 09:04 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +そのため配信対象OSバージョンの中からさらにユーザ使用率が高いバージョン、大きな機能追加・変更があったバージョンという観点で絞り込むものとし、これをテスト対象OSバージョンとします。
「大きな機能追加・変更があった」というのが、具体的にどういったものを指すのか曖昧と思いました。
また、大きな変更でなくてもアプリへの影響度が高そうであれば対象には含めるかなと。
「テストに必要と思われるバージョンは、アプリへの影響を都度判断して選定します」というのが言えればいいかと思いますが、いかがでしょう。

2021-11-25 09:08 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +| [性能テスト](#性能テスト) | モバイルアプリケーションのレスポンス遅延がないことと、メモリリークが発生しないことを検証する |
後述ではCPUやメモリの使用率を見ると言っているので、少し内容が合ってない気がします。

2021-11-25 09:34 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +| 手動 | エミュレータ／シミュレータと実機にて、手動テストを実施する | レイアウト崩れがないかなどの表示確認と性能を検証する |
テスト内容に機能確認を追記 c160d60605290ea89d1b3f3da59242475c169cdf

2021-11-25 09:43 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +そのため配信対象OSバージョンの中からさらにユーザ使用率が高いバージョン、大きな機能追加・変更があったバージョンという観点で絞り込むものとし、これをテスト対象OSバージョンとします。
アプリへの影響があるものがポイントとなるので、その観点で内容を修正 adc47bbe90830fe9be19b54c869dfb0ccdea9de6

2021-11-25 09:51 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +| [性能テスト](#性能テスト) | モバイルアプリケーションのレスポンス遅延がないことと、メモリリークが発生しないことを検証する |
性能テストの検証概要を見直して、修正 1dd511eb0cc53a0a7eb59de12143c01167387ba5

2021-11-25 14:26 UTC, in-a-paddy commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +  | 選定基準 | 選定内容 |
選定基準として表を書くなら、シェアの話も表に入れないと勘違いしそう。下の表もかな。

2021-11-26 01:08 UTC, yuto-takeshita-tis approved these changes

2021-11-26 01:12 UTC, OshitaTatsuya commented on website/docs/react-native/santoku/requirements/non-functional/test-outline.mdx
> +  | 選定基準 | 選定内容 |
シェアの選定基準を追加。同じ表に入れると分かりにくい表現になると思い、表を分けました a277d5250cf8b3bcd1716a351ae7118096c555f1

2021-11-26 02:36 UTC, in-a-paddy approved these changes

2021-11-26 02:42 UTC, merged