✏️: 画面：スプラッシュスクリーンの画面設計を追加
ws-4020/mobile-app-crib-notes pull request #550
Opened 2021-11-08 11:25 UTC by yuto-takeshita-tis

## ✅ What's done

- [x] 画面：スプラッシュスクリーンの画面設計書を追加しました。

---------------------------------
※後続のタスク
- 画面一覧の更新（各設計書へのリンクを張る）

## Tests

- [x] npm run lint:textを実行して、lintエラーにならないことを確認
- [x] npm run lint:mdを実行して、lintエラーにならないことを確認
- [x] npm run startを実行して、表示内容を確認

## Devices

- [x] Macbook
  - [x] Chrome

## Other (messages to reviewers, concerns, etc.)

- 画面設計に関するPRを並行して投げているため、目次やsidebarについてはPRが承認され次第、整えていきます。
- 初期化処理の内容が本来とは異なりますが、サイクル1で実装する分のみ記載しています。

2021-11-09 01:06 UTC, yuto-takeshita-tis commented
エラーが起きているので、解消するまでレビューは少々お待ちください

2021-11-10 02:37 UTC, dodo-lab commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +  - 有効な利用規約に同意済みか確認する。
メッセージの読み込みは含まれませんか？

2021-11-10 02:37 UTC, dodo-lab commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +- 表示する画像は、端末サイズごとに用意します。
`端末サイズごと`がどこまでを指しているか分からなくて、曖昧に見えます。

2021-11-10 02:37 UTC, dodo-lab commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +（※1）[アプリスタートの種類](/react-native/santoku/application-architecture/life-cycle-management/overview.mdx)の、コールドスタートとウォームスタートが該当します。
リンクはページトップではなく、該当の項目まで飛ばしてあげた方が親切かと思いましたが、いかがでしょう？

2021-11-10 02:37 UTC, dodo-lab commented on website/docs/react-native/santoku/design/screen-specs/message-list.mdx
> +| app            | 初期化エラー          | アプリの初期処理でエラーが発生しました。アプリを再起動してください。                |
ユーザーにとっては、`処理`自体にあまり興味がないところだと思います。シンプルに「アプリの起動に失敗しました」はどうでしょう？

2021-11-10 02:37 UTC, dodo-lab commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +    - APIから正常レスポンスが返却された場合、返却値によって分岐します。
リスト記述のところは断定表現で統一ですかね？ここだけ丁寧語だったので。

2021-11-10 02:42 UTC, dodo-lab commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +| 初期化失敗 | メッセージキー：`app.初期化エラー`をダイアログで表示し、ユーザにアプリ再起動を促す。<br />画面遷移はしない。 |
ダイアログでＯＫを押下したら、アプリ終了でも良い気がしました。スプラッシュスクリーンだけ表示されていても、ユーザーは何も出来ないので。

2021-11-11 07:30 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +  - 有効な利用規約に同意済みか確認する。
入ってますが、内部的な処理なので無くていいかなと思ってました。

10cadad
初期化処理のところは、基本的に方式設計の資料と合わせるように変更してみました。いかがでしょう？

2021-11-11 07:33 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +- 表示する画像は、端末サイズごとに用意します。
確かに仰る通りですね。端末サイズというか、ピクセル密度ごとに用意する、というのを言いたかったです。

すみません、改めて見返して思ったのですが、この一文必要ですかね？
画面設計書に書く内容ではない気がしており、ご意見伺いたいです。

2021-11-11 07:33 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +（※1）[アプリスタートの種類](/react-native/santoku/application-architecture/life-cycle-management/overview.mdx)の、コールドスタートとウォームスタートが該当します。
10cadad
修正しました

2021-11-11 07:35 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/message-list.mdx
> +| app            | 初期化エラー          | アプリの初期処理でエラーが発生しました。アプリを再起動してください。                |
10cadad
修正しました。
※他のPR指摘の対応で、メッセージキーの書き方を変更しています。ファイルの配置場所も変更になる予定ですが、それはマージ後に対応します。

2021-11-11 07:35 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +    - APIから正常レスポンスが返却された場合、返却値によって分岐します。
10cadad
すみません、誤記ですね。。修正しました

2021-11-11 07:38 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +| 初期化失敗 | メッセージキー：`app.初期化エラー`をダイアログで表示し、ユーザにアプリ再起動を促す。<br />画面遷移はしない。 |
10cadad
修正しました。

ただ、React Nativeでアプリ終了の実現方法がイメージついておらず。実現できそうではありますが、検証は実装フェーズにて行わせていただければと思います。（既に検証済みでしたらすみません）

2021-11-11 07:56 UTC, creature-water-valley commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +- 表示する画像は、端末サイズごとに用意します。
どうでしょうかねぇ。あってもいいような。

2021-11-11 08:07 UTC, creature-water-valley commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +| 初期化失敗 | メッセージキー：`app.初期化エラー`をダイアログで表示し、アプリを終了します。 |
Firebase Crashlyticsにログを送信した方が良いかなって思います。

2021-11-11 08:18 UTC, creature-water-valley requested changes

2021-11-11 08:18 UTC, creature-water-valley commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +-（起動処理中の画面となるため、種別は定義しません）
```suggestion
起動処理中の画面となるため、種別は定義しません。
```

2021-11-11 11:50 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +| 初期化失敗 | メッセージキー：`app.初期化エラー`をダイアログで表示し、アプリを終了します。 |
bee8ba1
追記しました

2021-11-11 11:55 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +- 表示する画像は、端末サイズごとに用意します。
d417ea9
一旦書いてみました。ちょっと内部的な書き方になった感はありますが、、、

よさげなリンクがあれば、それを貼っておいてもいいかと思い、Androidは↓を見つけたのですが、iOS版が見当たらず。
もし心当たりがあれば、ご教示いただけると助かります。（Qiitaは流石にダメですよね？）
https://developer.android.com/training/multiscreen/screendensities?hl=ja

2021-11-12 00:53 UTC, dodo-lab commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +- 表示する画像は、端末サイズごとに用意します。
iOSの方ですが、こちらはいかがでしょう？
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/

2021-11-15 00:59 UTC, yuto-takeshita-tis commented on website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx
> +- 表示する画像は、端末サイズごとに用意します。
ありがとうございます。使わせていただきました。
56224a0

2021-11-15 01:36 UTC, creature-water-valley approved these changes

2021-11-15 04:20 UTC, dodo-lab approved these changes

2021-11-15 04:23 UTC, merged