🚀: サイクル１のプロトタイプ実装
ws-4020/mobile-app-crib-notes pull request #561
Opened 2021-11-09 09:59 UTC by dodo-lab

## ✅ What's done

- [x] `react-native-webview`パッケージの追加
- [x] メッセージのロード処理完了後にコンポーネントをレンダーするよう修正
- [x] 開発環境のみデモ画面へ遷移するように修正
- [x] 共通コンポーネントの作成
  - [x] Button
  - [x] WebView
- [x] 利用規約同意画面作成

## ⏸ What's not done

- テストコードは各機能および共通部品の作業で実施予定
- ナビゲーション用のパラメータがメッセージ管理に対応できていないが、別途メッセージ管理の作業として実施予定
- WebAPIの呼び出し全般は各機能の作業で実施予定
  - 利用規約同意時のAPI呼び出し
  - アプリ起動時、利用規約同意済み判断でのAPI呼び出し
- WebViewでonError発生時のスナックバー表示は、利用規約のPBIで実施予定

---

## Tests

- [x] 実機とエミュレータでの動作確認
- [x] npm run lint でエラーが出ないこと
- [x] npm test でエラーが出ないこと

以下のコマンドのいずれかをこのプルリクエストのコメントとして投稿すると、
Azure Pipeline上でSantokuAppをビルドしてDeployGateへアップロードできます。
4種全てのビルドバリアントを対象にする場合はdeploy-all、
特定のビルドバリアントだけを対象にする場合はdeploy-ビルドバリアント名のコマンドを利用してください。

- /azp run deploy-all
- /azp run deploy-devSantokuAppDebugAdvanced
- /azp run deploy-devSantokuAppReleaseInHouse
- /azp run deploy-santokuAppDebugAdvanced
- /azp run deploy-santokuAppReleaseInHouse

## Devices

- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [x] Android
  - [x] エミュレータ (Pixel 3a/Android 11)
  - [x] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-11-10 05:45 UTC, creature-water-valley commented on example-app/SantokuApp/package.json
> +    "react-native-webview": "~11.14.2"
`expo install react-native-webview`でインストールしてますかね？

2021-11-10 05:48 UTC, creature-water-valley requested changes

2021-11-10 05:48 UTC, creature-water-valley commented on example-app/SantokuApp/package.json
> +    "react-native-webview": "~11.14.2"
https://github.com/ws-4020/mobile-app-crib-notes/blob/master/website/docs/react-native/santoku/development/dependency-management.md#packagejson%E3%81%A8podfilelock%E3%81%B8%E3%81%AE%E8%BF%BD%E5%8A%A0

2021-11-10 05:48 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +type Props = {
react-native-elementsのPropsをもらう形ではダメですかね？
渡せるものを制限したい感じですか？

2021-11-10 05:48 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +type Props = {
react-native-webviewのPropsをもらう形ではダメですかね？
渡せるものを制限したい感じですか？

2021-11-10 05:50 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      console.log(event.nativeEvent);
ログはLoggerを使用して出力したいですね。

2021-11-10 06:01 UTC, creature-water-valley requested changes

2021-11-10 06:26 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      console.log(event.nativeEvent);
動作確認用のログで、最終的には出力しないつもりでしたので削除しました。 7342d1b

2021-11-10 06:34 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +type Props = {
同じく個人的にはreact-native-elementsのButtonのPropsも基本的には受け取れるようにしたいです。
部品によっては、その部品として変更させたくないものは受け取ってもさらに上書きすることはあるかもしれませんが。

2021-11-10 06:34 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      console.log(event.nativeEvent);
デバッグ用の一時的なログでもう不要であれば消しておきたいです。

2021-11-10 06:34 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +  }));
オリジナルのWebViewは最初からreloadを持っているので、新しいrefは作成せず、単純にRNWebViewのrefにforwardRefでもらったrefをそのまま渡せばuseImperativeHandleは不要になるようにも見えましたが、それだと動かなかったでしょうか。

2021-11-10 06:34 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      onError={onError}
スナックバーについては`What's not done`に記載の通り、別のタスクで実施予定です。
Firebase Crashlyticsへのエラーログ送信も別タスクで実施予定ですが、`What's not done`に書けてなかったので追記しました。

2021-11-10 07:01 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      renderLoading={() => <ActivityIndicator size="large" color="#0000ff" />}
ご指摘の通りでした。対応しました。 9fe47af

2021-11-10 07:24 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +  return <RNEButton {...buttonProps} raised buttonStyle={style} containerStyle={style} />;
スタイル指定を分離しました。 0c1f3d0

2021-11-10 08:23 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +type Props = {
チーム内で話し合い、ButtonPropsを拡張する形に変更しました。 4f8275c

2021-11-10 08:59 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +type ButtonWidthSize = {
こんな感じの方がシンプルで良さそうかなって思いました。

```
const buttonWidthSizes = {
  small: 90,
  middle: 140,
  large: 200,
  full: '100%',
} as const;

type ButtonSizeType = keyof typeof buttonWidthSizes;
```

2021-11-10 09:13 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +type Props = {
チーム内で話し合い、WebViewPropsを拡張する形に変更しました。 4f8275c

2021-11-10 09:15 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +  }));
敢えて機能を絞ってましたが、チーム内で話し合い、forwardRefで受け渡す形に変更しました。 4f8275c

2021-11-10 09:20 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +type ButtonWidthSize = {
ありがとうございます。たしかに、こちらの方がシンプルですね。差し替えました。 c91a371

2021-11-10 09:36 UTC, creature-water-valley requested changes

2021-11-10 09:36 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +type ButtonWidthSize = {
これ、そもそもなんですが、small〜fullまでの定義って必要ですかね？
React Native elementsのButtonって文字数の長さに応じて拡がるような？

2021-11-10 09:42 UTC, dodo-lab commented on example-app/SantokuApp/package.json
> +    "react-native-webview": "~11.14.2"
できてなかったので、expo-installでインストールしました。 71ab24c
pod-install は、11/11に三谷さんにて実施いただく予定です。

2021-11-10 09:46 UTC, dodo-lab commented
> これ、そもそもなんですが、small〜fullまでの定義って必要ですかね？
> React Native elementsのButtonって文字数の長さに応じて拡がるような？

下記２つの理由があって、そのようにしました。
- アプリとしてある程度の粒度を合わせておきたい
- loadingを指定すると、サイズが変動するのを防ぐ

2021-11-11 01:46 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +type ButtonWidthSize = {
別のところにコメントしてしまってたので、こちらにも反映します。

> 下記２つの理由があって、そのようにしました。
> 
> - アプリとしてある程度の粒度を合わせておきたい
> - loadingを指定すると、サイズが変動するのを防ぐ

2021-11-11 01:59 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +  const widthStyle = {width: buttonWidthSizes[size ?? 'small']};
defaultPropsに`size: 'small'`で良さそうな気がしました。

2021-11-11 02:09 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +  const widthStyle = {width: buttonWidthSizes[size ?? 'small']};
試してみましたが、親からの`size`指定が必須になってしまうため、このままで進めたいと思います。

2021-11-11 02:15 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      }
onScrollEndが指定されている場合のみこの辺の計算を行うようにした方がよさそう。

2021-11-11 02:33 UTC, creature-water-valley requested changes

2021-11-11 02:33 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +        onScrollEnd?.();
iOS（シミュレータ）だと、初期表示でも呼ばれてますね。

コンテンツのロードを待ってからじゃないとダメかもです。

2021-11-11 02:33 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +        onScrollEnd?.();
後、スクロールを最下部まで持って行ったら、イベントが何回も呼ばれちゃってますね。

2021-11-11 02:33 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      const scrollY = event.nativeEvent.contentOffset.y + event.nativeEvent.layoutMeasurement.height + 1;
`contentInset`は計算に含めなくても良いですかね？

2021-11-11 02:33 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/Button.tsx
> +  const widthStyle = {width: buttonWidthSizes[size ?? 'small']};
`!`を付けるのもアレなんで、しょうがないですね。
了解しましたー

2021-11-11 02:37 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      }
たしかに、その方が効率良いですね。対応しました。 1fba804

2021-11-11 02:37 UTC, creature-water-valley commented on example-app/SantokuApp/src/screens/account/TermsOfServiceAgreementScreen.tsx
> +  const onWebViewError = () => {
`useCallback`でラップした方が良いかなって思いました。

2021-11-11 02:37 UTC, creature-water-valley requested changes

2021-11-11 02:37 UTC, creature-water-valley commented on example-app/SantokuApp/src/screens/account/TermsOfServiceAgreementScreen.tsx
> +  const onReload = () => {
`useCallback`でラップした方が良いかなって思いました。

2021-11-11 02:44 UTC, creature-water-valley commented on example-app/SantokuApp/src/screens/account/TermsOfServiceAgreementScreen.tsx
> +          onHttpError={onWebViewError}
エラーページが表示された場合は、「同意」ボタンを非表示にした方が良いのではと思いました。
現状だと、エラーページを全部読むと同意できちゃいます。

2021-11-11 03:05 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +        onScrollEnd?.();
以下の通り、対処しました。 892d042
- ロード終了してからスクロール検知するよう修正しました。
- onScrollEndのイベント発行回数を指定できるように
  - １回だけ(デフォルト) or 毎回発行

2021-11-11 04:27 UTC, dodo-lab commented on example-app/SantokuApp/src/screens/account/TermsOfServiceAgreementScreen.tsx
> +          onHttpError={onWebViewError}
エラー発生時はWebViewが表示されず、独自UIでエラーメッセージとリロードボタンを配置してます。そのため、エラー発生時、同意ボタンは非活性のままで押下できません。onHttpError発生時はWebViewをそのまま表示する方針になるかもしれませんが、そこは利用規約 正式対応のタスクでの対応とさせて欲しいです。

2021-11-11 06:06 UTC, dodo-lab commented on example-app/SantokuApp/src/screens/account/TermsOfServiceAgreementScreen.tsx
> +  const onWebViewError = () => {
対応しました。 129b690

2021-11-11 06:06 UTC, dodo-lab commented on example-app/SantokuApp/src/screens/account/TermsOfServiceAgreementScreen.tsx
> +  const onReload = () => {
対応しました。 129b690

2021-11-11 06:11 UTC, creature-water-valley commented on example-app/SantokuApp/package.json
> +    "react-native-webview": "~11.14.2"
Podfile.lock更新してpushしましたー

2021-11-11 06:12 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +      const scrollY = event.nativeEvent.contentOffset.y + event.nativeEvent.layoutMeasurement.height + 1;
`contentInset`の余白分は特に見る必要がなく、利用規約コンテンツの最後まで見れたら問題ないため、計算しない方針で進めたいと思います。

2021-11-11 06:18 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +        onScrollEnd?.();
`onceScrollEnd`は、booleanじゃなくて、Functionにした方がわかりやすいかも？と思いました。

利用規約とかでは、`onceOnScrollEnd`のみを使用するイメージです。

2021-11-11 06:19 UTC, creature-water-valley commented on example-app/SantokuApp/src/screens/account/TermsOfServiceAgreementScreen.tsx
> +          onHttpError={onWebViewError}
> onHttpError発生時はWebViewをそのまま表示する方針になるかもしれませんが、そこは利用規約 正式対応のタスクでの対応とさせて欲しいです。

了解ですー。

2021-11-11 06:35 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +        onScrollEnd?.();
たしかに、使い勝手が良さそうです。対応しました。 f5b29ca

2021-11-11 07:07 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +        onScrollEnd?.();
`onScrollEndOnce`の方がいいかもと思いました。
（IDEでonで補完する場合が多いのと、jestとかもxxxxOnceみたいなメソッド名になっているので）

何度もすいません🙏

2021-11-11 07:25 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +        onScrollEnd?.();
いえいえ、こちらこそ細かいところに配慮できてなくて申し訳ないです。対応しました。 845af58

2021-11-11 07:32 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +  const {onScrollEnd, onScrollEndOnce: onceScrollEnd, ...webViewProps} = props;
細かい所ですが、onceScrollEndに名前を変えずに処理内でもonScrollEndOnceで通した方が読みやすいと思います。

2021-11-11 07:38 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +  const {onScrollEnd, onScrollEndOnce: onceScrollEnd, ...webViewProps} = props;
おっと。。そんなつもりなかったですが、VSCodeの`シンボル名の変更`機能で自動的に変換されたっぽいです。対応しました。 71a521e

2021-11-11 07:54 UTC, kz-takahashi approved these changes

2021-11-11 08:37 UTC, creature-water-valley approved these changes

2021-11-11 08:39 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +import React, {useCallback, useState} from 'react';
↓で話した結果のディレクトリ構成に変更お願いします。

https://github.com/ws-4020/mobile-app-crib-notes/pull/543#discussion_r747243909

2021-11-11 09:04 UTC, dodo-lab commented on example-app/SantokuApp/src/components/basics/WebView.tsx
> +import React, {useCallback, useState} from 'react';
対応しました。 8504872

2021-11-11 09:46 UTC, creature-water-valley approved these changes

2021-11-11 10:50 UTC, merged