🌱: SantokuApp BackendからFCMにデバイス単位のPush通知を送信する機能を追加
ws-4020/mobile-app-crib-notes pull request #667
Opened 2021-12-08 07:34 UTC by creature-water-valley

## ✅ What's done

- [ ] 時間割開始APIのPush通知送信部分を実装

## ⏸ What's not done

* FCMトークンの管理と取得は未実装です。
* 時間割開始APIの内、Push通知送信以外は暫定です。
* Push通知送信に関しても、送信する内容は暫定です。

---

## Tests

- [ ] 時間割開始APIをCurlなどで実行して、FCMのコンソールでPush通知がきていることを確認

以下のコマンドのいずれかをこのプルリクエストのコメントとして投稿すると、
Azure Pipeline上でSantokuAppをビルドしてDeployGateへアップロードできます。
4種全てのビルドバリアントを対象にする場合はdeploy-all、
特定のビルドバリアントだけを対象にする場合はdeploy-ビルドバリアント名のコマンドを利用してください。

- /azp run deploy-all
- /azp run deploy-devSantokuAppDebugAdvanced
- /azp run deploy-devSantokuAppReleaseInHouse
- /azp run deploy-santokuAppDebugAdvanced
- /azp run deploy-santokuAppReleaseInHouse

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-12-09 01:57 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/PushNotifier.java
> +            throw new RuntimeException("Failed to send message to Firebase Cloud Messaging.", e);
メッセージ送信失敗時にループを終了して残りのトークンが破棄されるのがいいかが気になります。
ログはいて続行だとダメですか？

2021-12-09 01:57 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/PushNotifier.java
> +      PushNotification pushNotification, List<PushNotificationToken> tokens) {
pub/subの方式がいいかと思いますが、今回はモバイル側の方式検討がメインなのでそこまではいいかと思います。ただ、非同期呼出にはしておきたいですね。

2021-12-09 01:57 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/EndTime.java
> +}
値オブジェクトなので、equalsとhashcodeメソッドを用意したほうがいいのではないでしょうか。
こちらもLocalTimeValue<T>を作ってもいい気がしますが。

2021-12-09 01:57 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/notification/PushNotificationToken.java
> +public class PushNotificationToken {
毎回、equalsとhashcodeメソッドを生やすの面倒なので、StringValue<T> クラスを作って継承したほうがいいですかね？

2021-12-09 01:57 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/PeriodList.java
> +  public List<Period> value() {
リストオブジェクト要りますかね？
`value` をそのまま外に出すのであれば必要ない気がします。

2021-12-09 01:57 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/StartTime.java
> +  }
値オブジェクトなので、equalsとhashcodeメソッドを用意したほうがいいのではないでしょうか。

2021-12-09 01:57 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/TimetableDate.java
> +  }
値オブジェクトなので、equalsとhashcodeメソッドを用意したほうがいいのではないでしょうか

2021-12-09 01:57 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/TimetableStartedAt.java
> +}
値オブジェクトなので、equalsとhashcodeメソッドを用意したほうがいいのではないでしょうか

2021-12-09 08:26 UTC, kz-takahashi commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/PushNotifier.java
> +            String response = FirebaseMessaging.getInstance().send(message);
複数の宛先に同一のメッセージを送ることになると思うので、ループせずにsendMulticastでまとめて送った方がリクエスト数が減らせて、エラーハンドリングも楽になりそうです。
https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/messaging/FirebaseMessaging#public-batchresponse-sendmulticast-multicastmessage-message

2021-12-10 02:15 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/EndTime.java
> +}
SPA側に合わせてStringしか作ってませんでしたが、作るように変更しましたー
3ceb37e8da222dac216bccbe7d6310d3396aa17b

2021-12-10 02:15 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/notification/PushNotificationToken.java
> +public class PushNotificationToken {
こちらもSPA側に合わせて作っていませんでしたが、作るように変更しましたー
3ceb37e8da222dac216bccbe7d6310d3396aa17b

2021-12-10 02:16 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/PeriodList.java
> +  public List<Period> value() {
こちらもSPA側に合わせてましたが、個人的には同じく不要かと思っているので、消しましたー
3ceb37e8da222dac216bccbe7d6310d3396aa17b

2021-12-10 02:16 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/StartTime.java
> +  }
3ceb37e8da222dac216bccbe7d6310d3396aa17b

2021-12-10 02:16 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/TimetableDate.java
> +  }
3ceb37e8da222dac216bccbe7d6310d3396aa17b

2021-12-10 02:16 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/TimetableStartedAt.java
> +}
3ceb37e8da222dac216bccbe7d6310d3396aa17b

2021-12-10 02:55 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/PushNotifier.java
> +            throw new RuntimeException("Failed to send message to Firebase Cloud Messaging.", e);
ログ出力して続行するように変更しましたー
ff6ebc38f51444bef37e8a43891d40774ee39134

2021-12-10 02:56 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/PushNotifier.java
> +      PushNotification pushNotification, List<PushNotificationToken> tokens) {
NablarchのRest APIで非同期処理がなさそう？だったので、今回は同期処理としたいです。
自前で非同期処理を実施するとなると、スレッドローカルに保存されている内容の引き継ぎとかが大変そうなので。

2021-12-10 02:57 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/PushNotifier.java
> +            String response = FirebaseMessaging.getInstance().send(message);
ですねー。ドキュメントも見ずにそのまま持って来ちゃいました。。。
ff6ebc38f51444bef37e8a43891d40774ee39134

2021-12-10 05:48 UTC, creature-water-valley commented
/azp run deploy-devSantokuAppReleaseInHouse

2021-12-10 05:53 UTC, creature-water-valley commented
/azp run deploy-devSantokuAppReleaseInHouse

2021-12-10 06:39 UTC, creature-water-valley commented
/azp run deploy-devSantokuAppReleaseInHouse

2021-12-10 09:54 UTC, creature-water-valley commented
/azp run deploy-devSantokuAppReleaseInHouse

2021-12-10 10:40 UTC, creature-water-valley commented
/azp run deploy-devSantokuAppReleaseInHouse

2021-12-13 11:20 UTC, in-a-paddy commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/TimetableStartNotifier.java
> +    pushNotificationRepository.notifyToDevice(
たぶん、500件ごとに分割しないといけないわ

2021-12-13 11:22 UTC, in-a-paddy commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/TimetableStartNotifier.java
> +    pushNotificationRepository.notifyToDevice(
`PushNotifier`側でやることか

2021-12-15 09:38 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/timetable/TimetableStartNotifier.java
> +    pushNotificationRepository.notifyToDevice(
41b14e971930e1eefe0b8ccc8a939b318bba5b94

2021-12-15 09:39 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/PushNotifier.java
> +public class PushNotifier implements PushNotificationRepository {
41b14e971930e1eefe0b8ccc8a939b318bba5b94

2021-12-15 09:46 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/PushNotifier.java
> +      case INVALID_ARGUMENT:
エラーの場合は、同じログを出力するように変更しました。
`UNREGISTERED `の場合は、そのトークンを返却するようにしました
（デバイストークンの削除は、このドメインの役割じゃないと思ったので、UnregisterdTokensを返却して、違うドメインで実施）

41b14e971930e1eefe0b8ccc8a939b318bba5b94
0fa3a67da424793c0da86df5b656954f6df1d82f

2021-12-17 05:20 UTC, creature-water-valley commented
/azp run deploy-devSantokuAppReleaseInHouse

2021-12-20 04:12 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/repository/PushNotificationRepository.java
> +public interface PushNotificationRepository {
謎に`Repository`にしてますね。。。
`PushNotifier`に変更しましたー

6048056298411b7db6d799dd88f980287ea0bb9a

2021-12-20 04:31 UTC, in-a-paddy commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/core/ValueObject.java
> +    this.value = value;
個人的には、VO自体はnullにしない方が扱いやすいのではないかと思うのですが、どうでしょう？代わりに、VOの値としてnullは許容したほうが便利なことが多いかな、と。

2021-12-20 04:48 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/core/ValueObject.java
> +    this.value = value;
値オブジェクトの値はnullを許容しない方針にした方が、不具合の温床も少なくなりベターだとは僕は思います。
が、なんだかんだ値を決めづらい場面も経験上あった気がして、一律nullを許容しないは大変なのかなという印象です。

例えば、今回はドメインのモデルには入れてませんが、Push通知のアイコン（アイコンのPath）をValueObjectとして定義した場合、アイコンを設定しない場合はnullを許容した方が便利なのかなって思いました。

2021-12-20 04:50 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/Account.java
> +    this.devices = devices;
やはり、そうですかね。僕も作りながらそうかもとは思いつつ、どこで集約しようか（PresentationかUsecaseか）迷いそうだったので、一旦アカウントに含めちゃいました。

2021-12-20 05:03 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/Account.java
> +    this.devices = devices;
そして、アカウントの集約にしない場合は、デバイスドメインにした方が良いですかね？（今は、アカウントドメインの中にデバイス関連のモデルを定義）

その場合、デバイストークン管理APIのパスも変えた方が良い？（現状は、`/account/me/device-token`）

2021-12-20 07:25 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/core/ValueObject.java
> +    this.value = value;
どちらにしようか、少し会話しました。
どちらにもメリ・デメがありますが、今回は、値オブジェクトの値にはnullを許容しない方針としたいと思います。

結論に至る理由としては、以下です。

- ValueObjectクラスで一括で`Objects.requireNonNull`でnullの混入を防げる
  - 値オブジェクトの値はnullを許容し、値オブジェクト自体のnullを許容しないにした場合は、コードで縛ることができず、運用ルールを作成して守るという形になると思うのですが、それだとチームメンバーがそれなりの頻度で変わる今のチーム体制だと、ルール厳守ができなくなりそうだったため

2021-12-20 07:29 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/core/ValueObject.java
> +    this.value = value;
205bfe64641e6b06b88276e11a5190932cf6f747

2021-12-20 07:40 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/Account.java
> +    this.devices = devices;
口頭で話しましたが、デバイストークンはアカウントと所有の関係がありますが、集約として含めるかどうかは判断迷いますね。
集約のルールとして、「境界の内部に存在するオブジェクトへのアクセスは、そのルートを経由して制御すること」があります。
この場合デバイストークンの追加や削除はアカウントエンティティを介して操作しないといけないことになりますが、実際はデバイストークンそのものを指定して削除したいケースもあると思うので、外す方向にしましょうかという話をしました。
（集約として纏めるなら、アカウントそのものではなく、アカウントが保持するデバイストークンというエンティティを作ってもいいかもという話もしました）。

2021-12-20 07:45 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/Account.java
> +    this.devices = devices;
以下の方針としました
- アカウントの集約からは除外
- デバイスはアカウントドメインに属す
- アカウント情報の返却APIでは、Presentationレイヤーで集約する

c66e2ed18340c433b9d0a66f2edccb3740a900e9

2021-12-20 08:12 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/Devices.java
> +public class Devices extends ListValue<Device> {
`Device` が`AcountDeviceToken` になるのであれば、こちらも `AcountDeviceTokens` となるかと思いま。

2021-12-20 08:12 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/Nickname.java
>      validateLength(value);
`validateNotBlank`、`validateLength` も `StringValue` のメソッドに移したいですね。

2021-12-20 08:12 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/core/LocalDateTimeValue.java
> +public abstract class LocalDateTimeValue extends ValueObject<LocalDateTime> {
内部で日付をLocalDateTimeで扱いますか？
というのも、APIで扱う日付はUTCタイムゾーンの日付として扱うので、そこで変換が必要になるかなと思いまして。

2021-12-20 09:44 UTC, kz-takahashi commented
/azp run deploy-devSantokuAppReleaseInHouse

2021-12-21 00:34 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/DeviceTokenCreatedAt.java
> +    return new DeviceTokenCreatedAt(LocalDateTime.now(Clock.systemUTC()));
cc669d6b18c37b0b8dc8d7c8df18d664c1723967

2021-12-21 00:36 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/core/LocalDateTimeValue.java
> +public abstract class LocalDateTimeValue extends ValueObject<LocalDateTime> {
デバイストークンの登録日時なんかは、バックエンド内でしか使用しないので、LocalDateTimeで扱って良いかなと思ってます。

2021-12-21 04:37 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/core/LocalDateTimeValue.java
> +public abstract class LocalDateTimeValue extends ValueObject<LocalDateTime> {
会話した結果、`OffsetDateTime`で統一することにしましたー

92d1a492011eed31bf7fc293b5fe94bdf2d988d6

2021-12-21 04:37 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/Nickname.java
>      validateLength(value);
92d1a492011eed31bf7fc293b5fe94bdf2d988d6

2021-12-21 04:56 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/account/Device.java
> +public class Device {
対応しましたー
c73f96edb8bd02a3aa2f791660221a46f8467278

2021-12-21 09:03 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/notification/PushNotificationToken.java
> +public class PushNotificationToken extends StringValue {
このクラス、使っていないのではないでしょうか。

2021-12-21 09:05 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/model/notification/PushNotificationToken.java
> +public class PushNotificationToken extends StringValue {
ですね。。。
7725a3f951818125b2ba94e3252a30ec18ec44f0

2021-12-21 09:31 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/repository/AccountDeviceTokenRepository.java
> +  AccountDeviceTokens findByAccountId(AccountId accountId);
個人的には引数が値オブジェクトなので、`findBy` のみでもいい気もしています（あまり強い思いではなく、単に`existsBy` に合わせるとくらいの感覚です）。

2021-12-21 09:31 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/FcmPushNotifier.java
> +package jp.fintan.mobile.santokuapp.infrastructure.notification;
パッケージはインフラのサービス部品という意味で `service` でいいのではないでしょうか。

2021-12-21 09:31 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/FcmPushNotifier.java
> +          deviceTokens.subList(i, Math.min(i + MAX_SEND_COUNT, deviceTokens.size()));
メソッドの処理が長いので、forループ内の処理はprivateメソッドに切り出したいです。

2021-12-21 09:31 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/FcmPushNotifier.java
> +        e.printStackTrace();
発生しない想定のエラーであれば、Runtime例外でくるんで投げるでもいいかと思います。

2021-12-21 09:37 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/FcmPushNotifier.java
> +        e.printStackTrace();
失礼しました。。。
4676bb5f48f13881035d1af9127a385258b0ff3c

2021-12-21 09:38 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/FcmPushNotifier.java
> +package jp.fintan.mobile.santokuapp.infrastructure.notification;
変更しましたー
65a23ec34c6eec5aebca3b163eebfffa9f1c68a6

2021-12-21 09:39 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/domain/repository/AccountDeviceTokenRepository.java
> +  AccountDeviceTokens findByAccountId(AccountId accountId);
修正しましたー
740bbdeb4e9d62a06961fdfbba3653c8216c8591

2021-12-21 09:46 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/FcmPushNotifier.java
> +          deviceTokens.subList(i, Math.min(i + MAX_SEND_COUNT, deviceTokens.size()));
マルチキャスト送信する部分をprivateメソッドに切り出しましたー
ae5b3af4e23096646ec1d7f3efa8c853b4e71e9b

2021-12-21 09:59 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/persistence/AccountDeviceTokenDataSource.java
> +            OffsetDateTime.ofInstant(accountDeviceTokenEntity.getCreatedAt().toInstant(), ZoneId.of("UTC")));
```suggestion
            OffsetDateTime.ofInstant(accountDeviceTokenEntity.getCreatedAt().toInstant(), ZoneOffset.UTC));
```

2021-12-21 09:59 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/persistence/AccountDeviceTokenDataSource.java
> +  private AccountDeviceToken toDevice(AccountDeviceTokenEntity accountDeviceTokenEntity) {
ドメインモデルへの変換なので、抽象的な名前にしていいかなと思いました。

```suggestion
  private AccountDeviceToken toDomainModel(AccountDeviceTokenEntity accountDeviceTokenEntity) {
```

2021-12-21 09:59 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/persistence/AccountDeviceTokenDataSource.java
> +    accountDeviceTokenEntity.setCreatedAt(Timestamp.from(accountDeviceToken.createdAt().value().toInstant()));
`toEntity`という privateメソッドで切り出しておくと便利だと思います。

2021-12-21 09:59 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/persistence/entity/AccountDeviceTokenEntity.java
> +  @Id private String accountId;
アノテーションは一律上に定義だと違和感ありますでしょうか？

```suggestion
  @Id
  private String accountId;
```

2021-12-21 09:59 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/presentation/restapi/account/MyAccountDeviceTokenAction.java
> +    }
サービスに呼び出しを分けてしまうとトランザクションが分かれてしまうので、`accountDeviceTokenService.updateDevice` とするのは如何でしょうか。

2021-12-21 10:06 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/persistence/entity/AccountDeviceTokenEntity.java
> +  @Id private String accountId;
Google Java Formatで自動フォーマットかけたせい？なのか、こうなりますね

2021-12-21 10:09 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/presentation/restapi/account/MyAccountDeviceTokenAction.java
> +    }
Nablarchはサービス単位でトランザクション管理してなさそうですかね。

2021-12-21 10:10 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/persistence/AccountDeviceTokenDataSource.java
> +            OffsetDateTime.ofInstant(accountDeviceTokenEntity.getCreatedAt().toInstant(), ZoneId.of("UTC")));
cdaec24e9d139ee7d2e5b8817de4e93a30df5840

2021-12-21 10:10 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/persistence/AccountDeviceTokenDataSource.java
> +  private AccountDeviceToken toDevice(AccountDeviceTokenEntity accountDeviceTokenEntity) {
8525511af21a44ee7562da0bb0e12d86dbd7f3d9

2021-12-21 10:10 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/persistence/AccountDeviceTokenDataSource.java
> +    accountDeviceTokenEntity.setCreatedAt(Timestamp.from(accountDeviceToken.createdAt().value().toInstant()));
7b400a7c1d1f81786a5d67754610bc8fd768c1e0

2021-12-21 10:23 UTC, kozake commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/system/nablarch/csrf/PathHttpMethodVerificationTargetMatcher.java
> +public class PathHttpMethodVerificationTargetMatcher extends HttpMethodVerificationTargetMatcher {
こちら、CSRFトークンの検証対象かどうかの判定クラスなので、`CsrfTokenVerificationTargetMatcher` でもいいかな？と思いました。

2021-12-21 10:27 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/system/nablarch/csrf/PathHttpMethodVerificationTargetMatcher.java
> +public class PathHttpMethodVerificationTargetMatcher extends HttpMethodVerificationTargetMatcher {
c3b6327bf02e1fcb4e5e1c8d03ad9f06a87152f0

2021-12-21 10:27 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/notification/FcmPushNotifier.java
> +          deviceTokens.subList(i, Math.min(i + MAX_SEND_COUNT, deviceTokens.size()));
7e2666f6300145bca9b8283617da37d42367da67

2021-12-22 04:28 UTC, creature-water-valley commented on example-app/SantokuApp/index.js
> +  console.debug(`Receive notification message in background. message=[${JSON.stringify(remoteMessage)}]`);
リリース時も、実機にログが出てしまいそうな？
出てしまう場合は、デバッグモードの場合のみログ出力とかの方が良さそうな気がしました

2021-12-22 04:42 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/snackbar/WithSnackbar.tsx
> +  const {reservedSnackbarMessage, clearReservedSnackbarMessage} = useInitializeContext();
`WithSnackbar`を`WithInitializeContext`より前に宣言すれば、Context経由で引き継ぐ必要なないですかね？
`WithSnackbar`は初期化処理の結果に依存がなさそうなので、前に宣言できそうと思いました。

2021-12-22 04:49 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/initialize/initialize.ts
> +    console.debug(`onMessage. message=[${JSON.stringify(message)}]`);
FirebaseCrashlyticsの初期化も終わっているので、アプリで用意している`log`を使用した方が良さそうです。

2021-12-22 04:55 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/initialize/initialize.ts
> +    console.debug(`onNotificationOpenedApp. message=[${JSON.stringify(message)}]`);
FirebaseCrashlyticsの初期化も終わっているので、アプリで用意している`log`を使用した方が良さそうです。

2021-12-22 04:55 UTC, creature-water-valley commented on example-app/SantokuApp/src/components/initialize/initialize.ts
> +      const snackBarText = [message.notification.title, message.notification.body].join('\n');
スナックバーのデフォルト表示は、タイトル、コンテンツの二つを表示するようなデザインになっていない気がして、スナックバーには`notification.body`のみを表示するのでも良いのかなと思いましたがどうでしょう？

2021-12-22 05:26 UTC, creature-water-valley commented on example-app/SantokuApp/src/navigation/RootStackNav.tsx
> +  const {navigatorOptions, reservedNavigation, clearReservedNavigation} = useInitializeContext();
`reservedNavigation`なんかは、`InitializeContext`ではなくて別のContextでも良いのかなって思いました。
（通知のリッスンを開始しているのは初期化処理ですが、通知イベントを受け取るのは初期化処理ではないと思ったので）

↓は感想で指摘ではないです。

個人的には、ここはコンテキストではなくイベント駆動で実装した方が良さそうに思いました。
が、それらができる機能がReact Nativeにはなさそう？で、ライブラリ入れるか自作しないとだと思うので、コンテキストで受け渡すのに結局落ち着くなとも思いました。

2021-12-22 06:01 UTC, in-a-paddy requested changes

2021-12-22 09:57 UTC, kz-takahashi commented on example-app/SantokuApp/index.js
> +  console.debug(`Receive notification message in background. message=[${JSON.stringify(remoteMessage)}]`);
動作確認用のデバッグログだったので削除しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/b64cf313eb7d5e28dd7a5432d91a74feddc8fba0

2021-12-22 09:57 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/initialize.ts
> +    console.debug(`onNotificationOpenedApp. message=[${JSON.stringify(message)}]`);
動作確認用のデバッグログだったので削除しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/b64cf313eb7d5e28dd7a5432d91a74feddc8fba0

2021-12-23 00:20 UTC, creature-water-valley commented on example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/infrastructure/service/FcmPushNotifier.java
> +        return new ObjectMapper().writeValueAsString(params);
ですな。
1fca27e47132fe104b71ae8ed9feebe0e50f3f72

2021-12-24 06:28 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/snackbar/WithSnackbar.tsx
> +  const {reservedSnackbarMessage, clearReservedSnackbarMessage} = useInitializeContext();
App.tsxでの呼び出し順をWithSnackbarを先にして、InitializeContext経由での引き渡しを不要にしました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/ea4b37a8277a8cba6b9bf84a75a59761c265887e

2021-12-24 06:30 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/initialize.ts
> +      const snackBarText = [message.notification.title, message.notification.body].join('\n');
通知本文があれば通知本文のみ表示、通知本文がなければ通知タイトルのみ表示するように変更しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/2033f2d403053506726404e7d187f7b5f2834f16

2021-12-24 06:31 UTC, kz-takahashi commented on example-app/SantokuApp/src/navigation/RootStackNav.tsx
> +  const {navigatorOptions, reservedNavigation, clearReservedNavigation} = useInitializeContext();
NavigationContainerContextを作成し、そちらでReadyになるのを待っている画面遷移の情報を管理するように変更しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/ea4b37a8277a8cba6b9bf84a75a59761c265887e

2021-12-24 06:32 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +  const [reservedSnackbarMessage, setReservedSnackbarMessage] = useState<string>();
SnackbarContextをInitializeContextより上位に持ってきても問題ないことに気づいていなかったので、
コンテキストの階層構造を変更して値の保持を不要にしました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/ea4b37a8277a8cba6b9bf84a75a59761c265887e

2021-12-24 06:48 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +  const [reservedNavigation, setReservedNavigation] = useState<NavigationArgs | undefined>(
最初はnavigationのオブジェクトをInitializeContextにうまく引き回せなかったので置いていました。
これは、InitializeContextをNavigationContainerより内側に持ってきても問題無さそうだったので修正しました。

しかし修正後の動作確認で、アプリがバックグラウンドの状態で通知を受信した後、通知をタップしてアプリを起動した時の処理で即座にnavigateすると"The 'navigation' object hasn't been initialized yet." のエラーになりました。
バックエンドから復帰した直後ではNavigationContainerの状態はまだReadyではないようです。

このエラーを回避するため、Readyになるまで一時的に同様の画面遷移の情報を保持しておきたくなったので、
NavigationContainerContextを追加してそちらで新たにreservedNavigationArgsという似たような情報を保持するようにしました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/ea4b37a8277a8cba6b9bf84a75a59761c265887e

2021-12-24 06:49 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/initialize.ts
> +export const initialize = async (
initializeの構成を見直して、引数経由で渡さない形にしました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/ea4b37a8277a8cba6b9bf84a75a59761c265887e

2021-12-27 06:52 UTC, kozake commented on example-app/SantokuApp/src/components/initialize/helpers/navigation.ts
> +  }
この部分は `getNavigationArgsFromNotification` と同様の判定処理になりますか？
それであれば、`getNavigationArgsFromNotification` の処理を使う形に変更したいで。
（`HomeStackNav` の `initialRouteName` が異なるので、同じかどうかの判断がつかず）

2021-12-27 06:52 UTC, kozake commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +      return;
このパスに入る条件ってあるのでしょうか。

2021-12-27 06:52 UTC, kozake commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +    setNavigatorOptions(initialNavigatorOptions);
`setNavigatorOptions` をこちらに持ってきた理由などあるのでしょうか。

2021-12-27 06:52 UTC, kozake commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +    messaging().onMessage(message => {
`messaging().onMessage` および `messaging().onNotificationOpenedApp` の処理は `initialize` 関数の引数にコールバック関数として渡すことで、 `initialize` 関数を外だしできると感じました。
やや、 `initialize` 関数の処理が大きく感じるので。

2021-12-27 06:52 UTC, kozake commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +        }
この判定ややこしいので、いっそ`setReservedNavigationArgs` の呼び出しで統一してしまってもいいかもしれませんね。

2022-01-05 03:11 UTC, in-a-paddy commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +  const [reservedNavigation, setReservedNavigation] = useState<NavigationArgs | undefined>(
バックグラウンドから復帰したとき（ウォームスタート）の処理と、初期化（コールドスタート）の処理って分ける必要ありますか？
どっちもコンポーネントを全てマウントしなおすので、`onNotificationOpenedApp`でナビゲートするのではなく、初期化時と同じようにinitialRouteNameを使うのが良いのでは？と思いました。

アプリの初期化処理でも、コールドスタートとウォームスタートは同じように記載してます。
https://ws-4020.github.io/mobile-app-crib-notes/react-native/santoku/application-architecture/life-cycle-management/overview#%E3%82%B3%E3%83%BC%E3%83%AB%E3%83%89%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88%E3%82%A6%E3%82%A9%E3%83%BC%E3%83%A0%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88

2022-01-05 07:24 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +  const [reservedNavigation, setReservedNavigation] = useState<NavigationArgs | undefined>(
バックグラウンドから復帰するウォームスタートの場合、各Navigatorはアンマウントされておらずマウントされ続けていて以前のrouteも記憶されているけれどもReadyではない状態のようで、この状態からinitialRouteNameを変更しても画面遷移は発生しませんでした。
そのため明示的なnavigateが必要になりそうです。

2022-01-05 07:31 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +      return;
WithInitializeContextの呼び出し順をApp.tsxで間違えない限りは原則無いと思います。
onMessageとonNotificationOpenedAppのコード分離と合わせて削除しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/faf15a53ff9804eda3dbac3b4e96d373eb1edf52

2022-01-05 07:32 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +    setNavigatorOptions(initialNavigatorOptions);
NavigationContainerContextを増やしたので確かにもうInitializeContextでなくてもよいと思ったので移設しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/faf15a53ff9804eda3dbac3b4e96d373eb1edf52

2022-01-05 07:33 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +    messaging().onMessage(message => {
両者の処理をinitializeの外に移動しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/faf15a53ff9804eda3dbac3b4e96d373eb1edf52

2022-01-05 07:34 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +        }
ややこしいのはややこしいですが、もし最初からReadyになるケースがあるなら遷移しても構わないと思うのでこのままにしておきます。

2022-01-05 09:12 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/helpers/navigation.ts
> +  }
Screen名が揃っていなかったのは誤りだったので修正しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/6a31cd3b93f32d3a8b2372313cc8838b5cb6c5a5
基本的には新規起動時もバックグラウンドからの復帰時も同じ画面に遷移することになると思うので、型の変換処理を用意すれば画面を指定する箇所は１か所に統一できるとは思います。
ただ変換処理がぱっと見て目的が分かりづらそうなコードになりそうなので、サンプルとしては一旦このままとさせてください。

2022-01-07 10:40 UTC, kozake commented
/azp run deploy-devSantokuAppReleaseInHouse

2022-01-11 04:46 UTC, kozake commented on example-app/SantokuApp/ios/SantokuApp/SantokuAppRelease.entitlements
> +	<string>development</string>
プロダクションビルドをすると自動でproductに変更されるとのことで解決

2022-01-11 09:46 UTC, kz-takahashi commented
/azp run deploy-devSantokuAppReleaseInHouse

2022-01-11 09:49 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +  const [reservedNavigation, setReservedNavigation] = useState<NavigationArgs | undefined>(
https://github.com/ws-4020/mobile-app-crib-notes/tree/feature/refine-initialize-component の内容をこちらのブランチに取り込みました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/c2b4f5ba13acdd4e97526fcc760dbb74077967c4

2022-01-11 10:20 UTC, kz-takahashi commented on example-app/SantokuApp/src/components/initialize/InitializeContext.tsx
> +  const [reservedNavigation, setReservedNavigation] = useState<NavigationArgs | undefined>(
AppWithInitializeをApp.tsxと同列に、WithFirebaseMessagingHandlersをframework/firebase以下に、その他の初期化系をframework/initializeに移動しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/29d8cf340d5f5aaf848ac53983e063f8e3b9ba25

2022-01-11 10:20 UTC, kz-takahashi commented
/azp run deploy-devSantokuAppReleaseInHouse

2022-01-12 09:49 UTC, kz-takahashi commented on example-app/SantokuApp/src/framework/firebase/WithFirebaseMessagingHandlers.tsx
> +  : [RouteName, ParamList[RouteName]];
navigationのtypes.tsへ移動しました。
https://github.com/ws-4020/mobile-app-crib-notes/pull/667/commits/b16982665e9af8d382a04cdf86d7835c04217ebb

2022-01-12 09:57 UTC, kozake commented on example-app/SantokuApp/src/AppWithInitialization.tsx
> +        <RootStackNav initialData={initialData} />
`initialData` を`context`で保持して各コンポーネントから参照する方式をとらず、コンポーネントのプロパティ渡しにしたのは何らかの理由があるのでしょうか？

2022-01-12 09:57 UTC, kozake commented on example-app/SantokuApp/src/screens/demo/push-notification/usePushNotification.tsx
> +  const [authStatus, setAuthStatus] = useState<string>();
`AuthStatusType`  を定義したほうがより良いかと思います。

```suggestion
type AuthStatusType = 'NOT_DETERMINED' | 'DENIED' | 'AUTHORIZED' | 'PROVISIONAL';

export const usePushNotification = () => {
  const [authStatus, setAuthStatus] = useState<AuthStatusType >();
```

2022-01-13 00:48 UTC, kozake commented
/azp run deploy-devSantokuAppDebugAdvanced

2022-01-13 10:24 UTC, kozake approved these changes

2022-01-14 00:47 UTC, in-a-paddy approved these changes

2022-01-14 01:34 UTC, merged