🎨: Improve project structure
ws-4020/mobile-app-crib-notes pull request #903
Opened 2022-07-25 09:47 UTC by creature-water-valley

## 📝 プルリクエストのタイトルについて

プルリクエストのタイトルは、先頭に絵文字を付けてもらいたいです。絵文字は[gitmoji](https://gitmoji.dev/)から選んでください。
絵文字をコピーする際には、：art：のような文字列ではなく、絵文字そのものをコピーして利用してください。
「<emoji>: Title」のようなフォーマットでお願いします。例: 💄: Lintエラーを修正

## 💣 BREAKING CHANGES 💣

- 破壊的な変更を箇条書きで記載してください
- 変更内容と変更理由を、わかりやすく記載してください
- なければ、このセクション（先頭行から「## ✅ What's done」の前の行まで）を削除してください

## ✅ What's done

- [ ] やったことをチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

## ⏸ What's not done

- やっていないこと（やる予定がないこと）を箇条書きで記載してください
- 解決できていない課題・障害があれば、それも記載してください

---

## Tests

- [ ] 実施した動作確認の内容をチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

以下のコマンドのいずれかをこのプルリクエストのコメントとして投稿すると、
Azure Pipeline上でSantokuAppをビルドしてDeployGateへアップロードできます。
4種全てのビルドバリアントを対象にする場合はdeploy-all、
特定のビルドバリアントだけを対象にする場合はdeploy-ビルドバリアント名のコマンドを利用してください。

- /azp run deploy-all
- /azp run deploy-devSantokuAppDebugAdvanced
- /azp run deploy-devSantokuAppReleaseInHouse
- /azp run deploy-santokuAppDebugAdvanced
- /azp run deploy-santokuAppReleaseInHouse

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

何かあれば記載してください。
なければ「なし」と記載してください。

2022-08-03 01:31 UTC, in-a-paddy commented on example-app/SantokuApp/.script/generate-acknowledgements-file.js
> +const DEPENDENCIES_OUTPUT_FILE = path.resolve(rootDir, 'src/features//acknowledgements/utils/ThirdPartyDependencies.ts');
```suggestion
const DEPENDENCIES_OUTPUT_FILE = path.resolve(rootDir, 'src/features/acknowledgements/utils/ThirdPartyDependencies.ts');
```

2022-08-03 01:31 UTC, in-a-paddy commented on example-app/SantokuApp/README.md
> +| features | 画面や、インタラクションに応じたユースケース、APIの呼び出しといったアプリ固有の機能を提供します。 |
`features`を`app`から切り出しているのってなんででしたっけ？普通のアプリ（例えば、トレーニングで作るQAアプリ）でも、この構成にしたほうがいいという認識でいいですか？

2022-08-03 01:31 UTC, in-a-paddy commented on example-app/SantokuApp/README.md
> +| apps | アプリのトップレベルのレイヤーです。通常ここには`app`という1つのアプリ機能のみ存在します。アプリ起動時の初期化処理やコンテキスト（プロバイダー）、テーマ機能などアプリ全般をコントロールします。 |
screenはどういう扱いになりますか？

2022-08-03 02:58 UTC, kozake commented on example-app/SantokuApp/README.md
> +| features | 画面や、インタラクションに応じたユースケース、APIの呼び出しといったアプリ固有の機能を提供します。 |
アプリとして機能する機能モジュールをレイヤーとして分けることで分かりやすさをあげるためです。
普通のアプリの場合は、`app` という機能モジュールが1つ存在するレイヤーになるかと思います。
説明を追加しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/903/commits/0b85ff2120b377aba9dee5fdbb9a9cfabb374ed3

2022-08-03 03:00 UTC, kozake commented on example-app/SantokuApp/README.md
> +| apps | アプリのトップレベルのレイヤーです。通常ここには`app`という1つのアプリ機能のみ存在します。アプリ起動時の初期化処理やコンテキスト（プロバイダー）、テーマ機能などアプリ全般をコントロールします。 |
screenはappsレイヤーのみで使用できます。
「画面やナビゲーションなど」という説明をappsレイヤーに追加しました。

https://github.com/ws-4020/mobile-app-crib-notes/commit/0b85ff2120b377aba9dee5fdbb9a9cfabb374ed3

2022-08-03 09:23 UTC, kozake commented
`useLoginUseCase`について、`mutation`を用いるほうが次の点でいいかと思いました。
- `isExecutingLogin`のステータス管理をReact Queryに任せることができる
- コンポーネントがマウントされているかどうかのチェックをReact Queryに任せることができる

また、`callGetAccountMe`、`callGetAccountsMeTerms`については、refatchを用いずに直接APIをキックしたほうが分かりやすいように感じます。

```typescript
  const {login: loginUsecase, isLoading: isExecutingLogin} = useMutation(
    async () => {
      if (await isValidForm(form)) {
        const accountId = form.values.accountId;
        const password = form.values.password;
        await callLogin({accountId, password});
        await savePassword(accountId, password);
        // callGetAccountMe.dataは必ず存在する想定
        const account = (await getAccountsMe()).data;
        const termsAgreementStatus = (await getAccountsMeTerms()).data;
        // 利用規約を取得できていない場合はボタンを非活性にしているので、termsOfServiceは必ず存在する想定
        accountDataOperation.login({account, terms: {termsAgreementStatus, termsOfService: termsOfService!.data}});
        setIsLoggedIn(true);
      }
    },
    {
      onError: e => {
        if (isUnauthorizedError(e)) {
          Alert.alert(m('ログイン失敗'), m('アカウントIDまたはパスワードに\n間違いがあります。'));
        }
      },
    },
  );

```

2022-08-03 11:12 UTC, kozake commented
機能モジュールの配下は技術要素ではなくステレオタイプで分ける形となりました。

- navigators 
- screens
- components
- pages
- forms
- client-states
- use-cases
- services
- contexts
- types
- constants
- utils
- errors
- configs
- apis

2022-08-03 11:13 UTC, creature-water-valley commented
>useLoginUseCaseについて、mutationを用いるほうが次の点でいいかと思いました。

isExecutingLoginのステータス管理をReact Queryに任せることができる
コンポーネントがマウントされているかどうかのチェックをReact Queryに任せることができる
また、callGetAccountMe、callGetAccountsMeTermsについては、refatchを用いずに直接APIをキックしたほうが分かりやすいように感じます。

対応しましたー
a73d5c2f1a21e91c054046279be77fd86c0e3db5

2022-08-03 11:15 UTC, kozake commented
コンテクストを使ってグローバル状態（および状態変更関数）を渡すものは`XXXProvider`
それ以外の処理などを付与するコンポーネントは`WithXXXX` の`With`を外す

2022-08-04 01:09 UTC, creature-water-valley commented
> コンテクストを使ってグローバル状態（および状態変更関数）を渡すものはXXXProvider
それ以外の処理などを付与するコンポーネントはWithXXXX のWithを外して、役割を定義する （例）XXXLoader

Fixed
f464f9712b150f9669362695f323823c35c32597

2022-08-04 05:51 UTC, creature-water-valley commented
> 機能モジュールの配下は技術要素ではなくステレオタイプで分ける形となりました。

Fixed
ce8f8b94287e45debf0bce8219b983b2b524d9cc
93bce6ae58fc3f51218dd19904b7eaaf84442e78
2e0f7a859d42d6b342e877d28f217cf058b853c4

2022-08-05 00:18 UTC, creature-water-valley commented
/azp run deploy-devSantokuAppReleaseInHouse

2022-08-05 00:49 UTC, creature-water-valley commented on example-app/SantokuApp/README.md
> +| Component | pageを構成する画面部品です。|
```suggestion
| Component | Pageを構成する画面部品です。|
```

2022-08-05 00:50 UTC, creature-water-valley commented on example-app/SantokuApp/README.md
> +| Use Case | ユーザインタラクションなど、Componentで発生したイベントに対するふるまいをhookで実装します。Use Caseの主な役割は以下になります。<br><br>・serviceの呼び出し<br>・serviceからthrowされるエラーに応じたUI（AlertやSnackbar）の表示<br>・ナビゲーションの呼び出し<br>・一つのインタラクション内のみで使用する
> ユーザインタラクションなど、Componentで発生したイベントに対するふるまいをhookで実装します。

Use Caseってhookだけですか？
単純な関数のユースケースがあっても良いかなと思いました。

2022-08-05 00:52 UTC, creature-water-valley commented on example-app/SantokuApp/README.md
> +| Context | React Contextを生成するReact Hooks。 |
ここには、Hooks以外にProviderなども置かれる認識ですが違いますか？

2022-08-05 05:19 UTC, in-a-paddy requested changes

2022-08-05 05:19 UTC, in-a-paddy commented on example-app/SantokuApp/README.md
> +| Apps | トップレベルのレイヤーです。このレイヤーには、後述する機能モジュールの頂点となるものを配置します。通常ここには`app`という1つの機能モジュールが存在します。1つのコードで複数のアプリに対応する場合、複数の機能モジュールをこのレイヤーに配置します。このレイヤーでは、アプリ起動時の初期化処理やコンテキスト（プロバイダー）、テーマ機能、画面やナビゲーションなどアプリ全般をコントロ
やっぱりこいつの必要性が、まだあまり伝わってこないかなぁ、と。

たぶん、「機能モジュールの頂点」って言われても、「機能モジュールって？？」ってなりますし、頂点も結局は機能モジュールなので、混乱を加速させている気がします。なんかもうちょっと明快な説明にしたいところです。。。

トップレベルのレイヤーってのも「画像上の位置」を表しているようなもので、役割を表していないからかもしれないです。例えば、DDDのレイヤードアーキテクチャ、Clean Architectureで紹介されている円状のレイヤードアーキテクチャなどから想像される「トップレベル」とは意味が違うのでわかりにくいのかもです。

2022-08-05 05:54 UTC, creature-water-valley commented on example-app/SantokuApp/src/apps/app/contexts/ReactQueryProvider.tsx
> +export {ReactQueryProvider};
Fixed.
7a1f2bed60bdf8baad982adfc7e0c1610db6b7b4

2022-08-05 05:58 UTC, creature-water-valley commented on example-app/SantokuApp/src/apps/app/contexts/ReactQueryProvider.tsx
>    const onAppStateChange = useCallback((newAppState: AppStateStatus) => {
Fixed.
1cdedff99a5148df3b60c7011e4efc8fa1e9f9be

2022-08-05 06:34 UTC, creature-water-valley commented on example-app/SantokuApp/README.md
> +├── assets（※２）
Fixed.
f5cbb574c528b1246ccc436c60cd919a4b0f6147

2022-08-05 07:12 UTC, kozake commented on example-app/SantokuApp/README.md
> +
こちらで修正しましたがいかがでしょうか？
機能モジュールは特にAngularの用語というわけではないです(モジュールはAngularの機能としてもありますが）。

https://github.com/ws-4020/mobile-app-crib-notes/pull/903/commits/813a0eabf46369e445074b9e0f1ff0f0a20c6236

2022-08-05 07:22 UTC, kozake commented on example-app/SantokuApp/README.md
> +| Use Case | ユーザインタラクションなど、Componentで発生したイベントに対するふるまいをhookで実装します。Use Caseの主な役割は以下になります。<br><br>・serviceの呼び出し<br>・serviceからthrowされるエラーに応じたUI（AlertやSnackbar）の表示<br>・ナビゲーションの呼び出し<br>・一つのインタラクション内のみで使用する
ユースケースの中で他のhookを使いたい時にカスタムhookに変更する必要があるので、最初からhookだけとしておいたほうがメンテナンス性がいいように感じましたがいかがでしょうか。
というよりは、画面から直接サービス呼び出しではだめでしょうかね。

2022-08-05 09:08 UTC, kozake commented on example-app/SantokuApp/README.md
> +アプリは汎用的なものからアプリ固有のものまで、さまざま種類の機能によって構成されます。
必要ないですね。削除しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/903/commits/e412463ff024e4827c7b8e9618d49828258e1863

2022-08-05 09:44 UTC, kozake commented on example-app/SantokuApp/README.md
> +このアプリでは、機能の種類に応じて3つのレイヤーに機能を分類します。
レイヤードアーキテクチャの一般的な目的にしかなっていないかもしれないですが、書いてみました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/903/commits/3f8838de0331176cf3c81cd6fcf6d0b4f58f2e03

2022-08-05 09:44 UTC, kozake commented on example-app/SantokuApp/README.md
> +| Apps | トップレベルのレイヤーです。このレイヤーには、後述する機能モジュールの頂点となるものを配置します。通常ここには`app`という1つの機能モジュールが存在します。1つのコードで複数のアプリに対応する場合、複数の機能モジュールをこのレイヤーに配置します。このレイヤーでは、アプリ起動時の初期化処理やコンテキスト（プロバイダー）、テーマ機能、画面やナビゲーションなどアプリ全般をコントロ
文章見直して修正しました。
こちらでいかがでしょうか。

https://github.com/ws-4020/mobile-app-crib-notes/pull/903/commits/3f8838de0331176cf3c81cd6fcf6d0b4f58f2e03

2022-08-05 09:51 UTC, kozake commented on example-app/SantokuApp/README.md
> +| Context | React Contextを生成するReact Hooks。 |
その認識のとおりです。こちらで修正しました。

https://github.com/ws-4020/mobile-app-crib-notes/pull/903/commits/f363b464ef1a254c3728ca61a079c8b06bc01e4a

2022-08-05 09:51 UTC, kozake commented on example-app/SantokuApp/README.md
> +| Context | React Contextを生成するReact Hooks。 |
こちらの文章でいかがでしょうか？

https://github.com/ws-4020/mobile-app-crib-notes/pull/903/commits/f363b464ef1a254c3728ca61a079c8b06bc01e4a

2022-08-15 12:37 UTC, kozake approved these changes

2022-08-16 01:27 UTC, in-a-paddy approved these changes

2022-08-16 01:31 UTC, merged