プッシュ通知開発ガイドの追加
ws-4020/mobile-app-crib-notes pull request #95
Opened 2021-03-15 07:17 UTC by kz-takahashi

## ✅ What's done

- [x] docs/referenceにプッシュ通知の章を追加
    - [x] 概要ページを作成
    - [x] Firebase Cloud Messagingを用いたプッシュ通知の構成例のページを作成
    - [x] 各サービスの初期設定のページを作成
    - [x] バックエンドの実装のページを作成
    - [x] クライアントアプリの実装のページを作成

## ⏸ What's not done

- 対象はリモート通知だけで、ローカル通知については触れていない
- プッシュ通知受信時のバッジ表示については今回触れていない

---

## Tests

- [x] npm run lint:text
- [x] npm run lint:md

## Other (messages to reviewers, concerns, etc.)

なし

2021-03-16 04:16 UTC, shkozake approved these changes

2021-03-16 04:41 UTC, tani-takanori requested changes

2021-03-16 04:41 UTC, tani-takanori commented on docs/reference/notification/overview.md
> +    - 今月のサービス利用料金が確定したのでお知らせ
```suggestion
    - 確定したサービス利用料金のお知らせ
```

2021-03-16 04:41 UTC, tani-takanori commented on docs/reference/notification/overview.md
> +iOSであればApple Push Notification service (APNs) が該当します。
```suggestion
Androidであれば[Firebase Cloud Messaging (FCM)](https://firebase.google.com/docs/cloud-messaging?hl=ja)がその役割を内包しています。
iOSであれば[Apple Push Notification service (APNs) ](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server)が該当します。
```

リンクにしたほうが親切かなと思いましたがAPNsのリンク良さげなやつがみつからないので、とりあえずRemoteNotificationの最初のページにしました

2021-03-16 04:41 UTC, tani-takanori commented on docs/reference/notification/overview.md
> +iOSであればApple Push Notification service (APNs) が該当します。
その後のページでFCMにリンクされてるからいらないですね

2021-03-16 04:41 UTC, tani-takanori commented on docs/reference/notification/configuration.md
> +アプリIDが既に発行済みの場合も、App Services内のPush Notificationにチェックが入っているか改めて確認し、
> 改めて確認

ミスしやすいポイントですか？（見落としがちであれば、Noteとかで補足不要ですか？）

2021-03-16 04:41 UTC, tani-takanori commented on docs/reference/notification/backend.md
> +バックエンド側から指定したデバイスへリモート通知を送信するサンプルコードは以下のとおりです。
サンプルコードとありますが、これってどこで実行されるものです？
Firebaseのコンソール上ですか？

コードイメージであればコードイメージと記載したほうがいいと思います。

2021-03-16 07:21 UTC, kz-takahashi commented on docs/reference/notification/overview.md
> +iOSであればApple Push Notification service (APNs) が該当します。
2重にあっても良いと思うので足しました。

2021-03-16 08:32 UTC, kz-takahashi commented on docs/reference/notification/configuration.md
> +アプリIDが既に発行済みの場合も、App Services内のPush Notificationにチェックが入っているか改めて確認し、
noteで切り出して触れるようにしました。

2021-03-16 08:35 UTC, kz-takahashi commented on docs/reference/notification/backend.md
> +バックエンド側から指定したデバイスへリモート通知を送信するサンプルコードは以下のとおりです。
一応このコードについては、GOOGLE_APPLICATION_CREDENTIALS環境変数に適切な認証情報を渡している環境ならローカルでもどこでも動くと思います。
表記はコード例とサンプルコードでぶれていたので、表記をコード例に統一します。

2021-03-16 08:58 UTC, tani-takanori approved these changes

2021-03-17 06:57 UTC, tani-takanori commented on docs/reference/notification/client.md
> +  });
```suggestion
    Alert.alert(
      'アプリの起動中にリモート通知を受信しました',
      JSON.stringify({
        notification: message.notification,
        data: message.data,
      }),
    );
  });
```
Santokuに組み込んだら警告でたので修正した内容をFeedbackします。

2021-03-17 10:10 UTC, kz-takahashi commented on docs/reference/notification/configuration.md
> +まずはこのAPNs Auth Keyを発行しましょう。
APNs Auth Keyの発行数は上限2なので、まずは勝手に発行しないで管理者に問い合わせるように言及しておく。

2021-03-18 09:50 UTC, in-a-paddy requested changes

2021-03-18 09:50 UTC, in-a-paddy commented on docs/reference/notification/client.md
> +3. `ios/Podfile`ファイルに以下のように利用したいFirebaseサービスのpodを追記
たぶん`Podfile`への追加は不要ではないかと。

2021-03-18 09:50 UTC, in-a-paddy commented on docs/reference/notification/client.md
> +### react-native-firebaseのインストール
「Firebase SDKの導入と認証情報ファイルの配置」の前にinstallしてしまったほうが良いと思います。

2021-03-18 09:50 UTC, in-a-paddy commented on docs/reference/notification/backend.md
> +```maven title="pom.xml"
たぶん、言語は`xml`にしたほうがいい気がします。

```suggestion
```xml title="pom.xml"
```

2021-03-18 09:50 UTC, in-a-paddy commented on docs/reference/notification/backend.md
> +```gradle title="build.gradle"
こっちも`groovy`が適切かと
```suggestion
```groovy title="build.gradle"
```

2021-03-18 09:50 UTC, in-a-paddy commented on docs/reference/notification/backend.md
> +許容されるトピック名は```[a-zA-Z0-9-_.~%]{1,900}```の範囲になります。
バックティックは一つで良さそうな？
```suggestion
許容されるトピック名は`[a-zA-Z0-9-_.~%]{1,900}`の範囲になります。
```

2021-03-22 02:23 UTC, tani-takanori commented on docs/reference/notification/client.md
> +3. `ios/Podfile`ファイルに以下のように利用したいFirebaseサービスのpodを追記
不要なため削除

2021-03-22 02:26 UTC, tani-takanori commented on docs/reference/notification/client.md
> +### react-native-firebaseのインストール
修正しました

2021-03-22 02:27 UTC, tani-takanori commented on docs/reference/notification/client.md
> +3. `ios/Podfile`ファイルに以下のように利用したいFirebaseサービスのpodを追記
0fa006765d0a04f10af20ef50a477d814fc88afb

2021-03-22 02:33 UTC, tani-takanori commented on docs/reference/notification/backend.md
> +```maven title="pom.xml"
ed2c433093947b9e8ef22d6455eb22cea58fc7b8
修正

2021-03-22 02:33 UTC, tani-takanori commented on docs/reference/notification/backend.md
> +```gradle title="build.gradle"
修正
ed2c433093947b9e8ef22d6455eb22cea58fc7b8

2021-03-22 02:33 UTC, tani-takanori commented on docs/reference/notification/backend.md
> +許容されるトピック名は```[a-zA-Z0-9-_.~%]{1,900}```の範囲になります。
修正
ed2c433093947b9e8ef22d6455eb22cea58fc7b8

2021-03-22 06:01 UTC, in-a-paddy commented on docs/reference/notification/client.md
> +そのため、本ガイドではreact-native-firebaseというライブラリを利用して間接的にFirebase SDKを利用する例について解説します。
```suggestion
そのため、本ガイドでは[React Native Firebase](https://rnfirebase.io/)というライブラリを利用して間接的にFirebase SDKを利用する例について解説します。
```

2021-03-22 06:03 UTC, in-a-paddy commented on docs/reference/notification/client.md
> +### react-native-firebaseのインストール
```suggestion
### React Native Firebaseのインストール
```

2021-03-22 06:04 UTC, in-a-paddy requested changes

2021-03-22 06:04 UTC, in-a-paddy commented on docs/reference/notification/client.md
> +まず、react-native-firebaseをインストールします。
```suggestion
まず、React Native Firebaseをインストールします。
```

2021-03-22 06:52 UTC, tani-takanori commented on docs/reference/notification/backend.md
> +バックエンド側からFirebaseのAPIを呼びだす際には、Firebase Admin SDKを利用します。
```suggestion
バックエンド側からFirebaseのAPIを呼びだす際には、[Firebase Admin SDK](https://firebase.google.com/docs/admin/setup?hl=ja)を利用します。
```

2021-03-22 09:13 UTC, in-a-paddy approved these changes

2021-03-22 09:13 UTC, merged